### ISSUE TITLE
Export some internal functions

### ISSUE THREAD

**Issue by AlexRMU** [sveltejs/kit#10025]
### Describe the problem

For example, I want to disable or change csfr or csp for different routes. To do this, I disable it in the settings, copy this functionality from the source and use it manually as I need. But if the implementation changes, I won't be able to find out about it.
Perhaps there are many more such functions.

### Describe the proposed solution

I suggest exporting some internal functions as utilities.

### Importance

nice to have

### Additional Information

Perhaps modularity and optionality are more suited to the Svelte ideology.

**Comment by Conduitry** [comment]
There's already #6784 for CSRF. There are a number of other CSP-related issues.

As a rule, we don't like to expose internal functions just because we can. That ties us to that API and prevents certain kinds of refactoring without it being a breaking change. The API of the internal function is also likely not designed with ease-of-use by an end-user in mind. If you have specific feature requests that are more actionable, please open separate issues for them instead.
