### ISSUE TITLE
How to use "Fetch" in component that is called outside of load()

### ISSUE THREAD

**Issue by saturnonearth** [sveltejs/kit#1005]
I have a component that queries something relative to a slug every so often, but "fetch" is only available to the server side via load(), and since components are run on server, then client, I need something universal. Checking for "browser" would not be applicable to my particular use case.

I can technically pass fetch as a prop to the component, but that just feels...wrong. Is there an alternative here?

**Comment by Conduitry** [comment]
`fetch` is asynchronous, and rendering a component on the server (once you have its props) is synchronous, so the only way to get data into the page during SSR is via `load()`.

If it's code that's going to be running later on the browser, you can safely use a regular `fetch` there.

If there's some code that needs to run both during SSR and periodically later on, you can write it to accept `fetch` as an optional argument (and pass that from `load()`), which it will use instead of the browser's default `fetch` if the argument is passed.
