### ISSUE TITLE
Support for Variable ORIGIN depending on host

### ISSUE THREAD

**Issue by xpluscal** [sveltejs/kit#10129]
### Describe the bug

We're trying to achieve a shared hosting infrastructure with a sveltekit instance.
Basically, it works like this:

- Users add their custom domain to their DNS provider to point to the Sveltekit instance
- Sveltekit server reads the host name and fetches the correct entry / site from the DB and serves to user

The current issue is that the host name will always be the ORIGIN itself, rather than the CNAME source.

What's a good fix from this?

### Reproduction

- Create a basic Sveltekit template
- Use Node adapter
- Host somewhere
- Create a DNS entry (if needed for SSL, setup proxy infra like traefik)
- Read host on server (e.g. high level layout.server.ts)
- Sveltekit always returns it's original host, not the CNAME DNS one

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 680.53 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2
    Yarn: 1.22.18
    npm: 9.6.4
  Browsers:
    Brave Browser: 104.1.42.97
    Chrome: 114.0.5735.106
    Safari: 16.0
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
Have you read all of https://kit.svelte.dev/docs/adapter-node#environment-variables ?

You should only use `ORIGIN` if you have a static origin. Otherwise, the default is that the origin is assumed to be `https://` followed by the incoming `Host` header. If your HTTPS proxy is changing that as requests pass through it, either configure it not to do that, or use the other environment variables listed in the documentation above to tell the adapter-node output what other header names it can read the host or protocol information from.
