### ISSUE TITLE
Cannot use import statement outside a module: blocking package upgrade

### ISSUE THREAD

**Issue by hahnrobert** [sveltejs/kit#10139]
### Describe the bug

Cannot use Firelord in a Sveltekit project but can use it in a pure Svelte-only (not Sveltekit) project.
Since Firelord works with pure Svelte, React and a few other frameworks this clearly seems like a blocking Sveltekit issue -- most likely blocking a few libraries, not just Firelord.

### Reproduction

Reproduction steps:
- Repo: https://github.com/hahnrobert/firelord-repro
- `npm i && npm run dev`

Alternative:
- `npm create svelte@latest` (select Skeleton app)
- `npm i firelordjs@2.5.20`
- Add the following to your `+page.svelte` file:
```
<script lang="ts">
	import { getFirelord } from 'firelordjs';
</script>
```

Working pure Svelte-only (no Sveltekit) repo:
- https://github.com/tylim88/firelord-vite-svelte

### Logs

```Shell
Internal server error: Cannot use import statement outside a module
      at internalCompileFunction (node:internal/vm:73:18)
      at wrapSafe (node:internal/modules/cjs/loader:1175:20)
      at Module._compile (node:internal/modules/cjs/loader:1219:27)
      at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
      at Module.load (node:internal/modules/cjs/loader:1113:32)
      at Module._load (node:internal/modules/cjs/loader:960:12)
      at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
      at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async DefaultModuleLoader.import (node:internal/modules/esm/loader:246:24) (x2)
/Users/rob/workspace/firelord_repro/node_modules/firelordjs/dist/index.js:21
import { docCreator, collectionCreator, collectionGroupCreator, andCreator, orCreator, } from './refs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1175:20)
    at Module._compile (node:internal/modules/cjs/loader:1219:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1309:10)
    at Module.load (node:internal/modules/cjs/loader:1113:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async DefaultModuleLoader.import (node:internal/modules/esm/loader:246:24)
```

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 4.84 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 108.0.5359.94
    Edge: 114.0.1823.43
    Firefox: 99.0.1
    Safari: 16.5
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.1.0 
    @sveltejs/kit: ^1.5.0 => 1.20.2 
    svelte: ^3.54.0 => 3.59.1 
    vite: ^4.3.0 => 4.3.9
```

### Severity

blocking an upgrade

**Comment by Conduitry** [comment]
This is a bug in the packaging of that library. They are shipping `.js` files that are ESM, but they do not have `"type": "module"` in their `package.json`. https://nodejs.org/dist/latest/docs/api/packages.html#type

**Comment by tylim88** [comment]
that is because it is not an ESM, the reason I do not transpile `import` statement is because of this firebase issue https://github.com/firebase/firebase-js-sdk/issues/7135

**Comment by tylim88** [comment]
update: after giving it some thoughts, my guess is, if build tools can resolve `import` in non ESM, then they definitely can work with ESM, so I change my package to ESM, or so I thoughts

I tested both non ESM and ESM

results:
1. Non ESM with `import` statement
- work with `react-sctipts`(v5.0.1)
- work with `@vitejs/plugin-react-swc`
- work with `@sveltejs/vite-plugin-svelte`
- does not work with `@sveltejs/kit/vite`

2. ESM 
- work with `@vitejs/plugin-react-swc`
- work with `@sveltejs/vite-plugin-svelte`
- does not work with `react-sctipts`(v5.0.1), https://github.com/facebook/create-react-app/issues/11865
- still does not work with `@sveltejs/kit/vite` due to “Directory import is not supported resolving ES modules” error, https://github.com/sveltejs/kit/issues/612

I want to keep the non ESM because it works with most build tools but I can give up `react-sctipts` because it is dying anyway

but how can I solve the “Directory import is not supported resolving ES modules” error, @Conduitry? 

Should I open a new issue or continue it here or [here](https://github.com/sveltejs/kit/issues/612)?

**Comment by ghostdevv** [comment]
I would imagine that instead of importing from `dist/refs` you want `dist/refs/index.js`

**Comment by tylim88** [comment]
@ghostdevv if I fix this, there will be a new one
![image](https://github.com/sveltejs/kit/assets/5227509/abb1465a-1152-4b79-bd36-a92437b3be41)

I need to go to `node_modules/firelord/dist` and fix every single import

The best is to release Non ESM package with import statement because it works with `react-scripts`

but since `react-scripts` is dying, I am willing to give up `create-react-app` and release a proper ESM package

surprisingly CommonJS package work with svelte, it does not works for other build tools because it will break them ([firebase fked up](https://github.com/firebase/firebase-js-sdk/issues/7135))

Should I release a CommonJS variant just to support svelte kit users?

Maybe, but I prefer svelte kit solve this issue on their side, this will make not only me, but also others library author job easier
