### ISSUE TITLE
Doesn't hooks.server.ts run with adapter-static?

### ISSUE THREAD

**Issue by HBartolin** [sveltejs/kit#10171]
### Describe the problem

I am not sure, but using Vite and 'npm run build' and 'npm run preview' don't print anything what is in hooks.server.ts? 

+layout.ts
export const prerender = true;
export const trailingSlash = 'always';

### Describe the proposed solution

1. make hooks.server.ts
2. call it

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Your `handle` hook should be getting called while building when using the static adapter. It's not called when serving your app (i.e., hosting the static files somewhere), because there's no server-side app - just static files.

`npm run preview` is different from running the production version of your app. However, as part of attempting to simulate running your production app (regardless of what adapter you have selected), it will skip calling any of your code for prerendered files. In the case of apps built with the static adapter, every route is prerendered, so you will see no calls to `handle`.
