### ISSUE TITLE
Same route anchor links only fire once when a hash link is preloaded with `data-sveltekit-preload-data`

### ISSUE THREAD

**Issue by mattpilott** [sveltejs/kit#10234]
### Describe the bug

Clicking a link that goes to an anchor on the page works but after you remove the anchor via the page store the link no longer works.

The use case i had was using anchors for modals, modal opens on anchor link and anchor link is removed on modal close.

### Reproduction

Here's my original repro

https://stackblitz.com/edit/sveltejs-kit-template-default-qwsbag?file=src%2Froutes%2F%2Bpage.svelte

and here is a different approach that highlights the same issue made by a friend

https://stackblitz.com/edit/sveltejs-kit-template-default-fnttrd?file=src%2Froutes%2F%2Bpage.svelte

### System Info

```Shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 900.20 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Firefox: 114.0.1
    Safari: 16.5.1
```

### Severity

serious, but I can work around it

### Additional Information

The only work around atm is to force a page reload on modal close, which is not ideal

**Comment by dipunm** [comment]
This is the exact thing I have been struggling with. I ended up using querystring to solve it temporarily, but I want to track this because using anchors is preferable to me.

**Comment by s3812497** [comment]
I don't think the issue is tied to the page store. It stems from the `data-sveltekit-preload-data` attribute preload causing the router to think we've already navigated to the anchor (thus doing nothing).

The `preload` method gets called when hovering over the link, updating our `current.url` to the anchor before we even click the link.

https://github.com/sveltejs/kit/blob/715dfdd2236111d475ba451046ac8c4e272a937f/packages/kit/src/runtime/client/client.js#L1574
