### ISSUE TITLE
Update `ServerInitOptions` typing to accept `process.env` in adapter written in typescript

### ISSUE THREAD

**Issue by YimingIsCOLD** [sveltejs/kit#10304]
### Describe the problem

While trying to write a custom adapter in typescript, I realised that the type `ServerInitOptions` might be incorrectly typed.

In `adapter-node`, we are initialising the server with `process.env`,
```ts
const server = new Server(manifest);
await server.init({ env: process.env });
```

but the typing of `ServerInitOptions` is,

```ts
export interface ServerInitOptions {
  env: Record<string, string>;
}
```

### Describe the proposed solution

Update the `ServerInitOptions['env']` to accept `undefined`,

```ts
export interface ServerInitOptions {
  env: Record<string, string | undefined>;
}
```

### Importance

would make my life easier

**Comment by tcc-sejohnson** [comment]
This isn't actually incorrect. The server init function expects a `Record<string, string>`. A `Record<string, string | undefined>` is incorrect --  no value in the env passed to `server.init` should be `undefined`.

The fix for this just to cast `process.env` to `Record<string, string>`. Why? Because `process.env` is actually a `Record<string, string>`. For every key in `process.env`, the associated value is a string -- even if it's an empty string. The only way you'd get `undefined` back is if you accessed a key that doesn't exist at all -- which isn't possible in this context.
