### ISSUE TITLE
Receive cookies in universal `load` function

### ISSUE THREAD

**Issue by NatoBoram** [sveltejs/kit#10346]
### Describe the problem

When making a SSR+PWA project, it is impossible to obtain cookies during SSR build because `+page.server.ts` and `+page.layout.ts` crashes in PWA builds.

Obtaining cookies in `+page.ts` can be done with `if (browser) document.cookie` since it runs sometimes on the browser, but it doesn't make sense that it can't be done with `cookies` since the function also runs sometimes on the server.

### Describe the proposed solution

Receive the `cookie` object in `+page.ts` and `+layout.ts` just like we do on `+page.server.ts` and `+layout.server.ts`. This object would be `null` during CSR, but set during SSR.

Obtaining cookies in `+page.ts` can be done with `if (browser) document.cookie` since it runs sometimes on the browser, but it doesn't make sense that it can't be done with `cookies` during SSR, since the function also runs sometimes on the server.

### Alternatives considered

* Fixing https://github.com/sveltejs/kit/issues/10332
* Implementing https://github.com/sveltejs/kit/issues/10344

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
This request came up previously, and we closed it because we think that it's more confusing to have the API available and sometimes it works and sometimes now compared to it never being available in that environment. Solving it would only partially help your specific use case, your larger problem is how to achieve builds for multiple environments in one project, so closing in favor of #10344
