### ISSUE TITLE
`create-svelte` output is missing `.gitignore`

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/kit#1036]
**Describe the bug**
`create-svelte` output is missing `.gitignore`

**To Reproduce**
```bash
npm init svelte@next
```

**Expected behavior**
`.gitignore` is included in the default template

**Severity**
Oops.

**Additional context**
Probably got missed by accident when we re-wrote the template to generate the JS version from the single TS version.

**Comment by Conduitry** [comment]
Should we first ask people whether they want to use Git? (And default to yes.) And if they do, then not only create .gitignore, but also run git init for them?

**Comment by benmccann** [comment]
I'm not sure I'd want `git init` run for me. I probably wouldn't realize that had happened and am not sure what happens if you run it twice

**Comment by Conduitry** [comment]
It should be pretty much a no-op if you run `git init` in an already well-formed Git repo.

**Comment by benmccann** [comment]
Yeah, looks like basically a no-op. I just tested and it says "Reinitialized existing Git repository"

**Comment by rmunn** [comment]
I'd vote no on `git init` by default because there might be times when I'm creating a new directory in a monorepo or something. But running it after someone says "yes" to the "Do you want to use Git?" question would not be a problem.

**However,** I think adding too many questions to the template is something to avoid. Instead of asking "Do you want to use Git?" and then running `git init` for them, I think a better way to help users would to be *suggest* a series of steps after the template is created. In the template output, suggest running `git init .` followed by `git add .` and `git commit -m 'Initial commit from template'`, but don't actually run those commands. That way there's still an easy-to-follow-without-thinking procedure for anyone who wants to use Git, but people who prefer Mercurial or some other solution can still blindly press the Enter key to accept all defaults without ending up with a version control system they didn't want.

**Comment by dummdidumm** [comment]
I agree with too many steps being a concern but this step feels important enough for me. It's also the default for `create-react-app` and the Angular/Vue CLI I think.

**Comment by benmccann** [comment]
For anyone that runs into this issue, you can solve it by copying this `.gitignore` into your project: https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/.gitignore

**Comment by nico-bachner** [comment]
>I agree with too many steps being a concern but this step feels important enough for me. It's also the default for `create-react-app` and the Angular/Vue CLI I think.

[Nuxt](https://nuxtjs.org) also does it that way:

<img width="306" alt="Nuxt.js git setting" src="https://user-images.githubusercontent.com/45149421/115107412-f9ba0680-9f6a-11eb-86df-7340bed2584c.png">

>However, I think adding too many questions to the template is something to avoid. Instead of asking "Do you want to use Git?" and then running git init for them, I think a better way to help users would to be suggest a series of steps after the template is created. In the template output, suggest running git init . followed by git add . and git commit -m 'Initial commit from template', but don't actually run those commands. That way there's still an easy-to-follow-without-thinking procedure for anyone who wants to use Git, but people who prefer Mercurial or some other solution can still blindly press the Enter key to accept all defaults without ending up with a version control system they didn't want.

Personally, I find the 'select option' method to be a smoother experience than being suggested code to copy & paste.

**Comment by Rich-Harris** [comment]
I PR'd this issue without actually reading the thread above — will create a separate issue about `git init`
