### ISSUE TITLE
Convert boolean environment variables to native booleans

### ISSUE THREAD

**Issue by Zerotask** [sveltejs/kit#10549]
### Describe the problem

If you have env variables like PUBLIC_DEBUG or feature flags like PUBLIC_FEATURE_XY which are true or false, it would be handy to automatically cast them from string to booleans.
This ways you can use them very easily like

```svelte
<MyComponent show={PUBLIC_DEBUG} />
```

instead of writing
```svelte
<MyComponent show={PUBLIC_DEBUG === 'true'} />
```

or even
```svelte
<MyComponent show={PUBLIC_DEBUG.toLowerCase() === 'true'} />
```

### Describe the proposed solution

Add a new `env` configuration to svelte.config.js

```js
convertBoolean?: boolean;
```

or castBoolean or something similar.

### Alternatives considered

as described above

### Importance

nice to have

**Comment by Conduitry** [comment]
This feels unwise to me. How do we deal with env vars that are missing? How do we deal with env vars that are set to a value other than `true` or `false`? How do we know which ones ought to be booleans? What happens if someone wants to set an env var to the string `true` or `false` without it being interpreted as a boolean? What happens to the TypeScript types?

This all feels like something that should happen in userland with a wrapper module that does precisely what you need for that given application.

**Comment by Zerotask** [comment]
> How do we deal with env vars that are missing?

The same as you do now.

> How do we deal with env vars that are set to a value other than true or false?

They will be processed as you do right now - as string.

> How do we know which ones ought to be booleans? 

"true" | "false"

> What happens if someone wants to set an env var to the string true or false without it being interpreted as a boolean? 

then he won't set the new configuration key at all - just the default behavior.

> What happens to the TypeScript types?

Nothing. Those env vars are boolean, the others are string.

> What happens to the TypeScript types?

If you set an env var to true or false, don't you expect it to be a native boolean? I mean by default every env var is a string, sure, but what you really want is a boolean, right? So with this proposal you can opt-in for that behavior, but you don't have to.

**Comment by ghostdevv** [comment]
I personally would do `<MyComponent show={PUBLIC_DEBUG} />` even with it a string. Because people represent booleans in different ways with env vars. E.g. `PUBLIC_DEBUG="true"`, `PUBLIC_DEBUG="1"`, `PUBLIC_DEBUG=""`. I think this is probably best kept as a userland problem with something like

```ts
function is_bool(variable: string) {
	return variable == 'true';
}
```

Although I still think you're better off letting javascript evaluate it as truthy. You could even do `!!PUBLIC_DEBUG` in your code.

**Comment by Zerotask** [comment]
> Because people represent booleans in different ways with env vars. E.g. PUBLIC_DEBUG="true", PUBLIC_DEBUG="1", PUBLIC_DEBUG="".

Yea, that's a good point and as you mentioned, you can catch/convert it easily with `!!`, which isn't really verbose.
So that's definitely a viable way.
Although I'm still thinking about offering a way to optimize the env loading. At the end of the day a framework should ease your life and I think bool values (switches) are very common.

**Comment by dummdidumm** [comment]
Given all the possible ways this could go wrong (different formats for true/false, omitting variable == suddenly String again) I'm also against adding something like this. It might be convenient for some cases but there's too much nuance to explain in the docs about how it behaves, at which point it's better to solve this in user land - therefore closing.
