### ISSUE TITLE
Add an option to disable removal of "unused" css rules

### ISSUE THREAD

**Issue by malammar** [sveltejs/kit#10572]
### Describe the problem

The Svelte CSS preprocessor is removing CSS styles (to produce an arguably minimal result in reducing bundle size) which means:

1. Components cannot use scoped styles to target _any_ third party components.
2. Scoped styles cannot target classes that are programmatically added.
3. Developers are having to resort to using `:global` styles as a workaround, which causes CSS to leak out of possibly deeply nested components.

### Describe the proposed solution

As an alternative, we should be able to have these "unused" CSS removals become warnings on compilation or the ability to completely turn off this feature.

In my opinion, Svelte has no business removing code it regards as "unneeded" especially when there is much better tooling for detecting unused code such as https://github.com/webpro/knip.

### Alternatives considered

Tried using the `:global` flag on style rules, but this results in CSS leaking out of the component, defeating the entire purpose of style scoping.

### Importance

i cannot use SvelteKit without it

### Additional Information

I realize that this has been requested multiple times and dismissed by certain maintainers, but I view it as important enough to severely impact the adoption of Svelte.

**Comment by Conduitry** [comment]
Svelte's feature that scopes styles to components works at compile time via component-specific scoping classes added to the selectors and to the elements. Keeping these styles when the compiler can't see what they match would have to mean either:

- The selectors do not get the scoping class, and they become global, affecting all elements on the page, or
- The selectors do get the scoping class, but there's no guarantee that the elements they want to match will get it, so you have no idea whether they will apply to the elements in that component that you want them to.

Having a given selector mean radically different things depending on whether the compiler can see during compilation what it applies to is bad. The answer is to use `:global(...)`, which lets you explicitly opt in to global selectors and styles. Keep in mind that you can also wrap part of your selector in `:global()` and leave the rest scoped to the component.

The reason that certain maintainers have closed all of these issues is because the above is true no matter how many times people ask about it. Until modern browsers ship some other CSS feature that lets us scope styles better, this is the kind of scoping that Svelte is going to have.
