### ISSUE TITLE
npm run build should produce something by default (adapter static by default?)

### ISSUE THREAD

**Issue by francoisschwarzentruber** [sveltejs/kit#10739]
### Describe the problem

When running the demo from:

````
npm create svelte@latest my-app
cd my-app
npm install
npm run dev -- --open
````

`npm run build` does not work It says:

````
> Using @sveltejs/adapter-auto
  Could not detect a supported production environment. See https://kit.svelte.dev/docs/adapters to learn how to configure your app to run on the platform of your choosing
  ✔ done
✓ built in 2.00s
````

The problem is that the new user is frustrated. He or she has to lear the notion of adapter etc. whereas he/she just tasted the elegance of Svelte! Everything is so super intuitive with Svelte that `npm run build` should also directly work!

### Describe the proposed solution

The project should directly use the static adapter in order to produce a static website. The user would have nothing to configure for having a basic example working.

### Importance

nice to have

**Comment by Conduitry** [comment]
The default adapter (`adapter-auto`) was chosen so that the user can just deploy directly to any of the supported cloud providers. The static adapter doesn't work for any site with a dynamic server-side component (including, for example, the default application you get if you use `create-svelte`), and so it would be an even worse experience to receive an error telling you that `adapter-static` won't work with the current app where it was installed by default. We also don't want to use the Node adapter because that can't be deployed configuration-free to any providers.

**Comment by francoisschwarzentruber** [comment]
Thank you for your answer. I think I understand. But the problem is that `adapter-auto` does not work. I do not see any folder `build` with the `index.html` file + the bundle. So I do not know how to deploy my sveltekit app, and I can just use it with `npm run dev`.

**Comment by hankaibo** [comment]
me too.
