### ISSUE TITLE
file name ending in `-event` causes a hydration error

### ISSUE THREAD

**Issue by ryanfiller** [sveltejs/kit#10889]
### Describe the bug

When I have a TypeScript (or JavaScript) file with a name ending in `-event` imported either directly or via an alias the app will get a 500 error during hydration.

### Reproduction

https://replit.com/@ryanfiller89/sveltekit-vite#src/routes/index.svelte

### Logs

```Shell
From the logs in the replit repro - 

failed to load module for ssr: /src/helpers/helper-event
Error: failed to load module for ssr: /src/helpers/helper-event
    at instantiateModule (/home/runner/sveltekit-vite/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:
```
```


### System Info

```Shell
System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 69.13 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    pnpm: 8.6.10 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 118.0.5993.70
    Chrome Canary: 120.0.6074.0
    Edge: 117.0.2045.55
    Safari: 16.6
    Safari Technology Preview: 17.0
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/adapter-static: ^2.0.1 => 2.0.1 
    @sveltejs/kit: ^1.25.2 => 1.25.2 
    svelte: 4.2.1 => 4.2.1 
    vite: ^4.0.0 => 4.1.4
```

### Severity

serious, but I can work around it

### Additional Information

I know I can just _not_ name the file that... but its fires an event... so I really want to...

**Comment by dominikg** [comment]
the replit you provided uses a really old version of sveltekit (obtained via "next" tag that points to the last published beta before the 1.0.0 release). The versions logged in your system info show more up2date versions though. There seems to be no way to clone the replit as well.

adding a file named `foo-event.js` to the output of `pnpm create svelte@latest` failed to reproduct your issue.

To prevent getting overloaded with manually building reproductions, we ask reporters to share a link to a public repository or stackblitz so that it's easier to analyze. 

> A link to a repository, or a fork of https://node.new/sveltekit, that reproduces the issue. Reproductions must be [short, self-contained and correct](http://sscce.org/) and must not contain files or code that aren't relevant to the issue — please do NOT just paste a link to your project. Explaining how to reproduce is generally not enough. It pushes the burden of creating a reproduction project onto a small set of volunteer maintainers and isn't scalable. If no reproduction is provided, the issue will be closed.
