### ISSUE TITLE
Generate a static 404.html when using adapter-static

### ISSUE THREAD

**Issue by gusvd** [sveltejs/kit#10880]
### Describe the problem

I'm using sveltekit with adapter-static (as a SSG) to generate a pre-rendered site.

I'm hosting it on Cloudflare Pages who [asks for a top-level 404.html file](https://developers.cloudflare.com/pages/platform/serving-pages/#single-page-application-spa-rendering), otherwise it'll treat the site as a SPA and redirect any 404s to the root.

I'm looking for a way to generate a static 404.html file on the root of my project using adapter-static on build time. The 404 template uses data from `+layout.server.js` or `+page.server.js` to load links that will help users find what they're looking for.

It seems trivial, but everything I've tried so far failed.

### Describe the proposed solution

I'm punching above my weight here, but the closer I got to a good solution was when I tried creating  a `/routes/404/+page.svelte`.

This way I could take advantage of all the templating svelte/kit provides and use data from a `+layout.server.js` or `+page.server.js` that pre-rendered at build time.

But as you'll read bellow the relative links to .css files were an issue. So maybe there's an option to generate this page with absolute links to .css and .js files.

### Alternatives considered

**1)** fallback: '404.html' proposed [here](https://github.com/sveltejs/kit/issues/1209#issuecomment-1120367821) with a custom `+error.svelte` 
This one breaks as soon I start customising the layout and adding a footer or other components that depend on data from `+layout.server.js` or `+page.server.js`.

It tries to load data from the non-existent directory. When trying to load http://domain.com/nonexistent/ it gives the following error:

`Failed to load resource: the server responded with a status of 404 (Not Found) --> http://domain.com/nonexistent/__data.json?x-sveltekit-invalidated=1`

**2)** Creating a `/routes/404/+page.svelte`
This solution renders the 404.html page in the right place. However all the links to the .css are relative to the file and they break when the 404s come from a subfolder of the site (example.com/nested/folder).

**3**) Creating static 404.html page in the `static` folder.
Similar problem with the relative links to css and js files. In this case the CSS files change name on every build, so the hard coded links break. In my test `./_app/immutable/assets/0.6c214458.css` became `0.328b4a33.css`, for example.

### Importance

nice to have

**Comment by uranderu** [comment]
I'm not a maintainer or anything. But maybe you could use the Cloudflare Pages adapter and set prerender to true in your root layout file. Then you have easy deployment to Cloudflare Pages plus you make sure everything is statically generated. I think it is a more robust solution then what you are trying to do here with the extra route. Do note, I have not tested this myself. Read more about the Cloudflare Pages adapter [here](https://kit.svelte.dev/docs/adapter-cloudflare) and about how you prerender (SSG) [here](https://kit.svelte.dev/docs/page-options#prerender).

**Comment by leereamsnyder** [comment]
I hit your problem with the page-relative css/js links on 404 pages on Netlify. If you're serving your site at the the server root, you can use in svelte.config.js the option `kit.paths.relative` and set it to `false` to use server root paths. Like instead of './_app/immutable/something.css` it'll be `/_app/immutable/something.css`

**Comment by arkmech** [comment]
> I hit your problem with the page-relative css/js links on 404 pages on Netlify. If you're serving your site at the the server root, you can use in svelte.config.js the option `kit.paths.relative` and set it to `false` to use server root paths. Like instead of './_app/immutable/something.css`it'll be`/_app/immutable/something.css`

What option does this go with?

I don't want to manually create a `404.html` page in `static` for Cloudflare Pages.

I don't know why it just doesn't pre-render a `404` page from the root `+error.svelte` as my error component is in between all my header and footer component. I have all my errors with a Svelte Component. Now I need to manually build this with raw html?

**Comment by teemingc** [comment]
> > I hit your problem with the page-relative css/js links on 404 pages on Netlify. If you're serving your site at the the server root, you can use in svelte.config.js the option `kit.paths.relative` and set it to `false` to use server root paths. Like instead of './_app/immutable/something.css`it'll be`/_app/immutable/something.css`
> 
> What option does this go with?
> 
> I don't want to manually create a `404.html` page in `static` for Cloudflare Pages.
> 
> I don't know why it just doesn't pre-render a `404` page from the root `+error.svelte` as my error component is in between all my header and footer component. I have all my errors with a Svelte Component. Now I need to manually build this with raw html?

I think you can already do this if you're using the Cloudflare adapter. https://svelte.dev/docs/kit/adapter-cloudflare#Options-fallback. You can also do the same thing with the static adapter by specifying a `404.html` file as a fallback https://svelte.dev/docs/kit/adapter-static#Options-fallback

**Comment by leereamsnyder** [comment]
This is closed, but wanted to follow up in case someone finds this.

To make sure a 404.html page gets built, here's what I do on my site using adapter-static but deploying on Netlify—which like Cloudflare looks for a /404.html file to show when rendering an error:

1. Make a `src/routes/404/+page.svelte`
2. That file just imports and renders your root `+error.svelte` as a component. [Mine looks like this ](https://github.com/leereamsnyder/lee-reamsnyder-dot-com-v6/blob/main/src/routes/404/%2Bpage.svelte). It'll inherit all the layout stuff and look like your regular error page if done correctly. If you're not pre-rendering _everything_, this route [needs to be prerendered](https://svelte.dev/docs/kit/page-options#prerender). I also pass in a status code override `404` as a prop, because when SvelteKit renders this in the build the status code is 200 (it exists!), so I have to override that.
3. In your root layout or page, add a `<link href="/404" />` element to the head. I only do this on the home page because it just needs to be in markup once. [Mine looks this this](https://github.com/leereamsnyder/lee-reamsnyder-dot-com-v6/blob/main/src/routes/%2Bpage.svelte#L31-L35). Now, when `adapter-static` runs and parses your output markup for links, it will see that relative link, and add "/404" as a route that it has to output and generate a 404.html. **This is the key! Even if you set a route to pre-render, SvelteKit won't build it unless you actually link to it somehow in your markup**. Adapter-static won't pre-render routes that aren't in "use" somehow.
4. As I [mentioned above](https://github.com/sveltejs/kit/issues/10880#issuecomment-1775782888), in your svelte.config set `kit.paths.relative` to `false`. [Mine looks like this.](https://github.com/leereamsnyder/lee-reamsnyder-dot-com-v6/blob/main/svelte.config.js#L7-L19) You need server-root asset URLs (eg `/_app/immutable/something.123.css`) because Netlify (and presumably Cloudflare) will serve the HTML for `/404.html` for deeper not-found (eg `/someting/that/doesnt/exist/in/a/deep/hierarchy`). If the 404.html has relative paths to CSS/JS files, all those files won't be found because the browser sees you as waaaaay deeper in the pathname hierarchy, and `/someting/that/doesnt/exist/in/a/deep/_app/immutable` doesn't exist. With `relative: false`, the absolute path URLs for build assets will work anywhere on the site (assuming you're deploying at the root `/` pathname) 

So, there: a little setup with the route and some tricky bits a `<link />` and you get a 404.html using SvelteKit stuff.
