### ISSUE TITLE
Sveltekit remembers only the last prefetched link

### ISSUE THREAD

**Issue by kvetoslavnovak** [sveltejs/kit#11056]
### Describe the bug

Not sure whether this is intended but SvelteKit remembers only the last prefetched/preloaded link. If you hover between two or more links SvelteKit refeteches  already  prefetched links/data again and again. SvelteKit does not refetech only if you hover repeatedly over the very same link.

### Reproduction

![Recording 2023-11-16 at 21 24 32](https://github.com/sveltejs/kit/assets/5719547/33621a66-72c8-4067-8397-380e8beb2921)

### System Info

```Shell
Pop!_OS
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is intentional, I believe. We don't want to assume any safe cache TTL that didn't come from the user. In the server `load` function, you should be able to use [`setHeaders`](https://kit.svelte.dev/docs/load#headers) to specify cache headers that will be returned in the response and prevent the browser from making the request again.

**Comment by dummdidumm** [comment]
Yes, this is intentional. @Conduitry's solution to using headers is good. Closing - thank you.
