### ISSUE TITLE
Amplify Adapter

### ISSUE THREAD

**Issue by gzimbron** [sveltejs/kit#11431]
### Describe the problem

Amplify is now supporting SSR for any frameworks
https://aws.amazon.com/es/blogs/mobile/introducing-support-for-hosting-any-ssr-app-on-aws-amplify-hosting/

At this moment I used to deploy static adapter, but It should be great to use SSR.

### Describe the proposed solution

Create an official Amplify SSR Hosting adapter
https://docs.aws.amazon.com/amplify/latest/userguide/ssr-deployment-specification.html

### Importance

would make my life easier

**Comment by benmccann** [comment]
Thanks the suggestion. However, we do not have the resources to create and maintain an adapter for each platform. We'd recommend that someone in the community create such an adapter and submit it to https://sveltesociety.dev/packages#svelte-kit-adapters

**Comment by benmccann** [comment]
Thanks for creating the adapter!

Leaving a link here for anyone who comes across this issue, so that they're aware there's now an Amplify adapter: https://github.com/gzimbron/amplify-adapter

And as always, the community can check for other adapters on https://sveltesociety.dev/packages#svelte-kit-adapters as a few platforms have multiple adapters available
