### ISSUE TITLE
Global styles not persisted after routed page refresh

### ISSUE THREAD

**Issue by mjdNjhNJ** [sveltejs/kit#11588]
### Describe the bug

The bug is causing global styles to dissapear on a routed page after refresh.

The styles that are defined as `:global()` in `src/+page.svelte` dissapeared after the refresh of routed page.

### Reproduction

Clone this repository: https://gitlab.com/SalvageLividly/sveltekit-global-styles-bug

1. Run the server using `pnpm run dev`
1. Check DOM for existing styles of `body` element
1. Navigate to `/contact`
1. Check DOM for existing styles of `body` element which should be the same as in second point
1. Refresh the page

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (8) arm64 Apple M2
    Memory: 177.83 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - /opt/homebrew/bin/node
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.14.0 - /opt/homebrew/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.114
    Safari: 17.2.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.0 
    @sveltejs/kit: ^2.0.0 => 2.2.1 
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.1 
    svelte: ^4.2.7 => 4.2.8 
    vite: ^5.0.3 => 5.0.11
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is the intended behavior, and is one of the reasons why global styles attached to a particular page are not recommended. Every page (and every component) loads its styles when it's first rendered, but does not unload the styles when navigating away from that page (or when destroying the last instance of that component).

That the styles from the root page are still present after client-side navigation to another page is an artifact of this. The styles disappearing after you refresh the page is actually the ideal behavior, and the fact that they persist when client-side navigating is a limitation that we live with so that components don't need to track when they should remove styles.

If you want global styles that are loaded for multiple routes, you can put them in a layout file instead of a particular page file.
