### ISSUE TITLE
Ideas for more adapters

### ISSUE THREAD

**Issue by dominikg** [sveltejs/kit#117]
### github pages
- Could be useful for documentation sites of libraries that don't want to host elsewhere
- Maybe even for dogfooding sveltekit docs

### gitlab pages
pretty much the same as github

### docker image(s)
- single image based off node
- optional http server (caddy, letsencrypt) in front of node

### 3rd party adapter support
  - Documentation on how to create your own adapter
  - official api
  - discoverablity via naming scheme - sveltekit-adapter-foo

**Comment by apoorvmote** [comment]
I personally am very interested in Server Side Rendering with lambda. 

One reason we love Svelte because the best framework is not have framework and compile to vanilla JS.

So on export if you just point out which directory has static assets and which directory has lambda function and how they are connected to each other then deploying part we can do on our own.

At least AWS provides this IAC called AWS CDK.  For beginners it comes with good default values and for advance user you can go in as much detail as you want. So basically person without deep knowlege about AWS can deploy without problem. 

At least in my experience I was able to use any services in AWS without knowing everything then I googled each default value set and was able to customize to my requirements.

**Comment by davidberglund** [comment]
Regarding:
"Before you can deploy your SvelteKit app, you need to adapt it for your deployment target" (https://kit.svelte.dev/docs#adapters)
Wouldn't it make more sense to have "adapter-static" be the default deploy target? Convention over configuration and all that. Static target should help most people get up and running quickly, you'd think.

I know the adapter API is WIP, and I just started looking at the docs for SvelteKit, sry if this isn't helpful at all.

**Comment by amccausl** [comment]
> 
> 
> For github/gitlab pages would the existing `adapter-static` work?

Not as is, problem outlined in #1553

**Comment by jthegedus** [comment]
>Wouldn't it make more sense to have "adapter-static" be the default deploy target? Convention over configuration and all that. Static target should help most people get up and running quickly, you'd think.

I disagree because `adapter-static` requires usage of the fewest features of SvelteKit, so doesn't really demonstrate the flexibility of the framework and could potential confuse people who's expectations aren't managed by their reading of the specific adapter capabilities.

**Comment by boehs** [comment]
Thank you, sorry for the stupid questions

**Comment by Rich-Harris** [comment]
Going to close this in the interests of issue tracker hygience as there isn't specific action we need to take here. There's a couple of [community](https://github.com/MikeBild/sveltekit-adapter-aws) [adapters](https://github.com/architect/sveltekit-adapter) for AWS, and it may be worth promoting something to 'official' status eventually, but for now I don't think there's anything to do
