### ISSUE TITLE
How to change rollup option in sveltekit2?

### ISSUE THREAD

**Issue by LeeYoungHu** [sveltejs/kit#11773]
### Describe the bug

I'm setup rollupOptions like below.

![image](https://github.com/sveltejs/kit/assets/65886694/c80a4123-715b-40af-aa95-dd68129ce898)

but, building file name not change without hash.
what should i do?

I need this option for this issue 
[https://github.com/sveltejs/kit/issues/9089](url)

This issue occurs not finding past files.
so, i want to fixed file name.

### Reproduction

-

### System Info

```Shell
System:                                                 
    OS: Windows 10 10.0.19043                             
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 4.60 GB / 15.83 GB                            
  Binaries:                                               
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (121.0.2277.83)
    Internet Explorer: 11.0.19041.906
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.0.0
    @sveltejs/adapter-node: ^4.0.1 => 4.0.1
    @sveltejs/kit: ^2.4.3 => 2.5.0
    @sveltejs/vite-plugin-svelte: ^3.0.2 => 3.0.2
    svelte: ^4.2.9 => 4.2.9
    vite: ^5.0.0 => 5.0.12
```

### Severity

annoyance

**Comment by Conduitry** [comment]
SvelteKit enforces this Rollup config because it wants to be able to have guarantees about the generated output. Trying to use this to avoid errors like those in #9089 is not a good idea because, for speed, these files are served with a year-long TTL in their `Cache-Control` header, under the assumption that the contents for a single URL (which includes a hash of the contents) will never change even when you deploy new versions of your app.
