### ISSUE TITLE
chart.js not working but no errors

### ISSUE THREAD

**Issue by aradalvand** [sveltejs/kit#11894]
### Describe the bug

It works in the Svelte REPL: https://svelte.dev/repl/dcf956846db84fa28b601e83d28db4c0?version=4.2.12

But the same exact code doesn't work in SvelteKit: https://github.com/aradalvand/sveltekit-chartjs-test

### Reproduction

- Run `git clone https://github.com/aradalvand/sveltekit-chartjs-test`
- Run `pnpm install` and then `pnpm run dev`
- Navigate to the home page
- Notice how the chart isn't rendered, even though there are no errors in the console. And the code inside `src/routes/+page.svelte` is identical to the REPL linked above.

### System Info

```Shell
  System:
    OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 5.76 GB / 11.63 GB
    Container: Yes
    Shell: 3.6.1 - /home/linuxbrew/.linuxbrew/bin/fish
  Binaries:
    Node: 20.6.0 - /home/linuxbrew/.linuxbrew/bin/node
    npm: 9.8.1 - /home/linuxbrew/.linuxbrew/bin/npm
    pnpm: 8.7.1 - /home/linuxbrew/.linuxbrew/bin/pnpm
    bun: 1.0.25 - ~/.bun/bin/bun
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.1.1
    @sveltejs/kit: ^2.0.0 => 2.5.1
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.0.2
    svelte: ^4.2.7 => 4.2.12
    vite: ^5.0.3 => 5.1.4
```

### Severity

blocking an upgrade

### Additional Information

Also tried adding `ssr: { noExternal: ['chart.js/**'] }` to `vite.config.js`, but it had no effect.

**Comment by eltigerchino** [comment]
Probably specific to chart.js: the `<canvas>` element cannot have a parent container with `style="display: contents"`. This is currently the case if you look at the `app.html` template. It works in the Svelte REPL because the immediate parent is the `<body>` element which has a block display style.

You'll just need to wrap your canvas with a container such as `<section>`. See https://stackblitz.com/edit/github-7npp6c?file=src%2Froutes%2F%2Bpage.svelte
