### ISSUE TITLE
ESLint + Typescript results in dependency errors since v9.0.0 inclusion on svelte@latest

### ISSUE THREAD

**Issue by danxcraig** [sveltejs/kit#12105]
### Describe the bug

When using TypeScript syntax and ESLint with svelte@latest, dependencies cannot be resolved.

### Reproduction

npm create svelte@latest example-project
- Skeleton project
- Yes, using TypeScript syntax
- Add ESLint
cd example-project
npm install

### Logs

```Shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: example-project@0.0.1
npm ERR! Found: eslint@9.0.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^9.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^8.56.0" from typescript-eslint@7.6.0
npm ERR! node_modules/typescript-eslint
npm ERR!   dev typescript-eslint@"^7.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.


# npm resolution error report

While resolving: example-project@0.0.1
Found: eslint@9.0.0
node_modules/eslint
  dev eslint@"^9.0.0" from the root project

Could not resolve dependency:
peer eslint@"^8.56.0" from typescript-eslint@7.6.0
node_modules/typescript-eslint
  dev typescript-eslint@"^7.5.0" from the root project
```

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 21.00 GB / 31.92 GB
  Binaries:
    Node: 20.11.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 123.0.6312.107
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.19041.3636
```

### Severity

blocking an upgrade

**Comment by dustsucker** [comment]
I have the same issue, seems to be a major bug.

**Comment by DevLeoko** [comment]
This issue seems to have been introduced in https://github.com/sveltejs/kit/pull/12089
`typescript-eslint` does not yet support ESLint v9 ( https://github.com/typescript-eslint/typescript-eslint/issues/8211 )

When running `npm create svelte@latest` and selecting both ESLint and typescript it currently adds both ESLint v9 and typescript-eslint as a dependency causing the conflict
https://github.com/sveltejs/kit/blob/main/packages/create-svelte/shared/%2Beslint%2Btypescript/package.json
https://github.com/sveltejs/kit/blob/main/packages/create-svelte/shared/%2Beslint/package.json

**Comment by benmccann** [comment]
Ah, it seems we may have upgraded too early. Despite the version warnings and the libraries not being officially compatible it should still work: https://github.com/typescript-eslint/typescript-eslint/issues/8211#issuecomment-2044094079

I wonder how long it will take for a new version to roll out though and if we need to rollback in the meantime :thinking:

**Comment by benmccann** [comment]
I guess the other potential solution would just be to leave the typescript-eslint rules in place, but comment them out and add a note that you should install typescript-eslint and uncomment the rules once https://github.com/typescript-eslint/typescript-eslint/issues/8211 is fixed. This might provide an easier upgrade path for people since it's a bit complicated to upgrade from v8 to v9

**Comment by danxcraig** [comment]
Thank you for both the temp workaround advice and subsequent quick resolve @benmccann  ❤️.

**Comment by jpenna** [comment]
ts-lint v8 will support eslint v9
Until it is the main version, you have to use the alpha: https://github.com/typescript-eslint/typescript-eslint/issues/8211#issuecomment-2106427365
