### ISSUE TITLE
SvelteKitError: Not found: /build/bundle.js

### ISSUE THREAD

**Issue by ARajgor** [sveltejs/kit#12115]
### Describe the bug

I install svelte via `bun create svelte@latest my-app`

I ran this commands,
```
bun install
bun run build
bun run preview
```

when I click on the link generated by the run preview it shows this error,

![image](https://github.com/sveltejs/kit/assets/76404080/8fe8666a-f80b-48da-ac09-fe1661df9f64)

I tried adapter-node and adapter-static but same issue. I didn't change any code. I'm using Skeleton project. 

### Reproduction

install fresh sveltekit via official website [here](https://kit.svelte.dev/docs/creating-a-project)
run `bun create svelte@latest my-app`

then,

```
bun install
bun run build
bun run preview
```

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 452.22 MB / 7.76 GB
  Binaries:
    Node: 20.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.4.0 - C:\Program Files\nodejs\npm.CMD
    bun: 1.1.3 - ~\.bun\bin\bun.EXE
  Browsers:
    Edge: Chromium (123.0.2420.81)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @sveltejs/adapter-auto: ^3.0.0 => 3.2.0
    @sveltejs/kit: ^2.0.0 => 2.5.5
    @sveltejs/vite-plugin-svelte: ^3.0.0 => 3.1.0
    svelte: ^4.2.7 => 4.2.14
    vite: ^5.0.3 => 5.2.8
```

### Severity

annoyance

**Comment by benmccann** [comment]
Works with `npm` and default options chosen when running `npm create`. Please either post steps to reproduce with npm or file this issue with bun

**Comment by ogrotten** [comment]
I'm having very similar error with `npx sv create`, also with brand new projects. Will create a new issue. 

@ARajgor did you find a solution?

**Comment by ogrotten** [comment]
@benmccann FYI I think I discovered the cause of this on my own system.

Turns out that I had a rogue tab related to a work project. Normally, stopping the dev server closes all related tabs. . . except maybe it didn't this time, and that remaining tab kept polling for the server. So when I started a new server for a different proj, on 5173, the tab was probably polling on the same port and getting 404s back from that different project. Looking at the errors that @ARajgor was having, it seems to line up. For me, it would explain why separate distros would have the same problem.

I fixed it by closing all work project related tabs and restarting the browser.
