### ISSUE TITLE
Leak of all sveltekit routes

### ISSUE THREAD

**Issue by skyf0l** [sveltejs/kit#12210]
### Describe the bug

All in the title: it's possible to see all the routes of a sveltekit site in the generated code. Even private routes (e.g. /admin). This can be a vector for security issues.

I don't know if this is important for sveltekit's behavior, but it would be best to avoid revealing all these routes.

### Reproduction

Leaked routes are in the generated `_app/immutable/entry/app.*.js` file. See the end of <https://kit.svelte.dev/_app/immutable/entry/app.5_c18i1j.js> for exemple:

![image](https://github.com/sveltejs/kit/assets/59019720/267116ea-e619-4c01-a34e-4c22bc8d4084)

`de={"/":[3],"/docs":[4,[2]],"/docs/[slug]":[-6,[2]],"/faq":[6],"/search":[-8]}`

### System Info

```Shell
  System:
    OS: Linux 6.5 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 4.03 GB / 15.34 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.12.0 - ~/.nvm/versions/node/v20.12.0/bin/node
    Yarn: 1.22.22 - ~/.nvm/versions/node/v20.12.0/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.0/bin/npm
    pnpm: 9.0.6 - ~/.nvm/versions/node/v20.12.0/bin/pnpm
  Browsers:
    Chrome: 123.0.6312.122
  npmPackages:
    @sveltejs/adapter-cloudflare: ^4.4.0 => 4.4.0 
    @sveltejs/kit: ^2.5.7 => 2.5.7 
    @sveltejs/vite-plugin-svelte: ^3.1.0 => 3.1.0 
    svelte: ^4.2.15 => 4.2.15 
    vite: ^5.2.10 => 5.2.10 
```

### Severity

annoyance

**Comment by Conduitry** [comment]
Yeah, this is by design. Without something like this, the browser would have to reach out to the server for every page change just to do the mapping, which we don't want. It would also be impossible to render out HTML/JS/CSS files for static sites because in that case there _is_ no server to be doing the mapping.

In general you shouldn't be relying on security through obscurity to hide certain parts of your website. If these section display information that is sensitive, put that information behind an endpoint that requires authentication.
