### ISSUE TITLE
Endpoint should not call JSON.stringify(body) if content-type is json

### ISSUE THREAD

**Issue by hgl** [sveltejs/kit#1226]
**Describe the bug**
According to the doc, endpoint's body should only be converted to JSON string when the `content-type` header doesn't exist.

Also converting to JSON string when the `content-type` header is `application/json` prevents the endpoint from functioning as a relay, that is, it can't fetch an API that returns a JSON string and then forwards the headers and the body as they are, because svelte kit would call JSON.stringify on the string again, and `content-length` would also be incorrect.

**Logs**

**To Reproduce**
```ts
export async get() {
  return {
    headers: { 'content-type': 'application/json' },
    body: '{}',
  }
}
```

browser now receives`'"{}"'`

**Expected behavior**
browser should receive `'{}'`

**Stacktraces**

**Information about your SvelteKit Installation:**

**Severity**
Very, being able to make endpoint function as a relay is pretty important.

**Additional context**

I believe this is the code

https://github.com/sveltejs/kit/blob/e616da248f51584e58bece9d0e906638dba43739/packages/kit/src/runtime/server/endpoint.js#L34

I'd be happy to send a PR if svelte kit team think it's ok to remove this condition check.

**Comment by rmunn** [comment]
There may be some use cases where people want to return a JSON string, and have set an `application/json` header explicitly because they wanted Svelte-Kit to convert the string `'foo'` into the JSON string `'"foo"'` for them. This won't happen often, but it will happen. So it should probably be noted in the docs, once this change is made (and I agree that this change should be made) that if you really want a JSON string to be output, you'll need to call `JSON.stringify()` yourself. (But that the automatic JSON stringification will still happen for objects.)
