### ISSUE TITLE
Compatibility with latest version of Vite

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1227]
@GrygrFlzr reported issues with Vite 2.2.3 in https://github.com/sveltejs/kit/pull/1224. The Vite version is currently locked to 2.2.2 in the template. We should fix the error and add back the `^` to the version specifier in the template

**Comment by GrygrFlzr** [comment]
Specifically, [this commit](https://github.com/vitejs/vite/pull/3128) which was supposed to identify `.svelte` files as JS in the Vite repo is triggering the issue. This is probably more of a symptom of a root problem somewhere between Vite or `vite-plugin-svelte`, as the problem was initially encountered by a non-SvelteKit setup [here](https://github.com/reepolee/vite-223-replication). I've made [a minimal SvelteKit reproduction](https://github.com/GrygrFlzr/vite-223-regression) but it's just an extracted version of the failing test in #1224.

**Comment by benmccann** [comment]
CC @dominikg
