### ISSUE TITLE
Cannot disable router when in SPA mode

### ISSUE THREAD

**Issue by weaseldotro** [sveltejs/kit#1229]
**Describe the bug**
Disabling the router in the svelte config file when `ssr: false` will cause a javascript error and the index page will not load.

**Logs**
```
Uncaught (in promise) TypeError: router.goto is not a function
start http://localhost:3000/.svelte/dev/runtime/internal/start.js:1025
```

**To Reproduce**
Install sveltekit, set `ssr: false` and `router: false` in `svelte.config.cjs`

**Expected behavior**
Disable the built-in router and use my own router.

**Severity**
Average.

**Comment by benmccann** [comment]
there's a guard there now:
https://github.com/sveltejs/kit/blob/be30a938c42619d0af61ba98d540c103ffade216/packages/kit/src/runtime/client/start.js#L54

there wasn't when this bug was file:
https://github.com/sveltejs/kit/blob/1d76d66038647c8a67dbb011cf9c0e231fd086a6/packages/kit/src/runtime/client/start.js#L49

so I think this got fixed when we enabled typescript strict mode
