### ISSUE TITLE
Detect svelte.config.mjs and svelte.config.cjs files as config files.

### ISSUE THREAD

**Issue by Karechta** [sveltejs/kit#12331]
### Describe the problem

Due to some limitations i have to use the .mjs ending to have my product chain working.
I tried looking for an Option in the kit, but there is no option to set nor does it automatically detect the file with a .mjs ending.

### Describe the proposed solution

Optimal Solution would be to automatically detect .mjs and .cjs files if they exist and use those.

### Alternatives considered

Alternatively you should add the option to set the path to the config file, which would be a nice QoL feature to structure a project.

### Importance

i cannot use SvelteKit without it

**Comment by Conduitry** [comment]
Can you go into more detail about why you need `svelte.config.mjs`? All SvelteKit projects should have `"type": "module"` in their `package.json`, which means that `.js` files would get treated as ESM.

We really don't want to encourage people to put this file in other places because there are other bits of tooling that also are looking for it in its one place, and they'd all need to be updated as well. We also definitely don't want to be encouraging people to write it in CJS.

**Comment by Karechta** [comment]
Yeah the CJS part was on me.

>because there are other bits of tooling that also are looking for it in its one place

I did not consider this. Thinking about this makes it more logical to restructure my project.

Should not have wasted your time, thanks for the quick response and indirectly helping me find my way!
