### ISSUE TITLE
Cant import local files into svelte.config.js

### ISSUE THREAD

**Issue by Velesarix** [sveltejs/kit#12390]
### Describe the bug

Error [ERR_MODULE_NOT_FOUND] thrown when trying to import a local file into svelte.config.js

### Reproduction

Build a next sveltekit project, then create a file anywhere like test.ts
```ts
const x = 90;
export { x };
```

Then try to import this file into svelte.config.js and it will return Error [ERR_MODULE_NOT_FOUND] on dev or build.

### System Info

```Shell
Windows 11
Vite 5.0.3
Svelte 4.2.7
@sveltejs/kit 2.0.0
```

### Severity

annoyance

**Comment by Conduitry** [comment]
`svelte.config.js` - and all of the files you import from it - need to be javascript, not typescript.

The `ERR_MODULE_NOT_FOUND` is, assuming, happening because you're importing the file without its `.ts` extension, and that file doesn't exist. (If you did import it with the `.ts` extension, you get a different error - `ERR_UNKNOWN_FILE_EXTENSION`.)

**Comment by Velesarix** [comment]
Yeah that was it... Dang now I feel dumb
But thank you
