### ISSUE TITLE
[docs] +server does not inherit from +layout

### ISSUE THREAD

**Issue by sacrosanctic** [sveltejs/kit#12401]
### Describe the bug

As far as I can tell, `+server.ts` does not inherit from `+layout`. I propose to draw a clearer distinction between `+server.ts` and the other +files.

For example, an auth guard placed in `routes/(app)/+layout.server.ts` does not protect `routes/(app)/api/+server.ts`. ([relevant discord thread](https://discord.com/channels/457912077277855764/1254872342182760449))

An inverse example showing the other +files are highly connected is when using `+page@.svelte`. In this case, it also affects which `+page(.server).ts` gets loaded.

The above shows that of the 4 +files, `+server.ts` is logically distinct. Aside from using the same file system to determine its route, it has nothing to do with the other 3 +files and doesn't inherit from any of them.

But the docs seem to imply that `+server.ts` is a part of the family in the way that it is presented:
- [`+layout and +error files apply to subdirectories as well as the directory they live in`](https://kit.svelte.dev/docs/routing)
- ![image](https://github.com/sveltejs/kit/assets/2974920/539e553d-a18b-43c4-84cc-e60906c4f956)

### Reproduction

.

### System Info

```Shell
.
```

### Severity

annoyance

**Comment by CaptainCodeman** [comment]
No, it doesn't, because `+server` is for REST endpoints and has no bearing on `+layout` which is for page rendering (and vice versa). `+layout.server` can access the same server-side event props that `+server` can, that's the only similarity.

As for security, expecting any checks in `+layout.server` to protect any routes underneath is a mistake, unless they all await the parent load fn which can be a [performance killer](https://captaincodeman.com/securing-your-sveltekit-app).

They only reside together because that is how routes are defined.
