### ISSUE TITLE
svelte-kit build --watch options

### ISSUE THREAD

**Issue by kayakyakr** [sveltejs/kit#1250]
### Feature requests and proposals

Pretty short feature request: would love a --watch option for svelte-kit that will re-run the prod build on update.

Why would I want this?

In my case, I'm working on a chrome extension, which can't use the dev server. I have to load it up and refresh it from the build directory, so to dev I currently have to force a rebuild after every change.

**Comment by Conduitry** [comment]
`svelte-kit build --watch` is something that, generally, isn't a good idea to be doing (because of how long each iteration takes), and I don't think we want to tacitly endorse it by having this as an option. I'll let other maintainers weight in, but my vote is that this is something to be taken care of in userland, by using some other tool that watches a directory and calls `svelte-kit build` when appropriate.

**Comment by kayakyakr** [comment]
I'm OK with that solution. I'm sure that there are a few things out there that already watch the directory and execute a script.
