### ISSUE TITLE
Should private module be dropped?

### ISSUE THREAD

**Issue by hgl** [sveltejs/kit#1253]
Maybe I missed something, but it seems private module can be achieved by importing files from outside `routes`.

And the doc also seems to suggest that you can do the same thing with different approaches:

Private module

> ... such as src/routes/foo/_Private.svelte or src/routes/bar/_utils/cool-util.js

$lib

> ... It allows you to access common components and utility modules

If private module can be dropped, it opens up the special naming rule for other stuff like layout as mentioned in #1149

**Comment by Conduitry** [comment]
We don't want to get rid of these, because it's convenient to colocate the private .svelte/.js files with the routes that use them, if they aren't used in a bunch of different places. Neither `_priviate` modules nor `$lib` modules are strictly necessary, but they are different mostly complementary ways of avoiding `../../../../../..` stuff.
