### ISSUE TITLE
%layout.svelte and [param].svelte

### ISSUE THREAD

**Issue by probablykasper** [sveltejs/kit#1254]
Adding my suggestion for what special filenames should look like, re #1149 

### `%layout.svelte`
@Rich-Harris suggested % for params, which I feel strongly would rather be the ideal option for the prefix. Can't see any downside with this.
- Unsafe for URL pathname
- Safe for filenames and terminal link click
- No interference with Twitter/Discord
- Looks better than $ and @ imo

### `[param].svelte`
- Conventional
- Has an opening and closing, which is easier to read: `[one]-[two]` vs `%one%-%two%`
- Unsafe for URL pathname
- Safe for filenames, but not terminal link click, but I agree with @arxpoetica that it should rather be considered a terminal/IDE bug.

**Comment by Mlocik97** [comment]
There was already a lot of talking about this, and I don't think we need new thread... about layout files, Svelte will still use $layout.svelte (it's has few advantages), and yes, there is small problem in VS Code, but issue was created, and VS Code devs plan to fix it... same for [param].svelte, that is as it is now.

**Comment by dummdidumm** [comment]
Closing in favor of #1149 . In #1149 there's already a lot of discussion about chosing the right character set where you can please your comment, so there's no need to open another one.

**Comment by dummdidumm** [comment]
Oh yeah, my bad. Closing anyway because it was locked for a reason, that doesn't mean that the discussion should just continue in another open thread.

**Comment by probablykasper** [comment]
> about layout files, Svelte will still use $layout.svelte (it's has few advantages), and yes, there is small problem in VS Code, but issue was created, and VS Code devs plan to fix it

As far as I could tell from #1149, it didn't seem like a decision was made yet to stick with `$layout.svelte`. Are there any disadvantages to `%layout.svelte` at all? Not being able to type `touch $layout.svelte` is a pretty major drawback, and `@layout.svelte` has the minor drawback of interfering with Discord/Twitter.

> (%) is something in browser used for encoding, so no, it's not good for file name, https://github.com/sveltejs/kit/issues/1149#issuecomment-823339251

I think you're misunderstanding, `%` is advantageous exactly because of that. Since `%` is unsafe for URL pathnames, it makes sense to use it for special filenames.

@dummdidumm Any chance of mentioning my points in #1149? I think there's a pretty solid case for it, especially `%layout.svelte`.

**Comment by Kapsonfire-DE** [comment]
ehm is it that hard to put the filename in singlequotes? 
> touch '$layout.svelte'

**Comment by rmunn** [comment]
Or you could use backslash-escaping and write `touch \$layout.svelte`, that works too.

**Comment by Mlocik97** [comment]
"I think you're misunderstanding, % is advantageous exactly because of that. Since % is unsafe for URL pathnames, it makes sense to use it for special filenames."

I think, the most advantage has !layout.svelte, you can't write it on Windows, so You will be forced to use Unix system with better qulity...

Now for real,... it's disadvantage, because it's used for encoding, and I think, we should not use letters that are typical for something else... I'm strictily agaisnt %layout.svelte it doesn't even look good, and has a lot of disadvantages... for example what if I want server %layout.svelte in browser or use it with URI? It will not be possible.

btw. please lock this thread, because there is again a lot of discusion about this, that was already locked for same "war" reason.

**Comment by probablykasper** [comment]
Don't quite see the argument there, I agree more with Rich on that. Anyways, agreed that this should be locked, point was just to get the suggestion considered
