### ISSUE TITLE
Improve scss compile speed

### ISSUE THREAD

**Issue by nosovk** [sveltejs/kit#12629]
### Describe the problem

There is an article, on how we can improve scars compilation time for one file components.
https://www.oddbird.net/2024/08/14/sass-compiler/

### Describe the proposed solution

Update scss integration to use scss-embed

### Importance

nice to have

**Comment by dominikg** [comment]
sveltekit is a vite plugin at heart. If you use vitePreprocess in your svelte.config.js and follow the instructions in the linked article you are all set

**Comment by dummdidumm** [comment]
As Dominik points out, you can do this today. I'm also not sure what the proposed solution is exactly asking for. SvelteKit nor Svelte provide SCSS out of the box, it's Vite that does it for SCSS files, and when using SCSS inside Svelte style tags, you can use svelte-preprocess for that.

svelte-preprocess does not have an built-in option currently to use `sass-embedded` - is this what this is about?

**Comment by dominikg** [comment]
not sure if svelte-preprocess has a way to keep the embedded instance going, but worth investigating as it could provide a nice speed bump for users who dont use vitePreprocess

**Comment by nosovk** [comment]
I think that it could be implemented in basic setup template to improve compile time. Probably it should be addressed to svelte-preprocess, as far I see scss is not part of standard sveltekit setup now.

**Comment by dominikg** [comment]
we don't have scss enabled by default in templates and there are no plans to add it because many of its features are supported natively by css now (props, nesting, calc).

In case you stil need it, our docs already recommend [vitePreprocess](https://kit.svelte.dev/docs/integrations#vitepreprocess ) and vite docs show how to enable modern-compile for scss [here](https://vitejs.dev/config/shared-options.html#css-preprocessoroptions)

Now this could be documented a little bit better on the vite side there is really not a lot for kit itself to do here. I recommend checking the vite documentation and if you find them lacking, to send a PR with improvements so all of vite community benefits from it.

In case you prefer to use svelte-preprocess over vitePreprocess, filing a feature request there for support of modern-compile will help.

**Comment by nosovk** [comment]
Thanks, it seems that nowadays there is no need in scss, it was even removed from svelte-add
