### ISSUE TITLE
Dynamic Route Parameters Options

### ISSUE THREAD

**Issue by lsabi** [sveltejs/kit#1268]
**Is your feature request related to a problem? Please describe.**
So, I'm using a dynamic route in a file `/path/[slug]-[id].svelte`. If I navigate to `/path/foo-1`, the variables are assigned as follows

slug === "foo"
id === "1"

Instead, when I navigate to `/path/foo1-foo2-1`, then the variables are assigned as follows

slug === "foo1"
id === "foo2-1"

**Describe the solution you'd like**
What I expect is for the first dynamic parameter to match the longest possible pattern. Otherwise, at least, have a way to specify it. For instance the regex `[a-zA-Z-]*-[a-zA-Z]` matches the pattern with the last characters after `-` to be in the second part, but this is not a valid name for a file.

Also, the docs IMHO could be more extensive regarding this subject.

**Describe alternatives you've considered**
One can match the entire part of the route and then split it.

**Comment by benmccann** [comment]
Hmm. This is difficult because the URL is ambiguous with respect to the pattern. In your case the request makes sense, but if someone else had `[id]-[slug]` they'd probably want the opposite (though I think your URL looks nicer in that case). Or another example would be if someone wanted `[slug]-[date]` where date is something like 2021-04-28.

Maybe we need a way to provide regexes and slug extraction to the router

**Comment by Conduitry** [comment]
One of the reasons for implementing route fallthrough was so that we could get rid of Sapper's regex route params.

I don't have strong opinions about how to resolve this. _Maybe_ it would be nice for SvelteKit to provide all different partitionings of the path and try them in some arbitrary order, but that sounds annoying.

A simpler solution would be to pick one way to handle this, document it, and also document that if people want different behavior, they can use a single param for the folder name or filename and then do their own splitting and fall through if appropriate.

**Comment by benmccann** [comment]
I hadn't thought of the single param solution. I agree that's the best way to handle this and documenting it would be nice

**Comment by lsabi** [comment]
As @benmccann suggested, a single dynamic parameter can be matched against a regex in the `load` function. Though the developer has then to redirect to a `404 Not found` url. It could become tricky to maintain, especially for big projects.

Another possibility could be to specify a regex that `sveltekit` can use to match against the dynamic parameter and handle the routing in case of 404. In case the route exists/is valid, one will then access the parameter and split it wherever more appropriate.

**Comment by GrygrFlzr** [comment]
> the developer has then to redirect to a 404 Not found url

We can already take advantage of fallthrough by not returning in the `load` function, so non-matches would already turn into a 404.

**Comment by irg1008** [comment]
Sorry to type in here again but this is not working for me:

"We can already take advantage of fallthrough by not returning in the load function, so non-matches would already turn into a 404."

Instead of falling back to 404 page it says:
"Bad request in load function: failed to fetch undefined"

**Comment by benmccann** [comment]
There's an open bug for that: https://github.com/sveltejs/kit/issues/2041
