### ISSUE TITLE
Prerender based on different domains

### ISSUE THREAD

**Issue by maxfriedmann** [sveltejs/kit#12834]
### Describe the problem

We're running a webapp that shows different content based on the browser/request domain. How can we use prerendering in this case? I don't see an option to tell the prerenderer entry routes which domains I want to have prerendered, just paths... And globally I can only set one base origin. 

Example: domainAAA.com/home renders something completely different than domainBBB.com/home. So am not talking about dynamic routes. 

### Describe the proposed solution

Instead of only passing prerender routes, I'd also like to add the host header / domain / origin 

### Importance

i cannot use svelte (prerendering) without it

**Comment by eltigerchino** [comment]
Hi Max, I believe you'll need to run multiple builds for that if you want to continue with prerendering, otherwise you may want to look at dynamic rendering based on the domain. Prerendering the home page with different domains isn't supported because it will produce a single file `index.html` on a single build. However, different paths allow us to prerender multiple pages because we will have multiple files such as `a.html`, `b.html`, etc.

**Comment by BohdanK-W32** [comment]
That one is really a blocker for a SvelteKit to become an ultimate solution in front-end/full-stack frameworks world
