### ISSUE TITLE
Please add an adapter for Digital Ocean App platform

### ISSUE THREAD

**Issue by oliver-lehner** [sveltejs/kit#1314]
I fiddled around trying to get the sample project to build on [DO's app platform](https://docs.digitalocean.com/products/app-platform/) using the node and static site adapters. I gave up because I'm quite incompetent. So I tried to deploy on vercel with the corresponding adapter and it just works instantly and beautifully. I want this experience for Digital Ocean too because I am already hosting all of my little side projects there. It's quite a popular platform, so I'm sure it's worth the effort. Thanks for considering my request.

**Comment by benmccann** [comment]
I think this is a great idea, but we don't want to be responsible for creating an adapter for each different hosting platform. Our hope is that the community will create adapters for the various platforms. It's too difficult for us to do because we would need accounts at each one and knowledge of each
