### ISSUE TITLE
Add HTTP Status Codes ENUM

### ISSUE THREAD

**Issue by Kapsonfire-DE** [sveltejs/kit#1439]
**Is your feature request related to a problem? Please describe.**
When giving proper error codes in response of endpoints/loads sometimes I have to google for the correct code, like PAYMENT_REQUIRED, BAD_REQUEST and some other things. Most Codes are well known, others not. To make it easier implementing a ENUM is a good solution.

**Describe the solution you'd like**
I'd like to get the Status Code ENUMs integrated in svelte kit. 

**Describe alternatives you've considered**
I started using https://www.npmjs.com/package/http-status-codes package.
```javascript
export async function post(request) {
    let ct = request.headers['content-type'] ?? '';
    if(ct !== 'application/json') {
        return {
            status: StatusCodes.BAD_REQUEST,
            body: ReasonPhrases.BAD_REQUEST
        };
    }
    let data = request.body;
    return {
        body: data
    }
}
```

A decision has to be made. 
1)
I can create a PR and add it to svelte kit. 
2)
A already written npm package could be put into the package.json.
3)
Leave it to the user like current state.

**Comment by dummdidumm** [comment]
Personally I'm against adding this as a dependency or adding this built-in. I could imagine adding this to the docs somewhere though.

**Comment by Kapsonfire-DE** [comment]
@dummdidumm what are the reasons, why you are against it. I could think of the additional footprint on client. 
But to solve this the ENUM could be replaced on preprocess

**Comment by rmunn** [comment]
I'd be against this for two reasons:

1. There's already an NPM package (probably several packages) that can solve this issue completely, for those who want it, and
2. Many people won't want to add the package because they're only using well-known codes like 200 and 404.

So there's no need to add this into Svelte-Kit core. The people who want this, and are willing to pay the cost of [an extra 3.5 kB sent to the client](https://bundlephobia.com/result?p=http-status-codes@2.1.4), can use the `http-status-codes` package. Those who can't easily remember the status codes but don't want an extra 3.5 kB bundle size can create a single file with constants for just the ones they use, or even just put a comment on every unusual status code they use (`status: 202  // ACCEPTED`) to make it easy. And finally, those who don't need it won't have to pay an extra 3.5 kB size cost.

**Comment by benmccann** [comment]
I'm going to close this for the reasons given in the above comment
