### ISSUE TITLE
Hooks for passing default fetch options

### ISSUE THREAD

**Issue by intrnl** [sveltejs/kit#1473]
**Is your feature request related to a problem? Please describe.**
When building sites containing authentication, it's often that you'd encounter something like this:

```js
export async function load ({ fetch, page, context }) {
  // ...
 
  let resp = await fetch('https://api.example.com/entries/1', {
    headers: {
      'Authorization': `Bearer ${context.token}`,
    },
  });

  // ...
}
```

This have the potential to get unwieldy especially when trying to do multiple fetch requests.

**Describe the solution you'd like**
A `getFetchDefaults` hook

```ts
function getFetchDefaults (args: FetchDefaultsHookArgs): FetchDefaults;

interface FetchDefaultsHookArgs {
  request: Request;
}

interface FetchDefaults {
  headers?: Headers | string[][] | Record<string, string>;
  // ...
}
```

The defaults passed from this hook gets merged for use in the `load` function of pages

**Describe alternatives you've considered**
I'm not sure about any other alternatives worth pursuing, there might be a better solution for this.

**How important is this feature to you?**
Somewhat important, I think it would heavily benefit everyone else too.

**Additional context**
None.

**Comment by Rich-Harris** [comment]
This seems like something that can be solved in userland with very little boilerplate — I definitely don't think it warrants adding new surface area to the framework, where we'd need to figure out all the complexities around merging semantics (and what happens when the `fetch` call passes a `Headers` object vs a POJO, etc etc etc). 

If we implemented #2979 it could be done with less boilerplate still.
