### ISSUE TITLE
How can I send secure API requests from SvelteKit app, without showing API keys on the client side?

### ISSUE THREAD

**Issue by sbutler-gh** [sveltejs/kit#1474]
I'm using Supabase for a new Sveltekit app, with this template (https://github.com/joshnuss/svelte-supabase)

Currently, I'm passing the Supabase keys through on the client side, like this:

```
const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY
)
```

What is the simplest way that I can create a secure backend/API, so the application can fetch content from Supabase, without showing Supabase key on the client side?

Is there any functionality built into Sveltekit that enables me to do this?  Or would I need to integrate a backend like Rails?

**Comment by Conduitry** [comment]
Make the requests from an endpoint rather than directly from a page, so the keys only exist on your server.

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).

**Comment by sbutler-gh** [comment]
Thanks so much for the tip @Conduitry 

FYI when you click `New Issue`, **Questions and Help** is listed as one of the options, so others may see that and share similar types of support question.

Not sure if the `New Issue` UI/options are hardcoded from GitHub or customizable within the organization, but just wanted to note that if helpful

**Comment by babichjacob** [comment]
The issue opener only has that option so that this message can be shown:

> This issue tracker is intended to collect bug reports and feature requests.
For help with installation, information on how features work, or questions about specific features of SvelteKit, please come and join us in the Svelte Discord, or ask your question on Stack Overflow. Any issues open for help requests will be closed to keep from clogging up the issue tracker.

to prevent issues like this from being created.

**Comment by sbutler-gh** [comment]
That makes sense @babichjacob 

Perhaps the clarification message could be made more explicit.  I just clicked "New Issue" again, and was still confused by the sequence.

Of course, this doesn't matter very much if I'm one of the rare folks to misunderstand — if it happens more often, could be worth considering

Something like:
> **PLEASE DON'T SUBMIT ANY QUESTIONS HERE**
> 
> This issue tracker is intended to collect **bug reports** and **feature requests**.  If you have one of those, return to the previous page and select one of those options.
> 
> For support, help, or any questions about how things work, please come and join us in the [Svelte Discord](https://discord.com/invite/yy75DKs), or ask your question on [Stack Overflow](https://stackoverflow.com/questions/tagged/svelte). Any support or help requests will be closed to keep from clogging up the issue tracker.

**Comment by dominikg** [comment]
it is possible to disable creation of blank issues and use links to provide directions for topics not covered by a template eg https://github.com/sveltejs/vite-plugin-svelte/blob/main/.github/ISSUE_TEMPLATE/config.yml

**Comment by dominikg** [comment]
enabling github discussions could also be an option

**Comment by sbutler-gh** [comment]
> enabling github discussions could also be an option

From a UX perspective, this is the first thing that I looked for.  I was a little bit confused to see that a project with this large of a community doesn't have it.

I understand not wanting to spread the conversation to thin between GH Issues, GH Discussions, Discord, and any other platforms, and have a go-to location (Discord).  It also seems that Discord lacks the capacity for the kinds of threads and dedicated discussions which could be of value.  Maybe it's time for someone in the SvelteKit community to build a SvelteKit chat tool for the SvelteKit community!

**Comment by lsabi** [comment]
@Conduitry I believe this should be documented though. I've used sapper quite a lot and was used to using a middleware in order to forward requests starting with `/api` to my other, internal, endpoint and adding the keys.

Now, I'm migrating to `kit` and this is all strange to me, and I'm not sure how to deal with it. The `load` function is documented, but it does only suggest not to use private keys/tokens in the load function, without suggesting/linking the proper way of doing it. Adding endpoints can be a solution, though it'll be quite long if the api contains many possible routes, all sharing the same codebase (is there a way to create just one endpoint, e.g. `api` under which all requests are added the token and forwarded to another service?).

It would be nice if either `kit` implemented some sort of middleware to forward requests that have sensitive information, or if there was an example to show how a possible solution could make it work.

**Comment by AleCandido** [comment]
Quote @lsabi and: what about static generation?

I would like to use `kit` for reading bunch of markdown files provided by an external API and consume it to produce pages.

Think about a markdown folder hosted somewhere else, with subfolders and so on: if it were leaving inside `src/routes` folder it would have been translated to the proper thing, but this way I need some sort of redirection.

And *endpoints* are not really an option for static rendering @Conduitry, or am I wrong?

**Comment by lsabi** [comment]
@AleCandido it doesn't matter if it's static or dynamic. In order to generate a static website, you need to run the whole app and get the pages. In order to get the pages you have to perform the request to the API. In my case I was forwarding the requests via a middleware and adding the secret API key.

That's why I was confused and would like the docs to describe it in details. The middleware was a really nice thing to have in sapper and can slow down the development/transition to kit.

I solved my problem with an endpoint that forwards every request, though it doesn't feel the right approach...

**Comment by AleCandido** [comment]
I'm not sure I'm understanding: my point about static was that endpoints are supposed to run on a server (that is not present while serving static pages), and I'm not sure they are served during static generation (I can't tell just reading the docs).

So forwarding doesn't seem an option for SSG, and the disclaimer on `load` instead does apply even for static, since the code in load would be shipped to client (and run there), so you can't consume APIs the require secrets.

Where am I supposed to consume the API then? (I'm sorry I have no experience with sapper)

**Comment by lsabi** [comment]
@AleCandido with a static website, you cannot have secrets because you serve files with no backend (you have it, but it just serves files with no logic). Also, if you are using sapper, this is another project

**Comment by AleCandido** [comment]
No, I mentioned sapper because you compared to it, but I have no experience and not going to try it.

Actually I generated static sites with other generators and I have secrets: you use them at generation time.
The problem is that static does not mean there is no client-side javascript, so I would like to have secrets and naively I would use them in `load` function, but then `load` would try to rerun on client.

**Comment by lsabi** [comment]
If you have secrets, you'll always have them. Either you setup a server and proxy requests by adding the secret or you'll reveal the secret. This works for any website, static or not.

My point is, to provide an example of how to surpass this problem with a normal website, since static website won't rely on any backend logic per se (e.g. sessions).

**Comment by AleCandido** [comment]
I'm stil not getting it: if I need a token to consume an API for getting some content, I can use it to retrieve what I need, generate all my static pages, and then trash the token (up to next generation), so:
- no need for a server, and
- no need to reveal the secret

Simply if I want to generate my site on CD I need the token to be available on that machine (and I can make it available as a secret), but simply I don't want to rerun the function that made use of the secret, that in this case is `load` (or anything accessed by `load`).

Then for sure the thing for normal websites is **also** relevant, that's why I quoted you in the first place, but since `kit` (or better Sapper) has been (also) presented as [Next.js for Svelte](https://sapper.svelte.dev/docs#Comparison_with_Next_js), and even Next.js claims to be (also) a SSG, I would say that also the static case is quite relevant.
Think about all the projects that are hosted on Github Pages (or other similar hosts): no backend available, nevertheless you might want to consume an API while generating.

**Comment by lsabi** [comment]
I thought you meant to generate a static website and to consume, from the client dynamically from an API.

Well, it's similar to my case and I that's why I commented, asking for an example with the most appropriate way of solving the problem.

**Comment by AleCandido** [comment]
I wonder if at this point we should open a new issue: this one being closed looks like no one cares much...
