### ISSUE TITLE
Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#1506]
**Describe the bug**
Warning in console:

`Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.`

**To Reproduce**
svelte-kit init

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`:

  System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.13.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/kit: 1.0.0-next.108 => 1.0.0-next.108
    svelte: 3.38.2 => 3.38.2
    vite: 2.3.3 => 2.3.3

- Your browser: Chrome 90

- Your adapter (e.g. Node, static, Vercel, Begin, etc...): static
</details>

**Comment by dummdidumm** [comment]
This is a result of #1263 . You either can opt in to floc if you want to, or just ignore this.

**Comment by frederikhors** [comment]
I am always of the opinion that a default browser warning is wrong.

**Comment by bugs181** [comment]
> I am always of the opinion that a default browser warning is wrong.

Then you may wan't to complain to Google for introducing this "feature" to begin with. ;)
Google is an analytics company and not all of it's users deserve to have their privacy invaded with an "opt-out" feature. The browser is complaining because it's not letting the browser fingerprint you.

You can read more about it [here](https://seirdy.one/2021/04/16/permissions-policy-floc-misinfo.html) and [here](https://paramdeo.com/blog/opting-your-website-out-of-googles-floc-network)

**Comment by jonathanstanley** [comment]
One way to address this is to edit your `svelte.config.js` to allow FLOC during development-only. 

```js
const config = {
  // etc...
  kit: {
    // etc...
    floc: process.env.NODE_ENV === "development",
  },
};
```

IMO, I would only allow this if using Brave browser, which has entirely [disabled FLOC at the browser level](https://brave.com/why-brave-disables-floc/) 🤩.  Otherwise, development is essentially the same as Google Chrome.
