### ISSUE TITLE
Why is redirect not supported from __error.svelte cmpt?

### ISSUE THREAD

**Issue by alexbjorlig** [sveltejs/kit#1574]
I have a small [reproducible](https://github.com/alexbjorlig/sveltekit-redirect-question) example here.

In the `__error.svelte` cmpt I have thrown in a redirect like this in the load function:

```ts
 return {
                status: 302,
                redirect: '/login'
            }
```

But this is not working. Is this a bug, not allowed - or do I misunderstand something here?

**Comment by alexbjorlig** [comment]
In other words - are redirect supported from the `__error.svelte` cmpt or not? Because if they are supported, there is a bug ☺️

**Comment by frederikhors** [comment]
I would just like to add my voice to this problem. I think the same @asalexbjorlig, it must redirect.

**Comment by benmccann** [comment]
There's a whole bunch of bugs here that are all coupled together (e.g. https://github.com/sveltejs/kit/issues/1942 https://github.com/sveltejs/kit/issues/1576). I think that there's a general problem that error components are rendered in their own code path and don't share the general page rendering code. I think this whole section needs to be refactored

https://github.com/sveltejs/kit/blob/4e8e69c1ab16b08678a6d2be8796e17e41482c52/packages/kit/src/runtime/server/page/respond.js#L131

**Comment by benmccann** [comment]
One danger here is a possible infinite redirect if you redirect to a page that has an error or can't be found, etc.

**Comment by benmccann** [comment]
We just need to add a check for `error_loaded.loaded.redirect` right before this line:

https://github.com/sveltejs/kit/blob/5538107377a6685ed78c666e8a77dd9a4184f5f0/packages/kit/src/runtime/server/page/respond.js#L165

**Comment by iOiurson** [comment]
From what i can read, for 404s, `server/page/respond` never gets called since, when accessing an unknown page, it never gets past

https://github.com/sveltejs/kit/blob/5538107377a6685ed78c666e8a77dd9a4184f5f0/packages/kit/src/runtime/server/index.js#L60

and goes straight to `respond_with_error`, which does not seem to implement the redirect features.

I haven't tested for errors other than 404 yet, behaviour probably is different.

**Comment by benmccann** [comment]
Ah, yeah, it looks like 404 and the rest are implemented differently. My last comment is about how you'd implement for the rest

One thing we'd need to test is to make sure you can return a redirect status on `_error.svelte` (e.g. `{ status: 302, redirect: ... }`). If you leave the status as 404 the redirect will be ignored by the browser: https://github.com/sveltejs/kit/issues/2068#issuecomment-893961933

**Comment by iOiurson** [comment]
Some work is being done [here](https://github.com/sveltejs/kit/pull/2127), still in draft.

I think i handled redirections from `__error` in these cases:
- [x] server redirect on errors
- [x] server redirect on 404
- [x] client redirect on errors
- [ ] client redirect on 404
- [ ] client redirect only on browser ([edgy](https://github.com/sveltejs/kit/blob/c3c25ee09fb8d108ecbe1afc85a52e1b27411bcc/packages/kit/src/runtime/client/renderer.js#L191))

Would there be other cases i missed ? Let me know if anything pops to mind.
I might also need to write some tests, but i haven't looked into it that much yet.

I'll probably open a PR in the days to come.

*P.S: There is also #1575 that could be handled in this PR, but maybe i should work on it in a different PR. What do you think ?*

**Comment by benmccann** [comment]
That's great! Thanks so much

It looks good so far. Tests would be a good idea. You could add them in `packages/kit/test/apps/basics/src/routes/redirect/` based off the existing tests

#1575 could be handled in the same PR or a different PR

**Comment by benmccann** [comment]
I talked about this with the rest of the maintainers at today's maintainer's meeting. Folks suggested you could already do this in one of a couple ways:

- for the 404 case, create a `[fallthough].svelte` that would catch any unhandled routes and redirect there
- for other cases, do it in `handle`. (call `resolve`, check the returned status, and then do a redirect based on that)

There was a consensus that redirecting on error pages is in general a bit of a weird thing to do and so folks didn't want to add support for it directly into the router, but instead suggested it be handled in these other ways since it's a relatively uncommon use case

**Comment by PlopTheReal** [comment]
Hey I've added a [fallthough].svelte but it doesn't catch 404 form urls with subsequent path:
/someInvalidUrl => ok
/someInvalidUrl/otherPage => not ok
Any ideas to catch all urls that are giving 404s?

**Comment by PaintingWithCode** [comment]
@PlopTheReal I don't know if you were able to solve it, but I managed to get a catch-all 404 redirect working by adding a `+error.svelte` at the root of `/routes` with the following script:
```svelte
<script>
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';

	if ($page.status === 404) {
		goto('/');
	}
</script>
```
