### ISSUE TITLE
Why is redirect from `__layout.svelte` ignored, when an unkown route is hit?

### ISSUE THREAD

**Issue by alexbjorlig** [sveltejs/kit#1575]
I have a small reproducible example [here](https://github.com/alexbjorlig/sveltekit-redirect-question).

In the above repo, there is `__layout.svelte` file, that will redirect like this: 

```ts
return {
  status: 302,
  redirect: '/login'
}
```

Works great when a route is matched, but if there is an error the redirect is not respected.
The load function does actually run, but the browser is not redirected to login.

Is this a bug, not allowed - or do I misunderstand something here?

**Comment by benmccann** [comment]
Can you explain your use case and why you'd want to redirect instead of showing the error page?

**Comment by alexbjorlig** [comment]
I expect the following: 

1. User attempts to access application, an unknown route is hit
2. __layouat.svelte is then processed, and determines in this case it's best to redirect to `/login`


BUT the above is not what happens, **despite** the layout's load function actually being called(!)

**Comment by benmccann** [comment]
Right. But what's your use case? I.e. what application are you building, what is the user doing in your application, what are you trying to accomplish?

**Comment by alexbjorlig** [comment]
My usecase here is to redirect user to login, when trying to access a route that does not exists. Combined with layout resets, that would be a powerfull way to show some users 404 pages, and redirect others to login.

**Comment by benmccann** [comment]
If you have a redirect on the error page as requested in https://github.com/sveltejs/kit/issues/1574 why do you need one on the layout to do that?

**Comment by alexbjorlig** [comment]
Ok so It's a bit hard to explain without a conversation for me. But let's be concrete. Why is a redirect from __layout.svelte ignored? The load function runs, and returns a redirect. The redirect is then, silenty, ignored. That's is the purpose of this issue to put clarification to. As a developer, I expect a redirect to happen when I return a redirect 😅

**Comment by benmccann** [comment]
> Why is a redirect from __layout.svelte ignored?

It's not ignored in the general case. But if you hit an error then it might not have a chance to execute. That actually seems like the more intuitive behavior in my mind.

**Comment by Kapsonfire-DE** [comment]
But the __error.svelte is using the __layout.svelte, isnt it?
so the redirect should execute. this is not the case - I had this issue before. 
Why I needed it: I didnt want to give the user a 404 Error page for my mobile game - Instead I wanted to recover to a proper state (home route). I ended up, to make a redirect on the __error.svelte itsself - this worked.

But to sump up, the bug is here. __error.svelte ignores the redirect of the __layout.load
But there are circumstances which should be pointed out....

What happens if multiple redirect statements are up here, like nested layouts or one in layout and one in the route itsself?

**Comment by benmccann** [comment]
> I didnt want to give the user a 404 Error page for my mobile game - Instead I wanted to recover to a proper state (home route)

Wouldn't you expect to put the redirect in `__error.svelte` in this case? I think `__error.svelte` is called when navigating to a route that doesn't exist. I'm not quite sure how you'd detect this in `__layout` (there's an open issue to be able to detect if it's being rendered with an error state https://github.com/sveltejs/kit/issues/598)

**Comment by Kapsonfire-DE** [comment]
the issue goes for __error.svelte as well, it does not respect the redirect return - you linked it already
https://github.com/sveltejs/kit/issues/1574

But in my case, I worked in folders and nested layouts and with reset, So i knew, if the basic layout loaded, its either 404 or not logged in - special case. but still we have to point out
1) why is it not respected?
2) what happens if multiple files returns a redirect (nested layouts or layout + route)

**Comment by annaghi** [comment]
My use case is the following: when a page not found, instead of a dedicated error page I would like to be able to display a notice on the page to which I redirected to. Something like this:

![page-flows](https://user-images.githubusercontent.com/8246853/124512387-8771f900-ddd8-11eb-8e23-824c1ca090bf.gif)

I can imagine two solutions for this:
- define explicitly the page to redirect to, and be able to catch if a page displayed "normally" or as a result of redirection
- automatically try to find a matching route by cutting out more and more segments from the end of the URL. For example:
Given a non-existing URL: `mysite.com/existing/path/ruined/here`
`mysite.com/existing/path/ruined/here` -> non-existing, try to redirect
`mysite.com/existing/path/ruined` -> still non-existing, try further
`mysite.com/existing/path/` -> this one exists, redirect here, and if needed display a notice about the missing page

The latter might be useful in case of non-existing details page automatically redirect to the list page: `/posts/9xy99` -> `/posts`

**Comment by benmccann** [comment]
I'm still not understanding how the layout is involved in that case

**Comment by Kapsonfire-DE** [comment]
Think about a /admin/ route... Put there a layout file, and do the isAdmin check here in the load function of the layout file, and redirect if not logged in to a login page.

Doing this is useful, because you dont have to do it in every route of the /admin/ folder
/admin/users.svelte
/admin/news.svelte
/admin/groups.svelte


and so on....


But well we could just export a variable in load function and check it afterwards and redirect with goto

**Comment by benmccann** [comment]
Yeah, that's a good use case. Ok, I'm convinced

**Comment by benmccann** [comment]
@Kapsonfire-DE if you're hitting those routes and they exist then it's not a 404. The question would be what should happen when you hit `/admin/does-not-exist`. Should you 404 or redirect to the login page? I'd probably say that you should 404

**Comment by Kapsonfire-DE** [comment]
in that case yes - but I have another usecase in my mobile game, where i want to reset to a valid state and in that case im gonna redirect

**Comment by Allezxandre** [comment]
I think I might have figured out a likely culprit to missing redirects (be it in `__layout` files or even their leaf pages).

The redirect returned by your page's `load` function gets lost when the result goes through [`_get_navigation_result_from_branch`](https://github.com/sveltejs/kit/blob/155b088768cf30c7442926cb91fe8f467693e78c/packages/kit/src/runtime/client/renderer.js#L445): the `result` returned by the function never includes a `redirect`.

So after this function call [here](https://github.com/sveltejs/kit/blob/155b088768cf30c7442926cb91fe8f467693e78c/packages/kit/src/runtime/client/renderer.js#L183), [this check of a redirect](https://github.com/sveltejs/kit/blob/155b088768cf30c7442926cb91fe8f467693e78c/packages/kit/src/runtime/client/renderer.js#L195) never passes, and a redirect is missed.

**Comment by baseballyama** [comment]
Now I'm working on https://github.com/sveltejs/kit/issues/2424.
And inside this issue, there is a comment that  https://github.com/sveltejs/kit/issues/2424 is maybe related to this.

So I read all comments but still, I'm confusing what is the issue.

I summarized this issue.
So Could you please tell me if wrong or lacking point is there.
And let me know about the Issue3 about your opinion.

## (CLOSED) Issue1 : Redirect if request page is 404

> User attempts to access application, an unknown route is hit
> __layouat.svelte is then processed, and determines in this case it's best to redirect to /login

> in that case yes - but I have another usecase in my mobile game, where i want to reset to a valid state and in that case im gonna redirect

Already maintainers talked about it at maintainer's meeting.
And their suggestion is below way (Please see the link).
https://github.com/sveltejs/kit/issues/1574#issuecomment-919336290

Some comments in the issue mentioned regarding 404 case,
but this is already closed and we don't need to discuss it.

## (CLOSED maybe) Issue2: Redirect if some condition is true (e.g. Login Status)

> Think about a /admin/ route... Put there a layout file, and do the isAdmin check here in the load function of the layout file, and redirect if not logged in to a login page.
> Doing this is useful, because you dont have to do it in every route of the /admin/ folder
> /admin/users.svelte
> /admin/news.svelte
> /admin/groups.svelte
> and so on....

In that case we can use `__layout.svelte` or `__layout.reset.svelte`.
And `load` function is working properly at least in my environment.
(I can redirect wherever I want.)

So I think this is also not issue. (Is this correct understanding??)

## (???) Issue3: Documentation

According Issue1, `__error.svelte` can not use redirect.
But actually, the document doesn't mention that.
So maybe more people will have the same confusion in the future.
We should update the document about it IMO but what do you think?

https://kit.svelte.dev/docs#layouts-error-pages
https://kit.svelte.dev/docs#loading-output-redirect

**Comment by Rich-Harris** [comment]
The semantics get awfully fuzzy if you try to redirect while rendering an error page. What if an error happens while rendering the page you were redirected to — do we start again, re-executing the root `__layout` and following any redirects encountered? By what mechanism do we prevent infinite loops? It's something that _sounds_ obvious (I asked for a redirect, and I want a redirect dammit!) but as soon as you get into the implementation details it turns out to be fraught.

In fact I would say that in general, interfering with errors is dangerous — if something goes wrong, it's usually better to just communicate it than to try and course-correct, since the number of ways in which things can fail usually exceeds our ability to plan for them. Luckily though, there is a very easy way to get the behaviour you want in the 404 case — just add a [catch-all rest route](https://kit.svelte.dev/docs/routing#advanced-routing-rest-parameters) (and I would typically do the redirecting there rather than in the `__layout`).

We probably _do_ need better error messages here — if a `redirect` is encountered while rendering an error page (whether in a `__layout` or an `__error` component) we shouldn't just silently ignore it.

**Comment by Rich-Harris** [comment]
Going to close this as it's been obsoleted by the changes in #5748 — it's no longer possible for an error page to have a `load` function, meaning this situation can never arise (and errors need to be dealt with more explicitly)
