### ISSUE TITLE
Tests fail if a SvelteKit app is running somewhere else

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1591]
**Describe the bug**
It should fail because the port is occupied, but it doesn't — instead it tries to run the test suite against the already-running app, which is confusing as hell

**To Reproduce**
Run a SvelteKit app, then inside `packages/kit` do `pnpm test:integration` and watch things fail in interesting ways

**Expected behavior**
It should report that the port is occupied and fail

**Severity**
Irksome, for those of us developing the framework. Inconsequential for everyone else

**Comment by sidharthv96** [comment]
I also faced this issue yesterday.
Here are some things I observed.

- The tests inside port-authority works perfectly.
  - If I have another server in 3000, the tests fail
  - Else, all tests pass 
- When running `pnpm run dev` the tests inside svelte kit tries to run on the background server and acts weird
- When running `pnpm run dev -- --host` the test inside svelte kit fails instead of staring on 3001
- When a background server is running
  - If I try to create a new server using this script, it works
  - The same command again in another terminal, it fails
- But if this script is running in a shell
  - `pnpm run dev` fails as expected.
  - port-authority test fails as expected. 
```js
import * as net from 'net';
const server = net.createServer();
server.listen({ port: 3000 }, () => {
	console.log('Running');
});
```

## Fix
Adding host: 'localhost' to server.listen in port-authority fixes the issue.
