### ISSUE TITLE
Assets path wrong when importing from nested routes

### ISSUE THREAD

**Issue by rohanharikr** [sveltejs/kit#1634]
**Describe the bug**

My project structure is as follows:
```
routes
│   login.svelte
└───wizard
│   │   email.svelte
```

When adding an img tag that uses an image from the `static` folder
`<img src="logo.svg"/>`

This works correctly for the `login` route but not for `/wizard/email` route.

A fix I found for this was to prefix `/static/` to all images used,
for example: `<img src="/static/logo.svg"/>`

Just wondering why its not working with just `logo.svg`

Note: I am in dev enviroment

**Comment by goncalolobo3** [comment]
Where is your static folder? Depending on where it is, and what config you have in your project, you might be able to change the file path. 
In the meantime, use "/static/" when using images.

**Comment by Rich-Harris** [comment]
You shouldn't use `/static/` as a prefix, you should just just `/`. It's a bug that the `/static/` prefix works (to do with how Vite handles requests — fixed in #4535).

This is expected behaviour — relative URLs are relative to the current page. You need to use absolute or root-relative URLs, either like `/logo.svg` or `${assets}/logo.svg` (using https://kit.svelte.dev/docs/modules#$app-paths-assets)
