### ISSUE TITLE
Change $lib, $app and $service-worker to #lib, #app and #service-worker

### ISSUE THREAD

**Issue by raythurnevoid** [sveltejs/kit#1727]
I think svelte kit should stick to the node.js package.json `imports` property spec: https://nodejs.org/api/packages.html#packages_imports
https://nodejs.org/api/packages.html#packages_subpath_patterns

This could avoid future inconsistencies with node and would allow to use the `imports` property instead of actual aliases (Vite, tsconfig, jest, etc...)

**Comment by benmccann** [comment]
That won't work on the client-side. I guess the question is if the bundler will find and convert it during the build process. It's interesting that you raised this though. I wasn't familiar with that feature.

I'm not entirely sure this is something we'd change, but I've added it to the 1.0 milestone so that we at least consider it before then since it'd be a breaking change.

**Comment by raythurnevoid** [comment]
> That won't work on the client-side. 

Why have you raised this? aren't you forced to go through a bundler/builder (Rollup/Vite w esbuild) in order to use sveltekit? 🤔

**Comment by benmccann** [comment]
After thinking about this for a bit, I think it could be confusing. E.g. I think that you'd still need Vite aliases sometimes because the Node stuff only works with `.js` files.

For example, I don't think this will work:
```
  "imports": {
    "#img/*": "./src/images/*"
  }
```

There's a lot of questions I'd have and none of them seems specific to SvelteKit. I think this is an area where we'll follow Vite's lead and support whatever they support. If they start recommending Node `imports` over aliases then we'll follow that advice

**Comment by ximus** [comment]
Makes sense to follow vite's lead. Though I couldn't find any discussion about it in their repo.

After spending much time fighting the module resolution system in my app when using `ts-node`, I chose to adopt the standard '#' and move on.

Just wanted to report here that it works well for me.

Using kit `1.0.0-next.295`, adapter-node, typescript and "module" module type

package.json:
```json
"imports": {
    "#lib/*": "./src/lib/*"
}
```

svelte.config.js:
```js
vite: {
      resolve: {
        alias: {
          '#lib': path.resolve(__dirname, './src/lib'),
        },
      },
}
```

tsconfig.json:
```json
"paths": {
    "#lib/*": ["src/lib/*"],
    "#lib": ["src/lib"],
}
```

relevant for those fighting with `ts-node`: If I recall correctly, [this](https://github.com/TypeStrong/ts-node/pull/1585) is the issue preventing use of `$lib` alias.

**Comment by echocrow** [comment]
cheers @ximus, been running into issues with a `ts-node` code gen script throwing
```
CustomError: Cannot find package '$lib' imported from [...]
```
Followed the same steps above to adopt `#lib`, and can now move on. `dev`/`test`/`build` scripts run just fine, too (after applying the unfortunate config overwrites).

Not strictly relevant to Svelte/SvelteKit per-se, but also leaving this here in case someone else hits this particular error while better ESM + paths support is still WIP.
