### ISSUE TITLE
Propagate SSR errors

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#1857]
**Is your feature request related to a problem? Please describe.**
If an error occurs during SSR, `resolve` returns an object with a `500` status code: https://github.com/sveltejs/kit/blob/babe515f9f5c816fd507920f1f16012263e7a71f/packages/kit/src/runtime/server/index.js#L95-L99

In the case where you're using an error reporting tool like Sentry, you want to be able to get at the original error.

**Describe the solution you'd like**
Not 100% sure what the best solution is here. Adding an `error` property to the response object? (Seems icky.) Having a separate hook for handling errors? (The relationship between that and `handle` could be confusing). Not catching the error in the first place? (What happens if there's no `handle` hook, or the custom `handle` hook doesn't try-catch?)

**Describe alternatives you've considered**
Still brainstorming.

**How important is this feature to you?**
It's important to my coworkers, so it's important to me

**Comment by benmccann** [comment]
The latter two options both sound reasonable. With the hook, `handle` and `handleError` might be a bit weird, so it could make sense to do a rename so that we have `handleRequest` and `handleError` instead. If we expect the user to take care of it with a `try`/`catch` then in the case that they don't have the hook or they didn't handle it then we should just fallback to showing the same error page we do today (that would be needed with the prior option as well if they don't have a `handleError` hook)

In favor of `try`/`catch`:
1. We wouldn't have to decide if the hook should be just for uncaught exceptions or for all error status codes (e.g. 400-599)
2. There are probably existing Express middlewares out there that handle this kind of stuff. And while we don't want to encourage using them too much, there probably are esoteric cases where just being able to use something off-the-shelf would greatly accelerate development. (User would still need to convert between SvelteKit and Express request/response. I'm imagining someone will write a helper for that eventually)
3. Least important since we're still in beta, but it doesn't require renaming `handle` which makes upgrades easier

In favor of `handleError` hook:
1. The biggest reason here is that it's potentially easier to handle errors that happen outside of `resolve` in SvelteKit's own code. I would want those logged to Sentry so that I can file a bug with SvelteKit or try to send a PR

I've gone back and forth, but think that the `handleError` hook might be the best, so that it covers more
