### ISSUE TITLE
Template tests

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#19]
If the app template doesn't include tests, then one of the first questions people will ask is 'how do we add tests'? We should probably have *some* way of answering this question

**Comment by benmccann** [comment]
Jest just merged support for async transforms, which means pre-processing will now be supported with the next release of Jest

**Comment by dominikg** [comment]
I'm not entirely sure i understand what this issue is about but some thoughts crossed my mind that i'd like to share in hopes they will be helpful

1) playwright-core without bundled browser
to reduce download size for integration tests with playwright, you can use playwright-core and an existing chrome installation passed to it via CHROME_BIN env or by guessing the path https://github.com/svitejs/svite/blob/3a9e1a069450cd3fa009716192dc645802e5370e/scripts/jestGlobalSetup.js#L35

2) use a browser server
chromium.launchServer creates a service that can be reused across tests so they don't have to start/stop chrome all over again https://github.com/svitejs/svite/blob/3a9e1a069450cd3fa009716192dc645802e5370e/scripts/jestGlobalSetup.js#L59

3) compile / transform with the tools we already have available
Would it be possible to levarage a vite dev server instance for transforms via https://github.com/vitejs/vite/blob/26c46b92b2b5b21e21380459d1d1a76cb929a69a/packages/vite/src/node/server/index.ts#L192
Or maybe a special vite-plugin-svelte instance that works standalone?

**Comment by Rich-Harris** [comment]
This could be useful: https://github.com/microsoft/playwright-test

**Comment by kenkunz** [comment]
(Sorry… I just realized I was auto-commenting on this ticket from my forked-repo commits. Ignore the first two above – I overwrote my history thinking it wouldn't be viewed by anyone else.)

I've had good experience using Modern Web's [@web/test-runner ](https://modern-web.dev/docs/test-runner/overview/) with Svelte projects using both the [Vite](https://github.com/betaboon/vite-web-test-runner-plugin) and [Snowpack](https://github.com/snowpackjs/snowpack/tree/main/plugins/web-test-runner-plugin) plugins. I created a POC SvelteKit plugin to see if a similar approach would work – this is still rough around the edges, but it demonstrates the basic idea: [kenkunz/sveltekit 1d99ee1](https://github.com/kenkunz/sveltekit/commit/1d99ee1751fe0a68672daecd43c5179156da5fd4). To try it out, install the [kenkunz/sveltekit](https://github.com/kenkunz/sveltekit), use `create-svelte` with the `default` template, run `npm it` from the new app directory.

I included sample tests for both a page component (that includes nested components) and a private component to show that this works for either case. I intentionally kept the dependencies to a minimum, but I've also tested this with [Svelte Testing Library](https://testing-library.com/docs/svelte-testing-library/intro) and it layers on top of this approach nicely.

There are several benefits to this approach that align with the concerns I saw raised in this thread:
* relatively lightweight
* un-opinionated about test framework (mocha is the default, but supports others)
* un-opinionated about assertion library (I used [npm assert](https://www.npmjs.com/package/assert) in my examples, but you could use chai, jest or whatever)
* can launch tests in a variety of browsers, including headless (uses locally installed Chrome by default, but supports Puppeteer, Playwright, Selenium and others off-the-shelf)
* can directly test page components, private components, etc.

If you think this approach has merit, I would gladly work on turning it into a releasable version. Per my code comments, I think we'd want to extract & export a method from SvelteKit to start a dev server (from JS vs. cli), then create a real WTR SvelteKit plugin as a separate package.

If you don't think Web Test Runner is the right fit, please share some feedback as to why – I'm open to exploring alternatives. I think providing a working and flexible off-the-shelf testing solution would help with SvelteKit adoption. Personally, this was a potential barrier – having a proven/working testing solution has given me confidence to move forward with SvelteKit on my current project.

**Comment by rob-balfre** [comment]
I've been converting a component over to SvelteKit and as Rich's original post states, I had a question. 'how do we add tests?' 

As Rich said last year:
> ... it's hard to know what testing setup to suggest when collectively we haven't really figured out what sort of things should live in a test suite

It might be as simple as being clear in the docs/FAQ that kit doesn't have opinions on tests (yet).  Next.js just has a section about how to add tests using [popular solutions](https://nextjs.org/docs/testing), we could have something similar.

Otherwise we could find the new most asked question is about tests and no longer about routers 😄

**Comment by benmccann** [comment]
I think Svelte Adders are a pretty good solution for this. There's [one for Jest](https://github.com/rossyman/svelte-add-jest) already and folks could create new ones for other testing solutions

**Comment by rob-balfre** [comment]
@benmccann thanks `svelte-add` looks like a good resource, I hadn't heard of it before.

I'm still leaning towards SvelteKit having an 'official' way of doing things though. It is after all the official framework for Svelte. Maybe just some basic examples in the docs and then let power users discover tools like `svelte-add`.

**Comment by benmccann** [comment]
I think the problem with having "an official way" to do testing is that even among the maintainers we all have our favorite libraries and it will be hard to get consensus.

We do have [an FAQ which mentions Svelte Adders](https://kit.svelte.dev/faq#how-do-i-use-x-with-sveltekit-how-do-i-setup-library-x). Perhaps we could make one specifically for testing if that'd make it more discoverable

There's also an FAQ on the main Svelte site about testing: https://svelte.dev/faq#how-do-i-test-svelte-apps

**Comment by rob-balfre** [comment]
Yes that's why I'm suggesting adding some examples on the official docs and not choose an official approach, sorry I wasn't very clear in my previous response. 

So when people look for a testing solution for SvelteKit the docs can show some examples, including a section on using `svelte-add`.  I personally never noticed the FAQ section, it's second nature for me to just read the docs.

**Comment by rmunn** [comment]
One thing that Svelte-Kit probably needs to provide, or at least the FAQ should give recipes for, is some way to mock `fetch` in load functions. There are plenty of libraries that can let you replace methods on your components with mock versions of the methods, but it's not obvious to me how the `fetch` parameter of load functions can be mocked. (It's possible I'm missing something, of course).

I wonder if Svelte-Kit could provide a way to tell the compiler "Here's a mock `fetch` function that I want you to provide to my component instead of the real one." That would be very useful in integration tests. For unit testing, you could just compile the component to JS and call its `load()` function with parameters you provide, but for integration tests, it would be very nice to be able to hand the component a mock `fetch` function so that when it tries to fetch `realapi.example.org/some/path` it gets handed `{ "ok": true, "data": "some-test-data" }` without ever hitting `realapi.example.org` at all.

Another subtlety around mocking `fetch` is its API: if your load function does `const res = await fetch(url)` and then `const result = await res.json()`, as most probably do, it's not always trivial to mock that. It would be nice if Svelte-Kit could provide some kind of scaffolding for mocking `fetch`, where you pass in a function that takes a URL string and returns a Javascript object, and the scaffolding would turn that into a function that returned the right kinds of promises for `res.json()` and `res.text()` and so on.

Just off-the-top-of-my-head ideas at this point.

**Comment by brev** [comment]
Hi All, thanks for the great code and community.

I've come up with a new, simple, fast, more reliable way to test my SvelteKit site, using only:

- [Node.js](https://nodejs.org/) + Experimental [ESModule Loaders API](https://nodejs.org/api/esm.html#loaders)
- [uvu](https://github.com/lukeed/uvu) (or any test runner you want)
- [jsdom](https://github.com/jsdom/jsdom)
- [c8](https://github.com/bcoe/c8) (code coverage)

Ideally, this will make for a new [svelte-adder](https://github.com/svelte-add/svelte-add), somewhat like [svelte-add-jest](https://github.com/rossyman/svelte-add-jest). I don’t have time to do this right now, but hope to later, and wouldn’t mind if someone else beats me to it.

## Demo

Install a fresh SvelteKit demo app:

```sh
npm init svelte@next my-app  # demo app, +typescript, +eslint, +prettier
cd my-app
npm install
```

Install our additional packages:

```sh
npm install --save-dev \
  @testing-library/svelte \
  c8 \
  dotenv \
  esm-loader-css \
  esm-loader-import-alias \
  esm-loader-import-meta-custom \
  esm-loader-import-relative-add-extension \
  esm-loader-json \
  esm-loader-mock-exports \
  esm-loader-svelte \
  esm-loader-typescript \
  global-jsdom \
  jsdom \
  node-esm-loader \
  node-fetch \
  uvu
```

Create a `.loaderrc.js` config file for the awesome [node-esm-loader](https://github.com/sebamarynissen/node-esm-loader) library by @sebamarynissen. You can find code and documentation for each of these loaders in my [esm-loaders monorepo](https://github.com/brev/esm-loaders):

```js
// .loaderrc.js
import dotenv from "dotenv";
import { resolve } from "path";

dotenv.config({ path: "./.env.development" });

export default {
  loaders: [
    "esm-loader-svelte",
    "esm-loader-typescript",
    "esm-loader-css",
    "esm-loader-json",
    {
      loader: "esm-loader-import-alias",
      options: {
        aliases: {
          "$app/env": resolve(".svelte-kit/runtime/app/env.js"),
          "$app/navigation": resolve(".svelte-kit/runtime/app/navigation.js"),
          "$app/paths": resolve(".svelte-kit/runtime/app/paths.js"),
          "$app/stores": resolve(".svelte-kit/runtime/app/stores.js"),
          "$lib/": `${resolve("src/lib/")}/`,
          "$service-worker": resolve("src/service-worker.js"),
        },
      },
    },
    {
      loader: "esm-loader-import-meta-custom",
      options: {
        meta: {
          env: process.env,
        },
      },
    },
    {
      loader: "esm-loader-import-relative-add-extension",
      options: {
        extensions: {
          ".js": ".js",
          ".svelte": ".ts",
          ".ts": ".ts",
        },
      },
    },
    {
      loader: "esm-loader-mock-exports",
      options: {
        includes: [/svelte\/motion/],
      },
    },
  ],
};
```

We'll add a new test for the `src/lib/Counter.svelte` component:

```ts
// src/lib/Counter.test.ts
import * as assert from "uvu/assert";
import { cleanup, fireEvent, render } from "@testing-library/svelte";
import Counter from "./Counter.svelte";
import { _MOCK } from "svelte/motion";
import { suite } from "uvu";
import { writable } from "svelte/store";

import "global-jsdom/register";

const test = suite("Counter");

test("render", async () => {
  _MOCK("spring", writable); // mock spring motion for jsdom

  const { findByText, getByLabelText, queryByText } = render(Counter);

  const buttonAdd = getByLabelText("Increase the counter by one");
  const buttonSub = getByLabelText("Decrease the counter by one");
  assert.ok(buttonAdd);
  assert.ok(buttonSub);
  assert.ok(queryByText("0"));
  assert.not(queryByText("2"));

  await fireEvent.click(buttonAdd); // 1
  await fireEvent.click(buttonAdd); // 2
  await fireEvent.click(buttonAdd); // 3
  await fireEvent.click(buttonSub); // 2
  assert.ok(await findByText("2"));

  _MOCK.CLEAR();
  cleanup();
});

test.run();
```

And, we'll add a new test for the `src/routes/todos/index.ts` data endpoint, where we'll do a custom mock of the `fetch()` method (cc @rmunn):

```ts
// src/routes/todos/index.test.ts
import * as assert from "uvu/assert";
import fetch from "node-fetch";
import { get } from "./index";
import { suite } from "uvu";

globalThis.fetch = fetch;

const test = suite("TodosEndpoint");

test("get", async () => {
  globalThis.fetch = async () => ({
    ok: true,
    status: 200,
    json: async () => [
      {
        uid: "f3fafa29-31ec-41e5-8258-4af5ce938ed0",
        text: "hello",
        done: true,
      },
      {
        uid: "ad794a97-4f91-4861-a5ab-a52c657822b3",
        text: "hi",
        done: false,
      },
    ],
  });

  const result = await get({
    request: {},
    locals: {
      userid: 1234,
    },
  });

  assert.ok(result);
  assert.ok(result.body);
  assert.ok(result.body.todos);
  assert.is(result.body.todos.length, 2);

  globalThis.fetch = fetch;
});

test.run();
```

Finally, we run our new demo tests:

```sh
NODE_OPTIONS='--experimental-loader node-esm-loader' npx uvu src .test.ts
```

Setup C8 code coverage report config file `.c8rc.json`:

```json
// .c8rc.json
{
  "all": true,
  "exclude": [".svelte-kit/**", "**/*.d.ts", "**/*.test.ts"],
  "extension": [".js", ".cjs", ".ts", ".svelte"],
  "reporter": ["text", "html"],
  "src": "src/"
}
```

Generate code coverage reports into `coverage/` subdirectory:

```sh
NODE_OPTIONS='--experimental-loader node-esm-loader' npx c8 uvu src .test.ts
```

## Notes

- You'll need to run `svelte-kit dev` or `svelte-kit build` before the aliases will work.
- This should work just fine without Typescript if you prefer vanilla JS.
- Some Svelte lifecycle methods (`onMount`, `beforeUpdate`, `afterUpdate`) cannot be tested yet, I've filed an issue here: https://github.com/sveltejs/svelte/issues/7267.
- The mocking library uses `eval`, which isn't ideal.

Thanks for any feedback!

cc @jerrythomas

**Comment by Rich-Harris** [comment]
closed via #4056

**Comment by benmccann** [comment]
@fredguth it's not clear to me what you were hoping would be tested. We demonstrate how to setup and configure things, which is the hard part. What exactly is missing?

**Comment by fredguth** [comment]
As someone who has never seen Playwright, I was expecting `tests/test.js` would be a complete test of the demo app.  For example, testing not only the about page, but the todo app in the `/todos` route. Maybe it is out of scope, but I think this kind of detail helps newcomers to SvelteKit.
