### ISSUE TITLE
svelte.config.ts – Svelte Config TS Support

### ISSUE THREAD

**Issue by ScarletFlash** [sveltejs/kit#1919]
### Describe the problem

Overview of available config fields currently is only available from [docs](https://kit.svelte.dev/docs#configuration).

### Describe the proposed solution

It would be great if we had build-in Interface, describes all available fields for config file.
Moreover, it would be great if we had build-in support for `.ts`-file extension for config files.

### Alternatives considered

–

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
This interface already exists, and the JSDoc at the top of the file which comes with the starter tepmlates should enable the type hints: `/** @type {import('@sveltejs/kit').Config} */` . Adding `.ts` support for the config files is out of scope since it would require SvelteKit to also install TypeScript or some other form of TS-JS-transpiler for everyone, even if they don't use TS, and it adds additional maintenance overhead for a file that should be pretty simple anyway.

**Comment by michael0liver** [comment]
I was also searching for this feature because it is [supported](https://vitejs.dev/config/#config-intellisense) with vite:
> Vite also directly supports TS config files. You can use `vite.config.ts` with the defineConfig helper as well.

Not essential but its nice to have, especially when you have local custom svelte preprocessors and vite plugins written in TS.
