### ISSUE TITLE
Allow error pages with json bodies

### ISSUE THREAD

**Issue by Astavie** [sveltejs/kit#1931]
### Describe the problem

I'm making a full-stack website in SvelteKit, and am now working on my API. This api is located under `/api/*`. When a user requests from an unknown URI I want to send a 404 message. As the API responds with json, I would like to respond in the same manner with the error message. However, to my knowledge, `__error.svelte` files only support html as an output.

### Describe the proposed solution

I can see two solutions

1. implementation of an `__error.json` file
2. an export in endpoints that get executed on all undefined http methods

I prefer number 2, as then I could also implement 405 Method Not Allowed errors.

### Alternatives considered

For now, I'm using an endpoint like this:

```javascript
function response() { return {
    status: 404,
    body: {
        "error": "notfound",
        "message": "Not Found"
    }
}}

// Most HTTP request methods
export const get = response;
export const post = response;
export const put = response;
export const patch = response;
export const del = response;
export const options = response;
export const head = response;
```

this is located under `src/routes/api/[...error].ts`

Although this works, it's pretty ugly imo and it doesn't cover all infinite custom http methods clients could be using.

### Importance

nice to have

**Comment by Conduitry** [comment]
Something perhaps tidier that you can already do now is use a [`handle` hook](https://kit.svelte.dev/docs#hooks-handle) that returns the desired JSON instead of whatever `resolve()` returns.

I'm not sure how we'd want `__error.json` (or, more likely, `__error.js`) to behave. I'm not clear on what its API should be, what the file should `export`, or what it would be passed. As for what the function _returns_, presumably it would be the same as other endpoint functions (i.e., an object with `status`, `headers`, `body`, etc.) and if it returned falsy, rendering would fall back to `__error.svelte`. But it's not clear what should be passed to this function.

**Comment by Astavie** [comment]
The handle hook practically solves my 404 issue (thanks for pointing me to it!)
For my other issue (giving a 405 error when a wrong http method is used) it would be the easiest if there was a generic `handle` function like the `handle` hook in endpoints that receives the request before passing it along to the function corresponding to the http method, kinda like this:

```typescript
export function get() {
    return {
        status: 200,
        body: { "hello": "world" }
    }
}

export async function handle({ request, resolve  }) {
    // Try to resolve the request like normal with one of the functions corresponding to an http method
    const response = await resolve(request)

    // If it returns falsy, it means we haven't given the http method a function
    if (!response) {
        const error = { "error": "badmethod", "message": "Method Not Allowed" }
        const body = JSON.stringify(error)
        return {
            status: 405,
            body: body,
            headers: { 'content-type': 'application/json; charset=utf-8' }
        }
    }

    // Otherwise, return like normal
    return response
}
```

**Comment by benmccann** [comment]
This might also be related to https://github.com/sveltejs/kit/issues/1857

**Comment by xpuu** [comment]
I have a very same feature request, but different use case and proposed solution.

### Describe the problem

I have a complex API consumed by 3rd party programs. I'd like to communicate errors in JSON. So far, I do something like
```typescript
export const get: RequestHandler = async ({ request, locals }) => {
  try {
    return { body: await getProductsByOwner(locals.ownerId) }
  } catch (e) {
    return { body: { error: e.message } }
  }
}
```
But it's very repetitive and verbose. I tried to catch the error in `hooks.ts`, but it doesn't work. 

### Describe the proposed solution

If `handleError` hook returns `Response` use this instead of default or custom error page.

### Alternatives considered

Allow creating `__error.js|ts` endpoint, which would be used instead of `__error.svelte` if an error comes from endpoint rather than page. But this wouldn't cover 404 errors.

Endpoint would export one default function with the same parameters as `handleError` hook (error, event).

### Importance

Nice to have

**Comment by Rich-Harris** [comment]
Nowadays SvelteKit returns 405s automatically (it wasn't possible at the time this issue was raised). 

Related: #4477

**Comment by Rich-Harris** [comment]
This is basically implemented already — in newer versions of SvelteKit, errors will be turned into JSON if you request with the appropriate `accept` header — but #6497 finishes the job by making that the default with `accept: */*`. 

See also https://github.com/sveltejs/kit/discussions/6499
