### ISSUE TITLE
Ability to disable hydration and client routing on error pages

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/kit#1942]
### Describe the problem

Currently, it is not possible to disable hydration and client routing for error pages. Error pages are arguably one of the best candidates for 0kB JS delivery when SSR'd, because in many cases they do not need to include any JS-powered interactivity.

This very basic error page on a fresh kit install:
```svelte
<script context="module">
  export const load = ({ status, error }) => ({
    props: { status, error },
  });
</script>
<script>
  export let error;
  export let status;
</script>
<h1>{status}</h1>
<h2>{error.message}</h2>
<pre>{error.stack}</pre>
```
In production mode using adapter-node takes **nearly 8 seconds to load** on simulated Slow 3G, with a small data URI favicon embedded into app.html to prevent a favicon request. On 6x CPU slowdown on my computer it takes over 700ms to process the useless clientside JS. 11.4 kB of the total 12.8 kB transferred was for JS alone.

### Describe the proposed solution

SvelteKit should respect the `hydrate` and `router` exports of the `__error.svelte` page.

### Alternatives considered

Since `__error.svelte` is a core part of kit, there's not really a good user alternative.

### Importance

Depends on usage - could be critical in particular regions of the world.

**Comment by benmccann** [comment]
I agree error pages should be treated the same as standard pages for those options

That being said, I'm not sure it'd make a huge difference for network latency. You still need to download the CSS, logo, etc. and that happens in parallel. I also wouldn't say that the JS is useless because if you navigate to another page from the error page (or vice versa) then client-side routing means that you don't have to rerender the layout.

I think the biggest thing we can do is improve hydration, so that you don't have to hydrate a non-interactive component and that hydrating interactive components is more like the way React does it

**Comment by benmccann** [comment]
Error pages are second-class citizens in other ways too https://github.com/sveltejs/kit/issues/1574
