### ISSUE TITLE
documentation for publishing to nginx web server

### ISSUE THREAD

**Issue by chovy** [sveltejs/kit#1976]
### Describe the bug

Please provide example of how to deploy staticly to an nginx web server.

### Reproduction

Please provide example of how to deploy staticly to an nginx web server.

### System Info

```shell
nginx/ubuntu
```

### Severity

serious, but I can work around it

**Comment by Kapsonfire-DE** [comment]
This isnt a easy task, because deployment/publishing depends on the adapter.
i.e.
static adapter can just document root to the dir where its uploaded (look in the nginx documentation)
node adapter is gonna need reverse proxy
if you gonna use other apis on the same domain you need a more complicated server config

Also what should the documentation include:
how to upload to a server? is not part of nginx
how to setup a vhost in nginx? is not the job for svelte - look into nginx documentation


all in all, if a documentation is gonna created, its in the scope of the adapter 
has nothing to with svelte kit here

**Comment by Conduitry** [comment]
Once you have static files you want to server, getting a given web server to serve them is both (a) just about the simplest thing one can do with a web server and (b) not something SvelteKit should be responsible for documenting.
