### ISSUE TITLE
SSR error details are dropped when not of type `Error`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1982]
### Describe the bug

SSR errors are being swallowed in next133

Maybe the upgrade of Vite or `vite-plugin-svelte` did it?
https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next133

### Reproduction

Checkout repo in https://github.com/sveltejs/kit/issues/1978

### Logs

```shell
I get terribly unhelpful message "500" in browser and nothing in console
```

### System Info

```shell
next133
```

### Severity

blocking an upgrade

**Comment by benmccann** [comment]
Seems to be caused by https://github.com/sveltejs/kit/pull/1980. I manually reverted in node_modules/@sveltejs/kit/dist/ssr.js and it fixed it

**Comment by babeard** [comment]
I don't get it how #1980 is the culprit here. The same behavior seems to exist when I use the repro on `next.131` and `next.132` as well.

**Comment by babeard** [comment]
In the repro, the request is to `https://api.github.com/graphql` which is an external request. This then should follow the external `else` branch in the conditional, right? #1980 correctly forces it to resolve externally. 

I don't think #1980 is _actually_ causing errors to be swallowed. Rather, it isn't following the same logic tree as an internal resolve/respond would and therefore not encountering the `Cannot read property 'split' of undefined` error because it never reaches the `parse_body` function where it occurs.

We are seeing the annoying `500 undefined` because we 
1. We didn't define the `VITE_GH_OAUTH_TOKEN` env variable and it subsequently responds with 401 - Not Authorized
2. We didn't handle a failed promise via catch or try / catch within either `routes/index.svelte` or `fetchGithubData()`
3. and then kit tries to render without the expected data payload.

I, of course, could be grievously mistaken. Just my 2 cents. I hope this is understandable. 🤔

**Comment by benmccann** [comment]
Thanks for investigating! It makes sense that #1980 isn't causing an issue here. I'm still wondering why SvelteKit isn't showing a stack trace though

**Comment by benmccann** [comment]
Ok, so the issue here is that the user's code is throwing an `object` and not an `Error`

The code in `src/runtime/server/page/respond.js` shouldn't compile:
```
	try {
		return await render_response({
			options,
			$session,
			page_config,
			status,
			error,
			branch: branch && branch.filter(Boolean),
			page
		});
	} catch (error) {
		options.handle_error(error);

		return await respond_with_error({
			request,
			options,
			state,
			$session,
			status: 500,
			error
		});
	}
```

`error` is of type `any`, but `respond_with_error` needs an `Error`. I think we need to tighten up our checks

**Comment by benmccann** [comment]
This is actually a hole in TypeScript: https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#unknown-on-catch
