### ISSUE TITLE
svelte-check error printed to console

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#1988]
### Describe the bug

svelte-check seems to be looking for a `svelte.config.js` file perhaps and then spitting out an error when it can't find it?

### Reproduction

cd packages/kit
pnpm check

### Logs

```shell
│ Error while loading config
│ TypeError: Cannot read property 'compilerOptions' of undefined
```

### System Info

```shell
kit `master`
```

### Severity

annoyance

**Comment by benmccann** [comment]
I thought maybe this was related to trying to load CJS configs, but I ran `rm -rf packages/kit/src/core/config/test/fixtures/default-cjs packages/kit/src/core/make_package/test/fixtures/typescript packages/kit/src/core/make_package/test/fixtures/javascript_no_types` to delete all the CJS configs and it's still occurring, so I don't think that's the issue after all

**Comment by benmccann** [comment]
Hmm. It seems to be choking on the file: `packages/kit/src/core/config/test/fixtures/export-missing/svelte.config.js`

**Comment by benmccann** [comment]
@dummdidumm I might need your help with this one. I can't figure out how to get `svelte-check` to ignore `src/core/config/test/fixtures/export-missing`. I've tried adding it to the `--ignore` flag and adding it to `exclude` in `tsconfig.json`

**Comment by jasonlyu123** [comment]
Since he's on vacation, is there anything I can help with on the language-tools side? This error it's logged with `console. error`. And it would fall back to using the default config. So it probably it's just confusing but won't fail the test. 

The ignore flag currently only affects the source file diagnostic. And the config loading is run before all the diagnostics without considering the ignored path. I think it makes sense to not search for config files in ignored paths. But since this is more of "annoying" behaviour. I think we can have more discussion and considering before fix this.

**Comment by benmccann** [comment]
Oh, right. I forgot he was away

It's just annoying as you said and so not very high priority

It's not printed when running the test (or if it is it's lost in the other output), but rather when running `pnpm check`

Considering `--ignore` when doing config loading sounds reasonable to me and is what I'd expect

**Comment by dummdidumm** [comment]
Can't we add an empty `export default {}` to these files instead? That would hopefully silence the error as well without having to think about edge cases like "`--ignore` ignores folder X, but something inside that folder is imported from a non-ignored file".

**Comment by ignatiusmb** [comment]
Narrowing down the config files, I found the suspecting error to come from https://github.com/sveltejs/kit/blob/master/packages/kit/src/core/config/test/fixtures/export-missing/svelte.config.js

**Comment by benmccann** [comment]
I just upgraded `svelte-check` so that it now prints out more details about the error and it's clear what's happening

Still, I don't know how to remove this warning since the file is purposefully malformed for testing purposes. 

I suppose if config loading got moved to its own package we wouldn't have to run `svelte-check` on that package since it presumably wouldn't have any `.svelte` files in it

**Comment by dummdidumm** [comment]
Some technical background why this all is so hard to tackle:
- `svelte.config.js` needs to be loaded in an asynchronous way
- language-tools, specifically TypeScript, needs synchronous code paths
- in order to invoke svelte2tsx correctly, the config needs to be known (mainly because of the default language option in `svelte-preprocess` - another point why I'd like to get rid of it)
- the two points above contradict each other. Moreoever, TypeScript will throw an error if you tell it "this file is now TS instead of JS". Therefore, upon seeing the first Svelte file, the file path is walked up to find a `svelte.config.js`, but the path is also walked _down_ to find possibly nested configs, which we then don't need to load afterwards --> this behavior likely produces the warning, even if you `--ignore` the path
- Also related: `--ignore` does nothing when you reference a `tsconfig.json`, because the referenced files are determined by that then instead (also see https://github.com/sveltejs/language-tools/issues/1074).

**Comment by ignatiusmb** [comment]
I wonder if we should just remove that specific test

**Comment by benmccann** [comment]
I wouldn't mind that as a solution. It doesn't seem like the most important thing to have
