### ISSUE TITLE
Specify config file or project location in CLI

### ISSUE THREAD

**Issue by iOiurson** [sveltejs/kit#2033]
### Describe the problem

I would like to be able to specify where `svelte.config.js` (or the target folder) is located when you have multiple apps based on a common `lib`.

### Describe the proposed solution

Have a CLI option for the config file location such as
```
svelte-kit dev --config my/path/to/svelte.config.js
```

Or 

Have a CLI option for the folder location, which will also handle all generated folders locations
```
svelte-kit dev --folder my/path/to/folder/
```

### Alternatives considered

I currently use the following architecture:

```
myRoot/
    lib/
    subProject-1/
        package.json
        svelte.config.js
    subProject-2/
        package.json
        svelte.config.js
    package.json
    svelte.config.js
```

which is not ideal to maintain, due to duplicate config/dependencies.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
Adding `--config` is possible but adds some complexity (see https://github.com/sveltejs/kit/issues/2973#issuecomment-1107863837). My recommendation would be to re-export a shared config, so that you don't duplicate stuff (but also have the ability to extend individual configs where necessary, which wouldn't be possible with `--config ../shared/config.js`):

```js
import config from '../../svelte.config.mjs';
export default config;
```

Since this is very similar to #2973, I'll close it in favour of that
