### ISSUE TITLE
CLI ignores Vite server config

### ISSUE THREAD

**Issue by dreitzner** [sveltejs/kit#2165]
### Describe the bug

`packages\kit\src\cli.js => async function get_Config()` does not load the vite part of the config.

Therefore the params for server (like `host`, `port`, `open`, `https`,...) are ignored.

**Solution:**

- read vite config
- overwrite values in cli

### Reproduction

```
import preprocess from 'svelte-preprocess';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		// hydrate the <div id="svelte"> element in src/app.html
		target: '#svelte',
		vite: {
			server: {
				port: 987,
			}
		}
	}
};

export default config;
```
will not open server on port 987.

### System Info

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 4.02 GB / 15.88 GB
  Binaries:
    Node: 14.17.2 - ~\AppData\Local\Volta\tools\image\node\14.17.2\node.EXE
    Yarn: 1.5.1 - C:\Program Files\Volta\yarn.EXE
    npm: 6.14.13 - ~\AppData\Local\Volta\tools\image\node\14.17.2\npm.CMD
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Spartan (44.19041.906.0), Chromium (92.0.902.67)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.146
    svelte: ^3.34.0 => 3.42.1
```

### Severity

annoyance

**Comment by dominikg** [comment]
sveltekit uses vite in middleware mode during dev. As a result not all of vite's config options are going to be used/effective and host/port are not because there is no classic "vite server" started by vite's cli

Currently the only option to customize sveltekit port is via [cli flag](https://kit.svelte.dev/docs#command-line-interface-svelte-kit-dev)

Not reading the port from vite config isn't a bug imho. If you want to be able to customize host/port from the config, a feature request to add new options to the kit namespace would be more appropriate.

**Comment by benmccann** [comment]
I'm not sure what to do with `port` in the config file because it'd only be used in dev mode, which might be confusing? In production, you can specify it in the config already in the adapter. I think for port it'd probably just be better for users to add it to the `dev` script in `package.json`

Maybe we should log a warning if people try to set options under the `server` config section? Though the one thing I do think we take from there right now is SSL cert config

**Comment by Conduitry** [comment]
HMR server/port config from the Vite config is also respected, which is under `server`. I think it makes sense to emit warnings (or errors?) for config we know will be ignored.
