### ISSUE TITLE
Option to disable the Fetch behavior of rendering raw data into HTML

### ISSUE THREAD

**Issue by ulvidamirli** [sveltejs/kit#2177]
### Describe the problem

As in [official document](https://kit.svelte.dev/docs#loading-input-fetch):

> When fetch runs on the server, the resulting response will be serialized and inlined into the rendered HTML.

This behavior intercepts with my reason to use SSR on SvelteKit.

Because I don't want my server-side JSON response to be accessible by the client (other developers) as a raw JSON. I do it for preventing possible parsing of raw JSON data. And also to avoid visibility of some app-specific data (they are not security-related data).

### Describe the proposed solution

I would like to have an option to disable rendering JSON as raw data into HTML. Just only rendering it to the template.

### Importance

i cannot use SvelteKit without it

**Comment by benmccann** [comment]
You could turn off client-side rendering. As long as your API is accessible on the web they could just hit your API directly to get the data, so taking it out of the page might not help you a lot

**Comment by benmccann** [comment]
Or, alternatively, if you turned off `ssr` I think that might stop it from including it in the page. (I haven't tested)

**Comment by ulvidamirli** [comment]
I'm trying to solve this issue by making database queries from the `.js` file and then import it with the `load function` inside the `module context`. `SSR` is valuable for me, but I don't want anybody to see the raw `JSON`. Do you think that would work? I can't get it to work, though because of errors. Need some help

**Comment by benmccann** [comment]
`load` cannot make database queries. it must call an HTTP endpoint

**Comment by ulvidamirli** [comment]
> You could turn off client-side rendering. 

I tested it, works. But other functionalities don't work which are very important for the page.

> load cannot make database queries. it must call an HTTP endpoint

Can I just make a `query` with a `.js` file and `export` as a `JSON` object, and then `import` this exported `JSON` from the `load function`?

**Comment by benmccann** [comment]
No. `load` runs on the client. It can't access your database no matter what you name your files.

You could also probably prerender your page so that the database is queried at build time and `load` doesn't need to run in the browser

**Comment by ulvidamirli** [comment]
It would be better to have partial hydration for these types of scenarios, I think. For example, type of load function which gives us a chance to make the queries or API calls on the server.

> You could also probably prerender your page so that the database is queried at build time and load doesn't need to run in the browser

By doing this, the pages won't update when I edit data on the database right? That's a disadvantage for me as well.

**Comment by rmunn** [comment]
> Because I don't want my server-side JSON response to be accessible by the client (other developers) as a raw JSON. I do it for preventing possible parsing of raw JSON data. And also to avoid visibility of some app-specific data (they are not security-related data).

Are you somehow blocking or disabling the Network tab of the browser developer tools? Because otherwise, your clients (who will definitely know about the dev tools since they're other developers) will be able to see the JSON response from your server to their browser anyway, whether or not it's been included in the HTML of the page, simply by using the Network tab of the dev tools.

And since as far as I know there's *no way* for a web page to disable the client's access to the developer tools (if you know a way, I'd be interested to learn it), what you're trying to achieve (hiding the server's JSON response from your customers) is impossible. So in my opinion, it's not worth adding extra complexity to Svelte-Kit's `fetch` function for this use case, because it wouldn't actually get you what you want anyway.

**Comment by ulvidamirli** [comment]
Sorry for my poor explanation. The thing I want is simply to get access to DB (for making queries) from the `load function`.

By doing that, I think the raw JSON won't be accessible to the clients/devs from the network tab or anywhere else.

**Comment by benmccann** [comment]
That's impossible. `load` runs in the browser. You can't access your database from the browser

**Comment by keehun** [comment]
@benmccann I wonder if I could ask for what @ulvidamirli was asking for but in a slightly different way as I think there was a bit of miscommunication:

Could it be possible in the future to get a function call like `load()` but one that will be **only** called during build time for pre-rendering.

As of today, if I enable pre-rendering with crawl with SvelteKit, it correctly generates HTML from API data. However, because `load()` is _also_ called in the browser in addition to build/pre-rendering time, the benefits of pre-rendering for this static content are mitigated.

Problem with turning off hydration for a page is that then it ruins interactivity with the rest of the page that absolutely need hydration.

Basically, I would get everything I need if I’m able to have an exact clone of `load()` but one that would only be called in the compiler while pre-rendering. Bonus points if that compiler-only JS never makes it into the client/browser but this is not necessary.

Here’s my use-case: I’m developing an application like an encyclopedia/dictionary where the content is fairly static and doesn’t need to be updated instantaneously. We will rebuild the site as a regular cadence. I do have other parts of the page (like search/autocomplete/etc) that benefits a lot from Svelte’s conveniences. The API doesn’t need to be a secret or hidden, but as you can see, there’s a lot of reduction in traffic we can achieve if the API is only hit during build-time.

I’ve tried the trick where you import `browser` from `$app/env` and short circuit `load()` when in the browser, but that throws errors into console as the page attempts to hydrate and is missing that data it would have fetched in the `load()` call.

Right now, my solution is to run a python script that is executed before `sveltekit build` which will pull all the JSON files from the API. These files get put in the static directory. In essence these files serve as the site’s API “server” so visitors will never actually hit my API services. This is working well for now, but I would like to see if I can skip this middle step.

The only other way I can imagine implementing this is by utilizing something like jinja2 or another “code generation” tool that would read the API and actually generate Svelte code which then would be built by Svelte. 

Both of these solutions fall far from the tree of what I would consider a good, long-term solution. SvelteKit and pre-rendering already does everything I want except for that “hydrate everything again in the browser”. So as soon as I get a lever where I can specify what doesn’t need to be hydrated again in the browser, I would be golden. Perhaps similar to what Deno’s Fresh is calling “islands” which are separate files of code that denote what needs to be hydrated in the browser. Basically, component-level configuration to enable or disable hydrating. Right now, it seems like it’s either the entire page or the whole site or nothing.

**Comment by benmccann** [comment]
@keehun you're asking for partial hydration. There's a ticket for that here: https://github.com/sveltejs/kit/issues/1390

**Comment by keehun** [comment]
Yes, thanks! I edited my comment to refer to that as I was reading that thread while you were reading my comment I think. Thanks!
