### ISSUE TITLE
The page object for handles should include full url and protocol

### ISSUE THREAD

**Issue by alexbjorlig** [sveltejs/kit#2219]
### Describe the problem

The current hooks handle does not expose protocol and full url.

This is an issue, because without either protocol or full url, a valid `URL` can not be constructed.

### Describe the proposed solution

Include both protocol and full url in hooks handle, to make it easy to be a developer.

### Importance

would make my life easier

### Additional Information

When running on localhost, it's for example not possible to only use the page.host to create a valid URL class. [See here for an example](https://stackoverflow.com/q/68799371/3694288).

**Comment by Conduitry** [comment]
There's not in general a way on the server to have access to the protocol. For serverless/lambda deployments, it's generally always going to be HTTPS. When using the Node adapter, there may or may not be a reverse proxy sitting in front and serving HTTPS.

In the past, I've used a function that reconstructs the full URL, using `request.host`, `request.path`, and `request.query.toString()`. It's pretty straightforward. I'm not necessarily against exposing the full URL somewhere, but it's not clear to me how to handle the protocol. For my purposes, `request.host.includes(".") ? "https://" : "http://"` worked fine in local development and in production, but this isn't a heuristic we'd want to force on everyone.

**Comment by alexbjorlig** [comment]
> but this isn't a heuristic we'd want to force on everyone

By _not_ exposing the URL or host, it's exactly what the framework is doing 🧐

Unless someone can come up with a good pragmatic example of `request.host.includes(".") ? "https://" : "http://"`  that does not work, why not just use that implementation?

**Comment by Mlocik97** [comment]
what if website can/use more than one protocol? What if there is nested protocol usage? I think, this is not good idea of implementation. It would need to be implemented different way.

**Comment by Conduitry** [comment]
> By _not_ exposing the URL or host, it's exactly what the framework is doing 🧐

Making something the user's responsibility is different from providing a solution that we claim works but has some confusing rules about when it works.

`request.host.includes(".") ? "https://" : "http://"` doesn't work if you are trying to access the site at `http://127.0.0.1:3000` instead of `http://localhost:3000`. It doesn't work if there are certain pages in production that are served over HTTP instead of HTTPS. By including this in the framework itself, we're asserting it's a good default, and it's not at all clear to me that it's a good default.

---

Handling this in the adapters won't work either, because there's no way for the output from the Node adapter to know whether it's being a reverse proxy.

**Comment by alexbjorlig** [comment]
I totally understand what you are saying, but still - hear me out.

With the current implementation, we **can't** use [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) on the server. Let that just sink in. Without doing work-arounds, it's not possible to simply construct new redirect url's, using the URL class.

Could the adapter/or-some-other-config-file not just be configurable with reverse-proxy headers? And regarding routes that could be served over both http and https, the framework could read the proxy headers and determine if it was http/https. 

Similarly, the config file could include a list of localhost; 127.0.0.1, localhost etc.

Seems weird to me that URLSearchParams are provided, but not URL as someone would expect. Are you guys not implementing oAuth and other "advanced" redirects in your applications where this would be SO much simpler?

**Comment by dennisjlee** [comment]
If I understand correctly, one of the scenarios that is of concern here looks like this:

1. ​Browser makes request to https://example.com/foo
2. A reverse proxy receives the request and passes it along to the backend (which could use HTTPS or HTTP at this point, depending on configuration)
3. SvelteKit receives the request

In situations in the past, I've looked at headers from the reverse proxy in order to determine whether the browser's original request was using SSL. For instance there's [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) and [Forwarded](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded). Would it make sense for SvelteKit to look at those headers and the request scheme to determine if the original request was HTTPS? (perhaps this could be opt-in if you don't want to assume that the developer trusts any reverse proxy)

I agree with @alexbjorlig that this limitation makes it difficult to construct a redirect URL that can be passed around - e.g. included in an email or used as part of an OAuth authentication flow.

**Comment by blairn** [comment]
Yeah, and we can't even check dev because preview mode has dev turned off.

Currently, I'm having to pass in which protocol is expected via environment.

**Comment by alexbjorlig** [comment]
Does the latest version of `kit` not actually expose the full URL class on the request object?
