### ISSUE TITLE
Cloudflare URL query params not loading

### ISSUE THREAD

**Issue by thinkloop** [sveltejs/kit#2316]
### Describe the bug

I am trying to read the url query params on initial site load like so:

```
<script>
    import { page } from '$app/stores'
    $: name = $page?.query?.get('name') || null;
</script>
```

This works locally, and it works on vercel when using the vercel adapter, but it does not seem to work on cloudflare pages, the params are always null on initial page load. I am using the static adapter per the tutorial on: https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site

I am *not* using cloudflare workers.

### Reproduction

The reproduction requires deploying 1 line to cloudflare and would not be helpful linking to a repo.

### System Info

```shell
node v14.17.3


  "devDependencies": {
    "@sveltejs/adapter-static": "^1.0.0-next.13",
    "@sveltejs/adapter-vercel": "next",
    "@sveltejs/kit": "next",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "less": "^4.1.1",
    "prettier": "~2.3.2",
    "prettier-plugin-svelte": "^2.4.0",
    "svelte": "^3.42.4",
    "svelte-preprocess": "^4.8.0",
    "svelte2tsx": "^0.4.5",
    "typescript": "^4.4.2"
  }
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
If you're using `adapter-static`, you're prerendering, and if you're prerendering then you can't access query parameters during SSR (from [the docs](https://kit.svelte.dev/docs/page-options#prerender-when-not-to-prerender): "Accessing `url.searchParams` during prerendering is forbidden").

In current versions of SvelteKit, trying to access them will result in an error thrown during build. I can't diagnose the issue you ran into further because you ignored the instruction to provide a repro, and the instruction to use `npx envinfo` instead of pasting a snippet from your package.json.
