### ISSUE TITLE
How to use kit.vite.resolve.alias if SvelteKit doesn't not allow this config?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#2319]
### Describe the bug

I need to use https://vitejs.dev/config/#resolve-alias in my `svelte.config.js` and I'm using it like this:

```js
resolve: {
  alias: [
    {
      find: /^custom\/node_modules\/package!(.*)/,
      replacement: "my-custom-alternative",
    },
  ],
},
```

but when I build SvelteKit writes in red in my console this text:

`build_client: The value for kit.vite.resolve.alias specified in svelte.config.js has been ignored. This option is controlled by SvelteKit.`.

How to use aliases now?

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.17 => 1.0.0-next.17
    @sveltejs/kit: 1.0.0-next.159 => 1.0.0-next.159
    svelte: 3.42.4 => 3.42.4
```

### Severity

blocking all usage of SvelteKit

**Comment by benmccann** [comment]
It's expected that you should be able to set this: https://kit.svelte.dev/faq#aliases

Perhaps that message is getting triggered because you're using regex?

`resolve.alias` is set here:

https://github.com/sveltejs/kit/blob/e21892b6f1a31e80910971a32a149caf0361435b/packages/kit/src/core/build/index.js#L170

**Comment by frederikhors** [comment]
I can confirm it works without regex. With regex the issue is there.

**Comment by JeanJPNM** [comment]
The problem may be in these places: https://github.com/sveltejs/kit/blob/c086b18adf6c146697f2b9c9900a3c7c4086aee1/packages/kit/src/core/build/index.js#L484-L489
https://github.com/sveltejs/kit/blob/c086b18adf6c146697f2b9c9900a3c7c4086aee1/packages/kit/src/core/build/index.js#L484-L489
https://github.com/sveltejs/kit/blob/c086b18adf6c146697f2b9c9900a3c7c4086aee1/packages/kit/src/core/build/index.js#L607-L611

Because they don't check if `vite_config.resolve.alias` is an array as bellow, thus creating a merging conflict.
https://github.com/sveltejs/kit/blob/c086b18adf6c146697f2b9c9900a3c7c4086aee1/packages/kit/src/core/dev/index.js#L121-L137

While fixing this won't give much work, I think we should also fix the code duplication between `dev` and `build`.

**Comment by bluwy** [comment]
@JeanJPNM are you fixing this? Because I'm currently working on it :smile:

**Comment by JeanJPNM** [comment]
I was, but I started a couple of minutes ago, but you problably made more progress than me, so I'll leave this issue to you.
