### ISSUE TITLE
Import in `service-worker.ts` from `$lib` throws

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#2321]
### Describe the bug

If I import this:

```ts
import { myFunc } from "$lib/utils";
```

in `service-worker.ts`, it throws like this:

```
[vite]: Rollup failed to resolve import "$lib/utils" from "src\service-worker.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

Why?

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
  Binaries:
    Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @sveltejs/adapter-static: 1.0.0-next.17 => 1.0.0-next.17
    @sveltejs/kit: 1.0.0-next.159 => 1.0.0-next.159
    svelte: 3.42.4 => 3.42.4
```

### Severity

serious, but I can work around it

**Comment by JeanJPNM** [comment]
I found the issue:

Here are the aliases for the client bundle:
https://github.com/sveltejs/kit/blob/c086b18adf6c146697f2b9c9900a3c7c4086aee1/packages/kit/src/core/build/index.js#L169-L174

Here are the aliases for the server bundle:
https://github.com/sveltejs/kit/blob/c086b18adf6c146697f2b9c9900a3c7c4086aee1/packages/kit/src/core/build/index.js#L484-L489

And here are the aliases for the service worker:
https://github.com/sveltejs/kit/blob/c086b18adf6c146697f2b9c9900a3c7c4086aee1/packages/kit/src/core/build/index.js#L607-L611

As you can see, the rollup config for the service worker bundle doesn't include the `$lib` alias like the other two, I don't know if this is an error or is there by design.

But I if it is a bug I will happily open a pr.

**Comment by JeanJPNM** [comment]
Thinking about it, it is problably a bug.
