### ISSUE TITLE
invalidate() only works once

### ISSUE THREAD

**Issue by j-panasiuk** [sveltejs/kit#2337]
### Describe the bug

According to the docs $app/navigation `invalidate` is supposed to re-run any load functions relevant to the resource being invalidated.
However, as I tried to trigger `invalidate` after some update on a page, I found out that the `load` function is called only the first time. On subsequent calls nothing happens.

### Reproduction

A minimal example provided here:
https://github.com/j-panasiuk/svelte-kit-invalidate-issue

### Logs

```shell
n/a
```

### System Info

```shell
node 16.2.0
npm 7.13.0

@sveltejs/kit: 1.0.0-next.160 
svelte: 3.42.4
```

### Severity

serious, but I can work around it

**Comment by rmunn** [comment]
I think you've misunderstood how the `invalidate` function works. Your code is doing this:

```svelte
<script context="module">
  import { invalidate } from "$app/navigation";

  export function load() {
    console.log("load...");
    return {
      props: {
        number: Math.random(),
      },
    };
  }
</script>

<script>
  export let number = 0;

  function mutate() {
    console.log("mutate...");
    invalidate(".");
  }
</script>

<div>Number = {number}</div>
<button on:click={mutate}>Refresh</button>
```

But [the documentation for `invalidate`](https://kit.svelte.dev/docs#modules-$app-navigation) says:

> `invalidate(href)` causes any `load` functions belonging to the currently active page to re-run if they `fetch` the resource in question.

Your `load()` function never calls `fetch`, so `invalidate` doesn't cause it to re-run.

If I change your `load()` function as follows:

```svelte
  export async function load({ fetch }) {
    console.log("load...");
    let response = await fetch('/example.json')
    let number = await response.json()
    return {
      props: { number }
    };
  }
```

And then use `invalidate('/example.json')` instead of `invalidate('.')`, then the `fetch()` is re-run every time I click the button, which results in fetching a different number from `/example.json` every time.

(Note that I also had to make one change to your `example.json.js` code: I changed `body: Math.random()` to `body: Math.random().toString()`, because Svelte-Kit doesn't allow numbers in the `body` of a response. I was getting "TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer or Uint8Array. Received type number (0.4247868833508568)" without that change.)

**Comment by rmunn** [comment]
In the version of your example that did use `fetch`, did the URL passed to `invalidate` match the one passed to `fetch`? Because I see your example calling `invalidate('.')`, and unless you're also running `fetch('.')`, that's not going to work. The URL passed to `invalidate()` isn't supposed to be the URL of the *current page*, it's supposed to be the URL of the *remote resource* that needs to be re-fetched. The documentation could perhaps stand to be a bit clearer on this point.

**Comment by j-panasiuk** [comment]
Ah, I see. When I switched `.` to the full resource name it works as expected.
So I was trying to be clever with refetching resources based on current location, but it won't work like that.
Thanks!
