### ISSUE TITLE
Seeing weird behavior where an error is sometimes shown in __layout slot, and sometimes not

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#2372]
### Describe the bug

It seems that error handling is quite different when it's done from the browser vs from SSR. To demonstrate I have two screenshots, both showing exactly the same non-existing webpage, the URL is 100% identical.

In this first one I started from an existing character page and clicked on "Fake link" on the left side, which takes me to the non-existing page, using the router in the browser:

![Screen Shot 2021-09-05 at 18 41 35](https://user-images.githubusercontent.com/229384/132134705-ab1a5111-36ff-4f93-84c1-1a86a18e77c2.png)

It's very weird how the error is showing the _entire website_ within the website in the `slot` of `__layout.svelte`!

The second one is the result of reloading that non-existing page, or going directly to it (not via the router):

![Screen Shot 2021-09-05 at 18 41 50](https://user-images.githubusercontent.com/229384/132134707-799efb94-9f0f-4627-a7d4-00c3721949b3.png)

What I would expect to happen is that errors would always show in the same consistent manner, both from SSR and from the router (client side).

### Reproduction

I have a single top-level `__error.svelte` page that renders the error with the navigation bar and the footer and all that, basically what you see in that second screenshot.

I also have a bunch of nested `__layout.svelte` components. In this particular example, there is a `campaigns/[campaignId]/characters/__layout.svelte` file, and a `campaigns/[campaignId]/characters/[characterId].svelte` page. In the page I am simply returning `{ status: 404, error: "Character not found" }` from the `load` function if the character isn't found. 

The `__layout.svelte` shows the list of characters on the left side, and has a `<slot />` on the right side to show character details. When the error is triggered from the client side router, the error page (with the entire website around it!) is shown _inside of that slot_, but when it's triggered from SSR, it only shows the error page.

### System Info

```shell
System:
    OS: macOS 12.0
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Memory: 128.39 MB / 32.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.6.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.3 - /usr/local/bin/npm
  Browsers:
    Safari: 15.0
  npmPackages:
    @sveltejs/kit: ^1.0.0-next.145 => 1.0.0-next.145 
    svelte: ^3.34.0 => 3.42.1
```

### Severity

blocking an upgrade

### Additional Information

I'm not able to update past version 145 at the moment because of https://github.com/sveltejs/kit/issues/2371. I will retest with the latest SvelteKit when I can.

**Comment by rmunn** [comment]
Can reproduce on latest release (version 163), and I may have found the cause of the difference between SSR and client-side loading. In client-side loading, after a `load()` function returns an error, [the following line is called](https://github.com/sveltejs/kit/blob/afb0e059528b050c525c8bb1db718827d439aec2/packages/kit/src/runtime/client/renderer.js#L668):

```js
branch.push(error_loaded);
```

Here, `error_loaded` is the `__error.svelte` component that has been chosen to render the error, and `branch` contains all the components found so far on the path to the component that threw the error (in your case and in my reproduction, it's a series of layout components). So the error component is put at the end of a chain of all the layout components found so far.

However, in server-side rendering, [the following line is called](https://github.com/sveltejs/kit/blob/afb0e059528b050c525c8bb1db718827d439aec2/packages/kit/src/runtime/server/page/respond.js#L148):

```js
branch = branch.slice(0, j + 1).concat(error_loaded);
```

Here, `branch` and `error_loaded` are the same as in client-side rendering, but instead of pushing the error component onto the end of the stack of components, the component stack keeps only components 0 through `j`, and then adds `error_loaded` onto the end after the component with index `j`. In earlier code, `j` is calculated by going backwards through the component stack until  the error component is found. In my repro, similar to yours, I put an `__error.svelte` only at the root, and so `j` was 0 once the calculations were finished. That means that although `branch` contained multiple layout components, when SSR rendered the error, only the root layout component was used for the rendering.

Given how the [docs for error pages](https://kit.svelte.dev/docs#layouts-error-pages) talk about rendering error pages in the parent layout if there's none at the current level, I believe the SSR code is the intended behavior, so I replaced the client-side code with the slice-and-concat logic from the SSR code in my reproduction, and it seemed to work.

I don't have time right now to turn my quick-and-dirty reproduction into a proper test for a PR, but I should be able to get to that in the next few days.

**Comment by kevinrenskers** [comment]
Hey, that's great!

What if I want to keep the client-side behavior where it shows the error next to the list of characters, instead of taking over the whole page? Obviously I'd have to remove the navigation header and the footer from the error page, but having the error be shown inside of the layout slot does make sense. Will that be possible?

**Comment by rmunn** [comment]
Yes; you just need to have an `__error.svelte` component at the same level as the `__layout.svelte` component that you want it to use for rendering. The rule is that Svelte-Kit climbs the folder list until it finds an `__error.svelte` component, and if none is found at all then it uses the default built-in error component. Once an `__error.svelte` component is found, it's supposed to be rendered with the layout that applies to other components in that same folder. This logic was happening correctly in SSR, but due to the bug (which I'm almost done creating a PR for), client-side rendering was selecting the layout *of the page that threw an error* rather than correctly selecting the layout *of the error component*.

So all you have to do, if you want your errors rendered with a particular `__layout.svelte` file, is to put an `__error.svelte` file in the same folder as that `__layout.svelte` file. Server-side rendering will correctly pick that up, and soon client-side rendering will use the same logic as SSR.
