### ISSUE TITLE
Using adapter-cloudflare-workers with a CDN other than Workers KV.

### ISSUE THREAD

**Issue by Supermath101** [sveltejs/kit#2385]
### Describe the problem

Cloudflare Workers KV has relatively high prices for storage, so I'd like to offload media assets to a CDN, such as Backblaze B2.

### Describe the proposed solution

To implement this, I'd imagine all you need to do is only publish the HTML, CSS, and JS directly to KV. Then, using some snippets from the [Configure your CDN Tutorial](https://developers.cloudflare.com/workers/tutorials/configure-your-cdn), you would need call out to a CDN, and serve it using the Workers script. Also while remembering to cache it, obviously.

### Importance

would make my life easier

### Additional Information

I think maybe there could be a better way of going about managing media assets. Like, correct me if I'm wrong, but I currently don't see any way to import (static/media) assets from external sources into the website, except for possibly the current system of using a `./static` directory.

**Comment by Rich-Harris** [comment]
This should work if you configure `config.kit.paths.assets`, though we might need to tweak the worker so that it knows it's not responsible for serving them.

> I currently don't see any way to import (static/media) assets from external sources into the website

What does this mean?

**Comment by isaac-mcfadyen** [comment]
> I currently don't see any way to import (static/media) assets from external sources into the website

SvelteKit does server-side rendering on Workers/Pages using a single bundle (single JS file).

KV is only used for assets that are being fetched from *the client* (such as CSS files or JS files or other static assets). There's no importing involved on the server at all, the client merely makes another request for those files.

Because these files are static, it's probably possible (as Rich said) to fetch from a CDN. But in that case you wouldn't need to go through the Worker at all, since they're just static files.

**Comment by Supermath101** [comment]
Closing this because I don't remember what the details behind use-case were.
