### ISSUE TITLE
Use `target es2020` as default in tsconfig.json

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#2457]
### Describe the problem

I think we as world are ready for `"target": "es2020"` as default when we generate new `SvelteKit` project.

Aren't we?

### Describe the proposed solution

Use `"target": "es2020"`.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
We have not done this in the past because some we support Node 12.x, and that doesn't support es2020 features, so it would be confusing for new users if they run into a situations where their deploy target does not support the newer features which are not transpiled if the target is es2020. More info in #772 .
