### ISSUE TITLE
Source maps in adapter-node

### ISSUE THREAD

**Issue by alastaircoote** [sveltejs/kit#2517]
### Describe the problem

Because adapter-node transpiles the original source the error stacks you see in production aren't always that useful in tracking down an issue. I thought it might be as simple as adding source maps to the esbuild config:

```
esbuild: function (config) {
    config.sourcemap = 'inline';
    return config;
}
```

which _sort of_ works, but now the source lines it gives me are in `.svelte-kit/build/app.js`. If I add:

```
build: {
 	sourcemap: 'inline'
}
```

to Sveltekit's vite config then `.svelte-kit/build/app.js` _does_ have source maps but [esbuild doesn't merge source maps](https://github.com/evanw/esbuild/issues/933). I've played a little with the [merge-source-maps](https://www.npmjs.com/package/merge-source-maps) module but it definitely isn't working with SvelteKit out of the box. 

### Describe the proposed solution

I'm not entirely sure what the answer is here but wanted to flag it as a desired feature. I'm happy to dig further into it myself but might benefit from the wisdom of someone more familiar with SvelteKit's internals. merge-module-maps fails because it tries to load `${PROJECT_DIR}/kit/dist/node.js` which is presumably `@svelte/kit/dist/node.js` but I'm not totally sure where that's being imported.

### Importance

nice to have

**Comment by benmccann** [comment]
The easy solution would probably be to make `esbuild` bundling optional. It was only added in https://github.com/sveltejs/kit/pull/1648, so shouldn't be required since we always got away without doing it before.

The better solution is probably to see if we can make Vite responsible for all bundling. That would also solve the problem that @ignatiusmb is trying to figure out of how to have the adapter reference the application output file without hardcoding it - the adapter would no longer need to because it could be kept internal to `build/index.js`. Instead, the adapter could just be a library and SvelteKit could do all the building instead of the adapter being in charge of the build process.

**Comment by Conduitry** [comment]
I'd hesitate to say we got away without doing it before that PR. `@sveltejs/kit` was previously a _production_ dependency of all apps using SvelteKit and the Node adapter, which is pretty bad.
