### ISSUE TITLE
Load not called correctly when using goto

### ISSUE THREAD

**Issue by JamesCoyle** [sveltejs/kit#2560]
### Describe the bug

I am using goto to update the page query string based on user selected filters which then changes the data that is fetched within the load function of the page. This works relatively well but the load function is only called every other time a filter is changed. I would expect the page's load function to be called every time the query string is updated so the page can request the correct data. 

### Reproduction

Here is a minimal reproduction of the issue. If you alternate clicking on the two buttons (they set a query string parameter to true or false by calling goto) you can see in the console that load is only called for one of the two changes. 

https://github.com/JamesCoyle/SvelteKit-Goto-Load-Issue

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
    Memory: 8.98 GB / 15.88 GB
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (94.0.992.38)
    Internet Explorer: 11.0.19041.1202
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.178
    svelte: ^3.42.6 => 3.43.1
```

### Severity

blocking an upgrade

**Comment by rmunn** [comment]
I think I got it figured out. Your repro code is doing this in the `updateQuery()` function:

```js
export function updateQuery(query, changes) {
    for (const [key, value] of Object.entries(changes)) {
        if (value === '' || value === null) query.delete(key)
        else query.set(key, value)
    }

    goto(`?${query.toString().replace(/%7C/g, '|')}`, { keepfocus: true, replaceState: true, noscroll: true })
}
```

But since you're passing it the `$page.query` object, you're actually modifying the `query` object that Svelte-Kit handed you, and that's causing this bug because Svelte-Kit has some internal checks that rely on that `query` not being modified by user code. Specifically, this line inside Svelte-Kit's internal `_load` function:

```js
const changed = this.current.page && {
    path: path !== this.current.page.path,
    params: Object.keys(params).filter((key) => this.current.page.params[key] !== params[key]),
    query: query.toString() !== this.current.page.query.toString(),
    session: this.session_id !== this.current.session_id
};
```

In the `query.toString() !== this.current.page.query.toString()` comparison, `query` is the query params of the *new* page being navigated to, and `this.current.page.query` is the query params of the *current* page. This optimization is designed to not re-run your `load()` function if the query params didn't change.

But because your code is **modifying the current `query` object** before calling `goto`, what's happening is that when you go from `test=false` to `test=true`, the `goto` command isn't seeing the current page as `test=false`. You're modifying `this.current.page.query` and setting it to `test=true` before calling `goto`, and thus the comparison compares `test=true` to `test=true` and says "Oh, the query parameters didn't change, no need to call the load() function". Actually, I'm not sure why half the time the load function *is* getting called; from what I've understood of the code so far, I'd think it would never be called.

But that doesn't really matter. Because all you have to do is keep the `$page.query` object unmodified, and modify a cloned query object instead. I've tested this, and making the following change to your code will be enough to solve the issue for you:

```js
export function updateQuery(query, changes) {
    const localQuery = new URLSearchParams(query.toString());
    for (const [key, value] of Object.entries(changes)) {
        if (value === '' || value === null) localQuery.delete(key)
        else localQuery.set(key, value)
    }

    goto(`?${localQuery.toString().replace(/%7C/g, '|')}`, { keepfocus: true, replaceState: true, noscroll: true })
}
```
