### ISSUE TITLE
Support session cookie backend auth

### ISSUE THREAD

**Issue by dmwyatt** [sveltejs/kit#2562]
First of all, I may be completely missing an existing feature. If that's the case, I apologize for the noise.

### Describe the problem

* `httpOnly` cookies are proof against XSS attacks against user sessions. <sup>[1](#myfootnote1)</sup>
* Sites have backend REST API servers at *domain1.com* that need auth to access.
* Sites want to serve their JS frontends from different origins (for example, from a CDN) at *domain2.com*.

### How this is done with JS frontends that are bundled

1. User logs in at `domain1.com/login` and has an `httpOnly` session cookie set.
2. User is redirected to `domain1.com/app/index.html`.  The `index.html` for this includes a script tag like: `<script src="http://domain2.com/bundle.js"></script>`.
3. `fetch` from inside `bundle.js` has `credentials: "include"` which sends along the `httpOnly` session cookie.

### How this is done with SvelteKit

⁉

<hr/>
<sub><a name="myfootnote1">1</a>: There <a href="https://security.stackexchange.com/questions/148161/security-issues-in-jwt-storage">are arguments</a> about whether XSS or CSRF are more important, but the fact remains that many major sites rely `httpOnly` cookies as described above.</sub>

### Describe the proposed solution

I just started seriously looking into SK a couple of days ago, so I don't quite understand how it works.

At my current level of understanding I think what needs to happen is that, the static adapter (for example) needs to be able to spit out a minimal bootstrap bundle.js that the user can then include in the `index.html` served by their backend site.

### Importance

i cannot use SvelteKit without it

**Comment by rmunn** [comment]
Sounds like https://github.com/pixelmund/svelte-kit-cookie-session might be useful to you.

**Comment by mohe2015** [comment]
> httpOnly cookies are proof against XSS attacks against user sessions. 1

I don't think so you can simply use XSS to make the requests directly can't you? As httpOnly just means the cookie can't be extracted but you can still make requests containing it.

> At my current level of understanding I think what needs to happen is that, the static adapter (for example) needs to be able to spit out a minimal bootstrap bundle.js that the user can then include in the index.html served by their backend site.
I don't think sveltekit currently supports providing a bundle but you rather create the whole page with sveltekit. You can then build a static build out of this and serve the index.html's. Alternatively you could probably use Svelte directly but I don't know.

Other than that I don't know why you think this is not possible yet (or I am forgetting something)

**Comment by rmunn** [comment]
In the sentence "you just include your JS bundle from `some-cdn.com` in a script tag in an `index.html` served from `my-cool-app.com`", I was assuming that the `index.html` (which will be served from `my-cool-app.com`) is what you're building with Svelte-Kit's static adapter, since the static adapter outputs HTML files. But I see I got your question wrong way around. What you are asking is how to produce a Javascript bundle of your Svelte files, and that JS bundle is what would be served from `some-cdn.com`, while the login page lives on `my-cool-app.com` so that it can use `httpOnly` cookies.

That's a scenario I have no experience with, so I'm aftraid I can give you only generalized guesses. But I know the Svelte-Kit `npm run build` process outputs a Javascript bundle as part of the process, in a directory named `.svelte-kit/build` if I recall correctly (or maybe that was moved somewhere else recently, I haven't kept up with that part of the code). Then the various adapters — static, Node, Vercel, ... — take the bundle that was just built and transform it to work in their particular environments. If none of the existing adapters are doing the thing you need, I suspect it wouldn't be too difficult to write an adapter that just takes the bundle Svelte-Kit has just built, and produces that as the output instead of a set of .html files like the static adapter does.

But all that is general guesses. Perhaps someone else will have a more specific idea.

**Comment by ZirionNeft** [comment]
If I properly got your question, you are trying to save sessions cookies in different domains, right? 
I got a some research due my work tasks that sounds just the same, and I went to conclusion - this is  actually not working, cause cookies designed to have only one domain origin.
And I just did rework my backend auth from sessions to jwt and all is fine.

**Comment by Rich-Harris** [comment]
I'll be honest, I don't really understand what's going on in this issue. But if you're looking for a way to put your JS bundle and other static assets on a different domain than the site itself, [`config.kit.paths.assets`](https://kit.svelte.dev/docs/modules#$app-paths-assets) is the way to do that. Does that help at all?

**Comment by dmwyatt** [comment]
>  I don't really understand what's going on in this issue.

I understand. It's hard to wrap your head around until you actually try to implement it.  

> Does that help at all?

I don't know, as I had to move on to another solution as I couldn't get this working.
