### ISSUE TITLE
bug: Invalid Url on fetch in a store when first loading the page

### ISSUE THREAD

**Issue by jesperordrup** [sveltejs/kit#2629]
### Describe the bug

Svelte store fails to fetch from /api/test.json when accessing a page. When prefixing url endpoint with http://localhost:3000 i can get it to work on npm run dev but this does not work when building and previewing

We're trying to build a setup with SSR 

I've found another example of a user with similar problem here

https://stackoverflow.com/questions/69075449/cant-fetch-data-from-api-in-sveltekit

### Reproduction

Create endpoint that returns json

        ///api/test.json.js
        
        export async function get({ params }) {
	        return {
		        body: {
			        message: 'Looks good from up here'
		        }
	        };
        }

Create store that fetches data from endpoint. Ive tried many things here

        // stores/testStore.js

        import { writable } from 'svelte/store';
        export const testStore = writable([]);
        
        // url1 gives me TypeError [ERR_INVALID_URL]: Invalid URL
        const url1 =  '/api/test.json'; 
        
        // url2 works on dev but not when previewing a build (npm run build npm run preview
        const url2 =  'http://localhost:3000/api/test.json'; 
        
        const fetchTest = async () => {
	        console.log('fetching test');
	        const response = await fetch(url2);
	        const content = await response.json();
	        testStore.set(content);
        };
        fetchTest();

Creates a page to render stuff

        /test/testpage.js

        <script>
	        import { testStore } from '/src/stores/testStore';
	        $: message = '... praying';
	        $: {
		        console.log('what do you know', $testStore);
		        message = $testStore.message;
	        }
        </script>
        
        <h1>What are you doing down there?</h1>
        
        {#if message}
	        <p>{message}</p>
        {/if}

## When using url2 and running `npm run dev` all looks good and i get this render:

        What are you doing down there?
        Looks good from up here

## When using url2 and running npm run build and npm run preview i get errors 

        npm run preview
        
        > tailwind3@0.0.1 preview
        > svelte-kit preview
        
        fetching hammer
        fetching test
        
          SvelteKit v1.0.0-next.180
        
          network: not exposed
          local:   http://localhost:3000
          network: not exposed
        
          Use --host to expose server to other devices on this network
        
        
        file:///C:/Code/test/sveltekit/sveltetest_20211008/tailwind3/node_modules/@sveltejs/kit/dist/install-fetch.js:5779
                                reject(new FetchError(`request to ${request.url} failed, reason: ${error.message}`, 'system', error));
                                       ^
        
        FetchError: request to http://localhost:3000/api/content.json failed, reason: connect ECONNREFUSED 127.0.0.1:3000
            at ClientRequest.<anonymous> (file:///C:/Code/test/sveltekit/sveltetest_20211008/tailwind3/node_modules/@sveltejs/kit/dist/install-fetch.js:5779:11)
            at ClientRequest.emit (node:events:394:28)
            at Socket.socketErrorListener (node:_http_client:447:9)
            at Socket.emit (node:events:394:28)
            at emitErrorNT (node:internal/streams/destroy:157:8)
            at emitErrorCloseNT (node:internal/streams/destroy:122:3)
            at processTicksAndRejections (node:internal/process/task_queues:83:21) {
          type: 'system',
          errno: 'ECONNREFUSED',
          code: 'ECONNREFUSED',
          erroredSysCall: 'connect'
        }

## When using url1 and running npm run build and npm run preview i get errors 

        npm run preview
        
        > tailwind3@0.0.1 preview
        > svelte-kit preview
        
        fetching hammer
        fetching test
        
          SvelteKit v1.0.0-next.180
        
          network: not exposed
          local:   http://localhost:3000
          network: not exposed
        
          Use --host to expose server to other devices on this network
        
        
        node:internal/errors:464
            ErrorCaptureStackTrace(err);
            ^
        
        TypeError [ERR_INVALID_URL]: Invalid URL
            at new NodeError (node:internal/errors:371:5)
            at onParseError (node:internal/url:536:9)
            at new URL (node:internal/url:612:5)
            at new Request (file:///C:/Code/test/sveltekit/sveltetest_20211008/tailwind3/node_modules/@sveltejs/kit/dist/install-fetch.js:5512:16)
            at file:///C:/Code/test/sveltekit/sveltetest_20211008/tailwind3/node_modules/@sveltejs/kit/dist/install-fetch.js:5722:19
            at new Promise (<anonymous>)
            at fetch (file:///C:/Code/test/sveltekit/sveltetest_20211008/tailwind3/node_modules/@sveltejs/kit/dist/install-fetch.js:5720:9)
            at fetchTest (file:///C:/Code/test/sveltekit/sveltetest_20211008/tailwind3/.svelte-kit/output/server/app.js:2163:26)
            at file:///C:/Code/test/sveltekit/sveltetest_20211008/tailwind3/.svelte-kit/output/server/app.js:2167:1
            at ModuleJob.run (node:internal/modules/esm/module_job:183:25) {
          input: '/api/test.json',
          code: 'ERR_INVALID_URL'
        }

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 9.40 GB / 31.93 GB
  Binaries:
    Node: 16.6.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 94.0.4606.81
    Edge: Spartan (44.22000.120.0), Chromium (94.0.992.50)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.180
    svelte: ^3.42.6 => 3.43.1
```

### Severity

blocking all usage of SvelteKit

### Additional Information

I know Im doing something wrong, but ?

**Comment by rmunn** [comment]
Not a Svelte-Kit bug. Please ask for support on the Discord channel, not here. But I'll go ahead and explain what you're doing wrong before this bug is closed. Short version: you should be using the `export async load()` functionality and doing your `fetch` calls in there.

What's happening is that your testStore.js code is sometimes running during server-side rendering. When `fetch` runs in the browser, you can use URLs like `/api/foo` without specifying a host, and it can fill in the host from the URL the browser loaded. But when `fetch` runs server-side, it has no knowledge of what URL it's running on, and so it requires supplying a complete URL. And that is why your `fetch` sometimes fails with a type error, because `url1` is not a complete URL (it lacks a host and a protocol).

So why did I say to use the `export async load()` functionality and do your tests there? Because the `fetch` parameter passed into `load` is a special wrapper that Svelte-Kit provides around `fetch` that can run in either the server or the browser. When it runs in the server, it automatically fills in the missing pieces of the URL for you, because it knows the base URL that you provided in your `svelte.config.js`. So if you need that piece of data from the API, fetch it in the `load()` function and it will Just Work™ whether it's server-side rendered or not.

"But," you may say, "I need that value put into a store no matter what browser page I load from, so your solution would mean I have to write a `load()` function for each page?" Well, there's another thing you could try. Make that `fetch` call in the *setup* method of your store — the one that runs when you get your first subscriber. That way you can just use that store's value in a page as `$testStore`, and the page will subscribe to it. This will ensure that the fetch is always running on the browser. Less efficient than using `load()` since you have to wait for the data browser-side instead of having it fetched server-side, but it'll work. To do that, you would do:

```js
// stores/testStore.js

// url1 gives me TypeError [ERR_INVALID_URL]: Invalid URL
const url1 =  '/api/test.json'; 

// url2 works on dev but not when previewing a build (npm run build npm run preview
const url2 =  'http://localhost:3000/api/test.json'; 

import { writable } from 'svelte/store';
export const testStore = writable([], async (set) => {
    console.log('fetching test');
    const response = await fetch(url1);
    const content = await response.json();
    set(content);
});
```

... Except I just realized that if you subscribe to that store from a server-side rendered page, it may not work. So you'll want to use `env` (see https://kit.svelte.dev/docs#modules-$app-env for details) and check if you're in the browser. And if you're server-side, import `base` from https://kit.svelte.dev/docs#modules-$app-paths and use that to build your URL.

That's probably what I should have recommended in the first place. But I'll leave that store example up because it may be useful to you.

At any rate, this is not a bug and should have been a request for help on the Discord channel, not here.

**Comment by 205g0** [comment]
> you should also always be very careful about using globals or singletons (including stores) on the server, 

@Conduitry in other words: Within `load`, write first to `props`, then within the page use `props`' value to write the prefetched values to some store but do this not within 'load'.

1. Is this what you meant?
2. Why props and not stuff: With props, I'd have more flexibility to carry the prefetched data to some non-page components. Does this make sense? Found `stuff` pretty limited but I assume, I  got it wrong
3. In general, I just try to wrap my head around the concept of writing right to the store within `load': The server would create a writable store, which is a singleton or global at the end of the end, which would get overwritten on every request; this should be safe as well as long, as long no derived stores are created or just some part of the store gets overwritten. So, as long as `load` writes a complete new state to the store it shouldn't matter if this happens on the server as well. This would create a bit leaner code at the costs of risks of still exposing things, it just need more awareness. So, I would still opt to writing to the props before. Are my thoughts in this point 3 correct (just to know if I understood the whole thing)

Looking forward to your feedback!

**Comment by rmunn** [comment]
@205g0 -

The `stuff` and `props` values in `load` functions have two different uses:

1. `stuff` is passed down to *other `load` functions*. It is therefore only useful in the `load` function of *layout components*, because once you reach the *page*, that `load` function is the last one that will be run before the page is rendered.
2. `props` is passed *only to the component* and not to other `load` functions. It is therefore only useful on pages (usually; I suppose you could have a layout component that uses props to affect the layout, but most use cases won't want to do that).

So when @Conduitry talked about fetching data in one place and making it available throughout the site, he was talking about fetching it in the `load` function of *root `__layout.svelte` component*, and then returning the value in `stuff`. Then any page that wanted the data could have a `load` function that pulls it out of `stuff` and sticks it into `props` so that it's available in the page.

Hopefully that answers your 1 and 2. As for your 3, I don't understand why that would be useful. If the `load` function happens to run during SSR and the store is written on the server, that's a total waste of server RAM because there's no way it can be useful. (Since it would be overwritten every time a new client loads that URL). But I'm not totally clear on what you meant, so perhaps I'm just misunderstanding it. But the right way to do it is to keep the stores client-side, which means not writing to them in `load` but in the component instantiation code (that is, the `<script>` section that isn't `context="module"`).
