### ISSUE TITLE
Web components and SSR

### ISSUE THREAD

**Issue by tiloio** [sveltejs/kit#2666]
### Describe the problem

Our `adapter-node` SvelteKit app is using a [web components](https://developer.mozilla.org/en-US/docs/Web/Web_Components) library (build with [Stencil](https://stenciljs.com/)) to have a common design over multiple applications.

When we include this components in our SvelteKit application without SSR or prerendering everything works fine.

When we activate SSR or prerendering we have massive layout shifts. The components are not visible when the page is loaded. The components will appear a few seconds later which leads to that layout shifts.

### Describe the proposed solution

One solution would be to migrate the library to svelte.
Another solution would be to compile the [stencil](https://stenciljs.com/) components to svelte.
Both of these solutions need a lot of effort to be implemented.

[Stencil](https://stenciljs.com/) provides [static site generation](https://stenciljs.com/docs/static-site-generation) and [app hydration](https://stenciljs.com/docs/hydrate-app). Maybe its possible to integrate on of these in the Vite build steps of SvelteKit?

There is also a package [`@skatejs/ssr`](https://github.com/skatejs/skatejs/tree/master/packages/ssr) which should server side render web components. I have tried it out yet but maybe this is also a opportunity.

### Importance

would make my life easier

**Comment by christianp86** [comment]
Hi,

I have just created a small PoC using [OpenUI5 Web Components](https://sap.github.io/ui5-webcomponents/ )
In order to get it working properly (without diabling SSR etc.) I had to do the following:
`import { onMount } from 'svelte';

	onMount(async () => {
		await import('@ui5/webcomponents/dist/Table');
		await import('@ui5/webcomponents/dist/TableColumn');
		await import('@ui5/webcomponents/dist/Button');
		await import('@ui5/webcomponents/dist/TableRow');
		await import('@ui5/webcomponents/dist/TableCell');
	});`

Not sure if this helps in your case as I do not know the details of your library.

**Comment by Rich-Harris** [comment]
> When we activate SSR or prerendering we have massive layout shifts.

This is just how web components work — they're useless without JavaScript, and it's one of many reasons I generally steer people away from them.

There is a new proposal called 'declarative shadow DOM' which supersedes experiments like `@skatejs/ssr` and aims to solve this problem, though it's a bit of a mess and not widely supported (Mozilla have signalled that they don't intend to support it, and Safari have some significant reservations — it's really just Chrome and their Edge lackeys/hostages that are enthusiastic about it).

In order to use it, you basically need to simulate the DOM on the server, pass in the HTML along with the various custom element constructors, and serialize the result. There are some experiments for getting all that to work, but it's an expensive, cumbersome process that will have to happen in a custom `handle` hook — it's unrealistic to support it directly in SvelteKit, so I'll have to close this issue.

**Comment by FrancoisDF** [comment]
Hi, I know it was closed some time back, but I was actually having the same issue and found out that you could use `hooks.server.ts` to handle it with your stencilJs library:
```ts
import type { Handle } from '@sveltejs/kit';
import { renderToString } from '<your_lib>/hydrate';

export const handle = (async ({ event, resolve }) => {
  const response = await resolve(event, {
    transformPageChunk: async ({ html }) => {
      return renderToString(html, {
        prettyHtml: true,
        removeScripts: false
      }).then(results => results.html);
    },
  });
  return response;
}) satisfies Handle;
```
I still see some rendering glitch once the library script loaded on the client side, but that's maybe something that can be fine tune. But at least the "view page source" does have all the hydrated tags

**Comment by pauldemarco** [comment]
Looks like NextJs deemed this important enough to support. This would also unlock ionic components SSR for SvelteKit, which might be a big deal.

@Rich-Harris any change of heart?

**Comment by Rich-Harris** [comment]
I mean you can already do it, as shown in the previous comment. If you want to use happydom or whatever to fully render declarative shadow DOM regardless of which WC library you're using then you can even do that. What more would be needed?

**Comment by benbuc** [comment]
> Hi, I know it was closed some time back, but I was actually having the same issue and found out that you could use `hooks.server.ts` to handle it with your stencilJs library:
> [code omitted]
> I still see some rendering glitch once the library script loaded on the client side, but that's maybe something that can be fine tune. But at least the "view page source" does have all the hydrated tags

Hi, for a project I am required to use a supplied web components library (also StencilJS) and the approach from @FrancoisDF looked very promising. Unfortunately I am getting a `hydration_mismatch` warning in the console and I am having a hard time debugging this myself. Did you run into similar issues? The server-rendered page looks close enough, but due to the mismatch I still have a big content flash during page load. Prior I was just calling `defineCustomElements` in the `onMount` and only experienced a brief FOUC.
For lack of proficiency I might sadly resort to disabling SSR altogether for now or do the "hide content until loaded" trick to hide the initial FOUC.
Disabling SSR would probably be the better option here.

**Comment by FrancoisDF** [comment]
I have reached a point where we could successfully get SSR working with svelte4 but it's a bit of a dance between StencilJs hydration not conflicting with svelte hydration... and it's all about timing.
the DSD version of stencilJs will generate my component.svelte from
```html
<my-button text="cool" ></my-button>
```

into 
```html
<my-button>
 <style>
   button{ ...}
 </style>
 <template>
    <button>
        cool
    </button>
  </template>
<my-button>
```

like presented in my previous comment with the renderToString in the hooks.server.

Once that DSD land in svelte client side, svelte will start to mess with the DOM as it was expecting something like `<my-button text="cool" ></my-button>`

so 2 things need to be done:
1. load my stencilJs library after svelte hydration with something like
```js
afterNavigate(() => {
   initWC(); // this will call the /loader.js that register all lib web-component
});
```
2. wrap each WC in a way that even if the svelte mess with it (remove comment tag and id/class used by stencilJs to re-hydrate) It will swipe the version coming from the server with a fresh version of the web-component
SSRWrapper.svelte
```html
<script lang="ts">
  import { afterNavigate } from '$app/navigation';
  $: didNavigate = false;
  afterNavigate(() => {
    didNavigate = true;
 });
</script>
{#if !didNavigate}
   <slot>
{:else}
  <slot />
{/if}
```
then
```html
<SSRWrapper>
   <my-button text="cool" ></my-button>
<SSRWrapper>
```
At this point, in the client side the web-component will be re-initiated creating a small FOUC but quickly picked up by StencilJs then working fine after that.

This only works with svelte4. Svelte5 is supposed to be more forgiven on such external manipulation, but it still friction a lot with stencilJs generated DSD.. I'm yet under investigation this situation and pushing back the migration to svelte5 after I find a similar stable solution...

**Comment by capricorn86** [comment]
Hi,
I'm the author and main maintainer of [Happy DOM](https://github.com/capricorn86/happy-dom/).

For those who found this thread and wants to know how to achieve this in a performant way using Happy DOM, there is now a [guide available here](https://github.com/capricorn86/happy-dom/wiki/Server-Renderer#advanced).
