### ISSUE TITLE
Configurable allow list passed to Vite

### ISSUE THREAD

**Issue by hobbes7878** [sveltejs/kit#2701]
### Describe the problem

Vite's server.fs.allow config is now set [here](https://github.com/sveltejs/kit/blob/0b9d3df82419eacdd0404e5f0782faf7d7168d81/packages/kit/src/core/dev/index.js#L95-L107) as of next191. But in some cases users like us may have additional directories we'd like to allow.

For example, we have a `locales` directory at the root of our project, which is outside `src/` and the directories set to kit's lib and assets config. ([Here's a looksie](https://github.com/reuters-graphics/bluprint_graphics-kit) if it helps.) We'd like to import JSON from this directory in our app, but the new config throws an error like this:

```
The request url "/Users/.../my-project/locales/en/content.json?import" is outside of Vite serving allow list.
```

### Describe the proposed solution

Could y'all allow an option so additional allowed directories can be passed through to Vite? Maybe by concatenating with directories set in [config.kit.vite](https://github.com/sveltejs/kit/blob/0b9d3df82419eacdd0404e5f0782faf7d7168d81/packages/kit/src/core/dev/index.js#L113)?

### Importance

would make my life easier

**Comment by danielzsh** [comment]
It seems the `kit.vite.server.fs.allow` property is no longer supported; is there an updated solution for this?

**Comment by benmccann** [comment]
Any Vite config now goes in the Vite config file: https://vitejs.dev/config/server-options#server-fs-allow

**Comment by henke443** [comment]
This does not seem to work in version 2.5.5:
![image](https://github.com/sveltejs/kit/assets/2922864/784271bc-5d21-41cf-9856-5f769f56384a)

Granted, I'm using both storybook and tauri which complicates things probably. Writing it here anyways just because it might be worth looking into. I have already spent many hours on this issue but when I gather the strength for it I will look if I can make a minimal reproducible example.
