### ISSUE TITLE
Endpoint throws 500 error on empty body

### ISSUE THREAD

**Issue by denizkenan** [sveltejs/kit#2706]
### Describe the bug

when `'Content-Type': 'application/json'` and body is empty. Application throws:

```

Exception has occurred: SyntaxError: Unexpected end of JSON input
  at JSON.parse (<anonymous>)
...

``` 

### Reproduction

```
fetch("<url>/<endpoint>.json", {
  "headers": {
    "content-type": "application/json",
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "DELETE",
  "mode": "cors",
  "credentials": "omit"
});
```

should do the trick

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 163.00 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 15.0
  npmPackages:
    @sveltejs/adapter-cloudflare-workers: ^1.0.0-next.25 => 1.0.0-next.25 
    @sveltejs/kit: next => 1.0.0-next.191 
    svelte: ^3.38.2 => 3.44.0

```

### Severity

serious, but I can work around it

### Additional Information
[this line to be precise](https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/server/parse_body/index.js#L20)
_No response_

**Comment by rmunn** [comment]
For non-JSON data sent with `Content-Type: application/json`, I'd say a [400 Bad Request](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) would be the right error code to return. That error "indicates that the server cannot or will not process the request due to something that is perceived to be a client error (e.g., **malformed request syntax**, invalid request message framing, or deceptive request routing)." (Emphasis mine).

For the specific case of an *empty* body, though, I feel it would be slightly more user-friendly to accept that response and set `body` in the endpoint params to something empty. WHAT that "something empty" should be, of course, is a big question. There are a few possibilities:

* `null` - Pro: Since any JSON input *could* be the value `null`, endpoints have to be able to handle `null` in the body. Con: Now we are making a JSON body of 0 bytes be the same value as a JSON body of 4 bytes `n`, `u`, `l`, `l`. And someone might possibly want to distinguish those.
* `undefined` - This is an invalid JSON value (`null` is valid JSON but `undefined` is not) so there's no chance that using `undefined` to represent an empty body will somehow match a valid input that someone might have wanted to distinguish. Con: It's an invalid JSON value, so some people might not like having to test for it. Pro: They had to test for `null` anyway, so a quick `if (body)` check is enough to test for both `null` and `undefined`.
* Empty string - Pro: also falsy so `if (body)` works. Con: Conflates with a body of `''`, and also many endpoints might be expecting an object.
* Empty array - Con: not falsy so `if (body)` won't detect this. Con: many endpoints might be expecting an object.
* Empty object - Con: not falsy. Pro: many (I'm guessing most) endpoints expect an object, so this won't cause them errors.
* 0 (zero) - No. Just no.

Of those, I'd favor `undefined` as being the best way to represent an empty body, with an empty object in close second place.

**Comment by kevinrenskers** [comment]
After updating my SvelteKit app a few days ago, I am now running into the same problem, but it's actually crashing the Node server process (I am using adapter-node).

From my server logs:

```
Jan 07 03:03:46 criticalnotes node[926627]: SyntaxError: Unexpected end of JSON input
Jan 07 03:03:46 criticalnotes node[926627]:     at JSON.parse (<anonymous>)
Jan 07 03:03:46 criticalnotes node[926627]:     at parse_body (file:///opt/www/build/server/app.js:1173:19)
Jan 07 03:03:46 criticalnotes node[926627]:     at respond (file:///opt/www/build/server/app.js:1255:11)
Jan 07 03:03:46 criticalnotes node[926627]:     at App.render (file:///opt/www/build/server/app.js:1494:12)
Jan 07 03:03:46 criticalnotes node[926627]:     at Array.ssr (file:///opt/www/build/handler-1d60625a.js:7258:29)
Jan 07 03:03:46 criticalnotes node[926627]:     at runMicrotasks (<anonymous>)
Jan 07 03:03:46 criticalnotes node[926627]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jan 07 03:03:46 criticalnotes systemd[1]: www.critical-notes.com.service: Main process exited, code=exited, status=1/FAILURE
```

**Comment by Rich-Harris** [comment]
Since we no longer parse bodies eagerly, but instead wait for `request.json()`, this issue no longer occurs
