### ISSUE TITLE
adapter-static exports endpoints that are fetched inside module load

### ISSUE THREAD

**Issue by JackPriceBurns** [sveltejs/kit#2739]
### Describe the bug

When you run a static export, all the files are exported as expected. However, there are extra files that appear in the export that shouldn't be there.

When you run `fetch` inside the module load function it should store that payload inside the html and when the page loads it shouldn't make another request. This is true, the data is inside the .html files as expected and when you load the page it doesn't make an Ajax request to get that data.

However, this data embedded in the .html files is also stored as files in the export.

### Reproduction

Create a route which fetches an internal endpoint (`/blog/posts.json` for examples) in the module load function.

Load the page:
You can see that the fetch never happens client side and the data is available.

Run an export:
You can see the files in the export. `/blog/posts.json` can be seen in the export.

### System Info

```shell
System:
    OS: Linux 5.10 Alpine Linux
    CPU: (6) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.99 GB / 7.77 GB
    Container: Yes
    Shell: 1.31.1 - /bin/ash
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21
    @sveltejs/kit: next => 1.0.0-next.183
    svelte: ^3.43.1 => 3.43.2
```

### Severity

annoyance

**Comment by Conduitry** [comment]
This is intended. If you client-side navigate to that page from another page, you want `posts.json` to be available as a standalone file.

**Comment by JackPriceBurns** [comment]
But every .html file has that posts.json embedded in the page. So if you client side navigated to /about/index.html you wouldn't need to fetch that file either?

**Comment by babichjacob** [comment]
> But every .html file has that posts.json embedded in the page. So if you client side navigated to /about/index.html you wouldn't need to fetch that file again?

If you client-side navigate to `/about` then the JavaScript to hydrate the page with `src/routes/about.svelte` is loaded (so `/_app/pages/about.svelte-[hash].js`), which includes the `load` function that `fetch`es from `"/endpoint.json`.

If we wanted to reuse the results of the `fetch` we would have to load the `/about/index.html` file, which is more bytes than just the JSON file, and throw out everything except the saved results block. 

If you'd rather not load the `/_app/pages/about.svelte-[hash].js` and `/endpoint.json` files then you can choose to use regular browser navigation rather than the SvelteKit router's by [marking the `/about` link as `external`](https://kit.svelte.dev/docs#anchor-options-rel-external), making it not client-side navigation.
