### ISSUE TITLE
Support dynamic content of app.html

### ISSUE THREAD

**Issue by atuttle** [sveltejs/kit#2762]
### Describe the problem

While I imagine the current static approach for app.html is acceptable in ~99% of use cases, sometimes it would be useful to make its contents dynamic.

I have a multi-tenant application that loads a customer-provided skin at runtime and wraps my app in it. Hypothetically, let's say the skin looks like this:

```html
<html>
<head>
<title>APP!</title>
</head>
<body>
<p>some content before the application</p>
{{app}}
<p>some content after the application</p>
</body>
</html>
```

Achieving this isn't particularly difficult.

```js
//__layout.js
<script context="module">
  //load the skin async based on things like hostname
  //and other portions of the URL, then...
  return { props: { skin: skinHTML } };
</script>

const [before, after] = skin.split('{{app}}');
// ... some regex magic to strip out the html/head/body tags
{@html before}
<slot />
{@html after}
```

Indeed, this is exactly what I'm currently doing. But there's a problem. If the skin _wraps_ the app in a tag, Svelte(Kit?) starts to misunderstand the DOM and the app gets duplicated. Given a skin that contains this: `<div>{{app}}</div>`...

The app behaves very oddly, and most of the time results in 2 copies of itself on the page. (To the best of my understanding, sometimes in dev hmr it will clean itself up to a single instance, but not always)

Here's a video demonstrating why I want to do this, and how it affects the application: https://youtu.be/voYqm2Chu1U

If the contents of app.html were dynamic, it would be trivial for me to replace `{{app}}` with `<div id="svelte"></div>`.

### Describe the proposed solution

I can see that everything is currently hard-coded to read app.html from the file system and use that value.

https://github.com/sveltejs/kit/blob/fb262e5d3ac551b369cf3f50d8a073975f8b0606/packages/kit/src/core/dev/index.js#L462-L465

It would be nice if there were some sort of hook or middleware that I could add that would be called instead that could return the HTML contents currently obtained from app.html. It would need to happen at runtime (server-side) so that I can parse the URL to get the correct skin for the current hostname.

### Alternatives considered

The only other thing I can think of is to use Vanilla Svelte and express/etc to set the page contents to the skin at runtime. I'd hate to give up the routing/etc benefits of SvelteKit, though.

I haven't been able to think of any other alternatives, but I'm open to any current/proposed solution that lets me build the features I need in my app. It doesn't have to be the solution I proposed.

### Importance

would make my life easier

**Comment by Mlocik97** [comment]
`__layout.svelte` already does what You need, and what cover 99% of cases. I'm not sure if this is good idea at all, as it would be too complicated... we need some "entry" file, to which we hydrate, aka app.html, that imports initial script, but it's impossible to make this initial script be imported before app.html is loaded. (when vising website, browser download HTML first, and while it's parsing, it download scripts it's refering to in imports or `<script src>`... and downloading stuff like `{{app}}` inside HTML would harm SEO, as those stuff is not normal content of HTML.

**Comment by Mlocik97** [comment]
This totally doesn't make sense, and Your problem You describe is more error in Your code, that problem with app.html being static (which is not).

**Comment by atuttle** [comment]
The contents of app.html only need to be static for pre-rendering 100% static pages at build time. Code is already running on the server for the initial request (as it is with SvelteKit SSR when using the node adapter) then presumably it would be possible to call a function (left to me to implement) to return the HTML that should be used instead of the static app.html --- that's what I'm requesting.

**Comment by atuttle** [comment]
Here's a video where I show exactly what the problem is and why it's a problem. Sorry for the dog snoring in the background! https://youtu.be/voYqm2Chu1U

**Comment by rmunn** [comment]
Part of what's going on with the `<div>{{app}}</div>` case is that you're using `@html` to render the "before" and "after" portions, and if `{{app}}` is wrapped in a div then that will cause `@html` to be passed HTML that isn't valid *standalone* HTML. (That's even the example used in https://svelte.dev/docs#html as an illustration of what won't work). I think if you fix your regex to detect a wrapped `{{app}}` and remove that wrapper div (assuming it had nothing else inside it), then you should be able to make progress.

Because of that, I'm not yet persuaded that changing Svelte-Kit to load the app.html dynamically is the only way to solve your use case, though I can see where it would have advantages for you (it would certainly be simpler than the regex approach you're currently using). But as it's not necessary for most use cases, I suspect the only way you'll see this feature request implemented is to "scratch your own itch" by submitting a PR.

Alternately, if you don't want to wait for this feature request to be implemented, one thing you might be able to do for yourself, without needing to submit a PR to the Svelte-Kit project, is to write your own [adapter](https://kit.svelte.dev/docs#adapters) to take the built app and adapt it to load the template dynamically. You'd want to look at [these lines of code](https://github.com/sveltejs/kit/blob/93726c38d2118b1dc136f3ef659c5ae6bb039138/packages/kit/src/core/build/index.js#L291-L302) to see what it's producing and what you'd want to change.

**Comment by atuttle** [comment]
Thanks @rmunn there's a lot of great feedback there. I was thinking about submitting a PR this morning in the shower. :)

>  I think if you fix your regex to detect a wrapped {{app}} and remove that wrapper div 

The problem is that there is no way to predict what, if anything, will wrap the token. It could be nested inside 12 wrapping tags. The skin design is done by our customers. We can try to guide them, but that won't stop them from doing it wrong and then complaining to us when they've broken it. I think the best thing we could do would be to detect it using something like jSoup to parse the skin HTML and look at the element that contains the token -- if it's anything other than the body tag, they've done it wrong.

That said, I will definitely explore the adapter idea. I really appreciate the links to specific lines of code! 🤗

**Comment by Mlocik97** [comment]
Why don't just create some specific element, and use querySelector? You can do it on server-side too with jsdom or any other parser.

**Comment by atuttle** [comment]
@Mlocik97 I don't follow exactly. For what it's worth, the system where customers provide the skin HTML to us is not a node server, it's an entirely different platform (java-based, which is why I said I might be able to use jSoup)...

@rmunn I was thinking about maybe some sort of middleware for `adapter-node` (or maybe forking it if necessary). Started digging in to see where/how it runs. [I got this far](https://github.com/sveltejs/kit/blob/master/packages/adapter-node/src/kit-middleware.js#L27)... But the render method is passed as an option to that method, and it looks like it's from a file generated as part of the build (in `output/server/app.js`). Am I barking up the wrong tree? (I'm in the Svelte discord if you want to take this over there instead. 😄)

I'm not entirely certain that i need to change anything during the build phase. I need an SSR hook to override the template contents. So far I haven't found anything that appears to be the SSR portion of adapter-node (or is that the generated `output/server/app.js` file?)

**Comment by rmunn** [comment]
> For what it's worth, the system where customers provide the skin HTML to us is not a node server, it's an entirely different platform (java-based, which is why I said I might be able to use jSoup)...

I take it the customers need to be able to update the skin "live", i.e. they expect to be able to update the skins and have their updates take effect immediately. If they would find it acceptable to submit their proposed skins to you and wait for you to update their sites later, then you could insert a manual checking step where you could see what they've wrapped `{{app}}` in, and possibly update the regex accordingly. But I'm guessing you need them to be able to update "live", and therefore you can't know ahead of time how `{{app}}` will be wrapped. Is that right?

>> Why don't just create some specific element, and use querySelector? You can do it on server-side too with jsdom or any other parser.

> I don't follow exactly. 

I think @Mlocik97 meant that instead of asking your customers to put `{{app}}` in their markup, ask them to put in a specific element (or, I would add, an element with a specific ID). I.e. ask them to put `<div id="app"></div>` in their markup. Then after you retrieve the skin HTML, you can use existing HTML-parsing tools to find the div you need to replace, and remove the html/head/body stuff, etc. Which is going to be more reliable than regexes: if the customers give you malformed HTML skins, you can have the Java platform return an error saying "Must be valid HTML, here's the part that was invalid".

> Am I barking up the wrong tree?

I'm afraid I don't know the guts of the adapter system well enough to answer this, sorry. You're quite right that the Svelte discord is the right place to ask for help, so that these issue comments can be kept focused on your specific feature request (dynamically selecting the template HTML instead of serving up a static file). Thank you for keeping a good separation between feature requests and associated discussion (which do belong here), and "how do I do this thing?" requests, which belong either in the discord channel or in the GitHub Discussions feature. (I believe the project is planning to move to Discussions, but at the moment the discord channel is more active and you'll likely get faster responses there).

**Comment by atuttle** [comment]
> But I'm guessing you need them to be able to update "live", and therefore you can't know ahead of time how {{app}} will be wrapped. Is that right?

💯 Correct.

>  I believe the project is planning to move to Discussions, but at the moment the discord channel is more active and you'll likely get faster responses there.

I hope not. I've had nothing but negative experiences on GH Discussions (most memorably, with Next.js). So often questions just go completely unanswered, which makes the asker feel invisible. I appreciate that Discord has drawbacks too, but at least they don't include feeling like "nobody has seen my message" because you can see that others are around and chatting. Maybe enforce usage of threads in Discord instead?

---

Anyway, I submitted #2773 which would allow me to accomplish my goal using a `handle()` hook, thanks to some advice from Ben Mccann in **#contribute-to-svelte-kit** in Discord. :)

Thanks to both of you @rmunn and @Mlocik97 for your feedback here.

**Comment by benmccann** [comment]
solved here: https://github.com/sveltejs/kit/pull/2773#issuecomment-967099525
