### ISSUE TITLE
Scroll issue when navigating between pages (follow-up)

### ISSUE THREAD

**Issue by gavinr** [sveltejs/kit#2794]
### Describe the bug

This is a follow-up to #2760, which was closed #2761. I have updated my replication case to v`next.196` which has the fix from #2761. The issue is partially fixed but now there's an issue when using the back button.

### Reproduction

1. Go to https://gavinr.github.io/sveltekit-scroll-issue/
2. Scroll down 75% on the page, click link ~400
3. Next page loads at the top (As expected! This was fixed by #2761)
4. Scroll to the BOTTOM of this page.
5. Click "Back" button in the browser
    - Expected: page loads where you just were (about 75% down with item 400 in view)
    - Actual: page loads scrolled near the TOP of the page

### System Info

```shell
System:
  I have tested this on multiple browsers (Firefox, Chromium) on multple OSs (Windows 10, Linux) - it happens on all of them.
Binaries:
  Node: 14.18.1 - /usr/bin/node
  npm: 8.1.1 - /usr/bin/npm
npmPackages:
  @sveltejs/adapter-static: ^1.0.0-next.21 => 1.0.0-next.21 
  @sveltejs/kit: next => 1.0.0-next.196 
  svelte: ^3.42.6 => 3.44.1
```

### Severity

blocking an upgrade

### Additional Information

Thank you for your time supporting this project!

**Comment by simonxabris** [comment]
As extra info, I've tested this on macOS 11.6 in Chromium/Firefox/Safari with the reproduction site you provided and the scroll position was perfectly preserved.

**Comment by CarlosIvanchuk** [comment]
I tested it too on Windows 10 using Firefox 95.0b6 (64-bit) and it perfectly preserves scroll position as well.

**Comment by utkarshkukreti** [comment]
Another data point: I can reproduce the problem (page scrolls to top) on Edge 95 and Chrome 95, both on macOS 11.6. The scroll position is preserved on Safari 15 on the same macOS 11.6.

**Comment by gavinr** [comment]
Thanks all, sorry I did not post specific OS and browser details - I should have. The issue is happening for me on:

```
OS: Linux 5.4 Linux Mint 20.2 (Uma)
Chromium: 95.0.4638.69
```
video:

https://user-images.githubusercontent.com/209355/141660166-8c8d7ecc-97f8-438c-bd68-80028a25c2ba.mp4

**Comment by gavinr** [comment]
The issue also happens for me on:

```
Windows 10 Pro, build 19043.1348
Firefox 94.0.1
```

Video (Sorry no cursor in video but i think it's fairly obvious):

https://user-images.githubusercontent.com/209355/141660388-0468a53f-4317-497e-b38b-cd68eea45aaa.mp4

I will try to test with `Windows 10 and  Firefox 95.0b6 (64-bit)` (@CarlosIvanchuk says the issue should be resolved in that case)

**Comment by bttger** [comment]
I can reproduce this problem on my devices too, but only if I scroll down after navigating to page 400. If I click on the back button without scrolling down first, I get back to the same scroll position with the link to page 400 on the screen.

**Comment by gavinr** [comment]
@bttger yes, that's step 4 of the reproduction instructions.

**Comment by bttger** [comment]
Oh sorry, my fault.

**Comment by bluwy** [comment]
Thanks for the thorough reproduction! I'll try to look into this today or tomorrow if no one takes it.

**Comment by bluwy** [comment]
I took a look at this today, it isn't as easy as I thought. Turns out if you navigate back to the home page (based on repro steps), the `pageYOffset` before navigation is different after navigation. We had expected `pageYOffset` to be the same so we know there was no custom happening in `onMount()`. You can also reproduce this if you add a home link at the bottom of the slug page (not necessarily going back).

The interesting part is now that the difference mentioned can be derived from the body's implicit vertical margin, that happens because it's children are "inline" and has vertical mergin that extends over the parent:

![image](https://user-images.githubusercontent.com/34116392/141941174-3ff63b1e-65ad-405a-ac28-e783efa0181f.png)
(Opening devtools and highlighting `body` reveals this. Notice the implicit margin above the yellow area).

And the difference can be calculated by `top implicit margin - bottom implicit margin`px. What this also means is that if the top and bottom are the same, the bug doesn't happen, e.g. remove the "Welcome to SvelteKit" text in the repro.

With these said, I haven't found a solution yet and it feels like a simple navigation is getting too complex. IMO it might be better if we do it the proper way, but I'm not sure what yet.

**Comment by aolose** [comment]
I have same problem ~
here is what I do:

```
async function scTop() {
    await tick()
    document.scrollingElement.scrollTop = 0
    window.scrollTo(0, 0)
}
<svelte:window on:sveltekit:navigation-end={scTop}/>
```

**Comment by f-elix** [comment]
@bluwy I understand that the `no_scroll_happened` check in `renderer.js` originated from [#2664](https://github.com/sveltejs/kit/issues/2664), but I think this is really complicating things and is what is causing the scrolling issues.

I may be off here, but if custom scroll is happening inside `onMount`, it should happened AFTER the Sveltekit navigation scroll, not INSTEAD of it. 

Alternatively, we could let the author explicitly disable Sveltekit's navigation scroll by providing a function or option that could be called inside `onMount`. 

All this is to say that checking the different `pageYOffset`s, as is the case right now, produces inconsistent results and seems very brittle. Since this check only exists to satisfy a fairly niche case (explicitly overriding scroll position in `onMount`), I don't think it has its place and I feel the alternatives I outlined above (or some other) would be better.

**Comment by bluwy** [comment]
I agree, the `pageYOffset` checks we do now are very hacky and brittle :sweat_smile: I really want to move away from it but I can't find a way for it to satisfy all use-cases ootb.

> I may be off here, but if custom scroll is happening inside `onMount`, it should happened AFTER the Sveltekit navigation scroll, not INSTEAD of it.

Yes ideally we want this to be the case, but currently there's no way to do kit's navigation scroll *before* `onMount()`. Unless, the user runs their custom scrolling after a `tick`, which isn't something we'd want to enforce since it had always work in normal SPAs, and a kit specific condition for this would be off.

> Alternatively, we could let the author explicitly disable Sveltekit's navigation scroll by providing a function or option that could be called inside `onMount`.

I'm not sure if this would work nicely with actions that do custom scrolling, but so far we have `sveltekit:noscroll` (though that works a bit differently). An interesting idea though.

Ultimately, I too am very tempted to intentionally regress #2477, but so far the only way I think that might really fix this is if we inject a custom `onMount` for all the routes somehow (sounds like a bad idea). Or I wonder if we shouldn't mess with scrolls in the first place (I'm not sure why we did).

**Comment by f-elix** [comment]
> currently there's no way to do kit's navigation scroll before onMount(). 

I thought that the `await 0` was specifically to let `onMount()` run. Can't we just put it after kit's navigation scroll like it was done in the fix for #2477? Or am I wrong here?

**Comment by bluwy** [comment]
> I thought that the `await 0` was specifically to let `onMount()` run. Can't we just put it after kit's navigation scroll like it was done in the fix for #2477? Or am I wrong here?

If we put kit's navigation scroll before `await 0` the new route component wouldn't be rendered yet, so when kit's navigation scroll try to check for the `hash` element to auto-scroll to, it wouldn't be able to find it and causes #2664.

The current flow of the things is something like this:

1. Before new route component
2. Render new route component (no `onMount()` yet)
3. Mount new route component (called `onMount()`)

`await 0` now skips from step 1 to 3, ideally we want to run our navigation scroll checks in step 2.

**Comment by f-elix** [comment]
> If we put kit's navigation scroll before await 0 the new route component wouldn't be rendered yet, so when kit's navigation scroll try to check for the hash element to auto-scroll to, it wouldn't be able to find it and causes #2664.

Of course! Sorry I didn't catch that.

I think you just solved it! 

You could try something like this:

```js
if (scroll) {
    scrollTo(scroll.x, scroll.y);
} else {
    scrollTo(0, 0);
}

await 0;

const deep_linked = hash && document.getElementById(hash.slice(1));

if (deep_linked) {
    deep_linked.scrollIntoView();
}
```

**Comment by bluwy** [comment]
@f-elix I just tried that and turns out it won't solve this issue either. When we navigate back to the long list of numbers page, we're scrolling to a large `scroll.y` value when doing  `scrollTo(scroll.x, scroll.y);`, and because the old page doesn't a large scroll height, the scroll would be clamped when navigate to the new page after `await 0`. Meaning we would still need to run the `scrollTo(scroll.x, scroll.y);` after `await 0`, but that suffers from the incorrect `no_scroll_happened` logic.

Note: The `scroll.x` and `scroll.y` are values of which the user last scrolled to before navigating to a new page, so when navigate back, `scroll` would be defined and contains the values.

**Comment by f-elix** [comment]
@bluwy Hey thanks for trying!

I tried to find a solution myself for a few hours now and I am coming to the conclusion that we should keep sveltekit's scroll restoration to this (or something along those lines):

```js
await 0;

const deep_linked = hash && document.getElementById(hash.slice(1));

if (scroll) {
	scrollTo(scroll.x, scroll.y);
} else if (deep_linked) {
	deep_linked.scrollIntoView();
} else {
	scrollTo(0, 0);
}
```

This was the way scroll restoration was handled before version 193 and it is the in my opinion most efficient. It was changed to allow custom scrolling in `unMount` and actions, but I don't think there is a reliable way for Sveltekit to tell if that occured or not.

With the code above, the solution for users is pretty simple: they simply have to wait for the next tick to execute their custom scrolling.

This (does not work):
```js
const autofocus = (node) => {
	node.focus();
};
```

Would turn into this:
```js
import { tick } from 'svelte';

const autofocus = async (node) => {
        await tick();
	node.focus();
};
```

I would very much like that there was a way to not impose this on the user, but at the same time it's not that much work. 

I also looked at a few other client-side routing solutions and couldn't find on that tried to automate this. Vue router handles it by providing a special  `scrollBehavior` function to tell the router where to scroll to, or use `Vue.nextTick` to run your custom scrolling code after the router. React-router just gave up on handling it (https://v5.reactrouter.com/web/guides/scroll-restoration).

I understand this would be a breaking change to revert back to, but I really think it's worth it. After so many iterations on this, I doubt that anyone can find a reliable way to tell if scrolling occured in `onMount`.

**Comment by bluwy** [comment]
Thanks for the help @f-elix! Good to know that other frameworks had struggled with this as well. we can pull up our sleeves and find our own balance point. Regarding the `tick()` solution, that would be the last resort, or we would come up with a similar solution as Vue router or Nuxt.

But otherwise, I think I have an idea of using a custom preprocessor though to inject the scroll handling in the ideal mounting phase. I'm still testing it, but I'll also bring this up with the other maintainers and see what they think of the solutions.

**Comment by f-elix** [comment]
Oh interesting! Can't wait to see what you come up with.

**Comment by bluwy** [comment]
I made #2986, which hopefully will end all scrolling issues. It might be the last option we have for scrolling to work OOTB, otherwise we would be resorting to `export const autoscroll = false`. Feel free to try it out or give any opinions!

**Comment by benmccann** [comment]
#2986 was closed. There are some ideas for fixes listed in the final comments there: https://github.com/sveltejs/kit/pull/2986#issuecomment-1002302203
