### ISSUE TITLE
Have a way to render an error page when there's an exception in a hook (e.g. handle)

### ISSUE THREAD

**Issue by tomyan** [sveltejs/kit#2824]
### Describe the problem

When an exception occurs in handle you get the exception and stack trace in the response to the user.

### Describe the proposed solution

It would be great if there was a way to render an error page.

### Importance

nice to have

**Comment by dreitzner** [comment]
It might be nice to extend `handleError`.

There could be an optional return response with

```
{
  status: 301,
  redirect: 'error/some-special-page'
}
```

similar to https://kit.svelte.dev/docs#loading-output-redirect

**Comment by nhe23** [comment]
I like the idea of extending handleError, as this is the logical place for that. However I think this would create an infinite redirect loop in some cases because the handle hook would be executed again after the redirect (and potentially throw an exception again).

**Comment by nhe23** [comment]
After playing around a bit I came up with a working solution. I changed the handleError implementation in Sveltekit to optionally return a status and a redirect value (just as @dreitzner proposed). Then I changed the index.js in the server runtime in order to consider the redirect value if provided. The code looks like this:
```js	
const handleErrorOutput = await options.handle_error(e, request);
if (handleErrorOutput && handleErrorOutput.redirect) {
	return handleErrorOutput.redirect !== request.path
		? {
			status: handleErrorOutput.status ? handleErrorOutput.status : 301,
			headers: {
				location: handleErrorOutput.redirect
			}
		  }
		: await render_response({
		        options,
		        $session: await options.hooks.getSession(request),
		        page_config: { ssr: false, router: true, hydrate: true },
		        status: 200,
		        branch: []
		  });
}
```
This way a redirect loop is prevented and the provided error page is rendered as desired. If this is a feasible solution I can create a PR for my changes. Before I do that it would be nice if @benmccann or one of the other maintainers could provide some feedback on this solution.

**Comment by tomyan** [comment]
I'd prefer not to redirect if possible. For one thing a redirect is a successful status and if there's an error then I think a 500 should be returned so a non-human client can see that it wasn't successful. Furthermore if the error is transient I would like a user to be able to reload the page to retry, rather than be redirect away from what they were looking for.

**Comment by nhe23** [comment]
Those are some valid points. Maybe handleError could optionally return something like this:
```js
{
    renderError: true
}
```
If this flag is set the nearest [__error.svelte](https://kit.svelte.dev/docs#layouts-error-pages) component would be rendered. This solution would be consistent with the error handling of exceptions in load functions.
