### ISSUE TITLE
Obsfucate that Svelte was used (in production builds)

### ISSUE THREAD

**Issue by lkj4** [sveltejs/kit#2845]
### Describe the problem

First, I know that this is not really possible at the end of the day and every good dev can easily detect via different ways that Svelte was used. The problem is not a huge one but still, in high competitive markets you just want to disclose as little as possible about your stack.

### Describe the proposed solution

A start would be to remove all `svelte` strings in build filenames. From there we can find more hints which disclose that Svelte was used and address them.

### Alternatives considered

Maybe even as a build option `discloseSvelte` which defaults to true.

### Importance

would make my life easier

**Comment by rmunn** [comment]
:-1: from me because I don't think this would benefit enough people to merit the Svelte-Kit core team members spending any time implementing what would be a very difficult feature to implement. I would not oppose a PR adding that feature, if you feel strongly enough about it to write it yourself. But I feel that the number of people whom this would benefit is very low, and therefore it would be best for one of those people to do the work, and let the core Svelte-Kit team work on features that benefit a much larger number of people.

So don't take my downvote as saying "This should never be added", but rather as saying "The core team should not spend time on this, but feel free to write it yourself".

**Comment by bluwy** [comment]
I agree with rmunn, it would be weird for the team to invest time to hide Svelte, when we want to push its usage forward. Nonetheless, your proposed solution could already work with `@rollup/plugin-replace` by replacing `svelte` with some other thing.

**Comment by nosovk** [comment]
You already can achieve your goal using  `cssHash` option from compiler settings:
https://svelte.dev/docs#svelte_compile

We actually need it if we instantiate a few similar svelte components in a one page, but you can use that option to hide svelte prefix from generated classes.

**Comment by dominikg** [comment]
If we wanted to do this, it would have to be raised on svelte repo, not kit. But like others have said thats not something of interest.

If you need obfuscation, add it via post processing build output
