### ISSUE TITLE
[bug] `npm init svelte@next` - some files missing

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#2952]
### Describe the bug

I don't get any warning using npm 6 and Node 12 on Ubuntu. If I create an `.npmrc` with `engine-strict=true` then it will fail. We try to do that today:

https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/skeleton/.npmrc
https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/.npmrc

But those files don't get created for some reason

### Reproduction

If I run `npm init svelte@next my-test-app` I don't see an `.npmrc` file being created in the new app

### System Info

```shell
System:
    OS: Linux 5.13 Ubuntu 21.10 21.10 (Impish Indri)
  Binaries:
    Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
    npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
```

### Severity

annoyance

**Comment by Conduitry** [comment]
It looks like the files disappeared from the published package in `create-svelte@2.0.0-next.77`. The would point to #2109 as the culprit.

**Comment by Conduitry** [comment]
My next guess is that this was due to a bump in the version of (p)npm used to publish the packages. When I build everything locally, I do see `.npmrc` files where I expect to see them in the local file system, but when I run `npm pack` from `packages/create-svelte` to produce the tarball that would be sent to the registry, it doesn't contain the `.npmrc` files.

It could be that we need to store it as `npmrc` in the package (like we currently do with `gitignore`) and then rename it with the `.` afterwards.

**Comment by Conduitry** [comment]
Yeah, if I run `npm pack` with npm 6, I get the `.npmrc` files in the resulting tarball. I didn't look extremely closely, but I don't see anything in https://github.com/npm/cli/blob/latest/changelogs/CHANGELOG-7.md that sounds like it would have caused this. But in any case, we probably want to rename the file.

**Comment by benmccann** [comment]
https://stackoverflow.com/questions/58284494/npm-pack-publish-wont-pack-gitignore-or-npmrc-files

**Comment by Conduitry** [comment]
Hmm I don't see any relevant differences in the documentation page they linked to in their own answer between v6 and v7 (`.npmrc` is listed as automatically ignored in both) so maybe this was considered a bug in v6? In any case, it would be a lot easier to just deal with this than figure out why it changed.
