### ISSUE TITLE
CLI: Terminal output is unreadable in dark Visual Studio Code / terminal themes

### ISSUE THREAD

**Issue by mandrasch** [sveltejs/kit#2976]
### Describe the bug

The terminal output is unreadable when using a dark-colored theme in VScode such as Tomorrow Night Blue:

![image](https://user-images.githubusercontent.com/777278/144567626-b0f03015-d8ef-4283-9dd6-bf3a5654f3b6.png)

I just checked nextjs in comparison and they somehow solved this:

![image](https://user-images.githubusercontent.com/777278/144567841-c843694e-42a5-4292-8874-5b819deb7d46.png)

Couldn't figure it out with a quick google search, therefore just wanted to let you know. Thanks very much for providing svelte as open source! 👍 
(I also looked for an existing issue in svelte & svelte kit repo, if I missed something - sorry!)

### Reproduction

VSCode Version: 1.62.3 (Universal)
"workbench.colorTheme": "Tomorrow Night Blue"

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Apple M1
    Memory: 38.02 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 8.1.1 - /usr/local/bin/npm
```

### Severity

annoyance

**Comment by bluwy** [comment]
Thanks for checking around before reporting this. But I don't think this is something we can solve since everyone could be using their own light/dark themes, and the colors we choose can't please everyone. However, if you're using VSCode, you can adjust the `terminal.integrated.minimumContrastRatio` setting to output a readable color. I have mine at `9`.

Closing this due to above reasons.
