### ISSUE TITLE
[@sveltejs/adapter-static] - Adding endpoints that are used client side only

### ISSUE THREAD

**Issue by Cluster2a** [sveltejs/kit#3100]
### Describe the problem

I am using the @sveltejs/adapter-static-Adapter for prerendering the page during the build.

If I am using a contact form I need to send emails via a server-side endpoint.

Since the endpoint is called only client-side and not on load() the endpoint will work in dev, but not on production, as it's not considered during build.

Deploying the app to vercel, the endpoint call will result in a 404.

### Describe the proposed solution

Since there are many use cases for using server-side endpoints even on static pages, There should be a way to mark endpoints for building/deployment.

### Alternatives considered

The only option right now is to avoid static generated files if server-side endpoints are needed.

### Importance

would make my life easier

**Comment by bluwy** [comment]
I don't quite understand the proposed solution. If you're using the static adapter, it would assume that every page is prerendered and generate static HTML files only. Your deployment platform would then serve these HTML files as is.

If you want server-side endpoints to work, you would need to use the vercel adapter so that it runs as s serverless function, and the endpoint would work. And for pages that can be prerendered, you can mark `const prerender = true`.

Another way around this is to have that server-side code separate from the static files, and manually deploy that server-side code as a serverless function. Your static files would then call this API separately.

**Comment by ignatiusmb** [comment]
This should've been a discussion, but @bluwy is right, `adapter-static` is specifically for _static sites_ and endpoints are also pre-generated as static files so there won't be any server-side functionality to do stuff like sending emails. You need to use a serverless adapter and prerender the pages you want to prerender, or have a separate server running.

**Comment by Cluster2a** [comment]
@bluwy, using vercel functions besides the static page generator is something I considered, but I think the coding experience is awful using this kind of mix-up.

I wasn't aware that export const prerender = true; will result in statically rendered pages even with the vercel adapter. Thanks a lot!
