### ISSUE TITLE
Focus broken when navigating with hash

### ISSUE THREAD

**Issue by AnishDe12020** [sveltejs/kit#3105]
### Describe the bug

In an effort to make tab navigation better on my site, I was implementing a skip to content button which would skip the navbar and directly go to the content. I have implemented it as it is normally implemented but I am running into a small problem. Normally, focussing on the skip to content button and then pressing enter gets you to the content, and pressing the tab key after that makes you cycle through the content. In my implementation, I am brought to the skip to content button twice before I can cycle through the site's content. 

### Reproduction

Add a skip to content link to a page (basically a link that is the first thing to come into focus and shows up when tabbed on landing on the website and else remains hidden). Set the `href` to an id the link points to (usually something like `main` or `content` that is after that page's navbar/header). Navigate to the site, press tab, press enter, again press tab and the skip to content link will again show up.

### Logs

```shell
None. Check additional information for screen recording, details on code, source code, and a hosted site where it can be reproduced.
```

### System Info

```shell
System:
    OS: Linux 5.15 Pop!_OS 21.10
    CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
    Memory: 3.19 GB / 15.52 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.9.1 - ~/.nvm/versions/node/v16.9.1/bin/node
    Yarn: 1.22.17 - /usr/bin/yarn
    npm: 7.21.1 - ~/.nvm/versions/node/v16.9.1/bin/npm
  Browsers:
    Brave Browser: nightly
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.3 
    @sveltejs/kit: next => 1.0.0-next.201 
    svelte: ^3.44.0 => 3.44.2
```

### Severity

serious, but I can work around it

### Additional Information

Hosted Preview - https://portfolio-nlaow838l-anishde12020.vercel.app/
Source code (THIS SPECIFIC COMMIT) - https://github.com/AnishDe12020/portfolio/commit/d2406ffeb65e0f1da29d6d95e8a2c323051dd3b6

<details>
<summary>Details on the code</summary>
I have added a button to the layout of my website, that is in `__layout.svelte`. Here is the code:

```svelte
<script>
  import "../app.css";
  import WipBanner from "../components/wip-banner.svelte";
  import Header from "../components/header.svelte";
  import Footer from "../components/footer.svelte";
  import BackToTop from "../components/back-to-top.svelte";
  import Socials from "../components/socials.svelte";
  import data from "../data.json";
</script>

<div class="max-w-[1920px] mx-auto">
  <a href="#content" class="skip-content-link">Skip To Content</a> <!-- the skip to content button -->
  <BackToTop />
  <WipBanner />
  <Header />
  <slot />
  <Footer />
  <Socials
    socialsData={data.socials}
    classNames="fixed bottom-8 left-8 flex-col space-y-6 hidden md:flex"
    showText
  />
</div>
```

I have added some styles in `app.css` for the same:

```css
.skip-content-link {
  position: absolute;
  transform: translateY(-100%);
  background: #1d3dae;
  padding: 1rem 0.5rem;
  border-radius: 0rem 0rem 1rem 0rem;
}

.skip-content-link:focus {
  transform: translateY(0%);
}
```

At last, I have given the content an `id` of `content` in `index.svelte` so that it can be scrolled down to whenever the skip to content button is engaged:

```svelte
<main id="content">
  <Hero />
  <BlogPosts blogPosts={data.blogPosts} blogBaseUrl={data.blogBaseUrl} />
  <Projects projects={data.projects} />
  <Skills skillsData={data.skills} />
  <Contact emailAddress={data.emailAddress} />
</main>
```

Note: I was following this article on css-tricks: https://css-tricks.com/how-to-create-a-skip-to-content-link/

</details>

For more context, here is a screen recording - 

https://user-images.githubusercontent.com/63192115/147273364-a8b1ec40-e08a-4018-bc87-6b7cfdf8aeb4.mp4

Also, I have tried this on another SvelteKit project and had faced the same issue.

Discussion we are coming from - https://github.com/sveltejs/kit/discussions/3098

**Currently using a workaround as suggested in https://github.com/sveltejs/sites/pull/245**

**Comment by jasonlyu123** [comment]
It seems to be because we `preventeDefault` even when it's only navigating by hash.
 https://github.com/sveltejs/kit/blob/e79cf049ab36d42d6db0d0bb0092ea4e36dc937f/packages/kit/src/runtime/client/router.js#L164

This prevented browser's default [sequential focus navigation starting point](https://html.spec.whatwg.org/multipage/interaction.html#sequential-focus-navigation-starting-point) behaviour. Don't call `preventDefault` for same-page navigation could fix this specific case. 

But it won't work if the target is on another page(`otherpage#hi`). It would also be a problem when the app doesn't have SSR and the page started with a hashed URL like `/somepath#i-am-an-id`. 

Wondering if there's any prior art in other frameworks regarding this. Would like it to work like traditional page navigation. I don't know any dom API that could do this. And we can't just set focus on the target element. As the element might not be focusable and if we make it focusable it might show a focus ring. The only thing I could think of now is to just create a dummy element, insert before the target element, focus it and remove it.

**Comment by bluwy** [comment]
Looks like we're already detecting "hash navigation with no url change" scenarios at:

https://github.com/sveltejs/kit/blob/e79cf049ab36d42d6db0d0bb0092ea4e36dc937f/packages/kit/src/runtime/client/router.js#L155-L162

I don't remember why we decided to emit a `HashChangeEvent`, instead of just returning so it defaults to the browser behaviour. The `history.pushState({}, '', url.href);` looks extraneous too. @benmccann Is there a reason for the way it is now? Those changes are introduced at #2590.

**Comment by benmccann** [comment]
https://github.com/sveltejs/kit/issues/2588 was the motivation for adding `HashChangeEvent`. I guess you're suggesting we could instead do:
```
 if (u1 === u2) { 
 	return; 
 } 
 history.pushState({}, '', url.href); 
```

I don't think we really considered that. If that works better I think we could change it. Though according to @jasonlyu123's comment above https://github.com/sveltejs/kit/issues/3105#issuecomment-1003304642 I'm not sure that would fix all cases

**Comment by geoffrich** [comment]
As a note, this affects all navigation by hash, not just skip-to-content links, which makes it much less of an edge case. For instance, if I'm navigating by keyboard around the SvelteKit docs and hit enter on a link to another section of the page (e.g. https://kit.svelte.dev/docs#configuration), the page scrolls to the relevant section, but my focus is reset to the top of the page. This requires me to tab forever to reach the section I was linked to, if I can even find it. This also means that if I'm navigating the docs with a screen reader, all the intra-page links are unusable, since they'll make me lose my spot and reset my position to the top of the page.

Essentially, this bug makes experiences like the SvelteKit docs (with lots of hash links inside the page) inaccessible to screen reader and keyboard-only users.

**Comment by bluwy** [comment]
> Though according to @jasonlyu123's comment above [#3105 (comment)](https://github.com/sveltejs/kit/issues/3105#issuecomment-1003304642) I'm not sure that would fix all cases

> But it won't work if the target is on another page(`otherpage#hi`. It would also be a problem when the app doesn't have SSR and the page started with a hashed URL like `/somepath#i-am-an-id`.

If we're navigating to another page with a hash, or a page without SSR, I think we had already covered that together with the scrolling logic when we navigate to the new page. I think the only case where this wouldn't work is if we intentionally disable the router, which would be expected behaviour. Might need to double check this though.
