### ISSUE TITLE
`sveltekit:prefetch` seems to be invalid HTML

### ISSUE THREAD

**Issue by moritzebeling** [sveltejs/kit#3186]
### Describe the problem

Hey, I just validated my SvelteKit website with https://validator.w3.org/nu/ and it heavily complained about `sveltekit:prefetch` not being valid HTML.

Is this a problem? Maybe if some service wanted to rank the quality of some website, they would use an HTML validator and adjust the ranking accordingly?

### Describe the proposed solution

To avoid that, maybe the Svelte compiler could automatically turn such things into a valid HTML attribute like `data-sveltekit="prefetch"` from where the router can pick it up?

In my imagination this should be fairly easy to implement and would result in valid HTML.

### Importance

nice to have

### Additional Information

Thank you very much for building Svelte!

**Comment by ghostdevv** [comment]
Quite interested in this - is the site public so I can test it myself :p @moritzebeling

**Comment by moritzebeling** [comment]
I think it is not inherent to my specific site. You can try it out here

https://validator.w3.org/nu/#textarea

and put in the following code
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>SvelteKit check if sveltekit:prefetch is valid HTML</title>
</head>
<body>
    <h1>SvelteKit check if sveltekit:prefetch is valid HTML</h1>
    <a href="/page" sveltekit:prefetch>Link</a>
</body>
</html>
```

<img width="1072" alt="Bildschirmfoto 2022-01-07 um 14 44 34" src="https://user-images.githubusercontent.com/39742729/148552579-2ce4c6b6-da6f-4473-a439-6fab1334faab.png">

**Comment by dummdidumm** [comment]
I think we would need to do something like `data-sveltekit-prefetch` in order for it to be valid. The validator complains about every unknown attribute on any known tag.

**Comment by ghostdevv** [comment]
Could `sveltekit:prefetch` be internally search & replaced with `data-sveltekit-prefetch` so it's not breaking and it keeps the good DX?

**Comment by Greenheart** [comment]
I did some investigation on this.

This change will likely need to be solved similarly for `sveltekit:reload` and `sveltekit:noscroll` too.

Could this perhaps be solved without a breaking change? What if we transform all `sveltekit:*` attributes into `data-sveltekit-*` during compilation/rendering, where `*` could be slugified or matched against valid keywords.

It would be nice to keep the DX of `sveltekit:*` which would have consistent syntax with [svelte element directives](https://svelte.dev/docs#template-syntax-element-directives).

## To implement this, we would need to:

- Transform the build output by replacing `sveltekit:*` with `data-sveltekit-*`. This should be the same way on the client and server. Would also be nice to keep it consistent both for `dev` and `build`.

- We need to rename the expected attributes from `sveltekit:*` to `data-sveltekit-*` in the file https://github.com/sveltejs/kit/blob/6c84f40ebb34e744867fc7a2c50eb1b4ce3c62fe/packages/kit/src/runtime/client/client.js

- Update tests. Possibly also examples and docs.

Suggested changelog entry:

> SvelteKit will now replace `sveltekit:prefetch`, `sveltekit:noscroll` and `sveltekit:reload` with valid HTML data attributes. No changes required for most users, but if you're checking for the existence of `sveltekit:*` attributes you need to update to use `data-sveltekit-prefetch` instead.

I'd be happy to make a contribution to solve this, but have some questions... 😄 

1. Any feedback on this proposed solution?
2. Important: Can you link to the relevant code modules where it would make sense to replace `sveltekit:*` attributes with `data-sveltekit-*`? I assume this should happen during the rendering phase, or before passing the code on to adapters, since this should be a core SvelteKit feature and not a adapter-specific one.

**Comment by Greenheart** [comment]
Since this is a low prio issue I don't expect much support, but I'm documenting my progress here anyway 🙂 

Update: There are likely much better ways of solving this, but I've hacked together a partial solution here: https://github.com/Greenheart/kit/commit/545286dade31ae1be9a0390113456dbd522c3637

Status:
- It currently only works on `build` (not `dev`)
- It needs to be limited to only replace HTML attributes, and not text content within components.
- It needs to be tested with all rendering modes such as SSG, SSR and SPA.

Let me know if there's a way to solve this with ASTs when parsing the svelte code, since that would make the solution much cleaner. However, I'm afraid that the ability to use ASTs would happen outside of SvelteKit and instead in the `vite-plugin-svelte` or `svelte` which compile the components.

**Comment by kevmodrome** [comment]
Maybe a sveltekit preprocessor (maybe there already is one?) that is applied in the background could help us with most of these issues?

**Comment by Greenheart** [comment]
That's a good idea! It actually looks like `svelte-preprocess` already supports something very similar to what we need. It's already included as a dependency in SvelteKit too.

Here's the relevant code: https://github.com/sveltejs/svelte-preprocess/blob/main/src/transformers/replace.ts

This means we might be able to add a default transform to the `preprocess` option in `svelte.config.js`. And the best part: hopefully end users would still be able to add their own config for `preprocess.replace` https://www.npmjs.com/package/svelte-preprocess#replace-values. I'll see what I can find... 😄

**Comment by Greenheart** [comment]
Using `svelte-preprocess` worked great! We now have a PoC in https://github.com/Greenheart/kit/commit/ee56dc75f8b7f2f3239414e8396f52e51af111e2 which can be run from the user's own config :smile:

Now, we need to extend the user's `svelte.config.js` and their possible `preprocess` config (if they use postcss, mdsvex or similar). If we can do this, we could let sveltekit handle the replacing of `sveltekit:*` attributes internally, which would be super clean to app developers.

**Comment by Greenheart** [comment]
More progress to extend `svelte.config.js`. Not quite there yet, but getting closer :)

https://github.com/sveltejs/kit/commit/ca440d28028cc7b2a8052dc472ad2143b0afaf56
https://github.com/sveltejs/kit/commit/c512b27c461c6d5134649a5e77c87ecce5a02d28

**Comment by Rich-Harris** [comment]
As mentioned on the PR, I'm opposed to a transform step that changes `sveltekit:prefetch` to `data-sveltekit-prefetch` under the hood (https://github.com/sveltejs/kit/pull/6170#issuecomment-1223322743).

Which means that if we were to make this change, it would be a breaking change — we would no longer be able to use `sveltekit:prefetch` etc and would have to use the arguably inferior ergonomics of `data-` prefixes.

If we make such a change, it should be for a good reason, _not_ a speculative one like 'search engines might downrank you' or 'a11y tools might complain'. I'm unaware of any such impacts (and I'd expect more people to have found their way to this thread if there were), so my inclination would be to leave things as they are, but I'd be interested to hear from anyone if there's a compelling reason to switch?

**Comment by Tal500** [comment]
Just a noobie question - why do you need to emit the `sveltekit-prefetch` attribute to a real HTML attribute in the DOM?
I supposed it resolves internally to a Svelte action on the anchor element that prefetch on hover, no need to register the value in an attribute on DOM.

This raises the following question for a clear API - why not to export a `prefetch` action? The user code would look like:
```svelte
<script>
import { prefetch } from '$app/actions';
</script>

<a use:prefetch href='/about'>About</a>
```

**Comment by PatrickG** [comment]
> Just a noobie question - why do you need to emit the `sveltekit-prefetch` attribute to a real HTML attribute in the DOM?
> I supposed it resolves internally to a Svelte action on the anchor element that prefetch on hover, no need to register the value in an attribute on DOM.

https://github.com/sveltejs/kit/blob/master/packages/kit/src/runtime/client/client.js#L1151
