### ISSUE TITLE
Convert everything to ESM

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#349]
Modules are now fully supported in Node, except in Node 10 which will fall out of LTS very soon (the current 'active' LTS version is 14).

It makes sense, I think, for SvelteKit to fully embrace ESM, by which I mean that the CLI should be distributed as ESM, and that `svelte.config.js` and `snowpack.config.js` should be ESM. 

There is a practical benefit to this, aside from making everything new and shiny and futureproof: it means that you can trivially share modules between the app you're building and e.g. `npm run` scripts. (We've encountered this at the NYT — we have a `decompress` module that is primarily used in the client to calculate things like rolling averages, which don't need to come over the wire, but which are also needed script-side to generate some summary data files.)

**Comment by benmccann** [comment]
Electron 12 uses Node v14 I believe (https://www.electronjs.org/releases/stable). Help > About shows VS Code is on Electron 11.3. Hopefully at some point it will be updated which my unblock language tools being able to use ESM

**Comment by GrygrFlzr** [comment]
It says it's currently on Node 12.18.3, is that not compatible with ESM?

**Comment by babichjacob** [comment]
> It says it's currently on Node 12.18.3, is that not compatible with ESM?

If I remember correctly, only with the `--experimental-modules` flag.

**Comment by GrygrFlzr** [comment]
According to the [Node 12.17 changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V12.md#2020-05-26-version-12170-erbium-lts-targos):

> As of Node.js 12.17.0, the `--experimental-modules` flag is no longer necessary to use ECMAScript modules (ESM).

In fact, this is why our `create-app` template requires Node 12.17 as a minimum.

There seems to be an open issue about this: electron/electron#21457, in particular this [interesting comment](https://github.com/electron/electron/issues/21457#issuecomment-757790025):

> AFAIK, Electron does support esm, but not as the first file loaded.
> You still need to have a cjs file at first, that will load your esm application

It's the exact same situation as the AWS lambdas! We only need the entry point to be CJS, and it can `await import` ESM from there!

**Comment by dummdidumm** [comment]
Interesting, will do a spike if I have the time testing this.  If it works I need to come up with a good solution for the async loading of the config though, right now it's expected to be synchronous because that code path needs to be synchronous,too.

**Comment by hatemjaber** [comment]
I've burnt too many hours trying to resolve this issue.... I'm using typeorm and having issues running a migration, I keep getting the following error:

`import type { MigrationInterface, QueryRunner } from "typeorm";
^^^^^^

SyntaxError: Cannot use import statement outside a module`

outside of compiling the ts to js and using the js file, I can't get this to work. I just want an out of the box experience without having to tweak the generated files. Am I doing something wrong? Is there something else that I need to do in order to get this to work? I assumed using the ts version when generating the project would give me all the settings that I need to run ts code. I put all my ts code inside the src/lib to avoid issues.

I apologize if this is not the right place to ask, I tried on discord but was not able to get an answer. i have everything else working with typeorm except the migrations which uses their cli and causes this error.

**Comment by benmccann** [comment]
TypeOrm is known not to work with SvelteKit. See https://github.com/sveltejs/kit/issues/798

**Comment by benmccann** [comment]
TypeOrm is known to have difficulties working with SvelteKit. See #798. Though there is a suggestion there of a Vite plugin to try using. No one has reported yet whether it works or not

**Comment by hatemjaber** [comment]
@benmccann I know what the issue is but I don't know how to resolve it without breaking sveltekit, maybe you can guide me.

If I remove "type": "module" from package.json and i change "module": "es2020" to "module": "commonjs" in tsconfig.json, it works.

Is there a way around this where I don't have to make these changes?

**Comment by hatemjaber** [comment]
@benmccann I'm sorry to bother you, maybe this helps also...

I modified the recommendation in the typeorm documentation for adding the custom script by forcing it to use commonjs like so: 
`"typeorm": "TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\"}' node --require ts-node/register ./node_modules/typeorm/cli.js"`

The only issue now is getting around the ` "type": "module"`. I don't know enough about sveltekit/typescript and how they work to get around that one. If you can tell me how to do that without breaking sveltekit, that would make using tyeporm possible.

Thank you in advance!

**Comment by hatemjaber** [comment]
This is a hack, please advise if you have a better solution:

`"scripts": {
    "dev": "npx json -I -f package.json -e \"this.type='module'\" && svelte-kit dev",
    ...
    "typeorm": "npx json -I -f package.json -e \"this.type='commonjs'\" && TS_NODE_COMPILER_OPTIONS='{\"module\":\"commonjs\"}' node --require ts-node/register ./node_modules/typeorm/cli.js"
  }`

Rewrite the type each time we run an npm script
