### ISSUE TITLE
Store inconsistent when set inside `load` function

### ISSUE THREAD

**Issue by dodiameer** [sveltejs/kit#3549]
### Describe the bug

Setting/reading a store in a `load` function will cause some inconsistency between the server and the client  — The store will have the set value on the server but will get the initial value on the client side, so in a way the store's data isn't synced between the client and the server.

### Reproduction

I ran into the issue trying to use stores to cache response data so I also made the reproduction similar to what I'm doing in my app

https://stackblitz.com/edit/sveltekit-tbadn2?devtoolsheight=33&file=src/routes/index.svelte

### System Info

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 695.84 MB / 5.82 GB
  Binaries:
    Node: 16.13.2 - ~\AppData\Local\Volta\tools\image\node\16.13.2\node.EXE
    Yarn: 1.22.17 - ~\AppData\Local\Volta\tools\image\yarn\1.22.17\bin\yarn.CMD
    npm: 8.1.2 - ~\AppData\Local\Volta\tools\image\node\16.13.2\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (97.0.1072.69)
    Internet Explorer: 11.0.22000.120
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.15
    @sveltejs/kit: next => 1.0.0-next.242
    svelte: ^3.44.0 => 3.46.2
```

### Severity

serious, but I can work around it

### Additional Information

I'm not sure if this is intended behaviour - if so, sorry for wasting your time! 

This doesn't happen on StackBlitz for some reason, the first time you load the site it'll fetch on the server and then on the client, all subsequent times it'll only fetch on the client, on StackBlitz it seems like the cache already exists the moment you load the site but I can confirm that's something to do with StackBlitz

**Comment by Conduitry** [comment]
No state is automatically synced between the server and the client. It's not possible to do that with a store because it's just an object with a `subscribe` method, and there's no way of knowing where its state lives or whether it's serializable. If you want to pass state from the server to the client, you should use one of the other established mechanisms for doing so, like `props` or `session`.

And using a store like that on the server is something you need to be very careful about, because it will be shared by all users of the site when getting server-rendered content, as indicated at the bottom of https://kit.svelte.dev/docs#loading

**Comment by dodiameer** [comment]
That's what I thought but I wanted to make sure in case it does work and I was doing something wrong. Thanks for the quick reply
