### ISSUE TITLE
Reset layouts still inherit their parents' styles

### ISSUE THREAD

**Issue by GauBen** [sveltejs/kit#3622]
### Describe the bug

__layout.reset.svelte does not reset the style stack

### Reproduction

**/src/routes/__layout.svelte**
```svelte
<h1>Root layout</h1>
<slot/>

<style>
  :global(html) {
    background: skyblue
  }
</style>
```

**/src/routes/nested/__layout(.reset)?.svelte**
```svelte
<h1>Nested layout</h1>
<slot/>
```

Without .reset:
![image](https://user-images.githubusercontent.com/48261497/151665364-941bc6c0-8cdb-4b36-a020-2c76add17899.png)

With .reset:
![image](https://user-images.githubusercontent.com/48261497/151665335-44721488-eb4b-46f9-90e9-046a9bd26389.png)
(It should not have the blue background)

### System Info

```shell
devDependencies:
  '@sveltejs/adapter-auto': 1.0.0-next.17
  '@sveltejs/kit': 1.0.0-next.250_svelte@3.46.3
  svelte: 3.46.3
```

### Severity

annoyance

### Additional Information

I'm not sure if this is the intended behavior, but it seems inconsistent

**Comment by babichjacob** [comment]
Reason in https://github.com/sveltejs/kit/pull/1356#issuecomment-833572267

Is this only when using client side navigation (e.x. by clicking links to go from a page using the root layout to one using the nested layout), or do you still see the unexpected background color after refreshing the page?

**Comment by GauBen** [comment]
Both, that's why I considered it not being a bug but a feature

**Comment by Rich-Harris** [comment]
This is a consequence of how styles work in SvelteKit — if you import a component, its CSS will be applied to the page, regardless of whether it is rendered or not (and it won't be removed when the component is destroyed), because the contents of `<style>` are ultimately turned into a `<link rel="stylesheet">`, as if you had an explicit `import './styles.css'` declaration. You could definitely make the case that this is a bug, but changing that behaviour would make performance worse in the general case.

Styles from the root layout will therefore always apply, because the root layout is always imported eagerly (along with the root error component). You'll have to work around it by avoiding global `body` styles there.

Realistically this would be very difficult to change, so I'm going to close this issue. (Note that layout resets have been replaced by [named layouts](https://kit.svelte.dev/docs/layouts#named-layouts).)

**Comment by GauBen** [comment]
This makes sense, thanks for answering
