### ISSUE TITLE
missing params if route contains errors

### ISSUE THREAD

**Issue by ivanhofer** [sveltejs/kit#3647]
### Describe the bug

If a route contains an error (unhandled fetch-requests, errors in a component, etc.) then the `__error.svelte` file gets rendered.
This will also call the `load` function from the `__layout.svelte` file, like a normal request would do. Except that the `params` object is empty.

In a production application I use the slug to get the locale from the url e.g. `/en/settings`. When something fails then I no longer have the locale information in the `params` object and I need to use a workaround to get the locale.
```ts
const lang = params.lang || url.pathname.split('/')[1]
```
In this case it's simple and I know the position of the param, but for other cases it would be good if the `params` could also be accessed when a `error` page is rendered.

### Reproduction

Here is a demo repository with a short description in the `README.md`:
https://github.com/ivanhofer/sveltekit-missing-params

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz
    Memory: 2.63 GB / 7.66 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.volta/tools/image/node/16.13.1/bin/node
    Yarn: 1.22.17 - ~/.volta/tools/image/yarn/1.22.17/bin/yarn
    npm: 8.1.2 - ~/.volta/tools/image/node/16.13.1/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.17 
    @sveltejs/kit: next => 1.0.0-next.251 
    svelte: ^3.44.0 => 3.46.3
```

### Severity

serious, but I can work around it

**Comment by ivanhofer** [comment]
The issue is located here:
https://github.com/sveltejs/kit/blob/3b161613fce27c54f227994fbe8db3d0bed92016/packages/kit/src/runtime/server/page/respond_with_error.js#L27-L28

**Comment by EstebanBorai** [comment]
Hi! I'm having the same issue as well. I'm also a _typesafe-i18n_ user and I
followed the same approach from the [SevelteKit example][1].

This is my `load` function for `routes/__layout.svelte`:

```svelte
<script context="module" lang="ts">
  export const load: Load = async ({ url, params, session }) => {
    const lang = params.lang as Locales;

    // log to console for debugging
    console.log({
      url,
      params,
    });

    // redirect to preferred language if user comes from page root and no
    // `lang` param is present
    if (!lang) {
      return {
        status: 302,
        redirect: `/${session.locale}`,
      };
    }

    // redirect to base locale if language is not present
    if (!locales.includes(lang)) {
      return {
        status: 302,
        redirect: replaceLocaleInUrl(url.pathname, baseLocale),
      };
    }

    return { props: { locale: lang } };
  };
</script>
```

As you can see I'm logging `url` and `params` to console to inspect the values,
I expect the `lang` param to be present always because all of my routes exists
under: `routes/[lang]/`.

This works as expected when visiting existent routes, but when hitting error
pages (such as 404, 500), the `lang` param is missing.

First I visit my home page which is on: `https://localhost:3000/en`, so I get:

```js
{
  url: URL {
    href: 'https://localhost:3000/en',
    origin: 'https://localhost:3000',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'localhost:3000',
    hostname: 'localhost',
    port: '3000',
    pathname: '/en',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  params: { lang: 'en' }
}
```

As expected the `lang` param is present inside the `params` object.
But if I visit a unexistent page like: `https://localhost:3000/en/unexistent`

```js
{
  url: URL {
    href: 'https://localhost:3000/en/unexistent',
    origin: 'https://localhost:3000',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'localhost:3000',
    hostname: 'localhost',
    port: '3000',
    pathname: '/en/unexistent',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  params: {}
}
```

The `lang` parameter is not present. I get redirected to `/en/` because as is
appreciated in the `load` function logic, if no `lang` parameter is present the
user will be redirected to a URL with the preferred language.

```js
{
  url: URL {
    href: 'https://localhost:3000/en',
    origin: 'https://localhost:3000',
    protocol: 'https:',
    username: '',
    password: '',
    host: 'localhost:3000',
    hostname: 'localhost',
    port: '3000',
    pathname: '/en',
    search: '',
    searchParams: URLSearchParams {},
    hash: ''
  },
  params: { lang: 'en' }
}
```

[1]: https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit/blob/5118060f6681949e0633a45b6fe3cf39b7ab4e0f/src/routes/__layout.svelte#L14

**Comment by Badlapje** [comment]
@EstebanBorai you might be interested to know that @ivanhofer has already committed a work-around in the https://github.com/ivanhofer/typesafe-i18n-demo-sveltekit repo (amazingly speedy resolution).

**Comment by Rich-Harris** [comment]
Since #4344, `params` are available in error pages: https://stackblitz.com/edit/sveltejs-kit-template-default-h6by79?file=src%2Froutes%2Findex.svelte&terminal=dev
