### ISSUE TITLE
Client side load provided fetch follows redirect of endpoint instead of redirecting the app

### ISSUE THREAD

**Issue by Theo-Steiner** [sveltejs/kit#3861]
### Describe the bug

Hey everyone,
I am not sure if this has already been addressed by #3858, so please close this issue if that is the case. 

Returning a redirect from an endpoint works on the first load but on subsequent client navigation it seems to break as the fetch provided by the load function just follows the redirect, successfully fetches something(?) inlined into html.
As a result of this, the responses status is 200 instead of 302 and the location header is also lost. Since the response is .ok, the app then renders as if no redirect ever occured (although without the correct data)

### Reproduction

Here's a reproduction of this behavior on stackblitz:
https://stackblitz.com/edit/sveltejs-kit-template-default-wysivk?file=src%2Froutes%2Findex.svelte&terminal=dev

### System Info

```shell
stackblitz and also 

  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 131.28 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /opt/homebrew/bin/node
    npm: 8.3.1 - /opt/homebrew/bin/npm
    Watchman: 2022.01.31.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 98.0.4758.80
    Firefox Developer Edition: 97.0
    Safari: 14.1.2
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.67 => 1.0.0-next.68
    @sveltejs/adapter-static: ^1.0.0-next.18 => 1.0.0-next.28
    @sveltejs/kit: ^1.0.0-next.259 => 1.0.0-next.265
    svelte: ^3.46.2 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

This is quite severe, as redirecting is needed for most apps with auth.
A very ugly workaround for this is to check for res.redirected and manually redirect in case that were true.
```html
<script lang="ts" context="module">
	export async function load({ fetch }) {
		const res = await fetch('/endpoint.json');
		console.log(`Res status is: ${res.status}`);
		if (res.ok && !res.redirected) {
			return {
				props: { res }
			};
		}
		return {
			status: res.redirected ? 302 : res.status,
			redirect: res.status === 302 ? res.headers.get('location') : res.redirected ? '/login' : null
		}
	}
</script>
```

**Comment by babichjacob** [comment]
[I wrote on Discord](https://discord.com/channels/457912077277855764/940985543179776020/940985545054621746) that I don't think the redirect should be followed (nor that people should redirect to pages from API endpoints).

Imagine you were interacting with the endpoint (let's say it's `/login`) with an HTTP client like `curl`, perhaps if someone else was making use of your API:
```sh
$ curl http://localhost:3000/login --data '{"username": "j", "password": "acob"}' --verbose
...
> POST /login HTTP/1.1
...
< HTTP/1.1 307 Temporary Redirect
...
< location: /dashboard    # do I really want to go to a page? I'm in the terminal...
< set-cookie: jwt=some-token-stuff; Path=/; HttpOnly; Secure
...
```

and if the redirect were followed (for `curl` that's controlled by the `--location` flag, and [following redirects is the default behavior of JavaScript's `fetch`](https://developer.mozilla.org/en-US/docs/Web/API/fetch#parameters)), the response would have HTML for the `/dashboard` page!

It's my opinion that avoiding this design is probably the right idea.

My idea for an alternative is moving the redirect logic from the endpoint to the `load` function (or wherever the endpoint is `fetch`ed from), because going to another page is a feature of the frontend rather than the API. 

The original example is generic, so hopefully a real world situation is more simplistic:

```html
<script lang="ts" context="module">
	export async function load({ fetch }) {
		const res = await fetch('/endpoint.json');
		const data = await res.json();

		// displace the logic for these from the original src/routes/endpoint.json.js file
                // perhaps modify that endpoint's get request handler so that it returns useful data for the logic here 
		const status = ...;
                const location = ...;
                
                if (location) return { status, location };
                
                // if there was extra stuff returned from the endpoint per the above comments, feel free to pull them out here
                const props = data;
		
	        return { props };
	}
</script>
```


For the above,

> Returning a redirect from an endpoint works on the first load

*I* think it's a bug that it worked on the server rather than that it failed on the client.

**Comment by Theo-Steiner** [comment]
@babichjacob thank you for your detailed answer. I must have accidentally deleted the thread on discord, when trying to leave it, sorry for that!
What you're saying makes a lot of sense and I really should move this logic into the load function. I thought delegating the redirect to '/login' on being unauthorized a layer down could keep my load functions more DRY, but I understand that this shouldn't have worked in the first place!
I guess I'll close this issue, since this working on the server seems to be worth another issue on its own!

**Comment by newlegendmedia** [comment]
@Theo-Steiner I have the same issue trying to redirect from an endpoint after login. Did you try redirecting from the client yet? I tried it and the issue for me is that the getsession is not called when I redirect to the new page. I need it to be called like in normal navigation so I can return the session data to the new page.
