### ISSUE TITLE
officially support form validation on sveltekit endpoint

### ISSUE THREAD

**Issue by ramabie** [sveltejs/kit#3863]
### Describe the problem

I am a laravel framework user and after I found out about Sveltekit I was very amazed and amazed.
Some days I'm always looking for a way how Sveltekit implements validation on the endpoint side, but in my search I haven't found a validation form on the endpoint that is officially supported by Sveltekit, or indeed I don't know.
i am very new to sveltekit and i have very little knowledge about sveltekit.

### Describe the proposed solution

does the sveltekit endpoint have form validation?
like this guide deserves...

https://laravel.com/docs/9.x/validation

### Importance

would make my life easier

**Comment by UltraCakeBakery** [comment]
It does not. Svelte-kit is not a full blown application development framework. It lacks many features Laravel offers. You will have to implement validation yourself. I wouldn't even get started though since you can't get the validation errors back to your views in a proper way, and won't be able too any time soon.

**Comment by antony** [comment]
You might consider the approach I use here https://github.com/antony/hapda to provide a wrapper around endpoints which gives a full hapi server (with validation, body parsing, plugins, etc) which you can just wrap your endpoints with.

SvelteKit won't build something like this in, it's too opinionated and inflexible.
