### ISSUE TITLE
`getStores().page.subscribe()` VS `page.subscribe()` - what's the difference? [docs]

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#4078]
### Describe the problem

I don't know when to use `getStores().page.subscribe()` and when to use `page.subscribe()`.

I can't for the life of me understand when it is necessary to use `getStores()`, and what happens if I use for example `page.subscribe()` instead of `getStores().page.subscribe()`?

Can someone provide an example of when `page.subscribe()` goes wrong, and WHAT goes wrong?

The documentation says that using `getStores()` is "safely" - I have no idea what that means.
Documentation - https://kit.svelte.dev/docs/modules#$app-stores

### Describe the proposed solution

The documentation needs to specify what so in what exact situation using `page.subscribe()` causes problems.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
When you import `page`, you're not _actually_ importing the page store. That would be impossible, because the stores aren't free-floating objects, they're scoped to your app using Svelte [context](https://svelte.dev/tutorial/context-api) (if they weren't, on the server they would be shared by everyone who makes a request).

Instead, you're importing this: https://github.com/sveltejs/kit/blob/88ebc8e3033496cd842cf29fa127f5d7efc3d184/packages/kit/src/runtime/app/stores.js#L40-L47

`getStores` uses context to retrieve the actual app-scoped stores: https://github.com/sveltejs/kit/blob/88ebc8e3033496cd842cf29fa127f5d7efc3d184/packages/kit/src/runtime/app/stores.js#L17-L18

But you can only call `getContext` during a component's initialisation. Most of the time that's fine, because if you do something like this...

```svelte
<script>
  import { page } from '$app/stores';
</script>

<h1>{$page.url.pathname}</h1>
```

...Svelte is calling `page.subscribe` on your behalf (which in turn calls `getStores`, which in turn calls `getContext`) during init. But if you tried to subscribe _later_ for some contrived reason...

```svelte
<script>
  import { page } from '$app/stores';

  let pathname = 'untracked';

  function start_subscribing() {
    page.subscribe($page => {
      pathname = $page.url.pathname;
    });
  }
</script>
```

...then you'd be calling `getContext` outside component init, which would fail. If you instead use `getStores`...

```svelte
<script>
  import { getStores } from '$app/stores';

  const { page } = getStores();

  let pathname = 'untracked';

  function start_subscribing() {
    page.subscribe($page => {
      pathname = $page.url.pathname;
    });
  }
</script>
```

...you can subscribe safely.

**Comment by lukaszpolowczyk** [comment]
@Rich-Harris Thanks, I get it now.
