### ISSUE TITLE
Prerender during build rather than adapt

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4112]
### Describe the problem

Currently, prerendering happens inside adapters. This creates various minor problems:

* `svelte-kit preview` doesn't use prerendered pages — loss of fidelity, and slow performance that's unreflective of production build
* adapters have to be careful to prerender before generating manifests
* prerendering doesn't happen if you haven't configured an adapter, or you're doing `svelte-kit build` locally with `adapter-auto` (unless you prefix it like `VERCEL=1 npm run build`)

### Describe the proposed solution

I think prerendering should happen during build, _before_ the adapter runs. 

The fly in the ointment is `adapter-static`, which needs to specify that all pages should be prerendered (not just those explicitly marked as capable of being prerendered) unless a fallback is specified. A `config.kit.prerender.all` or `config.kit.prerender.default` option could stand in for that, and could also mean 'prerender everything without `export const prerender = false`. Together with a `builder.prerenderFallback` method, we could solve the `adapter-static` problem in a way that gives everyone a bit more flexibility. (Would probably need to make `adapter-static` aware of the `all`/`default` option via the builder so that it can instruct people to update their config accordingly.)

### Importance

nice to have

**Comment by benmccann** [comment]
Another thing that has been an issue is that the service workers are currently generated before prerendering and so they can't include prerendered content. We might be able to fix that as well if prerendering happened during build

**Comment by Rich-Harris** [comment]
Ah yeah, excellent point. That's a decisive advantage

**Comment by kdheepak** [comment]
(I'm going to tag on a couple more issues here as comments that I might might be related.)

Sometimes I get an error during `npm run build`. This doesn't happen all the time, but happens occasionally and the frequency of occurrence is higher when I delete the .svelte-kit folder and run `npm run build`. This error occurs when

- I have same .png content in multiple files that were linked as .png assets, _and_ 
- these assets are around 40kb linked from one of my routes, 

What I think is happening is that the "build" stage inlines it to a "data:..." image but the "adapt" stage doesn't know that (???), and `npm run build` fails. I'm using the static adapter. I haven't been able to consistently reproduce this which is why I haven't opened an issue for this.

**Comment by Rich-Harris** [comment]
Related: #3792, which would be fixed by `config.kit.prerender.default` (or `all`, or whatever it gets bikeshedded to)
