### ISSUE TITLE
CI on Windows sometimes timeout

### ISSUE THREAD

**Issue by baseballyama** [sveltejs/kit#4123]
### Describe the bug

For example, below both CI failed these tests on windows, but it succeeded on one side but failed on the other.

> 1) [dev+js] › test\test.js:242:2 › Scrolling › app-supplied scroll and focus work on direct page load 
> 2) [dev+js] › test\test.js:633:2 › Encoded paths › visits a route with non-ASCII character

[Fake Success]
https://github.com/sveltejs/kit/runs/5324276886?check_suite_focus=true

[Failed]
https://github.com/sveltejs/kit/runs/5325501189?check_suite_focus=true

As well as fixing these tests,
we need to fix it that CI should fail if CI fails in the middle of the process.

### Reproduction

N/A

### Logs

```shell
Please see CI logs.
```

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 76.88 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.nodenv/versions/17.4.0/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.1 - ~/.nodenv/versions/17.4.0/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.2
```

### Severity

annoyance

**Comment by rmunn** [comment]
https://github.com/sveltejs/kit/blob/master/packages/kit/test/utils.js#L154 sets `retries: 5` on CI, and if Playwright finds a test that fails on the first attempt but succeeds on a later attempt, it marks the test as "flaky", which is considered a success condition. The only time Playwright marks tests as "failed" is if they run out of retries and have failed every time.

In the two workflow runs you linked, I see the tests marked as "flaky" rather than "failed", meaning that they did pass at least once. So it looks to me like this is behaving as intended.

**Comment by baseballyama** [comment]
Ah, you are right.
But why always these specific tests are flaky...

Failed CI is failed because the below test is failed.

> 1) [build-js] › test\test.js:903:2 › Errors › error in shadow endpoint

**Comment by rmunn** [comment]
No, that's just the test that happened to be running when the workflow run was cancelled for going over the 15 minute timeout. If you look at the final entry in https://github.com/sveltejs/kit/runs/5325501189?check_suite_focus=true you'll see "Error: the operation was canceled", which is what happens when you hit Ctrl+C at the command line (or when you send the process-termination signal) to interrupt the test run. And if you look at the top of the workflow log, you'll see that it ran for 15 minutes and 7 seconds. [The workflow is set to timeout after 15 minutes](https://github.com/sveltejs/kit/blob/b7ebff7ecdac6b7e6901553ada453743b18d78e4/.github/workflows/ci.yml#L30), so that's why that particular run was canceled.

The simplest way to fix that issue will be to increase the workflow timeout to 20 minutes instead of 15. Looking through [several](https://github.com/sveltejs/kit/runs/5325965183?check_suite_focus=true) [successful](https://github.com/sveltejs/kit/runs/5329991569?check_suite_focus=true) [runs](https://github.com/sveltejs/kit/runs/5330268104?check_suite_focus=true) of the Windows workflow, it had times of 14:54, 13:52, and 12:27 respectively. The Ubuntu and MacOS runs took way less time. If the Windows workflow run is consistently in danger of hitting the 15-minute timeout, it's just going to hit that timeout more and more as more tests are added in the future. So these false-positive failures are likely to happen more and more in the future, and I think upping the timeout to 20 minutes instead of 15 will help solve the problem for a while.

**Comment by baseballyama** [comment]
@rmunn 

Thank you for PR!

I hope this will stabilize the tests for a while.
However, I was doing a little research to find a way to split the tests and run them in multiple machines, rather than extending the test timeout, considering that more and more tests will be added in the future.
I haven't come up with a good solution so far, but if I have any ideas at some point in the future, I'd be happy to share them.

I close this issue once the issue has been resolved for the time being.
If there are any remaining issues, please reopen it.

**Comment by rmunn** [comment]
> However, I was doing a little research to find a way to split the tests and run them in multiple machines, rather than extending the test timeout, considering that more and more tests will be added in the future. I haven't come up with a good solution so far, but if I have any ideas at some point in the future, I'd be happy to share them.

https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines looks like one way we could do it. Add `shard: [1, 2, 3]` to the `matrix` section of the `ci.yml` file, and have the tests run with `--shard=${{matrix.shard}}/3` on the command line. Just a quick, off-the-top-of-my-head idea, which maybe you've already looked at but maybe you hadn't seen that option yet so I thought I'd mention it.

**Comment by baseballyama** [comment]
Wao, Thank you! I didn't know that. This is a great feature.
(Firstly I googled why Windows CI is much slower than other OS, but it was maybe long way round😅)
I think we should use this feature but I would like to know your opinion @rmunn ?
