### ISSUE TITLE
adapter static+endpoint / adapter static + refresh page

### ISSUE THREAD

**Issue by dulyas** [sveltejs/kit#4142]
### Describe the bug

after last npm update after run build everythink is ok on npm run preview but if if deploy my site on hosting and refresh any not main page i got 403/404

also i need POST method on my form with endpoint and after run build on run preview its ok, but after deploy i got 404 on my index.json.js, index.js, api/, api/index.json etc have no idea what to do help pls 

### Reproduction

npm init svelte@next my-app // select test app
cd my-app
npm install
npm run dev -- --open
npm i @sveltejs/adapter-static
 change adapter on svelteconfig
npm run build
npm run preview - everythink is ok
deploy on host - cant refresh pages and not todo app

### System Info

```shell
any, any, any
```

### Severity

blocking all usage of SvelteKit

**Comment by chvanam** [comment]
`npm i -D @sveltejs/adapter-static@next` maybe to get the latest version of the static adapter ?

**Comment by Maxim-and-Ko** [comment]
![image](https://user-images.githubusercontent.com/67662289/157415249-114f9ff1-97ac-494b-87e4-3dfed80bf707.png)
the same problem. when the page is reloaded, it gives 404

**Comment by qbunt** [comment]
We're seeing this with the next-29 static adapter and `'@sveltejs/kit': 1.0.0-next.294_sass@1.49.9+svelte@3.46.4` deploying onto Cloudflare pages. `pnpm run preview` after build works absolutely fine, but when deployed to CF, we get consistent 404's. I don't see any root level index page inside the build folder when running builds locally.

**Comment by qbunt** [comment]
@Maxim-and-Ko, @dulyas current build locally outputs

```
> Using @sveltejs/adapter-static
  You should set `config.kit.prerender.default` to `true` if no fallback is specified
  Wrote site to "build"
```

adding `default: true` to the `svelte.config.js` file does fix this issue

```
kit: {
    // hydrate the <div id="svelte"> element in src/app.html
    adapter: adapter(),
    prerender: {
      crawl: true,
      enabled: true,
      onError: 'continue',
      default: true
    },
```

**Comment by benmccann** [comment]
You may want to try setting `trailingSlash: 'always'`

**Comment by qbunt** [comment]
@benmccann tried that first and had the same 404 result, did that change recently?

**Comment by Rich-Harris** [comment]
The `trailingSlash` thing was a separate change that happened a couple of weeks ago (prior to that, prerendering would always generate `page/index.html` files instead of `page.html` files, but that means that the majority of static hosts would redirect `/page` to `/page/`, so the new behaviour ensures that your URLs are consistent between dev and deploy).

@dulyas you can't use `adapter-static` if your endpoints have `post` handlers`. We probably need to make that clearer at build time via an error.

**Comment by Maxim-and-Ko** [comment]
> Вы можете попробовать установить`trailingSlash: 'always'`, если это то же [самое, что и #3852](https://github.com/sveltejs/kit/issues/3852)

okay, it worked. And what to do with [slug] pages? Now dynamic pages don't open 
![image](https://user-images.githubusercontent.com/67662289/157669250-d4e403c1-b9e3-415e-8f2c-d056056aa211.png)
![image](https://user-images.githubusercontent.com/67662289/157670492-be7a9363-8b24-46c3-97c3-3a661e3ffc1b.png)

**Comment by Maxim-and-Ko** [comment]
> You may want to try setting `trailingSlash: 'always'` in case this is the same as #3852

okay, it worked. And what to do with [slug] pages?
![image](https://user-images.githubusercontent.com/67662289/157671963-33a821b5-2b6c-4396-8073-f6d2e72fadcc.png)
![image](https://user-images.githubusercontent.com/67662289/157671965-56158937-56e1-4374-beb3-24816cd9a29d.png)

**Comment by Rich-Harris** [comment]
I don't know what it is you're facing @Maxim-and-Ko but you will need to open a separate issue _with a reproduction_ if you want to get help — please don't hijack other people's issues. I would assume that `/news/66` isn't being prerendered because the content isn't available at build time, in which case `adapter-static` is the wrong thing to use. If the content _is_ available at build time then you need to ensure that either a) the crawler can find a link to it, or b) you specify it in `config.kit.prerender.entries`.

**Comment by Rich-Harris** [comment]
Right, the behaviour changed. That's why you saw this message:

> You should set `config.kit.prerender.default` to `true` if no fallback is specified

**Comment by qbunt** [comment]
yeah I just tried again with a fresh app and see the messaging now. Thanks @Rich-Harris 👍
