### ISSUE TITLE
Template Unit Tests

### ISSUE THREAD

**Issue by vhscom** [sveltejs/kit#4143]
### Describe the problem

When scaffolding a new project I'd like a way to get started with Unit Testing using Vitest. This follows from the [recent introduction](https://github.com/sveltejs/kit/pull/4056) of a template option to add Playwright.

### Describe the proposed solution

Like with [Playright](https://github.com/sveltejs/kit/pull/4056), add an option to add Vitest for unit testing during project scaffolding.

### Alternatives considered

Following the README instructions for https://github.com/nickbreaton/vitest-svelte-kit during set-up.

### Importance

nice to have

### Additional Information

Leaning into Vitest as opposed to Jest will help code created with SvelteKit projects to be more streamlined given an integration with the Vite built pipeline and help eliminate years of potentially inapplicable search results for React- and Vue-based test configurations.

**Comment by rmunn** [comment]
I think writing an adder for https://github.com/svelte-add/svelte-add is the best way to solve the chicken-and-egg problem, or if not solve it completely at least get around the largest issue. Things shouldn't go into `create-svelte` until they're stable, but if there's an unofficial (or semi-official) adder package, people won't have the same expectation of stability. So any errors due to rapidly-moving targets won't reflect badly on Svelte-Kit for people trying it out for the first time. But at the same time, it could be mentioned in the documentation (in the FAQ section, perhaps) as a recommended way to set up unit testing that's simpler than using Jest.

**Comment by vhscom** [comment]
Closing due to low priority to reduce noise. Check out this Discord server for chat about configuring Vitest. 👍

**Comment by vhscom** [comment]
See also: https://github.com/nickbreaton/vitest-svelte-kit

**Comment by vhscom** [comment]
Superseded by https://github.com/sveltejs/kit/discussions/5285

**Comment by vhscom** [comment]
Further discussion and voting https://github.com/sveltejs/kit/discussions/5285
