### ISSUE TITLE
Switch to CircleCI?

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4201]
### Describe the problem

I'm finding GitHub Actions to be unbearably slow and unreliable.

### Describe the proposed solution

I don't know what the best alternative is, or if we can tune Actions so that it's a bit less rubbish, but someone probably does.

### Importance

would make my life easier

**Comment by baseballyama** [comment]
I agree with this but I have concern about cost.
CI has stabilized now with our efforts.
However, number of tests are more and more in the future, it is not good to have long CI times or unstable tests due to environment.
Therefore personally in terms productivity and quality, I prefer to use Circle CI.

However, AFAIK, the Windows environment can only be used for 750 minutes per month, even in OSS projects.
In the past month we have run 1,275 CIs, so even if a Windows CI takes 10 minutes to complete, we would still need 12,750 minutes.
This would require 285$ per month. Is this an acceptable cost?
Therefore in terms cost, I think we can postpone this consideration until CI has issue again.

https://circleci.com/pricing/
<img width="575" alt="image" src="https://user-images.githubusercontent.com/19153718/156888047-ec40028a-de3d-4a47-81d5-b5850047cab4.png">

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/19153718/156887874-bccd3442-082b-4174-8ddb-84c7449664fe.png">

I have no experience with Circle CI, but would be willing to help with the migration to Circle CI if you need.

**Comment by dominikg** [comment]
> I think Travis CI is good.
didn't particularly like the way they handled this incident
https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/

**Comment by Rich-Harris** [comment]
Yeah, Travis is an absolute non-starter — it was acquired by a private equity company that fired the bulk of the workforce with zero notice then screwed over its open source users. Will never consider using them.

We did some work to improve the state of our workflows and Github actions are a little better now, so I'll close this
