### ISSUE TITLE
Server-side fetch in endpoints should have headers

### ISSUE THREAD

**Issue by rgossiaux** [sveltejs/kit#4208]
### Describe the bug

This is basically the same issue as #696 but for endpoints instead of the load function: if your endpoint performs a `fetch`, it will not contain the headers from the user's original request. 

### Reproduction

https://github.com/rgossiaux/kit-endpoint-headers

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 2.94 GB / 64.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.8.0 - /var/folders/rn/2kdgb0jj25q2v656j3qc_ywr0000gn/T/fnm_multishells/764_1646342367055/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 7.21.0 - /var/folders/rn/2kdgb0jj25q2v656j3qc_ywr0000gn/T/fnm_multishells/764_1646342367055/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.30
    @sveltejs/kit: next => 1.0.0-next.291
    svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
If you want these, you should pass them along yourself. The global `fetch` that you call in an endpoint has no idea what request it's being called as part of - and it can't in a cross platform way, because of the async single-threaded nature of javascript.

This would only be possible if there were a wrapped `fetch` function as an argument to the endpoint handler, like what pages get, but this feels too niche for me. Fetches performed in endpoints are generally API calls, and it seems unlikely that these should include all of the headers from the underlying incoming request - unlike what happens in page `load`s, where we are trying to simulate what the browser's `fetch` does.
