### ISSUE TITLE
If you mutate the session store from __layout onMount, your route's afterNavigate no longer runs on mount like it should

### ISSUE THREAD

**Issue by johnnysprinkles** [sveltejs/kit#4209]
### Describe the bug

I was using `afterNavigate` to react to changed path parameters, but then it suddenly stopped working for me. Turns out it's related to my adding a `__layout.svelte` file, and one which does some client-side global initialization (according to #1538 this is the best place to do that kind of thing for now.)

My layout file's onMount looks something like this:

    onMount(async () => {
      let response = await fetch('/api/home/tracking/user')
      $session.user = await response.json()
    })

And for some reason, having that $session lvalue in there makes it so my afterNavigate doesn't run. If I take that line out it runs like it should.

### Reproduction

I can make a repro case if the description isn't enough.

### System Info

```shell
System:
    OS: macOS 11.6.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 598.38 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.17 - /opt/brew/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 94.0.1
    Safari: 15.2
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.29
    @sveltejs/adapter-static: ^1.0.0-next.24 => 1.0.0-next.28
    @sveltejs/kit: next => 1.0.0-next.287
    svelte: ^3.44.0 => 3.46.4
```

### Severity

serious, but I can work around it

### Additional Information

I'm able to workaround by not using the session store but instead making my own writable store.

**Comment by rmunn** [comment]
What happens if you replace `$session.user = whatever` with `session.update(data => { ...data, user: whatever })`? I.e., don't mutate the object in the store, but call the store's `update` function?

The reason I ask is because Svelte stores keep a reference to the old value, and when the store value changes, the old value is compared to the new value to see if subscribers need to fire their subscription functions. If you mutate the value in a store, then you're mutating the object that Svelte has kept a reference to. So the new value will always compare equal to the old value, because you've just changed the old value that Svelte kept. And therefore, store subscriptions won't fire and you're likely to get unexpected behavior.

Now, I haven't checked recently to see if the Svelte compiler will compile `$store.property = foo` into a call to `store.update(oldVal => { ...oldVal, property: foo })` or not. If the compiler makes that adjustment for you, then what I wrote above doesn't apply. But if you get different results from changing `$session.user = whatever` to a call to `session.update`, then the issue is probably that Svelte wasn't expecting the object in the `$session` store to be mutated, and the compiler didn't turn that line into correct code.

**Comment by johnnysprinkles** [comment]
So this is weird, I can no longer repro this morning. However, the original issue I had does repro, which seems to do more with asynchronousness. If I delay the construction of the main component, `afterNavigate` fails to run. Like if I have this in my `__layout.svelte`:

```svelte
<script>
  import { onMount } from 'svelte'
  import { session } from '$app/stores'

  let loading = true

  onMount(async () => {
    let response = await fetch('/api/home/tracking/user')
    $session.user = await response.json()
    loading = false
  })
</script>

{#if loading}
  <div>Loading...</div>
{:else}
  <slot></slot>
{/if}
```

and in my route component I have something like this which never prints:

```svelte
  afterNavigate(async ({from, to}) => {
    console.log('navigated!')
  })
```

**Comment by johnnysprinkles** [comment]
Since I can't reproduce the original issue now, I'll close this one. I might open a separate issue about `afterNavigate` not being called when the route component is constructed not in tandem with a navigation event.

**Comment by johnnysprinkles** [comment]
OK I see what's going on... `afterNavigate` has a couple of issues with the dev server. I'll open a separate bug.
