### ISSUE TITLE
TypeScript Error: No element indexed by 0

### ISSUE THREAD

**Issue by GrygrFlzr** [sveltejs/kit#424]
This is caused by Vite's source map handling on `.svelte` files that are not dynamic files.
As a temporary workaround, make sure to have `src/routes/$layout.svelte` with at least some "dynamic" content, e.g.
 ```html
<slot />
{''}
```

---

**Describe the bug**
As long as `svelte-preprocess` is used in `svelte.config.cjs`, attempting to run dev mode results in internal errors.

**Logs**
With TypeScript, the page is a plaintext error:
```
Error: No element indexed by 0
    at ArraySet_at [as at] (C:\Users\GrygrFlzr\Documents\projects\sk-36\node_modules\vite\dist\node\chunks\dep-1bdbec90.js:24278:9)
    at BasicSourceMapConsumer.<anonymous> (C:\Users\GrygrFlzr\Documents\projects\sk-36\node_modules\vite\dist\node\chunks\dep-1bdbec90.js:25193:67)
    at Array.map (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\GrygrFlzr\Documents\projects\sk-36\node_modules\vite\dist\node\chunks\dep-1bdbec90.js:25192:14)
    at merge (C:\Users\GrygrFlzr\Documents\projects\sk-36\node_modules\vite\dist\node\chunks\dep-1bdbec90.js:26656:18)
    at ssrTransform (C:\Users\GrygrFlzr\Documents\projects\sk-36\node_modules\vite\dist\node\chunks\dep-1bdbec90.js:61375:15)
    at transformRequest (C:\Users\GrygrFlzr\Documents\projects\sk-36\node_modules\vite\dist\node\chunks\dep-1bdbec90.js:61643:48)
    at async instantiateModule (C:\Users\GrygrFlzr\Documents\projects\sk-36\node_modules\vite\dist\node\chunks\dep-1bdbec90.js:67986:10)
```

**To Reproduce**
```bash
npm init svelte@next
# enable typescript
npm install
npm run dev
```

**Expected behavior**
No errors out of the box.

**Information about your SvelteKit Installation:**
```
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.36
    svelte: ^3.29.0 => 3.35.0
```

**Severity**
Unusable dev mode.

**Comment by dummdidumm** [comment]
I dug into this at well and I'm suspecting the Svelte compiler now and how it handles incoming `sourcemap`, or how that `sourcemap` is produced by Svelte's preprocessor.

I noticed that when you run a preprocessor before compiling
- the `js.map` is a class `SourceMap` instead of a JSON
- that class has empty `sources` and `sourcesContent` arrays, whereas without preprocessing they are set and filled

**Comment by dummdidumm** [comment]
After digging deeper. The problem is that inside the function [combine_sourcemaps](https://github.com/sveltejs/svelte/blob/master/src/compiler/utils/mapped_code.ts#L221) mappings go in, and then one mapping comes out without `sources` set. If I add this to the bottom
```ts
if (!map.sources.length) {
   map.sources = [filename];
}
```
It works. This could be a quick fix while we investigate why this even happens. Either the library which we use to combine source mappings is at fault, or we give it faulty input.

**Comment by GrygrFlzr** [comment]
Hm, should I update my Vite PR then? It was largely based on the existing `svelte` code for `combine_sourcemaps`.

**Comment by Conduitry** [comment]
I haven't been following this closely, but do we need that Vite PR at all if we change this on the Svelte side? Or do you think that's something their API should be able to handle anyway?

**Comment by dummdidumm** [comment]
Not sure. I think the PR over at Vite makes sense either way. To me it looks like the remapping library trips up when the first source map is empty. So if I want to merge this

```
[
  {
    version: 3,
    names: [],
    sources: [ 'C:/repos/svelte/kit-testsourcemaps/src/routes/$layout.svelte' ],
    sourcesContent: [ '' ],
    mappings: ';;;;;;;'
  },
  SourceMap {
    version: 3,
    mappings: '',
    names: [],
    sources: [ '$layout.svelte' ]
  }
]
```
It produces `{ version: 3, mappings: ';;;;;;;', names: [], sources: [] }` (note the empty sources array).

**Comment by benmccann** [comment]
I guess the question on the Svelte side would be whether Svelte should be returning empty source maps when there's no `script` tag. Should we have an issue in Svelte core for that?

**Comment by dummdidumm** [comment]
Postmortem analysis: I think the reason why both the change to Svelte core (adding sources) and the Vite PR solve this on their own is that
- if Vite used its old merge-sourcemaps it would work if Svelte core would set the `sources` array, avoiding the empty source map crash
- now that Vite is updated to use the new merge-sourcemaps, it can handle empty `sources`. 

Ultimately I does not matter what comes out in the end because those source maps are empty either way, so it was just a matter of preventing a crash along the way

**Comment by GrygrFlzr** [comment]
Yeah, I already figured that to fix the crash, all you'd need to do is fix it at one end. That's why later on I focused on "disappearing sourcemaps for non-dynamic files", which I guess should be a separate issue.
