### ISSUE TITLE
Require certain characters to be URL-encoded

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#4403]
### Describe the problem

With the addition of named layouts (#4388), the `@` symbol takes on a special meaning in route filenames, alongside `[`, `]` and `__`. If app authors wish to use these characters in their routes, they should URL-encode them.

We might need to add more such characters in future, and it would be nice if doing so wasn't a breaking change. For example, we haven't figured out how we're going to go about localising routes yet, but perhaps we'll decide we want to do this:

```
src/routes/translate(about).svelte
```

In order to reserve that possibility, we should insist that parentheses in route filenames are encoded:

```
src/routes/Street Spirit %28Fade Out%29
```

### Describe the proposed solution

a) figure out which characters we want to reserve, and reserve them
b) document it (we should do this regardless, for the characters already claimed)

### Importance

would make my life easier

**Comment by Conduitry** [comment]
Would the https://kit.svelte.dev/docs/configuration#routes callback be passed the not-yet-decoded path? I think this would make sense, because it would let users have a path segment that begins with `_` (or `.`) without needing to change their config and update a bunch of names throughout their app.

**Comment by Rich-Harris** [comment]
Yeah, it's passed the filepath rather than the route `id`, so even if the ID was decoded it wouldn't affect that part of the config

**Comment by rmunn** [comment]
Suggestion: to help people who don't have a URL-encoding reference cheat sheet pinned above their desk, perhaps a new CLI command could be added to help look up the URL-encoded version of a filename. E.g., `svelte-kit urlencode "Hello (Goodbye).svelte"` would print the string `Hello %28Goodbye%29.svelte` to stdout, which could then be copy-and-pasted into the VS Code "New file" option. Even for people who use URL-encoding all the time and have it memorized, such a command could be useful because it would only convert the characters that Svelte-Kit has reserved (in my example, the space character did not get converted to %20).

**Comment by mquandalle** [comment]
It might also be useful to reserve the “pipe” `|` in case something like that this prefered:

```
src/routes/about|i18n.svelte
```

**Comment by Conduitry** [comment]
That's a good thought, but `|` isn't allowed in Windows filesystems, so that wouldn't be possible as a special character anyway.

**Comment by benbender** [comment]
This issue is related: https://github.com/sveltejs/kit/issues/4629.

ATM it doesn't seem to be possible to use (at least) routes with an "@" in them (f.e. https://github.com/sveltejs/realworld is broken because of this with current sveltekit).

It works in dev with an encoded path like "/%40[user]" instead of "/@[user]", but breaks in prod because of the issue linked above. Unencoded urls with an "@" in them fail because of the special meaning in named routes.

**Comment by rdela** [comment]
see #5029 / #5056

**Comment by Rich-Harris** [comment]
I think we can close this post-#5748, since routing is now handled entirely by directories meaning that there's less likelihood of conflicts between filename punctuation and routes. I'm confident that we can implement whatever new features we'd want to (e.g. a localisation group) using `[]` and `()`, which would be non-breaking.
