### ISSUE TITLE
Redirect to base by default

### ISSUE THREAD

**Issue by ebeloded** [sveltejs/kit#4418]
### Describe the problem

When `kit.paths.base` is defined, by default the app opens to a "Not found" root route. The developer has to manually change the route to get to the desired location.

### Describe the proposed solution

It would be helpful if dev server redirected to base route by default.

### Alternatives considered

To solve the issue I created a vite plugin - [vite-plugin-redirect](https://github.com/ebeloded/vite-plugin-redirect), which works like this:
```js
import redirect from 'vite-plugin-redirect';

const base = '/admin';

/** @type {import('@sveltejs/kit').Config} */
const config = {
  kit: {
    paths: {
      base
    },
    vite: {
      plugins: [redirect({ '/': base })]
    }
  }
};
```

Unless there is a reason to not redirect to base, I think this functionality should be built-in.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
I think this is saying that http://localhost:3000/ should in dev mode should automatically redirect to http://localhost:3000/the/base/path

An alternative would be to make the `--open` option with `dev`/`preview` open up http://localhost:3000/the/base/path instead of http://localhost:3000/ like it does now.

The second one sounds like a good idea regardless. I don't have a strong opinion about the first one.

**Comment by ebeloded** [comment]
What I suggest is redirect from root to base (instead of showing "Not Found" error)
