### ISSUE TITLE
Infer parameter matcher from route parameters

### ISSUE THREAD

**Issue by accuser** [sveltejs/kit#4506]
### Describe the problem

Parameter matching is really useful, but could lead to increased / redundant complexity. For example, matching a UUID parameter is straightforward: `src/routes/post/[id=uuid]` whilst matching a `slug` parameter for a same-level route might be: `src/routes/post/[slug=slug]`. 

### Describe the proposed solution

If a parameter matcher could be inferred from the route parameter, this could lead to simpler routes. For example, the route `src/routes/post/[slug]` would use the `src/params/slug.js` (or `src/params/slug.ts`) matcher if it existed, inferring the route parameter matcher as being `slug`. It should still be possible to explicitly define the route parameter matcher to use.

### Importance

nice to have

**Comment by dummdidumm** [comment]
I don't think that we'd want to add this, because with a growing code base you could run into situations where you want to name something `slug` but don't have it related to the matcher. Matchers are (in my view at least) not that commonly needed, so in my opinion this should be opt-in (as it is currently), not opt-out.

**Comment by accuser** [comment]
Good point @dummdidumm. 

Personally, I didn't think I'd find matchers useful, but I have. I had a specific use case where I needed to make a request based on either the `id` or `email` and being able to separate the two routes simplified things. But beyond that, using a matcher to guard an endpoint and not make a metered API call is even better (yes, I did put this in shared module previously, but this feels tidier.)

**Comment by Rich-Harris** [comment]
The original plan was to do this, but it's a bad idea — aside from the case @dummdidumm brought up, it has several concrete downsides:

* when creating a new route with a dynamic parameter, you have to check that you're not using the name of a matcher you don't intend to use
* when creating a new matcher, you have to check that there aren't any routes that currently use it as the name of a dynamic parameter
* the same goes whenever you're renaming parameters or matchers
* there's no way for SvelteKit to distinguish between 'this route specifies a matcher that doesn't exist, throw an error' and 'this route doesn't specify a matcher' when the matcher is implicit
* the route compiler loses the ability (which we're not currently taking advantage of, but might in future) to detect if two routes conflict, at least without introducing constraints on the order in which things happen
* it's less explicit — someone learning the codebase must be aware of which matchers exist in order to parse the rest of the filesystem (and you have to keep that list in memory at all times)

I've often regretted APIs that attempted to save keystrokes; I've never regretted APIs that required explicitness!
