### ISSUE TITLE
Docs: "title and meta" entry in sidebar just says "and"

### ISSUE THREAD

**Issue by dimfeld** [sveltejs/kit#4575]
### Describe the bug

On the SvelteKit docs site, the left sidebar entry for "title and meta" just says "and". The anchor link is also incorrect: `#manual-setup-and` when it should be `#manual-setup-title-and-meta`

<img width="161" alt="image" src="https://user-images.githubusercontent.com/1369558/162501017-dcbd97e8-34fa-4edb-90ec-eaab11d4045f.png">

### Reproduction

Go to https://kit.svelte.dev/docs/seo#manual-setup-title-and-meta and scroll the left menu down to the SEO section.

### System Info

```shell
N/A
```

### Severity

annoyance

**Comment by saitheninja** [comment]
[The markdown file for the page.](https://github.com/sveltejs/kit/blob/master/documentation/docs/15-seo.md#title-and-meta)
Looks like the problem is the backticks in the heading.

The [Migrating from Sapper section](https://github.com/sveltejs/kit/blob/master/documentation/docs/80-migrating.md#a-attributes) uses angle brackets, so I'm going to go ahead and assume that's the fix, and open a PR.
