### ISSUE TITLE
Cannot run `npm ci --prod` with adapter-node

### ISSUE THREAD

**Issue by angryziber** [sveltejs/kit#4585]
### Describe the bug

adapter-node says that `npm ci --prod` should be used to run the build.
However, this command fails

### Reproduction

`npm ci --prod`

### Logs

```shell
> guidest@0.0.1 prepare
> svelte-kit sync

sh: svelte-kit: not found
npm ERR! code 127
npm ERR! path /app
npm ERR! command failed
npm ERR! command sh -c svelte-kit sync

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-10T11_03_37_215Z-debug.log
The command '/bin/sh -c npm ci --prod' returned a non-zero code: 127
```

### System Info

```
Docker image node:16-alpine
```

### Severity

serious, but I can work around it

### Additional Information

Workaround: `sed -i '/prepare/d' package.json && npm ci --prod`

**Comment by Conduitry** [comment]
I think making the `prepare` script in the template instead be `svelte-kit sync || echo` might work. It looks like the `||` syntax works in Windows cmd.exe as well, and `echo` should be (effectively) a no-op in Unix and Windows. If there's something more elegant than that, I'd love to hear about it. The first thing I tried was `true` and that unfortunately doesn't work in Windows.

**Comment by mrkishi** [comment]
Since we're mostly interested in the install behavior (since `build` implicitly runs `sync`), what about running `sync` from `@sveltejs/kit`'s `postinstall` instead?

ps. powershell's `echo` requires an argument, so it'd need to be at least `echo ''`.

**Comment by Conduitry** [comment]
I tried this from powershell and the script was still run with cmd.exe. I don't know whether there's some configuration that would have made that work differently.

Having it be in Kit's postinstall would be another option, and that would have been my fallback solution if I couldn't find a cross-platform thing to do in the prepare script, but I imagine it would be more moving pieces.

**Comment by mrkishi** [comment]
@Conduitry I don't know what the configuration or combination of shell and package manager is required to trigger it, but this is what I get on `pwsh` v7.2.2:

```
F:\projects\svelte\repros\my-app (succeeded in 8ms)
❯ pnpm install --prod --frozen-lockfile
Lockfile is up-to-date, resolution step is skipped
Already up-to-date

devDependencies: skipped

> my-app@0.0.1 prepare F:\projects\svelte\repros\my-app
> svelte-kit sync || echo

svelte-kit: The term 'svelte-kit' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

cmdlet Write-Output at command pipeline position 1
Supply values for the following parameters:
InputObject:
```

@dominikg `sync` is already run on `dev`/`build`/`package`. The reason for doing it on `prepare` was to get it to run right after installation so that you wouldn't get errors about the missing generated `tsconfig.json` until first build, so I don't think it'd be too bad for it to be skippable.

**Comment by mrkishi** [comment]
In theory `cwd` is at the root of the current project, so checking for `svelte.config.js` would indeed be a simple option... In practice, I'm seeing different behavior on `pnpm` (though perhaps because I was testing with a `.tar.gz` instead of a published package).

We do have access to `INIT_CWD` however, and that seems to behave consistently between the big three.

**Comment by johann-taberlet** [comment]
I'm hitting the same issue. Is there a solution to this ?

**Comment by dominikg** [comment]
As a workaround, remove the `prepare` script from `package.json`. This can lead to errors after updating sveltekit until after you executed `svelte-kit sync`. 

It is automatically called by `svelte-kit dev` and `svelte-kit build` so the worst thing that should happen are some red squigglies in your IDE

**Comment by benmccann** [comment]
Is `sync` automatically called by `build`? I didn't think it was...

**Comment by benmccann** [comment]
Vite tries to read the `tsconfig.json` upfront in order to bundle the config file. I looked at making Vite bundle the config file only if it's `.ts`, but it's not that simple because it uses the `esbuild` output to figure out what the config file dependencies are and I believe watch them to tell if the config file needs to be reloaded. So maybe easier to try to do something just on our side...

I was going to say I'm not sure how `postinstall` would help anything, but I guess it would because `@sveltejs/kit` wouldn't get installed with `npm ci --prod` since it's a `devDependency`. So yeah, that seems like the best solution to me

**Comment by dominikg** [comment]
The latest version of @sveltejs/kit now uses a post-install hook to run sync instead of prepare and `create-svelte` no longer adds a `prepare` script to new applications.

Please check it out and confirm that it fixes this issue you had

**Comment by Conduitry** [comment]
I'm going to go ahead and close this, because it looks good to me now. On a fresh template, `npm install && rm -rf node_modules && npm ci --prod` works fine. Same thing with the equivalent pnpm commands.
