### ISSUE TITLE
Better error handling for Cloudflare adapters

### ISSUE THREAD

**Issue by pzuraq** [sveltejs/kit#4635]
### Describe the problem

Currently there's a gap in error handling for the Cloudflare adapters, specifically the code for the adapter itself and the code for `server.respond` prior to any error handling is not covered. The adapters will return 500 error pages to users, but there's no way to hook in to run user error handling code (as far as I can see). This means we can't run code to _report_ the error to Sentry or other error tracking tools. 

### Describe the proposed solution

We're working on an internal fork of the adapter, and we added a `handleError` function which gets built into the adapter's output:

```ts
import { Server } from 'SERVER';
import { manifest, prerendered } from 'MANIFEST';
import { handleError } from 'HANDLE_ERROR';

const server = new Server(manifest);

const worker = {
  async fetch(req, res, env, context) {
    try {
      // ...
    } catch (e) {
      return handleError(e, req, res, env, context);
    }
  },
};
```

Users can provide a path to the adapter, and that file gets built with `esbuild` and then build into the worker:

```ts
adapter: adapter({
  handleErrorPath: './lib/handle-error.ts'
});
```

This has been working pretty well for us so far, but does feel a bit jank in some ways - we need to duplicate the error handling code between this and `hooks` for instance.

### Alternatives considered

Design-wise we're very open to alternatives here, the main thing is being able to integrate [Toucan.js](https://github.com/robertcepa/toucan-js) to catch all possible SSR errors.

### Importance

i cannot use SvelteKit without it

**Comment by Rich-Harris** [comment]
Sentry logging feels like something that belongs in `src/hooks.js` — why does this need to be in the adapter?

**Comment by pzuraq** [comment]
As mentioned above, that leaves a pretty significant gap in reporting. What if an error happens before hooks are executed? In the adapter code? We’d prefer to be safer here than have an error go undetected.

**Comment by pzuraq** [comment]
We also have sentry reporting in hooks, fwiw, with more detail provided in general. Our handling for the rest of the adapter is just-in-case, to make sure that any errors not handled by SvelteKit are caught and reported as well

**Comment by Rich-Harris** [comment]
My take on this is that error reporting tools like Sentry should only be used to capture errors in the app itself. It shouldn't be _possible_ for an error to occur in the adapter code or during app startup; the framework and the adapter should ensure that. Adding a mechanism to report errors outside requests _should_ be as nonsensical as this:

```js
function add(a, b, options) {
  let sum;

  try {
    sum = a + b;
  } catch (e) {
    options.handleError(e);
  }

  return sum;
}
```

In fact I think the try-catch in the current adapter-cloudflare is very unhelpful and we should get rid of it — silently returning a plain 500 rather than letting the platform handle it makes no sense.

Of course, bugs happen, so the instinct to wrap everything in try-catch is reasonable. But what if the code in `lib/handle-error.ts` contains bugs? It feels like we're doing things on a 'best effort' basis rather than having clearly defined boundaries.

I'd argue that this is where platform logging comes in. If an unexpected error happens in your app, `handleError` intercepts it and report it. But if an unexpected error happens _outside_ your app, and therefore outside your control, that's something that belongs in platform logs. The big flaw in my argument of course is that Cloudflare Pages [doesn't yet have logging](https://community.cloudflare.com/t/how-to-view-logs-from-cloudflare-pages-functions/343892) as far as I can tell, which seems like quite a significant omission. Still, I would claim that lobbying for that (while ensuring that the framework and adapter can't throw errors) is better than adding new API (which would come with its own set of gotchas, like making sure that `lib/handle-error.ts` doesn't accidentally use Vite features even though it happens to be in a directory of files that get processed by Vite).

**Comment by pzuraq** [comment]
That does seem reasonable, and given the adapter code is relatively simple we're ok with continuing to maintain our own adapter until Cloudflare Pages adds more universal error handling. Until then, we do want to have this fallback, if only so we can catch adapter-level bugs early and help to fix them upstream, since I agree in theory that they shouldn't really exist.
