### ISSUE TITLE
Cookie Management API

### ISSUE THREAD

**Issue by HibiscusCoffee** [sveltejs/kit#4765]
### Describe the problem

Astro opened an RFC to introduce the new Cookie Store API to simplify setting, parsing and deleting cookies in routes: https://github.com/withastro/rfcs/discussions/182
I think it’s actually a good idea. Maybe we can implement this in Svelte Kit’s endpoints too.

### Describe the proposed solution

The Cookie Store API has the advantage that it’s now the new standard API to work with cookies in the browser and that it works similar to the APIs used to get and set headers, which Svelte Kit is already using.

### Alternatives considered

Don’t change anything and just let users set, parse and delete cookies by manually setting and reading headers, which is quite cumbersome.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
I do like the idea of having a simple way to parse and serialize cookies built in (mainly so that it can be documented and people don't have to know about packages like `cookie` and `cookie-signature`, etc), but I don't love this API if I'm honest. It's deeply weird that `await cookieStore.get(...)` reads from the request but `await cookieStore.set(...)` writes to the response, and it would be a major conceptual break to have a way of manipulating the return value from an endpoint outside of the `return` itself.

Also, someone who wasn't familiar with the browser API would rightly wonder why these methods were async, when every other map-like interface is synchronous.

**Comment by Mlocik97** [comment]
we can maybe expose cookie same way as fetch?

**Comment by Rich-Harris** [comment]
> we can maybe expose cookie same way as fetch?

What does this mean — making it global? We're not going to do that — `fetch` is global because it's a _standard_ that's available in modern runtimes. And there's not much to be gained by adding it to `event` when it could just be imported as a normal module.

**Comment by Mlocik97** [comment]
ok, so it will be importable from kit? like:

```js
import cookie from '$app/utils'
```

for example, and kit will include it, so we don't need install it?

**Comment by Rich-Harris** [comment]
I was thinking along those lines, yeah. Perhaps something like

```js
import { read, write, sign, unsign } from '@sveltejs/kit/cookie';
```

**Comment by matthewp** [comment]
We went against using this Cookie Store API in Astro for similar reasons.

**Comment by HibiscusCoffee** [comment]
Since Svelte Kit now has a [cookie API](https://kit.svelte.dev/docs/types#sveltejs-kit-cookies) this issue can probably be closed?
