### ISSUE TITLE
Please, add support for `Fastify` server

### ISSUE THREAD

**Issue by Mr-M1M3** [sveltejs/kit#4770]
### Describe the problem

Hello, as far as I know svelte provides functions to work with node http libraries such as `express`, `polka`, `connect` but it does not provide any functions to work with `fastify` server. I think, adding support for `fastify` server will be on of the best features of sveltekit. 

### Describe the proposed solution

exporting simple function to use as `fastify plugin`

### Importance

nice to have

**Comment by Mlocik97** [comment]
adapter-node expose middleware, it's usable with any server that supports middlewares, fastify supports them (with https://github.com/fastify/fastify-express ), so it's already supposed.

**Comment by Rich-Harris** [comment]
This would be the responsibility of a Fastify adapter, rather than SvelteKit itself, and anyone is welcome to create one. Bear in mind though that `adapter-node` exposes middleware that can be used directly with Node's built-in `http` module — there's no performance advantage to be gained from using Fastify instead of creating a [custom server](https://github.com/sveltejs/kit/tree/master/packages/adapter-node#custom-server), so the only reason to do this would be to use Fastify middlewares in production (they wouldn't apply during development).

**Comment by woss** [comment]
unfortunately the node adapter doesn't work with fastify
