### ISSUE TITLE
next.326's production builds broken / won't build

### ISSUE THREAD

**Issue by lkj4** [sveltejs/kit#4827]
### Describe the bug

`pnpm run build` does not just build a production build but does also execute the build's server code since recently (I tried `next.324` and `next.326`, this didn't happen with `next.269`).

E.g. , it wants to connect to the database which is of course not running because I am just doing a production build and not executing a dev or preview environment (where a database would be running).

> make sure you have the latest versions of the packages you're using, including adapters.

Yes for both sveltekit and the node adapter

### Reproduction

clone https://github.com/lkj4/sveltekit-build-problem and run `pnpm run build`

`hooks.js` contains the connection to the database and some `console.log` printing _Why am I running?_ showing the execution of that code

### Logs

After half a minute or longer running `pnpm run build`, you get: 

```shell
MongoServerSelectionError: getaddrinfo EAI_AGAIN db_volume
    at Timeout._onTimeout (/home/.../sveltekit-build-problem/node_modules/.pnpm/mongodb@4.5.0/node_modules/mongodb/lib/sdam/topology.js:318:38)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)

> 500 /
    at file:///home/.../sveltekit-build-problem/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.326_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/index2.js:984:11
    at save (file:///home/.../sveltekit-build-problem/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.326_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1204:4)
    at visit (file:///home/.../sveltekit-build-problem/node_modules/.pnpm/@sveltejs+kit@1.0.0-next.326_svelte@3.48.0/node_modules/@sveltejs/kit/dist/chunks/index2.js:1095:3)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)                                                                                               
```

### System Info

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (2) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 610.16 MB / 3.75 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.6.2 - ~/.nvm/versions/node/v16.6.2/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v16.6.2/bin/npm
  npmPackages:
    @sveltejs/adapter-node: 1.0.0-next.73 => 1.0.0-next.73
    @sveltejs/kit: 1.0.0-next.326 => 1.0.0-next.326
    svelte: ^3.48.0 => 3.48.0
```

### Severity

blocking all usage of SvelteKit

### Additional Information

In my local app, this doesn't happen with `next.269`

**Comment by tcc-sejohnson** [comment]
I'm pretty sure this is intended behavior. I downgraded to `@sveltejs/kit: 1.0.0-next.300` just to make sure this wasn't recently-introduced behavior (as I seemed to remember this happening to me in the early 200s).

When building your app, SvelteKit crawls your entire site looking for pages to prerender. (Imagine that SvelteKit is a monkey that starts at `/` and clicks every link to every other page in your site until it's out of links to click.) You can mark pages for prerendering by doing the following:

```ts
<script context="module">
  export const prerender = true;
</script>
```

Alternatively, if your site is entirely static (or mostly static), you can set prerendering as the default by setting `kit.prerender.default = true` in your `svelte.config.js`, then opt pages _out_ of prerendering by `export const prerender = false`.

Regardless, under _either_ of those circumstances, SvelteKit still has to crawl your entire app to try to find pages with `export const prerender = true|false` -- if prerendering is the default, it has to because it has to look for pages opting out of prerendering. If prerendering isn't the default, it has to look for pages opting _into_ prerendering. This is why you're seeing `handle` run -- because in the process of crawling the site, the crawler is making requests, which have to go through `handle`.

You have two options here -- if you know for sure you're not going to prerender _any_ pages, you can set `kit.prerender.enabled = false`. This will cause Kit to skip the crawling phase altogether. Otherwise, you can `import { prerendering } from '$app/env'` and wrap calls to things you don't need for prerendering (like your database) in `if (!prerendering)` to only run them when not prerendering.

**Comment by lkj4** [comment]
Ok, thanks for your helpful answer. 🙂 This makes totally sense, I somehow forgot about the prerendering nature of SvelteKit. Out of curiosity, why did it work before?

**Comment by tcc-sejohnson** [comment]
Honestly, I have no idea why it worked before -- release 269 was quite some time ago! 😆 You'd have to get a comment from a maintainer who could remember what was going on around that time. My best guess would be that prerendering was disabled by default until a certain point, at which point it became enabled by default?
