### ISSUE TITLE
 `adapter-node`: Adding files in the `static` folder result in a 404

### ISSUE THREAD

**Issue by BlueFrog130** [sveltejs/kit#4832]
### Describe the bug

When building a system to upload files to the `/static` folder, I noticed that uploading and viewing images dynamically placed there works fine in development, but fails after building and running via `node index.js`.

### [Reproduction Repo](https://github.com/BlueFrog130/file-upload-bug)

Steps
---

1. Start server in production
```bash
npm run build && cd build && node index.js
```
2. Upload a file
![](https://github.com/BlueFrog130/file-upload-bug/raw/main/.github/choose.png)
4. Navigate to the file
![](https://github.com/BlueFrog130/file-upload-bug/raw/main/.github/submitted.png)

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 17.41 GB / 31.94 GB
  Binaries:
    Node: 17.2.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (101.0.1210.32)
    Internet Explorer: 11.0.19041.1566
```

### Severity

annoyance

**Comment by Conduitry** [comment]
You really shouldn't be uploading files to `/static`. They should go elsewhere.

We're using [sirv](https://www.npmjs.com/package/sirv) to serve static assets, and it traverses the filesystem once on startup and then caches that in memory so it doesn't need to traverse the filesystem on each request. Keeping that optimization in place is much more important than allowing for the use case of files in `static` that change.

You're free to fork the Node adapter and update the `sirv` call [here](https://github.com/sveltejs/kit/blob/master/packages/adapter-node/src/handler.js) to pass the `dev` option so that new files are picked up, but I would strongly advise to find a different solution.

**Comment by BlueFrog130** [comment]
Makes sense why that would be the case.

Able to use a custom express server to override the default behavior

```js
import { handler } from './build/handler.js';
import express from 'express';

const app = express();

app.use(express.static('static'));
app.use(handler);

app.listen(3000, () => {
	console.log('http://0.0.0.0:3000');
});
```
