### ISSUE TITLE
Need route for 'index.html' in the root directory regarding to 'adapter-static'

### ISSUE THREAD

**Issue by urbainy** [sveltejs/kit#4849]
### Describe the problem

I am using SK's version `1.0.0-next.321`.
In `svelte.config.js`, I made the following configuration: 
```
const config = {
	kit: {
		adapter: adapter({fallback: 'index.html'}),
                prerender: { default: true },
                trailingSlash: 'always',
	}
};
```
In `src/routes` directory, I created `index.svelte`, `about.svelte` and `__error.svelte` file.
And now I can get correct page render if I input `localhost:3000/about/index.html` in the browser. I mean `about` page is correctly displayed as expect.

BUT I get `404: Not found: /index.html` if I input `localhost:3000/index.html` in the browser. If we check the `build` directory, it is there for sure.

So I guess SK didn't consider to give the `index.html` in the root directory a route. If this is the fact, I wish the feature could be complemented in the future.

### Describe the proposed solution

I am newbie, I have no solution. Just wish the patch to my feature be not too complex;)

### Importance

nice to have

**Comment by urbainy** [comment]
I just try to change the configuration from `{fallback: 'index.html'}` to {fallback: '200.html'}, I found the issue is solved.
I am so sorry!

**Comment by urbainy** [comment]
Oh, no, the previous method didn't solve my issue, if I do that, no `error` page could be displayed, all requests will be redirect to `index.html` even there is an error.

**Comment by mrkishi** [comment]
What errors? 404s? You need to serve the fallback html on 404s or errors and the respective htmls files when they exist.

**Comment by urbainy** [comment]
Yes, on 404 error (I intentionally input the absent path to do the test), the browser didn't display the content of `__error.svelte`, but redirected to `index.svelte`. Maybe we could omit my wrong solution regarding to using `{fallback: '200.html'}`. Just go back to my initial request description. Currently I cannot access the home page by `http://localhost:3000/index.html`. I can only access the home page by `http://localhost:3000/`. I think this is a inconsistency. So I come here to find a solution or issue a feature request. Thanks!

**Comment by mrkishi** [comment]
If you have `fallback: 'index.html'` configured, that will clash with your _actual_ `routes/index.svelte` route since they'd both be rendered into `index.html`. You should name your fallback differently and configure your server/platform to serve it for all requests that don't have a matching html file.

Whether you can access your index page via `domain/` or `domain/index.html` is out of `adapter-static`'s power, though: your platform's configuration defines how it looks for and serves html files.

I don't see an immediate issue with SvelteKit here, so a discussion on [Github Discussions](https://github.com/sveltejs/kit/discussions), [Discord](https://svelte.dev/chat), or [Stack Overflow](https://stackoverflow.com/questions/tagged/sveltekit) would be more appropriate.
