### ISSUE TITLE
Create blank layout on sub-page not working

### ISSUE THREAD

**Issue by bluepuma77** [sveltejs/kit#5053]
### Describe the bug

I have a plain sub-page with zero layout for print purposes. Now I upgraded to the latest SvelteKit version and followed the [SvelteKit named layouts](https://kit.svelte.dev/docs/layouts#named-layouts) documentation, but I am not able to remove the root layout.

I tried 

- empty (`<slot />` only) `__layout-test.svelte` and `index@test.svelte`
- empty (`<slot />` only)  `__layout.svelte`
- empty (`<slot />` only)  `__layout@root.svelte`

<img width="668" alt="SvelteKit-named-layouts" src="https://user-images.githubusercontent.com/5221187/170012716-b3441e1a-5362-41fa-a085-6155278845de.png">

Maybe the documentation is not quit clear on how to just get a blank layout.

### Reproduction

Create [SvelteKit demo app](https://kit.svelte.dev/docs/introduction#getting-started) and try to reset /todos/index.svelte page to blank layout.

### System Info

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 92.53 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /opt/homebrew/opt/node@16/bin/node
    npm: 8.5.5 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 99.0.1
    Safari: 15.3
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.45
    @sveltejs/kit: next => 1.0.0-next.341
    svelte: ^3.46.0 => 3.48.0
```

### Severity

blocking an upgrade

**Comment by mrkishi** [comment]
This is working as intended: layouts inherit the parent folder's default layout if present.

In your example, move your layout resets from `src/routes/todos/__layout-test.svelte` into `src/routes/__layout-test.svelte`.

**Comment by bluepuma77** [comment]
@mrkishi Thanks for your response!

This somehow feels strange to me. So far I could have an independent "module" in a `routes` sub-folder, but for a layout reset I need to create a file in the parent folder? 

Are there plans to enable this within a sub-folder, enable a `__layout-root.svelte` within the "module" folder itself?

**Comment by mrkishi** [comment]
Layouts have always extended parent layouts, except for `__layout.reset.svelte`. But that old reset style can be replicated nearly identically with named layouts, you just have more control over it.

What you may be missing is the fact that named layouts in the root folder may be reused anywhere in the app. Taking that into account, you can recreate the old layout resets like so:

```sh
src/
└── routes/
    ├── __layout.svelte
    ├── __layout-reset.svelte        # an empty layout <slot/>
    ├── foo/
    │   ├── __layout.svelte
    │   └── {a,b,c}.svelte
    └── bar/
        ├── __layout@reset.svelte    # equivalent to the old __layout.reset.svelte
        └── {a,b,c}.svelte
```

Note that `foo`'s layout extends the root's main layout, while `bar`'s layout extends the empty `reset` layout. Each subfolder layout is still "self-contained," apart from being wrapped by their chosen parent.

**Comment by cerebrl** [comment]
I have a reproduction of a weird issue related to this topic. If you go to the StackBlitz repro listed bellow, and, once the application bootstraps, you append `/todos` in the embedded browser you should see the issue. Being that the `__layout@reset.svelte` file in the `/todos` directory uses the `__layout-reset.svelte` in the parent directory, I would think the todos page would be entirely unstyled, since that layout reset is just `<slot />`.

Repro: https://stackblitz.com/edit/sveltejs-kit-template-default-cxus9w?file=src/routes/todos/__layout@reset.svelte

You can see that the layout reset stripped away all of the components from the default layout, but that `import '../app.css';` is hanging around. Is my assumption that _everything_ the default layout imports should not be present when resetting the layout as demonstrated in the StackBlitz app incorrect?
