### ISSUE TITLE
allow async function for prerender.entries

### ISSUE THREAD

**Issue by rburgst** [sveltejs/kit#5107]
### Describe the problem

I would like to pre-render all pages within my database (e.g. a blog). I would like to avoid having to create index pages that list all available slugs. 
Think of it as creating something like bit.ly where users already know the url they want to load.

Right now it does not seem to be possible to provide an async function to come up with the urls to pre-render.

#1533 does not really cover this.

### Describe the proposed solution

it would be cool to be able to provide an async function that returns all URLs to pre-render.

### Alternatives considered

generating a static file beforehand and importing it into `svelte.config.js` would probably work but would make the solution a lot more complex.

### Importance

would make my life easier

**Comment by tcc-sejohnson** [comment]
@rburgst 

I agree there might be some degree to which Kit can make specifying dynamic (and unknown) routes at runtime easier, perhaps through a method like this. In order to unblock you now, though, here's a repo showing you how you can dynamically prerender any number of routes: https://github.com/tcc-sejohnson/prerender-all-blog-posts

The only semi-hack in this is that there has to be _some_ list, somewhere, of `<a>` tags that point toward every blog post (because that's how Kit crawls your site). In this case, we declare two routes:

```
/blog
/blog/[...route]
```

When we visit `blog`, its page endpoint sends a list of every post's route. `blog` then generates a list of anchor elements, one per blog post. Notably, `blog` itself wraps these `<a>` elements in `if prerendering`, so they won't be displayed when running in prod. (If you _wanted_ to display them as an index page, you could just remove the `if prerendering` tag and the `visibility: hidden` CSS attribute.) Since we now have an `<a>` tag for every post, the crawler will follow and prerender every one of those. As long as your `/blog/[...route]` endpoint is set up to use the spread-parameter-route to fetch the blog content and render it into the generic `/blog/[...route]` Svelte file, you're good to go -- all of your blog posts have been prerendered. :)

**Comment by babichjacob** [comment]
You don't need to provide an async function to `prerender.entries` because the `svelte.config.js` file is a module, so you can use top level await:

```js
// svelte.config.js
const getEntries = () => new Promise((resolve, reject) => resolve(["*", "/", "/user/123", ...]));
// consider checking if dev mode to avoid this computation / io 
const entries = await getEntries();

const config = {
  kit: {
    prerender: {
      entries,
    }
  }
}

export default config;
```

**Comment by rburgst** [comment]
@babichjacob you care correct that works. I initially tried it but got some error and apparently did not read the error message close enough.
