### ISSUE TITLE
New pages redirect to index or throw a 500 error

### ISSUE THREAD

**Issue by esfox** [sveltejs/kit#5142]
### Describe the bug

When creating a fresh new SvelteKit project, creating a new page under `routes` and visiting that page's URL seems to redirect to the index page (`index.svelte`).
Also...
- when creating another new page and linking to that page's URL...
or
- visiting the index page after creating new pages...

...throws the following error:
```
500
components[nodes[i]] is not a function
TypeError: components[nodes[i]] is not a function
```

Although, restarting the dev server seems to fix the issue.
Experienced this on version `1.0.0-next.347`, but it seems that it also occurs from `next.345` since downgrading to `next.344` seems to make the issue not occur.

Also, creating a new page while the dev server isn't running seems to also resolve the issue.

### Reproduction

1. `npm init svelte app-name`
2. `cd app-name && npm i`
3. `npm run dev`
4. Create a new page under `routes`, say `about.svelte` then save the file.
5. Visit `/about` in a browser.
6. Create another new page, say `asdf.svelte`
7. Visit `/asdf`
8. Visit `/`

### System Info

```shell
System:
  OS: Linux 5.6 Ubuntu 20.04.4 LTS (Focal Fossa)
  CPU: (4) x64 AMD Ryzen 3 2200G with Radeon Vega Graphics
  Memory: 768.98 MB / 13.68 GB
  Container: Yes
  Shell: 5.0.17 - /bin/bash
Binaries:
  Node: 16.13.1 - /run/user/1000/fnm_multishells/66257_1654141561309/bin/node
  Yarn: 1.22.17 - /run/user/1000/fnm_multishells/66257_1654141561309/bin/yarn
  npm: 8.1.2 - /run/user/1000/fnm_multishells/66257_1654141561309/bin/npm
Browsers:
  Firefox: 100.0.2
npmPackages:
  @sveltejs/adapter-auto: next => 1.0.0-next.50 
  @sveltejs/kit: 1.0.0-next.344 => 1.0.0-next.344 
  svelte: ^3.44.0 => 3.48.0
```

### Severity

annoyance

### Additional Information

Here's a screen recording to help describe what's happening.

https://user-images.githubusercontent.com/18418806/171550032-ff7a8bae-2514-4922-b4ca-fcd7ad3a384a.mp4

Also upon checking Kit's source code, it seems that these lines might be relevant to the issue, since checking the diff in the latest commit in the tag of version `next.345`, a modification was done in these lines.
`packages/kit/src/runtime/client/client.js`
![image](https://user-images.githubusercontent.com/18418806/171549689-d89a65b5-1b28-4f9c-b36f-3e7decb73705.png)

**Comment by gtm-nayan** [comment]
Looks like the underlying issue was present before as well but only became apparent after #4891.

The browser is getting the older version of `client-manifest.js` whose components array doesn't contain the new route. Creating an `about` route on a blank project makes it so that when it's getting hydrated it loads the page for the index page, because it's index is pointing to the wrong place which explains the supposed `redirect`.

When you navigate back to index, there you get an out of bounds index causing `components[nodes[i]]` to be undefined.

The updated client-manifest.js is correctly written but the dev server seems to be serving the old one regardless. 

I also tried by switching browsers (Brave -> Chrome if relevant) after creating the route and still got the same result so some server caching issue perhaps?

**Comment by benmccann** [comment]
From @gtm-nayan:

It seems like this may be a regression from https://github.com/sveltejs/kit/pull/4997:

> The negation doesn't seem to be working because it's performing a logical or on the array elements so it's ignoring everything
pre 4997 it logged an hmr update for client-manifest, which it doesn't afterwards
but sadly can't find a glob syntax to make it work

**Comment by nimatrengo** [comment]
I was not able to reproduce it
FYI, I am using Macbook and "NPM" instead of "PNPM". 

https://user-images.githubusercontent.com/88784130/174613170-d3903f12-9b64-49a5-8813-60d43b4e899b.mov
