### ISSUE TITLE
FOUC during SSR in production builds

### ISSUE THREAD

**Issue by oskarious** [sveltejs/kit#5194]
### Describe the bug

I am running into an issue where during SSR in production builds some css doesn't get applied on the server. Any styles that are not inline or defined with <style> tags in the svelte components are affected. i.e. the following pattern:

```
src/app.css

.some-class {
   background-color: red;
}
```
And then imported like:
```
src/__layout.svelte
<script>
  import "../app.css"; <--- Doesn't work
</script>

<p class="some-class">Some text</p> <--- Will be unstyled on SSR, but look correct during CSR (and when running the dev server)

<slot />

<style global>
  @import '../app.css'; <--- Doesn't work either
</style>
```

What trips me up about it is that when running dev, the inital SSR response from the server has the styles applied as expected, but when building the project and then serving it either via preview or something like `node index.js`, the server response will not have any css applied. I have had a look at other issues related to styles and fouc, but they seem to be almost exclusively the inverse of what I am seeing, i.e. fouc on the dev server and then works as expected on production builds.

Some images illustrating the problems

During CSR
![bild](https://user-images.githubusercontent.com/16356364/173129493-34491ac7-b289-441b-ac1f-874be9499b71.png)
SSRd response
![bild](https://user-images.githubusercontent.com/16356364/173129540-d68e0c47-e041-4a3a-8340-0166dc61ec4f.png)
SSRd response with dev server
![bild](https://user-images.githubusercontent.com/16356364/173129693-ed460462-5f19-4928-bd40-8495adecefb2.png)

### Reproduction

https://github.com/oskarious/svelte-ssr-css-issue

* Run the project with `yarn dev` and observe styling looking as expected.
* Run the project with `yarn build && yarn preview` and observe SSR styling being incorrect in the response in the console while CSR looks correct.

### System Info

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
    Memory: 9.77 GB / 31.93 GB
  Binaries:
    Node: 16.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.15.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.33)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.50
    @sveltejs/kit: next => 1.0.0-next.350
    svelte: ^3.44.0 => 3.48.0
```

### Severity

serious, but I can work around it

### Additional Information

I am fairly new to sveltekit, so it is of course entirely possible I am doing something wrong, but the pattern of importing a stylesheet in a __layout component is what for example https://github.com/svelte-add/tailwindcss creates, so I suspect it is the recommended approach to add global styles.

**Comment by tcc-sejohnson** [comment]
Strange, I am _not_ receiving the behavior you describe... I cloned your repo and ran `yarn`, then `yarn dev` -- all looks good. Then ran `yarn build && yarn preview` -- same exact page when hard reloading. Even tried closing the browser.

Have you tried deleting your `.svelte-kit` and `node_modules` directories and re-running `yarn install`?

**Comment by d3rpp** [comment]
I also attempted to reproduce this out of curiosity and had no luck (fresh install of the provided repo).

I tested this on macOS (2019 Intel MBP) and Windows 11 (Dell XPS) so I have my doubts it could be an issue with Win10. 

Maybe it is a case of clearing out your `.svelte-kit` and `node_modules` folder as @tcc-sejohnson recommended.

**Comment by oskarious** [comment]
I tried it on my windows 11 laptop now, since you mentioned not getting it, and I am running into the behaviour I originally described. And just for my own sanity, you are looking at the response from the html file request in the console, right?

**Comment by d3rpp** [comment]
The network tab only displays inline styles. As such the ones with inline styles will look correct. Im writing this on brave on a mac, which apparently just doesn't do that either, oh WebKit 

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/45675641/173180567-aafcf66a-461e-4132-a756-96d1a7aca928.png">

the reason that the "This should be styled but it's not" is only appearing unstyled is because the stylesheet that applies the styles to that class has not yet loaded (nor has anything else for that matter) but the inline styles are applied immediately because the browser has that kind of information, but we need to wait for the CSS File to load before the styles are updated

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/45675641/173180593-525ee4b5-b4f1-4d7c-8b43-87954d54c413.png">

the ssr is functioning correctly (more or less), it's just that the CSS file (that isn't in your network tab because it was likely loaded from cache, try disabling the cache) isn't loaded when that preview is rendered.

**Comment by oskarious** [comment]
Makes total sense now that you mention it! I will close this since it was just me being dumb and forgetting how the web works.  😅Thanks for helping me out!

**Comment by YoungElPaso** [comment]
Just jumping in here to mention to @d3rpp turning dev server on/off (and thus probably clearing cache) worked for me when I had changed `csr = false` from true. 

.svelte style tag hadn't been included anymore unless I turned CSR back on. I assume that's just because the rendering of the page was totally different

So, for anyone else with SSR/CSR CSS issues - try turning it on and off again 😄
