### ISSUE TITLE
when fetch request from sveltekit endpoint to laravel api create new session.

### ISSUE THREAD

**Issue by blitzkrieg1** [sveltejs/kit#5216]
### Describe the bug

but when try same thing on svelte page with load function  cookies send to api. and laravel api dont create new session.
in summary, endpoint js cant send session_id cokkie to api. but page load functon can.
i cant solve this problem. is this bug ? 

### Reproduction

**when try with page.svelte WORK ! laravel api can get session cookie**

<script context="module">
	export async function load({ params, fetch, session, stuff }) {
		const url = `http://127.0.0.1:8000/cart-view`;
		const response = await fetch(url)

		return {
			status: response.status,
			props: {
				cart: response.ok && (await response.json())
			}
		};
	}
</script>

---------------------------------------------------------------------------------------

**when try with page.js endpoint NOT WORK! laravel api cant get session cookie , therefor create new session**

const base = 'http://127.0.0.1:8000/products';
export function api(method, resource, data) {
    return fetch(`${base}${resource}`, {
        method,
        headers: {
            'content-type': 'application/json',
            'accept': 'application/json',
        },
        body: data && JSON.stringify(data)
    });
}

export const get = async () => {
    const apiResponse = await api('get', ``);
    if (apiResponse.status === 200) {
        return {
            body: {
                products: await apiResponse.json(),
            }
        };
    }
};

### System Info

```shell
sveltekit
```

### Severity

annoyance

**Comment by Conduitry** [comment]
The global `fetch` function available doesn't automatically pass along any cookies, and it wouldn't be able to because there's no way in JS for it to know what request it's being used as part of. If you need to pass along some cookies from the request, you need to manually do so by getting the cookie from the `event.request` object.

Please review the instructions about issues before you open another one. Pasting part of your code is not a valid reproduction. Use code blocks so any code you do include is actually formatted and doesn't look terrible. And just saying `sveltekit` for System Info doesn't tell anyone anything.

**Comment by blitzkrieg1** [comment]
sorry, my first try on github...

this is server side cookie. i dont need to pass with request. 
browser automaticly do it for me?
