### ISSUE TITLE
Serviceworkers `prerendered` paths incorrect with `trailingSlash: 'always'`

### ISSUE THREAD

**Issue by PatrickG** [sveltejs/kit#5225]
### Describe the bug

When having set `trailingSlash` to `'always'`, the paths for page-endpoints (`__data.json`) and endpoints like `sitemap.xml` in the `prerendered` variable of the `$service-worker` module are normalized to have a trailing slash.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-xkpctn
See console output

### System Info

```shell
Not relevant
```

### Severity

serious, but I can work around it

### Additional Information

I'm not sure, if it would be enough to revert this change: https://github.com/sveltejs/kit/commit/1ea4b06f158a8f52012e4a4cb5152a80b52f943b#diff-693bcce9e16dcf8cee3dc704a2e1c2f2024b1d540e31c3bb050a5112a61ef2d1

**Comment by rmunn** [comment]
> I'm not sure, if it would be enough to revert this change: [1ea4b06#diff-693bcce9e16dcf8cee3dc704a2e1c2f2024b1d540e31c3bb050a5112a61ef2d1](https://github.com/sveltejs/kit/commit/1ea4b06f158a8f52012e4a4cb5152a80b52f943b#diff-693bcce9e16dcf8cee3dc704a2e1c2f2024b1d540e31c3bb050a5112a61ef2d1)

That change was part of #4699, whose intent was to fix bugs like #4294. Reverting that specific change (which removes the special treatment of filenames with `.` in them) would undo the fix for #4294.

In the PR description of #4699, @Rich-Harris wrote that the `trailingSlash` option would now apply only to pages, and not be applied to endpoints. So I think this is just a bug that was missed when #4699 was written. Thanks for the reproduction; that'll be useful in solving it.

**Comment by PatrickG** [comment]
> That change was part of #4699, whose intent was to fix bugs like #4294. Reverting that specific change (which removes the special treatment of filenames with `.` in them) would undo the fix for #4294.

Yea, i thought something like that was the reason for this change.

The Problem is, in prerendering, we don't know if it is an endpoint or not.
