### ISSUE TITLE
Advanced matching, naming proposals : __matcher.ts in the [page] folder parallel of [page=isPagePattern]

### ISSUE THREAD

**Issue by 7antra** [sveltejs/kit#5298]
### Describe the problem

If we have a lot of folders with dynamic params ; like `[station]` / `[about]` / `[profils] `, etc  sometimes it could be annoying to read : 
 `[station=isStation]`, `[about=isAboutMatcher]` or `[profils=profils]`, it's little strange, even if you have a good naming like `archive/[year=integer]`

### Describe the proposed solution

Maybe an alternative solution is possible ? Like you could have a file inside your folder named : `__matcher.js`, and this solution could cohabit with the existing one : `[page=matcher].svelte`

```js
// src/route/[page]/__matcher.js

/** @type {import('@sveltejs/kit').ParamMatcher} */
export function match(param) {
  return /^\d+$/.test(param);
}
```

Maybe it would be cleaner when you read your files in the explorer

### Importance

nice to have

### Additional Information

Sry for my english 
<3 all your work

**Comment by Rich-Harris** [comment]
At present, SvelteKit is able to determine whether a given route matches the request without importing any code associated with the route. That's particularly important in the browser, where we'd have to `await import(...)` the matchers for the route candidates in order to test them. In the best case that introduces latency; in the worst case it leaves you more vulnerable to network errors and the like. It means that we can't determine inside the `click` handler whether or not the link should be handled by the client-side router, which means we can't `event.preventDefault()` when we need to. Even if we could make it work, this is a _lot_ of extra complexity, for something that ultimately discourages discoverability and reuse.

Given the examples you gave, it sounds like what you're looking for is a way to internationalise your routes. For now we don't have a great way to do that other than matchers, but it deserves a more appropriate solution — it'll be a focus area post-1.0. Until then I'm going to close this as wontfix

**Comment by 7antra** [comment]
Thank you for this answer, even if I'm not sure that I understand all the issues in detail, however if the "match function" could exist in `+page.ts` like this : 

```ts
// src/route/[example]/+page.ts

/** @type {import('@sveltejs/kit').ParamMatcher} */
export function match(param) {
  return /^\d+$/.test(param);
}

/** @type {import('./$types').PageLoad} */
export function load({ params }) {
...
}
```

Would this be a solution? Or maybe not... 🤔 But I'm fine with the matchers, it's just the way of writing [slug=isOk] that is problematic from a DX pov - when reading all the `route` folder with a lot of subfolders -

Either way, see you Thursday in Stockholm 🇸🇪 !
