### ISSUE TITLE
Improper import in route does not throw but builds nothing

### ISSUE THREAD

**Issue by iverks** [sveltejs/kit#5413]
### Describe the bug

When a page (a .svelte-file in the src/routes directory) has a broken import: 
I run `npm run build`.
No errors are thrown, no warnings are given and the site doesnt build. 

Expected behaviour would be one of: 

* Build fails with error
* Build succeeds with warning
* Build succeeds without warning, but throws in runtime

### Reproduction

https://github.com/iverks/sveltekit_import_bug

`npm install`
`npm run build` - nothing gets built, but no errors

Then you can comment out the import in `index.svelte`, and it builds just fine

### Logs

```shell
PS C:\Users\ivism\Progging\bug> npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> bug@0.0.1 build
> vite build

vite v2.9.13 building for production...
✓ 13 modules transformed.
```

### System Info

```shell
Testen on Windows 10 and windows 11.

From win10:
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 4.37 GB / 15.71 GB
  Binaries:
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (103.0.1264.44)
    Internet Explorer: 11.0.19041.1
```

### Severity

serious, but I can work around it

### Additional Information

About severity: I guess it could be considered "annoying", but its terrible DX and was almost impossible to debug.
Tested with adapter-node and adapter-static.
This is using the latest package.json, vite.config.js, svelte.config.js setup  supplied by `npm create svelte app-name`

**Comment by ZerdoX-x** [comment]
Spend about two hours on this issue, but found way that can help someone debug this faster: just run `npm run dev` (`vite dev`), interact with your application a little so it would throw an error. After that you could see which import is broken.

In my case it was `postcss.config.js` which was refactored from `require` to `import from` as for https://github.com/postcss/postcss-load-config/issues/230 but apparently `postcss-load-config` doesn't respect `type: "module"`, so I had to rename `postcss.config.js` to `postcss.config.mjs`.

Hopefully this would be resolved as much as possible.


For sveltekit dev team and volunteers: I was upgrading from 357 to 367 and this bug was likely introduced in https://github.com/sveltejs/kit/pull/5332
Even tho I'd even say I didn't have this bug before having `vite.config.js` was a must (but I was using this feature as experimental)

**Comment by kuechlerm** [comment]
@ZerdoX-x In my situation that was not helpful because the import error was in some long forgotton playground file.

I think the most helpful way to find errors in your code is to 

### **call `svelte-check`**
and then fix all errors.

I would **not** call this bug "annoying". I was not able to deploy my app for some hours. Yes, we can roll back to an older version. But there were so many changes, that it was a bit hard to pin down the culprit. I would suggest fixing this quickly or at least leave a hint somewhere to use svelte-check with build.

**Comment by ZerdoX-x** [comment]
@kuechlerm Yep.
In your case dev mode is not helpful.
In my case `svelte-check` is not helpful (as it doesn't check how project builds. my issue was with postcss config)

So I guess the most reliable way to check why build fails is to downgrade `@sveltejs/kit` package. It might not work if cause of your build failing is updating `@sveltejs/kit` itself. In this case you must read update notes for each version you get over _(actually you need to do this when upgrading even if your build works fine)_.

**Comment by benmccann** [comment]
Fixed. Thanks for tracking this down @gtm-nayan

**Comment by isaac-mcfadyen** [comment]
Just a heads-up that I caught this issue a while back and was directed to Vite: https://github.com/sveltejs/kit/issues/5382

I assume that this was a SvelteKit specific issue and *not* a Vite issue? In which case I don't need to make a Vite Issue?

**Comment by bluwy** [comment]
Yeah this was a SvelteKit specific issue. No need to open an issue in Vite.
