### ISSUE TITLE
Playwright times out due to bad default port setting

### ISSUE THREAD

**Issue by kyllerss** [sveltejs/kit#5429]
### Describe the bug

When I add `vitest` integration to a skeleton SvelteKit project, `playwright` ceases to work - I get a connection timeout.

### Reproduction

I have created the following project that illustrates the problem:

[https://github.com/kyllerss/sveltekit-vitest-and-playwright](https://github.com/kyllerss/sveltekit-vitest-and-playwright).

### Logs

```shell
Running 1 test using 1 worker

[WebServer] (node:18795) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[WebServer] (node:18807) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[WebServer] Generated an empty chunk: "hooks"
[WebServer] (node:18807) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
[WebServer] (node:18842) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[WebServer] (node:18854) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Error: Timed out waiting 60000ms from config.webServer.
```

### System Info

```shell
N/A
```

### Severity

serious, but I can work around it

**Comment by kyllerss** [comment]
I ran into this issue when following the guidance from [Issue #5094](https://github.com/sveltejs/kit/pull/5094).

**Comment by philip-weber** [comment]
It seems the problem was introduced in PR #5392. The problem does not come from using `playwright` together with `vitest` but because the port for the preview server was changed in PR #5392. `sveltekit` used the port 3000 for the `dev server` and the `preview server`. `vite`, on the other hand, uses port 3000 for the `dev server` and port 4173 for the `preview server`. You need to change the port in your `playwright.config.ts` to `port: 4173`. I guess this needs to be changed in the template.

**Comment by kyllerss** [comment]
Thank you for the fast turn-around! Works!
