### ISSUE TITLE
Concerns around increasing amounts of magic

### ISSUE THREAD

**Issue by pikeas** [sveltejs/kit#5481]
### Describe the problem

SvelteKit has added a lot of "magical" functionality over the past year, features that Just Work out of the box. These include:

- Virtual files like __types
- Magic routes like __data
- Shadow endpoints
- General control flow like handle(), getSession(), event.locals, and stuff

These features are great but add up to a significantly less explicit DX, especially for beginners. As a personal anecdote, I pop into SvelteKit once a year or so for a quick project, and each time I've had a *harder* time ramping back up, despite having *more* experience.

I'm now starting to feel some "React" vibes - I'm spending less time building and more time figuring out how to do things the SvelteKit Way and maintaining a mental model of all the moving parts. For example, I've just spent a day reading through issues, examples, and blog posts while trying to figure out the Right Way to display user-specific authenticated data from an API. This is one of the first things any non-trivial (that is, full static) SPA needs and this immediately took me down a rabbit hole (load? shadow endpoint? handle hook? stuff?!) instead of a happy path.

I want to emphasize that all of these features are legitimately great and useful. Each individual bit of magic is an improvement in isolation, but at a tipping point it can feel collectively overwhelming.

### Describe the proposed solution

1. More documentation with more examples.
2. More inline documentation (doc strings, starter template)
3. Specific new documentation, such as: request processing lifecycle, FAQ.
4. A comprehensive tutorial from 0 through "prodworthy".

### Alternatives considered

Less magic.

### Importance

would make my life easier

**Comment by Rich-Harris** [comment]
This is pre-release software; we're moving fast and breaking things precisely so that we don't have to quickly release a 2.0 with breaking changes from the stuff we didn't get right for 1.0. The cost of stability later is a bit of churn now, for users who are bold enough to deal with a framework that isn't designated production-ready.

All the features you mention _will_ have thorough documentation — it will live on https://learn.svelte.dev (currently has the placeholder of a tutorial, will eventually also have explanatory material etc). It's unfortunately just not practical to keep that up-to-date until things settle, because documentation is a ton of work. I'll close this issue since that work is already in progress (we're considering it a blocker for a 1.0 release).
