### ISSUE TITLE
Minify prerendered HTML (and app.html?)

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#568]
`sapper export` minifies the generated HTML. Perhaps we should do the same thing here?

```js
// svelte.config.cjs
module.exports = {
  kit: {
    prerender: {
      minify: true
    }
  }
};
```

```js
// svelte.config.cjs
module.exports = {
  kit: {
    prerender: {
      minify: {
        // manually specify options (https://www.npmjs.com/package/html-minifier)
        collapseBooleanAttributes: true
        // ...
      }
    }
  }
};
```

We could potentially do the same thing for `src/app.html`, though the benefits are less pronounced.

**Comment by benmccann** [comment]
I wonder if this config should live elsewhere because presumably you could minify the html on a non prerendered page

**Comment by Rich-Harris** [comment]
It's not cheap, you probably wouldn't want to do it on the fly. But yeah, if it lived in a separate place (`kit.htmlMinifierOptions`?) then it could at least apply to `src/app.html` as well as prerendered pages

**Comment by Conduitry** [comment]
Being able to control the minification options (or disabling it entirely) sounds good, as this is one of the requested Sapper features that we deferred on because of a lack of a sane way to handle configuration.

I have mixed feelings about whether this should be enabled by default for prerendered sites. It's probably a good idea, but then it's also been the subject of [a](https://github.com/sveltejs/sapper/issues/1061) [whole](https://github.com/sveltejs/sapper/issues/1161) [lot](https://github.com/sveltejs/sapper/issues/1171) [of](https://github.com/sveltejs/sapper/issues/1455) [invalid](https://github.com/sveltejs/sapper/issues/1663) [Sapper](https://github.com/sveltejs/sapper/issues/1702) [bugs](https://github.com/sveltejs/sapper/issues/1747).

I agree that it's probably only a good idea to include this on HTML that can be minified during build time and not at runtime.

**Comment by benmccann** [comment]
I thought about it being expensive, but it might still be worth it for `public` cached pages (i.e. no `session` and `maxage`)

**Comment by Conduitry** [comment]
As much as people should probably be deploying things behind a CDN, it sounds like a dangerous precedent to have default settings that will give people a bad time unless they're behind a CDN.

**Comment by benmccann** [comment]
Agreed. I wouldn't turn it on by default

**Comment by benmccann** [comment]
I wonder if people could implement this on their own using hooks now? Perhaps that's enough to close this issue?

**Comment by Rich-Harris** [comment]
I'd like it if it was a bit more turnkey but it _does_ seem very difficult to offer sensible defaults. Without configuration it won't do a whole lot for you. So it probably doesn't make sense to weigh the package down with a dependency that won't do very much for most people.
