### ISSUE TITLE
A bad route causes the application to be reloaded, losing all application state 

### ISSUE THREAD

**Issue by Mopholo** [sveltejs/kit#5808]
### Describe the bug

I attempted to find similar issues in the repository apologize if I missed it. 

Using SSR - When a bad route is encountered, whether or not a __error.svelte page is present or not, it appears that vite disconnects, then reconnects and reloads the application then displays the error page, one obvious side effect is that the content of any stores goes back to their default state.   

I hope this isn't 'correct' behavior. I tried redirecting in an __error. svelte page in the /routes dir, which worked so far as not displaying the error page, but the app was still re-loaded ( at least I think that's what's happening )    

If anyone has a work-around where state isn't lost on a bad route please let me know. 

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-guscor?file=src/lib/header/Header.svelte

Derived from  https://node.new/sveltekit as per request 

This is a pared-down demo project fork, clicking on non-error-producing links ( Home, About ) will push a string onto an array from a simple store. The array is then displayed below the header. 

Clicking on "Bad Link" will route to a page that doesn't exist. This appears to cause the app to be reloaded since the simple store gets set back to its default empty state.

Not sure if this is a vite issue, or kit issue. 

### Logs

```shell
Not Applicable
```

### System Info

```shell
Example was forked from https://node.new/sveltekit
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
This is design question we need to answer - is this the expected behavior or not? What happens is that the client tries to find a route, doesn't find any, and therefore tries to do a native navigation, in other words a page reload for the requested site, which is why the state is lost. I don't fully know the reasons for this or if changing this would have other bad implications, other maintainers maybe know more.

**Comment by dummdidumm** [comment]
Alright, got an answer - this is "works as designed" because we can't know if people did this on purpose. Maybe the `handle` function on the server does reroute this to somewhere valid, or maybe that's an endpoint which serves some content, so it's the right move to do a full-page-reload.
If you don't want that, you can create a catch-all route at the root and serve your own 404 page from there:
```
src/routes/
  |- your-other-routes
  |- [...rest]
      |- +page.svelte // your 404 fallback
```

**Comment by Mopholo** [comment]
I am not sure I understand, are you saying that if I provide a  __error.svelte error handling page, it is correct behavior for the application to completely reload causing all store state to be dumped? 

Why wouldn't the __error.svelte page just be loaded as if it were another route?

**Comment by dummdidumm** [comment]
If you have this:
```
|- some-page/+page.svelte
|- some-endpoint/+server.js
```
.. or this
```js
// hooks.js
export function handle({ event, resolve }) {
   if (event.url.basename === 'some-endpoint') {
      return resolve(new Response('something else'));
   }
   // ...
}
```
..then doing a 404 when clicking on a link to `some-endpoint` could be the wrong behavior. That's why the request goes back to the server in this case, because the client doesn't know, causing a full-page-reload-navigation, which is why the state is lost if it's actually a 404. The workaround I mentioned earlier solves your use case.
