### ISSUE TITLE
Redirect with Headers

### ISSUE THREAD

**Issue by luhagel** [sveltejs/kit#5908]
### Describe the problem

While trying to migrate our app, I stumbled on a problem with the way we handle logins/logouts right now:

login.ts
```ts
import type { RequestHandler } from '@sveltejs/kit'

export const GET: RequestHandler = async (event) => {
	const token = event.url.searchParams.get('token')
	const cb = event.url.searchParams.get('callBackUrl')
	return {
		status: 302,
		headers: {
			location: cb && cb !== 'undefined' && cb.length > 0 ? decodeURIComponent(cb) : '/',
			'set-cookie': `token=${token ?? ''}; Path=/; HttpOnly`
		}
	}
}
```

Previously, out login/logout endpoints could set/unset the cookie and redirect in the same response, but with redirect being reimagined as errors, that's no longer possible.

### Describe the proposed solution

I'm not really set on a specific solution, but it would be nice to have a convention for these kind of endpoints. 

### Alternatives considered

We could split the endpoint for setting/unsetting and call a goto if the request succeeds, but that take away quite a bit of simplicity and is something always to be remembered.

### Importance

would make my life easier

**Comment by tcc-sejohnson** [comment]
My entire OAuth integration is implemented as a `handle` middleware, so that's my recommendation for how to get around this. As for solutions that let you keep your endpoints... regular endpoints (`+server.ts`) just return a `Response`, so you should be fine there. The new `+page.server.ts` files get passed a `setHeaders` function as part of their event, which you could use to set the cookie. I think that covers all bases, right?
