### ISSUE TITLE
Using transitions with key blocks results in duplicated content

### ISSUE THREAD

**Issue by kiosion** [sveltejs/kit#5938]
### Describe the bug

When using {#key} blocks with transitions, new content is inserted before previous content is removed. This results in choppy / glitchy transitions between pages, and new / old content appearing stacked or on top of each other briefly.

### Reproduction

Example at https://stackblitz.com/edit/sveltejs-kit-template-default-euymle?file=src/routes/+layout.svelte . Most noticeable with long transitions, but also occurs when not using any.

### System Info

```shell
System:
    OS: Linux 5.18 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Memory: 2.40 GB / 31.30 GB
    Container: Yes
    Shell: 3.5.1 - /bin/fish
  Binaries:
    Node: 16.16.0 - /bin/node
    Yarn: 1.22.19 - /bin/yarn
    npm: 7.17.0 - /bin/npm
  Browsers:
    Firefox: 100.0.1
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.64 
    @sveltejs/kit: next => 1.0.0-next.406 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.0 => 3.0.7
```

### Severity

annoyance

**Comment by rmunn** [comment]
I suspect (but don't have time to do this myself at the moment) that this could be reproduced in the [Svelte REPL](https://svelte.dev/repl/) with no Svelte-Kit layout components involved at all. If so, then this should probably be reported in https://github.com/sveltejs/svelte/issues instead of here.
