### ISSUE TITLE
Provide a way for layouts to determine if current page is an error page

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#598]
In Sapper we did https://github.com/sveltejs/sapper/pull/1498

Suggestion from Rich for SvelteKit: 
> Given that it only applies to the root layout I think I'd prefer that we pass the error (and possibly status) as a prop. It doesn't belong on the page store

**Comment by Rich-Harris** [comment]
Created a new `straightforward` label for issues like this that should be pretty easy to implement since they don't touch a bunch of different places. In this case I think we just need to add a prop here... https://github.com/sveltejs/kit/blob/64d02910d0000a4ca28af7de1a1cae8f487cc5d7/packages/kit/src/core/create_app/index.js#L191 ...and add a test.

The one downside of this approach is that we'll get `created with unknown prop` warnings in dev if the root layout doesn't expose an `error` prop, but that's not the worst thing in the world

**Comment by Conduitry** [comment]
Could we partially relieve that by having the starter template define the prop in the root layout, even if it doesn't use it? That might not be worth it though, and would add bytes to the prod version just to avoid a dev time warning. I'm torn.

**Comment by Rich-Harris** [comment]
I think Svelte should probably skip the warning in cases where the prop is undefined _anyway_.

Relatedly, we have a similar problem with it often warning that a default slot was provided to a leaf component

**Comment by Rich-Harris** [comment]
We decided that the best way to do this would be

```js
import { status, error } from '$app/stores';
```

**Comment by Rich-Harris** [comment]
closed via #3096
