### ISSUE TITLE
Docs versioning for back compatibility

### ISSUE THREAD

**Issue by BeGeos** [sveltejs/kit#6023]
### Describe the problem

It is a rather simple suggestion but recently SvelteKit received a big update, especially regarding routing. The docs on the website `kit.svelte.dev` only concerns the new version. However, there are developers (like me 😄 ) that have started their projects using the previous version of SvelteKit, and now the docs for that seems missing on the official website.

### Describe the proposed solution

Just provide versioning for the docs, depending on the SvelteKit version the docs should be different. In a similar way, Django does it where they have docs for all versions even deprecated ones.

### Importance

nice to have

**Comment by dummdidumm** [comment]
We won't introduce for next version, although it's probably valuable to think about this for 2.x etc.

As a workaround, you can look at the repository state before the big refactor and read the docs from there:
https://github.com/sveltejs/kit/tree/0801e8e942534d3f6c614523f0ee4fe10b602b26/documentation/docs

**Comment by Rich-Harris** [comment]
Another thing you can do is view the snapshot of the docs. Search for `Version Packages (1.0.0-next.405)` in GitHub to find the changesets release PR...

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/1162160/185408276-59497d9e-735e-4cf7-b779-e60ab8ae90ac.png">

Click the PR link (there might be multiple ones due to how GitHub search works, but you should be able to find the correct one easily enough), and click on the `View deployment` link for `kit-svelte-dev` (highlighted blue in the screenshot):

<img width="936" alt="image" src="https://user-images.githubusercontent.com/1162160/185408739-806bbe29-b0e1-4073-9c45-e50f97c6f0cc.png">

This gives you a snapshot of the docs at that moment: https://kit-svelte-dovpukzmn-svelte.vercel.app.

Would be great to eventually do this in a more structured way, though it's a bit of a challenge — would require us to think about how to maek changes to how the docs are rendered in backwards-compatible ways. For now, I'll close this issue.
