### ISSUE TITLE
Are you planning to make embedded transitions?

### ISSUE THREAD

**Issue by FlymeDllVa** [sveltejs/kit#603]
**Is your feature request related to a problem? Please describe.**
This is more of a question about whether there will be a built-in implementation of transitions.

**Describe the solution you'd like**
I would like to see a built-in ability to create transitions. As an example: https://routify.dev/docs/transitions

**Describe alternatives you've considered**
Write your own implementation?

**How important is this feature to you?**
Strongly. If you migrate a project from Routify, you will need transitions, because they make the project look more dynamic.

**Comment by antony** [comment]
@FlymeDllVa It'd be super useful if you could fill out the provided template.

**Comment by Rich-Harris** [comment]
I don't know that there's a huge amount of value in SvelteKit providing anything beyond what Svelte provides, so I'm going to close this. If there's something that's not possible with Svelte by itself (that is somehow fixable within SvelteKit, rather than requiring a change to how transitions work in Svelte) then it would be helpful to have an issue with those specifics — thanks
