### ISSUE TITLE
+page.server cannot fetch relative path, fails with "Failed to parse URL from /path.json"

### ISSUE THREAD

**Issue by danawoodman** [sveltejs/kit#6090]
### Describe the bug

If you have a page `src/routes/foo.json/+server.js` that returns a JSON response and consume it with `src/routes/+page.server.js` via `fetch("/foo.json")` it fails with `"Failed to parse URL from /path.json"`. 

I understand the reason to do this is limited but multiple people are at least _attempting_ this in their Kit apps, so it should be addressed in some way. I assume this is just a limitation with `fetch`.

If this is expected, perhaps the docs need to mention this limitation?

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-o2ovx1?file=src%2Froutes%2F%2Bpage.server.js,src%2Froutes%2F%2Bpage.svelte,src%2Froutes%2Ffoo.json%2F%2Bserver.js&terminal=dev

### Logs

```shell
"Failed to parse URL from /path.json"
```

### System Info

```shell
cant seem to run in StackBlitz, but latest Kit
```

### Severity

annoyance

**Comment by PatrickG** [comment]
Related: https://github.com/sveltejs/kit/issues/618#issuecomment-822474031

**Comment by danawoodman** [comment]
Thanks. So it sounds like "won't fix" but perhaps the docs should communicate this?

**Comment by babichjacob** [comment]
I wrote about this [in Discord](https://discord.com/channels/457912077277855764/1009582749700604004/1009666395753173064): I would like for `PageServerLoad` to have a `fetch` argument, which would solve this issue. 

This would keep `+page.js` <---> `+page.server.js` renaming possible in most instances (besides the `PageLoad` <---> `PageServerLoad` change), which I thought was a goal since I saw [page options](https://kit.svelte.dev/docs/page-options) could be specified in either file and that [the docs suggest renaming the file](https://kit.svelte.dev/docs/routing#page-page-server-js) when you need your `load` function to only run on the server.

I also understand that this is kind of a variation of the "fetching another endpoint from this endpoint" question that is answered well by telling people to split that endpoint's work into a new function/module and importing that function into both places, so I'm not sure if that stance should be taken here too.

**Comment by Conduitry** [comment]
Having a `fetch` in `PageServerLoad` (or perhaps even in `RequestEvent` so that it can be used in `handle`) is a feature on the roadmap, and will probably get its own issue. It would do all the things the `PageLoad` `fetch` does - resolve relative paths, pass cookies, headers, etc.

But in the meantime, this is working as intended. And the global `fetch` won't get these features, because it's impossible to tell what request it should be relative to or it should get the cookies from.
