### ISSUE TITLE
Unable to use undeclared static environment variables

### ISSUE THREAD

**Issue by inta** [sveltejs/kit#6160]
### Describe the bug

I try to import an environment variable from `$env/static/public` not present in any `.env` file or environment and get an error. I do not know how the internals work, but the exported variables seems to be collected only from the environment and not from usages.

I filed this issue because Svelte Kits behaviour differs from Vite's `loadEnv` function, which allows me to use unknown variable names.

### Reproduction

https://github.com/inta/sveltejs-kit-template-default-3djxav

Stackblitz does not load the `.env` file (but I include it here anyways):
https://stackblitz.com/edit/sveltejs-kit-template-default-3djxav?terminal=dev

### Logs

```shell
The error message differs between my local machine:

500
ambiguous indirect export: PUBLIC_NOT_WORKING


and Stackblitz:

500
The requested module '/@id/__x00__$env/static/public' does not provide an export named 'PUBLIC_NOT_WORKING'
SyntaxError: The requested module '/@id/__x00__$env/static/public' does not provide an export named 'PUBLIC_NOT_WORKING'
```

### System Info

```shell
System:
    OS: Linux 5.18 Debian GNU/Linux bookworm/sid
    CPU: (16) x64 AMD Ryzen 7 PRO 4750U with Radeon Graphics
    Memory: 13.89 GB / 30.59 GB
    Container: Yes
    Shell: 3.5.0 - /usr/bin/fish
  Binaries:
    Node: 18.7.0 - /usr/bin/node
    npm: 8.13.2 - ~/.npm/global-modules/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Chromium: 104.0.5112.101
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.65 
    @sveltejs/kit: next => 1.0.0-next.428 
    svelte: ^3.46.0 => 3.49.0 
    vite: ^3.0.8 => 3.0.9
```

### Severity

annoyance

### Additional Information

Some background info:

I was implementing feature flags for some components and wanted them to always fall back to a default value. If missing variables lead to an error, I always have to make sure that every environment is up to date and has all new feature flags before introducing them in the codebase, otherwise the build pipeline would be broken.

**Comment by Rich-Harris** [comment]
You can fix this by adding empty values to your `.env` file:

```
PUBLIC_FEATURE_FLAG_1=
PUBLIC_FEATURE_FLAG_2=
PUBLIC_FEATURE_FLAG_3=
```

This will populate `$env/static/public` with `PUBLIC_FEATURE_FLAG_1 === ''` etc. You can test them out locally like so...

```
PUBLIC_FEATURE_FLAG_1=enabled npm run dev
```

...and their values will be overridden by `process.env` when your app is built.

**Comment by inta** [comment]
Yes, thank you, that works.
Is that how it's supposed to be or is that just a workaround?

**Comment by Rich-Harris** [comment]
Yep, that's how it's supposed to work! opened #6165 to clarify it in the docs

**Comment by tcc-sejohnson** [comment]
> Yes, thank you, that works.
> Is that how it's supposed to be or is that just a workaround?

Static environment vars are meant to be known at buildtime, so they _should_ all be present while you're developing. Dynamic environment variables are what you're looking for if the value isn't known at buildtime.

**Comment by inta** [comment]
Just thinking loud: Why not change the specs of static vars to match those of dynamic vars? That way you would import an object and if you reference an unknown var you get undefined instead of an error. By the way that would match the API of Vite*s loadEnv exactly.
I do not know which problems this could bring up, I just think this would be more intuitive and more consistent.

@tcc-sejohnson no, I do want the values at build time. My concern are environments without a declaration (of newly introduced environment vars) are going to break if a new version is deployed instead of falling back to the default.

**Comment by tcc-sejohnson** [comment]
> Just thinking loud: Why not change the specs of static vars to match those of dynamic vars? That way you would import an object and if you reference an unknown var you get undefined instead of an error. By the way that would match the API of Vite*s loadEnv exactly.
> I do not know which problems this could bring up, I just think this would be more intuitive and more consistent.

A few reasons. The current design allows for amazing levels of autocompletion -- type `PUBLIC_`, and boom -- all of your public static vars are available for autocomplete and autoimport. 

Also, because they're declared as individual exports, your build will fail if you're missing one, guaranteeing you're _never_ missing an expected static variable. This isn't possible with one exported object. 

> @tcc-sejohnson no, I do want the values at build time. My concern are environments without a declaration (of newly introduced environment vars) are going to break if a new version is deployed instead of falling back to the default.

I would consider this a feature of static environment variables, not a bug -- your app literally _will not build_ if you're missing an expected static environment variable. The escape hatch for this is dynamic environment variables.

**Comment by inta** [comment]
You make some good points, although I am not completely convinced. I need to commit the `.env` file to get a consistent state, but maybe that is ok.

**Comment by tcc-sejohnson** [comment]
> You make some good points, although I am not completely convinced. I need to commit the `.env` file to get a consistent state, but maybe that is ok.

I don't think you need to do that. It seems like there might be some level of misunderstanding here. There are really two cases to worry about: Local development and testing (i.e. where you or a coworker pull the repo down and need to work on it) and production builds. 

### Local

If you have `undefined`-able environment vars (like Vite's `import.meta.env`), when you pull a project down from GitHub, you're screwed. Run the app. Random, weird errors caused by missing environment variables? What missing environment variables? Better `Ctrl+Shift+f` `import.meta.env` and figure it out. Or keep a list of them in the `README` that'll inevitably get out of date. Or do neither and just ask a coworker to IM you their `.env.development` file. All annoying options.

If the environment variables are _required_, as soon as you build your app, it'll blow up and tell you _exactly_ which environment variables are missing, on _exactly_ which lines. It doesn't "fix" the "I don't know what env vars to fill out" problem, but it at least makes it easier.

### Build-time

.env files probably aren't very useful for production build-time. The good thing is, `$env/static/*` aren't just pulled from `.env` files -- they're pulled from anything that's on `process.env` _and_ `.env` and `.env.environment` files. This means that if you're running your builds on, say, GitHub actions, your GitHub repo secrets will be available as static environment variables -- and if you forgot to set one of them... _boom_, build fails before you even had a chance to deploy your broken site.

**Comment by inta** [comment]
Your sum up is definitely right, but not valid for the use case of feature flags I was working on and where this issue came up.

We do something like `import.meta.env.FOO ?? 'default'`so build will not break and default case will be chosen. For boolean values `undefined` will evaluate to false anyway. Features usually come up or go away, so a default of false will always work fine.

I see that this is just one use case and there are for sure other cases where a default value will not help much.

**Comment by tcc-sejohnson** [comment]
> Your sum up is definitely right, but not valid for the use case of feature flags I was working on and where this issue came up.
> 
> We do something like `import.meta.env.FOO ?? 'default'`so build will not break and default case will be chosen. For boolean values `undefined` will evaluate to false anyway. Features usually come up or go away, so a default of false will always work fine.
> 
> I see that this is just one use case and there are for sure other cases where a default value will not help much.

Ah yeah, I see what you're saying there. I would say the "correct" thing to do here is to use dynamic variables OR specify your defaults in your build environment. (FOO=default)

**Comment by Rich-Harris** [comment]
If you're adhering to twelve-factor ideology then _everything_ is in dynamic variables already. But if you're not, then I would strongly advocate for static variables with the solution I described above. This is part of what `.env` files are for — acting as documentation for what env vars are in use.

Using `static` rather than `dynamic` also means that deploys without a given feature flag can benefit from DCE etc

**Comment by tcc-sejohnson** [comment]
Oh wait, I think you can use your own TypeScript magic to do exactly what you want:

```ts
// public-feature-flags.ts
import * as env from '$env/static/public';


export env as Partial<Omit<typeof env, 'default'>> & Record<string, string | undefined>
```

Same for the private stuff. 

I'm not at an editor right now, so not sure if there are any syntax errors, but that should work...

**Comment by tcc-sejohnson** [comment]
@inta 

Turns out my idea does work for feature flags -- and well! Check it out here:

https://stackblitz.com/edit/sveltejs-kit-template-default-rehunj?file=src/routes/+page.svelte

Hopefully that (relatively simple) userland solution works for you.

**Comment by inta** [comment]
Thanks for that new idea @tcc-sejohnson. Your first approach actually works if I put it inside a .svelte file (without the export keyword).

The nice userland solution for feature flags works on Stackblitz, but in my local setup it throws an error on build:
```
[vite:load-fallback] Could not load /src/lib/featureflags/public (imported by src/lib/MainNavigation.svelte): ENOENT: no such file or directory, open '/src/lib/featureflags/public'
error during build:
Error: Could not load /src/lib/featureflags/public (imported by src/lib/MainNavigation.svelte): ENOENT: no such file or directory, open '/src/lib/featureflags/public'
```
(Paths shortened by me)

Is there any chance we could get such a Typescript definition shipped with Svelte Kit out of the box? Or does that only work if the env vars are contained in an object? I'm sorry for not being very helpful, but my knowledge about Typescript is relatively basic right now.

**Comment by tcc-sejohnson** [comment]
Only works if the vars are in an object. You're likely getting an error due to some local config issues. Try importing it with `.js` at the end? Without seeing your code, it's hard to help.

**Comment by inta** [comment]
Oh sorry, I'm embarrassed now, I accidentally moved the folder and didn't realize it.
Your solution works and is great for feature flags, thanks a lot.

I'm still thinking if committing the `.env` file with basic values to the repo does any harm. The values can be overridden by `.env*.local` files or environment variables on the build system. That would be the solution Rich has proposed and the state in the repo would still be consistent.

I think both are ok.
