### ISSUE TITLE
How to Dynamic Routing in adapter-static?

### ISSUE THREAD

**Issue by mzaini30** [sveltejs/kit#623]
Dynamic routing in adapter-static works in older version of Svelte Kit (1.0.0-next.49) and adapter-static (1.0.0-next.3)

Demo: https://older-kit.vercel.app/kittisaurus (return [slug].svelte)
Github: https://github.com/mzaini30/older-kit

But, why it not working in newer version of Svelte Kit (1.0.0-next.57) and adapter-static (1.0.0-next.4)

Demo: https://newer-kit.vercel.app/kittisaurus (return index.svelte)
Github: https://github.com/mzaini30/newer-kit

I hope this feature not deleted from Svelte Kit

Thanks~

**Comment by babichjacob** [comment]
This is definitely something wanted, but I will close this so that discussion can be tracked in https://github.com/sveltejs/kit/issues/231. I'd recommend subscribing to that issue for the latest updates. So far, it seems like there's work for disabling CSR but no one has talked about SSR yet until someone hypothesized how to implement it in https://github.com/sveltejs/kit/issues/231#issuecomment-805153356.

Thanks!
