### ISSUE TITLE
Route prioritization should disregard (foo) segments

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/kit#6235]
### Describe the bug

When the routes are being prioritized, they should disregard `(foo)` segments. Currently, something like `(foo)/[...catchAll]` is prioritized above `bar` because it has more segments. `(foo)` segments shouldn't be counted when doing this sorting.

### Reproduction

none, currently

### System Info

```shell
System:
    OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Memory: 10.36 GB / 12.32 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Yarn: 1.22.19
    npm: 8.15.0
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
I'm confident this is an easy fix — just need to change this line...

https://github.com/sveltejs/kit/blob/128340cdc4a9307dfa59bbc378cf9c644310bdaa/packages/kit/src/core/sync/create_manifest_data/index.js#L112

...to `.filter(segment => segment !== '' && affects_path(segment)` instead of `.filter(Boolean)` — but I haven't been able to come up with a failing test yet

**Comment by Conduitry** [comment]
Alrighty let me try to extract a failing test from my app.

**Comment by Conduitry** [comment]
Okay, I've added `(foo)/(bar)/[...catchAll]/+page.svelte` and `foo/[bar]/+page.svelte` to the `basics` test app, and visiting `/foo/something` is handled by the former instead of by the latter.
