### ISSUE TITLE
Changes to params no longer trigger updates (+page.js load)

### ISSUE THREAD

**Issue by chbert** [sveltejs/kit#6238]
### Describe the bug

In a multilevel setup, the page does not reload when changing from one level to another.

Example folder structure:
/Legal
    /[level1]
      +page.js
      +page.svelte
      /[level2]
         +page.js
         +page.svelte

Example load function in both +page.js:
```
import { error } from '@sveltejs/kit'

export async function load({ params, parent }) {
    const slug = params.level2 ? `${params.level1}/${params.level2}` : params.level1
    const { storyblokApi } = await parent()

    const { data } = await storyblokApi.get(`cdn/stories/terms-and-policies/${slug}`, {
        version: 'draft'
    })

    if (data) {
        return {
            story: data.story,
            slug
        }
    }

    throw error(404)
}
```
Console.log in page.svelte shows changes of slug prop, but page does not get rerendered.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-wvubip?file=src/routes/+page.svelte

### Logs

```shell
No errors in logs.
```

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 68.80 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.7.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - ~/Library/pnpm/yarn
    npm: 8.15.0 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 104.0.5112.101
    Firefox: 103.0.1
    Safari: 15.5
  npmPackages:
    @sveltejs/adapter-node: next => 1.0.0-next.86 
    @sveltejs/kit: next => 1.0.0-next.432 
    svelte: ^3.49.0 => 3.49.0 
    vite: ^3.0.9 => 3.0.9
```

### Severity

blocking an upgrade

**Comment by Lootwig** [comment]
As a workaround, does adding `target="_self"` to every affected `<a>` cause the behavior you want?

**Comment by christianbertschy** [comment]
@Lootwig thanks for the tip! That actually works for the moment. Though it causes the whole page to reload not only the content area but at least it is usable this way.

**Comment by vsimak** [comment]
Just came across this as well.

It just creates avery uncomfortable DX experience (gotta refresh the page each time).
Another workaround is using [sveltekit:reload](https://kit.svelte.dev/docs/a-options#sveltekit-reload) on the <a>.

But we remove it for production in order to not create an unnecessary full page reload.

**Comment by Rich-Harris** [comment]
This...

```js
export let data;
let { story, slug } = data;
```

...runs when the component is first updated. When you navigate, `data` is updated, but `{ story, slug } = data` doesn't re-run.

Just refer to `{data.story}` in your component, instead of `{story}`. If you _really_ need to destructure it (I don't recommend it, it's much simpler to just use `data.` everywhere) then you need to make that statement reactive:

```diff
-let { story, slug } = data;
+$: ({ story, slug } = data);
```

If you need to reference those values in the `<script>` block before the reactivity first applies, then you would need to do both:

```js
// initialise
let { story, slug } = data;
console.log(story); // this won't work if you only have the `$:` block

// update
$: ({ story, slug } = data);
```

**Comment by christianbertschy** [comment]
@Rich-Harris Good to know, I wasn't aware that the deconstructing has that impact! Thank you for taking the time to explain it in such detail 👍
