### ISSUE TITLE
Svelte transition impacts navigation

### ISSUE THREAD

**Issue by imCorfitz** [sveltejs/kit#628]
**Describe the bug**
If a component used in a route has a transition applied, it will delay navigation and potentially create UI errors. 

**To Reproduce**
In a brand new installation, create a new component e.g. `Linker.svelte` and include it in the `index` route.

```HTML
<!-- src/lib/Linker.svelte -->
<script>
  import { fade } from "svelte/transition";
  let showImage = false;
</script>

<div
  on:mouseenter={() => {
    showImage = true;
  }}
  on:mouseleave={() => {
    showImage = false;
  }}>

  <h1>Wow hi!</h1>
  <a href="/about">About</a>
  {#if showImage}
    <img
      transition:fade={{ duration: 2000 }}
      src="https://picsum.photos/20"
      alt="" />
  {/if}
</div>
```

```HTML
<!-- src/routes/index.svelte -->
<script>
  import Linker from "../lib/Linker.svelte";
</script>

...

<Linker />
<h1>Great success!</h1>

```

Moving the cursor on top of the link, a small picture will slowly fade in. Once clicking on the link, the image will slowly fade out again, but the `/about` page content will already be appended to the `<slot />` and visible in the bottom. If the user moves the cursor back on top of the link while it is fading out, it will just fade in again and prevent the component from being removed completely - causing UI errors.

![ezgif-4-99f035a10dee](https://user-images.githubusercontent.com/52371939/61592827-7bcf9c80-abd8-11e9-9171-e75da7d069c2.gif)

**Expected behavior**
When navigating, default behaviour should be to just switch route. No delays nor attempts to finalise transitions or to show both routes in the `<slot />` at the same time.

**Information about your Sapper Installation:**
- Issue appears in both Chrome and Safari from what I have tested, but I expect this to be the same across all browsers.

- Using iMac 2011 with OSX Mojave

- Running in localhost

- Current latest release v0.27.4

- Svelte v3

- dynamic application

- Using Rollup

**Severity**
Mainly it is just annoying, and I can't really find a workaround to prevent it unless I just remove the transition from the image having it appear and disappear instantly.

**Additional context**
Maybe a modifier to the transition could be an idea. We currently have modifiers like `once` or `preventDefault` on click events. Maybe add a `transition:fade|ignoreRoute={{duration: 200}}` or the quite opposite - having the developer purposely asking for route specific transition.

**Comment by macmillen** [comment]
I also encountered this issue with svelte kit but the `|local` directive doesn't solve my problem because my desired behavior is that all of my animations always trigger on route changes. With `local` that's not possible anymore because my animated components lie deeply nested in the component tree and have multiple render conditions additionally to the implicit route change condition. Does anyone know how to fix / workaround this? I really hope this annoying bug gets fixed soon and all transitions are handled gracefully on any condition.

**Comment by JuanDouek** [comment]
> i do not know if this is the right place, but i have a similar error. I have a List Component with Child Elements like this:
> 
> ```
> <IntersectionObserver let:intersecting>
>   {#if intersecting}
>      ...
>      {#if $isMobileOnly}
>        ....
>       {:else}
>           <List horizontal>
>              <div transition:page|local><Card href="/service" title="Service" /></div>
>              <div transition:page|local><Card href="/gallery" title="Gallery" /></div>
>              <div transition:page|local><Card href="/about" title="About" /></div>
>        {/if}
>    {/if}
> </IntersectionObserver>
> ```
> 
> When i add `|local` to my transitions, nothing happend. When i remove `|local` all Card transitions are fired, when i switch to another page, instead of just executing the transition from the Card i clicked. I also tried to replace my `<Card />` with `svelte:component this={Card} />` but it doesn't work too.
> 
> Is there any other way to fix this? Any ideas?

Try this:
```
<IntersectionObserver let:intersecting>
  {#if intersecting}
     ...
  {/if}

  {#if intersecting && $isMobileOnly}
    ...
  {:else if intersecting}
      <List horizontal>
         <div transition:page|local><Card href="/service" title="Service" /></div>
         <div transition:page|local><Card href="/gallery" title="Gallery" /></div>
         <div transition:page|local><Card href="/about" title="About" /></div>
  {/if}
</IntersectionObserver>
```

**Comment by FractalHQ** [comment]
I think a lot of issues involving transitions (elements not being removed from the dom, transitions interfering with navigation, etc) could be mitigated if we had a way to trigger / abort a transition manually, and/or forcefully remove elements from the dom without having to wait for a transition to finish.  I find myself battling with this often, especially when `|local` isn't an option.

**Comment by Matt-Pilott** [comment]
@evdama i'm finding that this no longer works in kit 202 i'm seeing the scroll to top flash before the next page fades in again like we used to get

**Comment by eduardoliron** [comment]
I was experiencing a similar problem as the one in the first post, reported by @imCorfitz.
As @macmillen said, the `|local` solution wasn't working properly either, once the animations stopped working after I applied it.

It turns out that the bug happens when the parent div to the `{#key refresh}` code is set as `relative`.
Changing it, the code worked as expected.

**Comment by mattpilott** [comment]
@eduardoliron this is quite interesting, i actually use a position: relative as a css reset, i'll try setting to static and see if i can confirm your results

**Comment by Rich-Harris** [comment]
I'm going to close this since transitions _are_ working as intended (Svelte won't remove elements until transitions have completed), and `|local` is the way to get the desired outcome. I do acknowledge that some behaviour around transitions is a little counterintuitive though — it's on our list of things to revisit for Svelte 4, when we have the opportunity to make breaking changes.

**Comment by power-f-GOD** [comment]
For some reason `|local` did not work for me, and even when I used/tried it, the smooth enter and exit transitions were lost (in my case, a Modal; it just, sort of, 'blips'). 💔

If you care about keeping your (smooth) transition, I have a hack which I've tried and used. Though not the best of solutions, but it worked and it works.

The root **__layout.svelte**
```
<script lang="ts">
  afterNavigate(() => {
    if (document?.querySelectorAll('body .App').length > 1) {
      document?.body?.removeChild(document?.querySelector('body .App')!)
    }
  })
</script>

<main class='.App'>
  Your App.
</main>
```

Welcome. ⚡️

**Comment by janwillemtulp** [comment]
> I'm going to close this since transitions _are_ working as intended (Svelte won't remove elements until transitions have completed), and `|local` is the way to get the desired outcome. I do acknowledge that some behaviour around transitions is a little counterintuitive though — it's on our list of things to revisit for Svelte 4, when we have the opportunity to make breaking changes.

Why is `|local` not the default behaviour and then you have to set the opposite, if desired (wait until something else is complete)?

**Comment by johnnysprinkles** [comment]
Could we add a compile option for `"transitionsLocalByDefault"` to https://svelte.dev/docs#compile-time-svelte-compile and extend the transition grammar to include a `|global` modifier?

**Comment by hanssens** [comment]
I agree with @janwillemtulp's suggestion: this should be the default. 

Because this issue is closed, question at @Rich-Harris regarding:

> _it's on our list of things to revisit for Svelte 4, when we have the opportunity to make breaking changes._

Is there by any chance a way to track or follow this topic, like is there a new issue registered? Or can we have a glimpse at  considerations for Svelte v-next somewhere?

**Comment by cubedhuang** [comment]
![image](https://user-images.githubusercontent.com/27079662/208760882-397730b1-2a7c-4f3e-be9e-3945c395e7dc.png)
One reason using `|local` may not work is that for me, I have both an `if` block and a `key` block, and using local now only transitions changes on the key block instead of both the if and the key

**Comment by FeldrinH** [comment]
> Would be nice to get warnings without using local, and to explicitly say `|out` or `|wide`

I think this is the case in Svelte 4, which was released about a month ago. (https://svelte.dev/docs/v4-migration-guide#transitions-are-local-by-default)

**Comment by ollyde** [comment]
@FeldrinH looks like I'm still on 1?

Vite is quiet behind then.

<img width="174" alt="Screenshot 2023-08-22 at 20 27 03" src="https://github.com/sveltejs/kit/assets/6940726/4cb5e396-5557-438c-87a8-b015d6f74b52">
