### ISSUE TITLE
[QUESTIONS] about the range for `route` `hydrate` `prerender` and the range for loading files.

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/kit#6364]
### Describe the problem

Why can't `route`, `hydrate`, `prerender` be added in `+layout.js`?
If you can set these properties in `svelte.config.js`, why not in `+layout.js`?

Similarly, I am curious about the `"$lib/"`.
And shouldn't it be possible to reference any superdirectory in `routes`, conveniently?
Like in Advenced layout you can refer to higher directories, by their name via at (`@`).
For example, something like this:
`./@/`, `./@(app)/`, `./@item/` or `./@[id]/`.

This is more of a question than a need. It puzzles me, and I'd like to know if it's completely unnecessary or not supported for some other reason (e.g., it didn't occur to anyone).

### Describe the proposed solution

Simply support `route`, `hydrate`, `prerender` in `+layout.js`.

Adding support for importing from such url:
`./@/`, `./@(app)/`, `./@item/` or `./@[id]/`.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
I don't understand what you mean by the `@` question; you can import code from upper directories if you want.

Regarding the options question: This will be done in #6197

**Comment by dummdidumm** [comment]
Ok I see. This would introduce needless complexity and would mean restarting your dev server all the time since we would have to
- parse the route folder on each change
- somehow create aliases from it which we hand to vite
- vite would restart since that's a config change

It would also create conflicts because as soon as you have two folders with the same name in different parts of your router tree.

So no, we won't do this.

**Comment by lukaszpolowczyk** [comment]
Ok. I get it.
