### ISSUE TITLE
Documentation shows "locals" available in +layout.js

### ISSUE THREAD

**Issue by danawoodman** [sveltejs/kit#6400]
### Describe the bug

[This example](https://kit.svelte.dev/docs/load#redirects) in the Kit docs shows a `LayoutLoad` `load` method using `locals` even though `locals` are not available outside `hooks` and server pages/layouts.

The example could mislead people into thinking it is available (did for me until look at [app-locals](https://kit.svelte.dev/docs/types#app-locals))

### Reproduction

see docs

### Logs

```shell
n/a
```

### System Info

```shell
n/a
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
There's a couple of things going on here — firstly the type is wrong, it should be `LayoutServerLoad`. Fixed in #6409.

The other issue is that diff blocks aren't showing the filename, even though it's there in the markdown: https://github.com/sveltejs/kit/blob/29bc3d73c0bd472410158285305c1987bfb5f8a6/documentation/docs/05-load.md?plain=1#L330-L333

**Comment by danawoodman** [comment]
Thanks for the quick action @Rich-Harris!
