### ISSUE TITLE
Reorder "Library skeleton project" to 3rd in the list for `create-svelte`

### ISSUE THREAD

**Issue by FractalHQ** [sveltejs/kit#6470]
### Describe the problem

I've been seeing reports of users mistakenly choosing "Library skeleton project" because it's 2nd on the list in `create-svelte`, resulting in confusion.  Moving it to be 3rd should help people avoid this mistake.

### Describe the proposed solution

Changing the template name from `libskeleton` to `skeletonlib` _sorts_ it out 😉

### Importance

nice to have

### Additional Information

Happy to submit the PR from my fork where I tested it.  If so- would the PR warrant a changelog?

**Comment by Conduitry** [comment]
I don't have strong thoughts about the change itself - but, yes, any change that results in user-visible changes should have a changeset, because it's the presence of the changset that marks a package as needing to have a new release cut. Otherwise the change would just sit unreleased until the next change with a changeset happened.

**Comment by benmccann** [comment]
The order was bugging me quite a bit. I personally would find a PR very welcomed
