### ISSUE TITLE
A page marked not to hydrate shouldn't need to prefetch `__data.js`

### ISSUE THREAD

**Issue by TranscendentalRide** [sveltejs/kit#6576]
### Describe the bug

Signal that a page should not hydrate `export let csr = false` and then hover on the link, `__data.js` is called. Yet the page doesn't have any JS so the call seems superfluous and unnecessary.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-p7qmhh?file=src%2Froutes%2Ftodos%2F%2Bpage.js&terminal=dev

- Click HOME
- Click TODO

Notice "fail" message. Notice `+page.js` exports `csr = false` and so this page should have no JS. Data from server should load.

- Reload TODO 

page using "Refresh", fail does not appear because data does work. Only __data.js fails and it shouldn't matter if there is no hydration / JS.

### System Info

```shell
MacOS 12.5, Chrome 104, SvelteKit 1.0.0-next.465
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
This is expected behaviour — `csr` means that the page doesn't hydrate if you visit it directly. It _doesn't_ mean that you can't navigate to it using the client-side router, which involves loading `__data`.

If you want a full page reload when visiting a route, that's not currently possible without marking all inbound links with `data-sveltekit-reload`, but there's a separate issue for that: https://github.com/sveltejs/kit/issues/5699
