### ISSUE TITLE
Styling not reset when navigating to a page that uses a different layout

### ISSUE THREAD

**Issue by louishuddleston** [sveltejs/kit#6706]
### Describe the bug

When navigating to a page that resets the layout using `+page@.svelte` the styling is not reset if using the back/forward buttons or `<a>`.
If you navigate to the page directly it is reset.

### Reproduction

[stackblitz reproduction](https://stackblitz.com/edit/sveltejs-kit-template-default-8xzmev?file=src%2Froutes%2F(app)%2F%2Blayout.svelte,src%2Froutes%2F%2Blayout.svelte&terminal=dev)

Click on "visit test layout reset page"

You will see that the styles are carried over from the first layout

If you refresh the page then all the styling is gone

### System Info

```shell
fork of https://node.new/sveltekit running in:
Brave Version 1.43.89  Chromium: 105.0.5195.102 (Official Build)  (arm64)
and
Firefox 104.0.2 (64-bit)

System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.72 
    @sveltejs/kit: next => 1.0.0-next.480 
    svelte: ^3.46.0 => 3.50.1 
    vite: ^3.1.0 => 3.1.0
```

### Severity

serious, but I can work around it

**Comment by Rich-Harris** [comment]
This is just the nature of how `.css` imports work (particularly in Vite) — they are applied to the document when they are imported, and never removed. Even if it made sense to couple `.css` application to component lifecycles, it would be an extremely complex problem: we'd need to analyse the module graph to discover which components imported which styles, then observe which components were rendered at any given moment (including inside `{#if ...}` blocks, and including `<svelte:component>` etc), and somehow use that to add and remove stylesheets on state changes (which would be bad for performance, since it would cause more frequently updates to the CSSOM).

A workaround would be to use component-scoped styles more widely, or to namespace your global styles like so...

```diff
// src/app.css
-p {
+.default-layout p {
  color: green;
]
```

...and apply the same thing to your layout:

```diff
// src/routes/(app)/+layout.svelte
-<main>
+<main class="default-layout">
```

Closing as this is basically unsolvable.
