### ISSUE TITLE
Clear Kit path to `config.server.fs.allow` in `vite.config.js` for dev server

### ISSUE THREAD

**Issue by Tal500** [sveltejs/kit#6723]
### Describe the problem

For security, Vite doesn't allow JS to load any script in any path, so this results with the disability to run Kit on dev mode.
To fix this for the user, in `create-svelte`, the initial user Vite configuration code is set to the following:
https://github.com/sveltejs/kit/blob/8748873fb4cb8078bf7842548d66b0406616fb39/packages/create-svelte/templates/default/vite.config.js#L4-L13

The problem is that it's not safe at all to assume that Kit is located in this path! Indeed, when I used `pnpm link`, it broke the dev mode.

### Describe the proposed solution

Simple - have somewhere in the Kit API some function that returns the path for the package!

This function can be implemented easily by using `import.meta.url` inside the Kit-internal JS file.

### Alternatives considered

I used the following complicated configuration in my code, to detect the real Kit path, using the external package [import-meta-resolve](https://www.npmjs.com/package/import-meta-resolve):

```js
import { fileURLToPath } from 'url';
import { resolve as importResolve } from 'import-meta-resolve';
import { sveltekit } from '@sveltejs/kit/vite';

const kitIndexPath = await importResolve('@sveltejs/kit', import.meta.url);
const kitWord = '/kit';
const kitPathUnnormalized = kitIndexPath.slice(0, kitIndexPath.lastIndexOf(kitWord) + kitWord.length);
const filePrefix = 'file:///';
const kitPath = kitPathUnnormalized.startsWith(filePrefix) ? kitPathUnnormalized.slice(filePrefix.length) : kitPathUnnormalized;

/** @type {import('vite').UserConfig} */
const config = {
	plugins: [
		sveltekit(),
	],

	server: {
		fs: {
			allow: [kitPath]
		}
	}
};

export default config;
```

### Importance

would make my life easier

**Comment by Conduitry** [comment]
`path.resolve('../../../kit')` is only used for running tests (where we _can_ assume where Kit will be located, because the whole monorepo is checked out), and it's not present in the templates you get when you actually run `create-svelte`.

If someone's symlinking a local copy of SvelteKit into their repo for testing something, they can presumably also just hack in a `server.fs.allow` value specific for their particular setup - it doesn't need to be super flexible, because this isn't something they'd need to check in. This feels like a niche case to me.

**Comment by Rich-Harris** [comment]
Yeah, I'm not sure there's anything to do here. Everything is working as expected. I don't see a good reason to hack the `kit` location into `server.fs.allow` but not other linked packages.
