### ISSUE TITLE
404 has the message "Internal Error"

### ISSUE THREAD

**Issue by kevinrenskers** [sveltejs/kit#6793]
### Describe the bug

When you hit a route that doesn't exist, the error message is "Internal Error" instead of something like "Page not found". Pretty sure this used to be something like the latter though.

"Internal Error" is not something we should be showing to our users when it's just a simple 404 error.

### Reproduction

No custom code needed at all. Just create a new project `npm create svelte@latest sk-404-bug`, run it, and enter an unknown route in your browser.

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.21 GB / 32.00 GB
    Shell: 3.5.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 16.17.0 - ~/Library/pnpm/node
    npm: 8.15.0 - ~/Library/pnpm/npm
  Browsers:
    Safari: 16.0
  npmPackages:
    @sveltejs/adapter-auto: next => 1.0.0-next.73
    @sveltejs/kit: next => 1.0.0-next.481
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.0 => 3.1.0
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
This is the expected behavior. All unexpected errors (and 404 is such an unexpected one) are shown as "Internal Error" by default. You need to implement the `handleError` hooks on the server and client and return the desired error shape from it. In your case it's probably enough to do

```js
// hooks.server.js
export function handleError({error}) {
  return { message: error.message };
}
```
```js
// hooks.client.js
export function handleError({error}) {
  return { message: error.message };
}
```

It's done this way to protect your app from accidentally showing sensitive data that could appear from an unexpected error.

The docs have more info on this: https://kit.svelte.dev/docs/hooks#shared-hooks-handleerror

**Comment by kevinrenskers** [comment]
It seems that the default behavior is kinda weird, forcing the normal happy path usage to implement two hooks or you get nonsensical error messages for even 404 pages. Why are those hooks not simply the default, and people can override it if needed?

**Comment by dummdidumm** [comment]
Because your message could contain sensitive data like "an error in occurred using <secret api key>". Also, it's not ensured that the `error` passed in is actually an `Error` object - anything can be thrown.

**Comment by kevinrenskers** [comment]
I get all that, but even without any custom code at all, just creating a new project and hitting a 404, you get a pretty bad error message. That is the default behavior right now, and you have to work to fix that default behavior. I would hope the default would be better. Working with SvelteKit keeps getting a tiny bit more complex bit by bit. It's a great framework, don't get me wrong, but recent changes are not all for the better when it comes to DX (and UX) I think.

**Comment by dummdidumm** [comment]
How would a better default look like that
- shows a 404 message in case of a 404
- doesn't show any message that any error has because it could contain sensitive data
- is consistent and concise to explain?

?

**Comment by kevinrenskers** [comment]
> doesn't show any message that any error has because it could contain sensitive data

I think the default behavior shouldn't maybe be concerned with that, and leave it to developers to add logic on top of the default logic if they want to filter out stuff. But by default just show the message property in the error as-is. That would show a 404 message in case of a 404, show all other error messages, and is consistent and concise to explain. You only have to explain how to alter the default behavior, same as now. But the default would be better, in most cases most developers won't ever have to change the default, whereas now you kinda always have to override it because the default behavior is bad.

**Comment by dummdidumm** [comment]
A way to avoid `handleError` for this altogether would be to create a catch-all fallback route for this, which you can design however you like:

```html
// src/routes/[...notfound]/+page.svelte
<h1>Not found</h1>
<p>etc etc</p>
```

**Comment by dummdidumm** [comment]
When implementing this, one problem is that `App.PageError` could contain more than `{ message: string }` so any access to `$page.error`, for example in `+error.svelte` could expect more properties to be available. This makes it hard for these 404s to _not_ go through `handleError`, just returning `{ message: 'Not found' }` wouldn't be enough here.

If we were to keep calling `handleError` in the 404 case we could make it so that the error is a `Error404` defined by SvelteKit which both the fallback (`{ message: error instanceof Error404 ? 'Not Found' : 'Internal Error' }` and the user could check for.

**Comment by Rich-Harris** [comment]
I think something like this...

```js
export function handleError({ error, event, status }) {
  if (status === 500) {
    console.log(error.stack);
  }

  return {
    message: status === 404 ? 'Not Found' : 'Internal Error'
  };
}
```

...would be preferable to exposing an `Error404` class just so the user can do an `instanceof` check. You _could_ argue even that isn't really necessary, since you could also do this...

```js
export function handleError({ error, event }) {
  if (event.routeId) {
    console.log(error.stack);
  }

  return {
    message: event.routeId ? 'Internal Error' : 'Not Found'
  };
}
```

...and it would be the same except in the edge case where `handle` throws an error (but not during `resolve`).

**Comment by maximedupre** [comment]
@Rich-Harris Sorry, I'm a bit confused. Are you saying 404s should be handled with `handleError` (your last message seems to suggest that) or are you saying they shouldn't (your first message seems to suggest that)?

Thanks 🙏

**Comment by Rich-Harris** [comment]
My initial feeling was that 404s shouldn't go via `handleError`, but @dummdidumm pointed out that `$page.error` would then have the wrong shape if you declare `App.PageError`.

So we _do_ need 404s to go via `handleError`, but we also need to be able to distinguish between 404s and 500s inside `handleError`. 

The maintainers discussed this a bit this morning and we decided that for now it's better to rely on `event.routeId` being `null` in the case of a 404:

```js
export function handleError({ error, event }) {
  if (event.routeId) {
    // an unexpected error was thrown while handling this route
    console.log(error.stack);
  }

  return {
    message: event.routeId ? 'Internal Error' : 'Not Found'
  };
}
```

For the avoidance of doubt: this doesn't apply in the case of an _expected_ error...

```js
if (!item) {
  throw error(404, { message: 'not found', code: 'NOT_FOUND' });
}
```

...since these errors already have the right shape.

Aside: `App.PageError` is probably the wrong name, since the error could come from `handle` or a `+server.js` file. It should probably just be `App.Error`.

**Comment by akkie** [comment]
@Rich-Harris Do you think it makes sense to return `App.PageError` from the server side `handleError` function, to allow to return another HTTP status code than 500? I see the `handleError` as a global error handler for all the server side code. If I throw a specific error in my API that some thing could not be found, I would like that the error handler catches the error, logs it and then still returns 404 to the client. Currently I think this is not possible. I could create an issue if you think this makes sense.
