### ISSUE TITLE
Hook for cleaning up server?

### ISSUE THREAD

**Issue by IRod22** [sveltejs/kit#6841]
### Describe the problem

Issue #1538 discusses about setting up external resources, but how do you clean them up?

### Describe the proposed solution

The solution would be a `cleanup()` hook. Here is an example:
```js
import DB from '$lib/db
const db = new DB(...)
const setup = db.connect() // returns a promise

/** @type {import('@sveltejs/kit').[Handle](https://kit.svelte.dev/docs/types#sveltejs-kit-handle)} */
export const handle = async ({ event, resolve }) => {
    await setup
    event.locals.db = db
    return await resolve(event)
}

export const cleanup = async () => {
    await db.disconnect()
}
```

### Alternatives considered

Not Applicable

### Importance

i cannot use SvelteKit without it

### Additional Information

I chose the "i cannot use SvelteKit without it" because releasing resources is very important in any server application.

**Comment by Conduitry** [comment]
I'm going to assume you're specifically talking about apps using the Node adapter.

Releasing resources when what? When the server process terminates? What sorts of resources are you concerned about not being automatically released already when the process terminates?

There's also currently not a reason (other than a catastrophic runtime error) that would result in the Node process from terminating besides it getting sent something like SIGINT, so you could also listen to that signal.

**Comment by IRod22** [comment]
I meant to say that there should be a hook for releasing resources when the process is about to terminate via `Ctrl-C`. I am using the `auto` adapter that was configured by `create-svelte`.

**Comment by Conduitry** [comment]
Again: What sorts of resources?

And are you deploying a production build anywhere? If you're just using `npm run dev` (or `npm run preview`) locally, then what adapter you have selected doesn't matter, because the adapter isn't used.

What does it mean to clean up resources when you're deploying to some sort of serverless environment? I don't see how this can be cross-platform. If you are targeting just Node, then you can use `process.on('exit', ...)`, `process.on('SIGINT', ...)` etc as appropriate, but I don't see what the framework can provide.

**Comment by IRod22** [comment]
The resources are anything that need to be `await`ed to close before the process is terminated. The example code shows a database connection (it could be `knex`, `typeorm`, etc.) with the `connect` and `disconnect` methods returning promises to be awaited by the hooks.

**Comment by IRod22** [comment]
Never mind. I'm using a query builder that automatically disconnects when the process exits. :man_facepalming: However, some devs may need to manually close a database or Redis connection when the process exits (see the [`sqlite3` API](https://github.com/TryGhost/node-sqlite3/wiki/API#closecallback) for example), so this still may need discussion either way.

**Comment by Rich-Harris** [comment]
For clarity, there's no opportunity to clean up resources when a module is invalidated during development. This is an issue with Vite: https://github.com/vitejs/vite/issues/7887

**Comment by tsmigiel** [comment]
I had a similar question about a prod sveltekit app. I am using adapter-node.  I use mysql connection pools and on shutdown need to call pool.end() otherwise I have found the database can hang. The cases it would usually hang are definitely due to bugs in my app, but shutting down gracefully makes sure my bugs don't hang the database.

Before migrating to sveltekit I would wait for the http server to close before calling pool.end(). e.g.,
```process.on('SIGINT', () => server.close(() => pool.end()));```  Using adapter-node, I have not figured out a way to achieve the same thing. 

It might be safe for me to call pool.end() with out waiting for the server to close. The app is shutting down anyway, so a potential brief window of the server running but the pool being closed is probably not an issue.

**Comment by tsmigiel** [comment]
To follow up on my example. The solution I am currently using is to call process.on('exit', ...) and process.on('SIGINT', ...) to call my clean up code. I am still a beginner, so if this is a poor approach, I appreciate any feedback.

I wrote a few details here: https://stackoverflow.com/questions/74020726/how-to-shutdown-gracefully-in-sveltekit

**Comment by konstantinblaesi** [comment]
Using containerized sveltekit with adapter-node this works for me

Containerfile/Dockerfile (the end of it)
```Containerfile
COPY --from=build /app/build build
ADD entry.js /app

EXPOSE 3000
ENTRYPOINT ["node", "/app/entry.js"]
```

entry.js
```javascript
import {server as app} from "./build/index.js"

function shutdownGracefully() {
    console.log("Server doing graceful shutdown");
    app.server.close();
}

process.on("SIGINT", shutdownGracefully);
process.on("SIGTERM", shutdownGracefully);
```

podman run output after podman stop
> Listening on 0.0.0.0:3000
> Server doing graceful shutdown

**Comment by konstantinblaesi** [comment]
@IRod22 sorry to disappoint you but your development setup is not my concern, there are free and non free options and also I don't make any proposals here what the node adapter should implement or not. Make your choice / pick your poison I guess :D 

I provide a solution that is usable **today** given someone wants to put their sveltekit app in a **nodejs container**.
I use podman on wsl2 fedora at work and podman on bare metal fedora at home. Me using wsl2 is just a consequence of my IT providing this by default and me not taking the time yet to mess around trying to change it to bare metal linux which I use on all my private machines.

Podman by the way is an open source tool developed by Red Hat (now IBM) and completely free, just like most of the tooling for making containers. Docker just made containers more accesible, improved the developer experience, provides more convenience. I don't use docker anywhere today, just open tooling.

**Comment by IRod22** [comment]
> @IRod22 sorry to disappoint you but your development setup is not my concern, . . .
I know that, @konstantinblaesi. I'm just stating a fact.

**Comment by dummdidumm** [comment]
As Conduitry pointed out, there's no cross-platform way to achieve this, so using the native functionality of the environment you're in is the recommended solution. For Node that's the mentioned `process.on('SIGINT', ...)`

**Comment by t1u1** [comment]
Since this issue is one of the first results on a web search for shutdown hooks for svelte kit, let me provide an update for newer visitors:

From version 5.1.0 onwards, adapter-node gracefully shuts down the http server and also [emits a shutdown event][1] which can be listened to.

Example usage:
```typescript

    // hooks.server.ts
    import type { ServerInit } from "@sveltejs/kit";
    
    export const init: ServerInit = async () => {
      console.info("Server created, registering shutdown hooks")
    
      process.on('sveltekit:shutdown', async (reason) => {
        console.info("SvelteKit has shutdown because of", reason)

        // Your custom logic for closing app specific resources
        closeDB()
        console.info("DB closed")
      });
    };

```

  [1]: https://svelte.dev/blog/whats-new-in-svelte-july-2024#What's-new-in-SvelteKit

**Comment by aubergene** [comment]
Just comment to hopefully help anyone else who ends up here. I'm connecting to `pg-listen` and had initially put the `subscriber.connect()` call in `init` but it turns out that running it within `if (!building)` worked correctly for my needs

https://svelte.dev/docs/kit/building-your-app#During-the-build

**Comment by hatemjaber** [comment]
I could not for the life of me get the `sveltekit:shutdown` to work, I had to do this instead:

```svelte
// hooks.server.ts
export const init: ServerInit = async () => {
    console.log("initializing");

    const gracefulShutdown = async () => {
        console.log('Shutting down gracefully...');
        // wait for a second before closing the server (not necessary, just for testing)
        await sleep(1000);
        client.close();
        process.exit(0);
    };

    process.on('SIGINT', gracefulShutdown);
    process.on('SIGTERM', gracefulShutdown);
}
```

I am curious if there is a working example that shows how to do this with an official sveltekit way... thank you in advance!
