### ISSUE TITLE
Invalidate doesn't work while prefetching

### ISSUE THREAD

**Issue by dummdidumm** [sveltejs/kit#6902]
### Describe the bug

Calling `invalidate` or `invalidateAll` doesn't behave as expected when a prefetch is happening. `load_route` returns early in this case, swallowing the `invalidate` calls.

### Reproduction

This thread has more info: https://discord.com/channels/457912077277855764/1013838400601731152

### System Info

```shell
Irrelevant
```

### Severity

annoyance

### Additional Information

In general I think we need to have some more stateful logic around invalidation - how they interact with redirects etc.

**Comment by ollema** [comment]
Figured I could post this here as well for those without discord:

---

I found how to more reliably trigger the issue now and I was able to record it with some timestamps.

In this video:

* I first demo the expected behaviour when a user signs in or out

* Then I attempt to *not* trigger the `load` function in `+layout.server.svelte` by
  1. Signing in
  2. Waiting a couple of seconds to show that it should not be a matter of `load` being  triggered too often
  3. Clicking `about`
  4. Quickly clicking `sign out`
  5. After a couple of attempts, I was able to reproduce it on video! You can see that:

```
21:34:31 signing out - calling `await invalidateAll()` - should trigger `load`
21:34:40 signing out - calling `await invalidateAll()` - should trigger `load`
```
are both printed before the:
```
21:34:40 load triggered
```

**Here's the interesting part:**

I believe that this issue is related to prefetching!

My `about` page is very simple:
```html
<main>about sersophane</main>

<footer />
```
in my `Nav.svelte` component that is used in my root `+layout.svelte` I have:
```html
...
<a data-sveltekit-prefetch href="/about" class:selected={section === 'about'}>about</a>
...
```

I found that if I remove `data-sveltekit-prefetch` I can no longer trigger it! (or at least it is much much more rare, it has not happened to me yet).

https://user-images.githubusercontent.com/31876997/191234146-36bb6419-c19b-439a-a635-78a02d7978a0.mov
