### ISSUE TITLE
Layout images break on cold visits to deeply nested pages

### ISSUE THREAD

**Issue by EvAvKein** [sveltejs/kit#6951]
### Describe the bug

When cold-visiting a page at least 2 dirs deeper than root, the app sends the GET requests for images in (+)layouts to the wrong addresses: The request paths includes all parent dirs.

For example:
- If visiting localhost:3000/first/second/ , the request path for layout images is /first/[image.png]
- If visiting localhost:3000/first/second/third/ , the request path for layout images is /first/second/[image.png]

The src attribute remains as ./[image.png] in all cases.

(This issue is happening in both HMR and deployment)

### Reproduction

https://github.com/EvAvKein/Repro-SvelteKit-LayoutImageRequests

The repro pages includes text guidance for reproducing the issue, with commentary and demonstration of things I tested to narrow it down

### Logs

```shell
Not found: /firstNested/secondNested/favicon.png
Error: Not found: /firstNested/secondNested/favicon.png
    at resolve (file:///C:/Users/conta/Repro-SvelteKit-LayoutImageRequests/node_modules/@sveltejs/kit/src/runtime/server/index.js:256:13)
    at resolve (file:///C:/Users/conta/Repro-SvelteKit-LayoutImageRequests/node_modules/@sveltejs/kit/src/runtime/server/index.js:287:5)
    at Object.handle (file:///C:/Users/conta/Repro-SvelteKit-LayoutImageRequests/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:336:66)
    at respond (file:///C:/Users/conta/Repro-SvelteKit-LayoutImageRequests/node_modules/@sveltejs/kit/src/runtime/server/index.js:284:40)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async file:///C:/Users/conta/Repro-SvelteKit-LayoutImageRequests/node_modules/@sveltejs/kit/src/exports/vite/dev/index.js:406:22
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
    Memory: 3.03 GB / 7.88 GB
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (105.0.1343.42)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @sveltejs/adapter-auto: 1.0.0-next.79 => 1.0.0-next.79
    @sveltejs/kit: 1.0.0-next.493 => 1.0.0-next.493
    svelte: 3.50.1 => 3.50.1
    vite: 3.1.3 => 3.1.3
```

### Severity

blocking an upgrade

### Additional Information

Apologies in advance if it's a Vite issue, I'm completely unequipped to determine that on my own

**Comment by Conduitry** [comment]
I haven't tried running your repo, but from looking at it, it sounds like this is the expected behavior `<img src="./favicon.png" alt="The Svelte logo"/>` means an image tag with precisely that attribute is inserted into the DOM. It doesn't mean something relative to that layer of layouts, and the framework doesn't update the `src` of the image to point somewhere else.

**Comment by EvAvKein** [comment]
@Conduitry Ah, then I have no idea what's causing this bug... but running that repo shows that something's definitely broken 😕

**Comment by Conduitry** [comment]
There's not a bug. You're inserting `<img src="./favicon.png" alt="The Svelte logo"/>`, which is getting inserted as-is into the document, and the browser is attempting to resolve that URL relative to the current URL. Again, the framework doesn't try to change these paths for you. They get resolved relative to the current URL, like any other URL would - not relative to the path of the layout they're in. For the first two layers, that's relative to `/` and `/firstNested`, which resolves to `/favicon.png` and the image loads. Any deeper, and `./favicon.png` resolves to somewhere else.

The browser, apparently, doesn't re-resolve relative image references when there's a `history.pushState()` that changes the page's URL once it's already running. That's why the initial two images remain visible as you click to deeper levels, at least until you refresh.

If you don't want to deal with the complications of relative links (especially ones in layouts), I would suggest using absolute paths, perhaps based on https://kit.svelte.dev/docs/modules#$app-paths if that would help.
