### ISSUE TITLE
Pretty URL's with the static adapter?

### ISSUE THREAD

**Issue by johnknoop** [sveltejs/kit#700]
This might be a silly question, but is it possible to get nice looking URL's when using the static adapter? The reason I'm asking is that I had a look at the NYT corona tracker that was mentioned in a blog post, and found that the URL's are ending with ".html".

Thanks

**Comment by Conduitry** [comment]
The static adapter will by default create directories with the route names and output the page to an `index.html` file in that directory.

**Comment by Rich-Harris** [comment]
> found that the URL's are ending with ".html".

That's just because of how our CMS works — if you look at any article (e.g. https://www.nytimes.com/2021/03/24/movies/bob-odenkirk-nobody.html) it will end with `.html`. Never really understood why but it is what it is. We actually have to compensate for it in our code base so that the router knows how to understand the non-pretty URLs:

![image](https://user-images.githubusercontent.com/1162160/112643572-e22fa800-8e1a-11eb-9aa3-e02a45103d74.png)

**Comment by johnknoop** [comment]
Thanks!
