### ISSUE TITLE
Named layouts aren't breaking out of the parent layout

### ISSUE THREAD

**Issue by asmajlovicmars** [sveltejs/kit#7006]
### Describe the bug

Named layouts aren't breaking from the main layout. I think this was working fine recently, but just saw it now either not working or I'm doing something wrong. 

### Reproduction

https://sveltejs-kit-template-default-mymbax--5173.local.webcontainer.io/ab
https://sveltejs-kit-template-default-mymbax--5173.local.webcontainer.io/cd

https://stackblitz.com/edit/sveltejs-kit-template-default-mymbax?file=src/routes/(c)/cd/+page@(c).svelte

<img width="468" alt="Sveltejs_-_Kit_Template_Default__forked__-_StackBlitz_🔊" src="https://user-images.githubusercontent.com/29715259/192078810-85785265-cc8a-47b9-b61a-dc520e6ffc0f.png">

### System Info

```shell
Mac, Chrome
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
What are you expecting to see at `/ab` and `/cd` of your repro?

For the record - you can no longer break out of the top level layout. `+page@` without a layout or group reference after the `@` will still place you within the top layout, not directly within `app.html` - in case that's what you were expecting to see.

**Comment by asmajlovicmars** [comment]
Thank you @Conduitry for a response.

My expectation was to somehow break out from a visual part of the top level layout, like layout reset used to work if I remember well. 

Our app has a number of topical areas, which all look and feel different than the main app, and this can be handled by groups layouts, but it seemed like a shortcut to simply reset the main layout with the Nav etc, and just serve a (group) layout. I can close this if you think it's not worth exploring further?

**Comment by Conduitry** [comment]
There was quite a bit of confusing behavior and bugs that were resulting from being able to completely break out of the top-level layout, so that's no longer possible. If you don't want the nav bar on certain pages, then either it can't be in your root `+layout.svelte` (or else you need to have it conditionally display, like with `{#if}` and `$page.routeId`). This is behaving as intended, and is one of the things layout groups (https://kit.svelte.dev/docs/advanced-routing#advanced-layouts-group) were designed for.
