### ISSUE TITLE
Smarter private variable check

### ISSUE THREAD

**Issue by smblee** [sveltejs/kit#7019]
### Describe the problem

Trying to create an isomorphic client module which uses both `private` key in SSR context (using `if (!browser)`) and `public` key in CSR. 

This currently fails in CSR context, since the compiler seems to naively check for illegal import strings 
https://github.com/sveltejs/kit/blob/55493cb64f420e413b91154cef6ad54a03b96d1f/packages/kit/src/exports/vite/graph_analysis/index.js#L9
https://github.com/sveltejs/kit/blob/55493cb64f420e413b91154cef6ad54a03b96d1f/packages/kit/src/exports/vite/graph_analysis/index.js#L129

`Cannot import $env/static/private into public-facing code:`

Is it possible to have this behavior be a bit smarter so that if the secret import is encapsulated in `if (!browser)` check, the compiler doesn't complain?

### Describe the proposed solution

Modify secret detection to allow secret variable in CSR context with `if (!browser)` check so the following code doesn't complain

`isomorphicClient.ts`
```js
export method() {
  if (!browser) {
     const private = await import('$env/static/private')).SOME_PRIVATE_KEY
  }
}
```

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
This is a slippery slope. Right now the feature works by extracting the module graph from the file statically. With this, the module would have to run before knowing if something ends up in the module, which I'm not sure how feasible (or possible at all) this is.

**Comment by tcc-sejohnson** [comment]
My guess (as the author of that module) is that this is practically impossible, and I don't actually know if it's even safe or desirable. Just because you guard the import with `!browser` doesn't mean that the compile steps won't statically replace the secret into the file and send it to the browser. For example:

```ts
<script>
  import { SECRET } from '$env/static/private';
  import { browser } from '$app/environment';
</script>

<p>{browser ? 'Ha, no secret' : SECRET}</p>
```

Wouldn't display the secret in the browser, but almost _certainly_ would statically replace the value and include it in the files sent to the browser, completely defeating the point of private modules. If you need to conditionally use a private variable, do it in a server-side load. 

I'll wait for @Rich-Harris to comment before closing, as he co-authored this feature and tends to have some pretty good ideas that we don't think of. 😉

**Comment by smblee** [comment]
any thoughts on this? 👀

**Comment by Rich-Harris** [comment]
Unfortunately I don't see a way that this is possible, so I'll close this. Though to be totally honest I'm also not convinced that it's a good idea; it muddies the waters somewhat. 'You can't import private stuff into public code' is a simple thing to teach and remember; 'You can import private stuff into public code as long as it's only used in a block of code that gets dead-code-eliminated when bundling for the client' is not
