### ISSUE TITLE
Replay events captured before hydration

### ISSUE THREAD

**Issue by jeremyjacob** [sveltejs/kit#7025]
### Describe the problem

During/prior to hydration, which in my experience can be around a second, there is no JS/reactivity—a caveat of SSR without something like Quik's resumability. Meaning all user inputs that would otherwise be handled by JS get blackholed. This creates a subpar UX where clicking a button too soon after page load just does nothing, forcing the user to click a second time.

### Describe the proposed solution

Perhaps a small bit of script could included in the static HTML that listens to events and then later replays them once Svelte has hydrated the page.

Here's an example I stuck in a script tag in `app.html`:
```js
let events = []
const listener = (event) => events.push(event);
const eventTypes = ['click', 'pointerdown', 'pointerup', 'mouseenter', 'mouseleave', 'keydown', 'keyup', 'keypress', 'focus', 'blur']

eventTypes.forEach((l) => window.addEventListener(l, listener))
// This event was deprecated so it must be manually emitted in an onMount in +layout.svelte
window.addEventListener('sveltekit:start', () => {
	events.forEach(c => c.target.dispatchEvent(c))
	events = []
	eventTypes.forEach((l) => window.removeEventListener(l, listener))
})
```

Perhaps there are some caveats to this method which I would love to hear e.g. isTrusted: false

### Alternatives considered

It's really not that much code to throw in the app.html, so I'm not sure how badly this needs to be in the framework itself.

### Importance

nice to have

**Comment by Rich-Harris** [comment]
I don't think we should implement this at the framework level, partly because of the caveats around `isTrusted` but mostly because it's often the case that you don't _want_ events to be replayed (think of e.g. a 'Purchase' button that the user clicks multiple times because of no initial reaction). I think it's probably better to disable the parts of the UI that need to be disabled (e.g. `<button disabled={!browser}>`) or, better still, use progressive enhancement so that they work before JS loads
