### ISSUE TITLE
Static and Prerendering -- Node Server required ?

### ISSUE THREAD

**Issue by dngo10** [sveltejs/kit#708]
Hi everyone, first of all, sorry that I'm quite new to web development.

Use case: 

I want to use SvelteKit for website with dynamic pages (calling information from server, pages content changed based on user)

My purpose is to make a front-end website that runs entirely on a host (like Hostinger, for example), then call a rest-api server to update information.

Problem:

It said in the [doc](https://kit.svelte.dev/docs#adapters):

1. [static-adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-static#adapter-static) - for prerendering your entire site as a collection of static files.

2. [when not to prerender](https://kit.svelte.dev/docs#prerendering-when-not-to-prerender) - "The basic rule is this: for a page to be prerenderable, any two users hitting the same page of your app must get the same content from the server. In other words, any app that involves user sessions or authentication is not a candidate for the static adapter."

I interpret it as if _I want to run a SvelteKit website with dynamic pages, I have to run it on a node server_  , don't I?

**Comment by Conduitry** [comment]
You will either have to use a Node server, or use an adapter for one of the serverless platforms out there. SSR requires javascript running on the server in some capacity. There's an open issue for disabling SSR so that you can an entirely client-side application.

GitHub issues aren't the right place for support questions like this. Please ask on StackOverflow or in our [Discord chat room](https://svelte.dev/chat).
