### ISSUE TITLE
Option to disable special handling of `url.startsWith(event.url.origin)` in provided fetch

### ISSUE THREAD

**Issue by endigma** [sveltejs/kit#7109]
### Describe the problem

SvelteKit's `fetch` gives special treatment to request URLs beginning with `event.url.origin`, this causes problems when paired with a reverse proxy that uses path prefixes to separate frontend/backend. 

example:
`/api/* -> localhost:4000`
`* -> localhost:4001`

SvelteKit will turn a request to `http://proxy/api/foo` into `/api/foo` because of this transformation code. This causes rather difficult to debug errors where under certain failure circumstances (unmatched path param is my example) SvelteKit's fetch manipulation causes unrelated fetch queries to fail.

This is not reproducible with external fetch implementation (sidestepping the provided one) or when using a request URL not beginning with `event.url.origin`.

This isn't really a bug because it seems to be the intended behavior for Svelte to rewrite these URLs (to avoid hairpinning for internal API paths?), however being able to turn it off would be great.

### Describe the proposed solution

I'd like to see SvelteKit have an option in `svelte.config.js` to disable special treatment of these request URLs.

### Importance

i cannot use SvelteKit without it

**Comment by Conduitry** [comment]
You should be able to deal with this with a check in the beginning of your `handle` hook that conditionally sends out the request somewhere else if, say, `event.url.pathname.startsWith('/api/')`. I'm doing something similar in project of my own.

Alternatively, you should also be able to write a `handleFetch` function that conditionally uses `globalThis.fetch` instead of the `fetch` implementation that's passed to it.

**Comment by endigma** [comment]
I already have a reverse proxy, doing extra work shouldn't be necessary to *prevent* SvelteKit from messing with the request parameters

**Comment by Rich-Harris** [comment]
As @Conduitry says, this is what `handleFetch` is for

**Comment by endigma** [comment]
How is circumventing non-configurable request manipulation by kit's internal fetch logic what `handleFetch` is for? 

SvelteKit is changing my `fetch` requests to be incorrect and error-causing without any way to affect it except by circumventing kit's implementation entirely. 

Not every user of kit uses kit as their backend, manipulating requests in this way is likely favorable for those that do, but it is causing breaking bugs for those that do not. There shouldn't be a "workaround" for using a non-kit backend.

**Comment by Rich-Harris** [comment]
It _is_ configurable. The means by which you configure it is `handleFetch`.

**Comment by endigma** [comment]
Shouldn't the configuration to be to *enable* messing with the request rather than *disable* messing with the request?

**Comment by Rich-Harris** [comment]
Look, this issue has been closed as wontfix, and it's only because I happened to still have the tab open that I noticed you're still commenting on it. We explicitly considered the case you're dealing with and `handleFetch` is the API we settled on. The 'messing with the request' happens for many very good reasons, and I'm not going to waste time enumerating them here; you can read the docs if you care.
