### ISSUE TITLE
Versioned documentation website

### ISSUE THREAD

**Issue by wvhulle** [sveltejs/kit#7143]
### Describe the problem

Looking for documentation for the specific version of SvelteKit I am using, I sometimes stumble against documentation for newer versions of SvelteKit. These newer versions are incompatible with what I am using and it is not possible to update everything every week.

### Describe the proposed solution

A toggle in the corner of the sveltekit documentation website to switch between sveltekit versions.

### Alternatives considered

Looking in the web archive.
Checking the archive of the git repository.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
This has come up before in #6023. The idea is to not continue to be making breaking changes all of the time (and indeed there have only been one or two small ones in the past month since the 1.0 RC was announced). As described in that other issue, we'll think about this when it comes time for 1.x -> 2.x, but for now, looking at Git is the suggested way to deal with this.
