### ISSUE TITLE
On POST request produces 500 Unexpected token 'C', "Cross-site"... is not valid JSON in dev 

### ISSUE THREAD

**Issue by d-adamkiewicz** [sveltejs/kit#7157]
### Describe the bug

Similar to https://github.com/sveltejs/kit/issues/6795
Run in dev mode on public site with reverse-proxy/docker container
Command:
```bash
npx vite dev "--host" "172.18.0.2" "--port" "3000"
```
or
```bash
pnpm vite dev "--host" "172.18.0.2" "--port" "3000" 
```
On POST/Form request produces on page
```
500
Unexpected token 'C', "Cross-site"... is not valid JSON
SyntaxError: Unexpected token 'C', "Cross-site"... is not valid JSON
```

While the following (using `adapter-node`)
```bash
npm run build
node ./build
```
On POST request works as expected ie sets cookie and redirect to another route

### Reproduction

```bash
pnpm vite dev "--host" "172.18.0.2" "--port" "3000" 
```

### System Info

```shell
System:
    OS: Linux 5.4 Alpine Linux
    CPU: (1) x64 Intel Xeon Processor (Skylake, IBRS)
    Memory: 1.44 GB / 1.89 GB
    Container: Yes
    Shell: 1.35.0 - /bin/ash
  Binaries:
    Node: 18.2.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.10.0 - /usr/bin/npm
  npmPackages:
    @sveltejs/adapter-node: ^1.0.0-next.96 => 1.0.0-next.96
    @sveltejs/kit: next => 1.0.0-next.507
    svelte: ^3.44.0 => 3.50.1
    vite: ^3.1.0 => 3.1.4
```

### Severity

annoyance

**Comment by Conduitry** [comment]
I could have sworn there was an issue for this somewhere, but I can't find it right now. Basically, you're running into the built-in CSRF protection. Because of the proxy, the `Origin` header on the requests isn't what SvelteKit is expected it to be. In production, you can control this at runtime with the `ORIGIN` environment variable (https://github.com/sveltejs/kit/tree/master/packages/adapter-node#origin-protocol_header-and-host_header), but (and this is the thing I thought there was an issue for) there's no similar feature for dev mode.

**Comment by Conduitry** [comment]
Ah, found it. Effectively a duplicate of #6676.
