### ISSUE TITLE
Allow custom response from handleError hook

### ISSUE THREAD

**Issue by Madd0g** [sveltejs/kit#7212]
### Describe the problem

Unless caught, certain errors can only be handled in `handleError` in `hooks.server.js`.

But the only documented way of handling the error is to return `{ message }` from handleError that ends up in `+error.svelte`.

Since the recent changes, `+error.svelte` cannot have a `load()` function.

I need a way of returning a JSON response based on the caught error.

### Describe the proposed solution

Allow more customizable response from `handleError`, or a way of adding server-side logic to `+error.svelte`

### Importance

i cannot use SvelteKit without it

### Additional Information

[Discussion I created about this](https://github.com/sveltejs/kit/discussions/7196)

**Comment by dummdidumm** [comment]
Please provide more info about your use case and why you would want a JSON response instead of the error page. Btw you can return more than just a message, the object can be of any shape you like (it just needs the message property at minimum).

**Comment by Madd0g** [comment]
I have code using `fetch` from routes to get the resulting HTML. I case of an error, I don't want the HTML of the error page, but still want the error object.

In case of an *unexpected error*, there's no other "global" place to handle the error other than the hooks and +error page. I think it makes sense to have more control there.

**Comment by dummdidumm** [comment]
Why do you fetch a route to get the HTML instead of navigating to that page?

**Comment by Madd0g** [comment]
It's a feature of the app I'm building.

I'm asking for this feature because I cannot achieve what I want and feel like it makes sense to have more control in the hook.

**Comment by dummdidumm** [comment]
The hook is integrated with endpoints and pages. It returns the error in a format that both can use for showing a error page or a error json response. It isn't intended to somehow return something completely different. I'm not sure that level of control is desired.

"It's a feature of the app" is not very detailed - what I'm really trying to ask is if there's a different way to achieve what you want, without the HTML rendering. And since this sounds like an edge case, I'm wondering if it wouldn't be better to just do a workaround, like rendering the error as JSON hidden into the error page, so you can retrieve it from there and then continue.

**Comment by dummdidumm** [comment]
Closing because a workaround exists and `handleError` is designed to be tightly integrated with the error shape of `App.Error`
