### ISSUE TITLE
Prefix all route IDs with `/`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#7332]
### Describe the problem

I don't recall if there was a reason we decided that the `routeId` for `src/routes/foo/+page.svelte` should be `foo` instead of `/foo`, but I think it was a mistake. On a number of occasions I've found myself doing things like `if (routeId)` and getting caught out because it can sometimes be the empty string.

Since we expose `routeId` via `event`, app developers will inevitably run into the same issue.

### Describe the proposed solution

It would be safer, and arguably more intuitive, if route IDs were always prefixed with `/`. 

### Alternatives considered

The problem of course is that this would be a breaking change, and we can't detect people doing `routeId === 'foo'`. For the people currently using `routeId` this would be annoying.

The question is whether causing breaking change for that population is more costly than reaching 1.0 with a known design flaw.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
On way to ease this for users would be to detect that `routeId` is accessed and print a warning once per dev session that this was changed.

**Comment by Conduitry** [comment]
I'm in favor of this change. The path portion of URLs always including the leading `/` is something everyone's fairly used to by now, and the empty string falsy exception is something that's nice to be able to avoid.

I suppose I'm ambivalent about the dev time warning, because for each person it sounds like that will either be (a) something they never look at, or (b) something that irritates them when it's printed every time, even after they've made the appropriate changes.

**Comment by jfreyberg** [comment]
It seems `$page.routeId` is now `$page.route.id`. I was wondering why `$page.routeId` is `undefined` and found this thread so I'm leaving this comment here.
