### ISSUE TITLE
when using form enhance, allow users to configure fetch

### ISSUE THREAD

**Issue by john-michael-murphy** [sveltejs/kit#7333]
### Describe the problem

`$app/forms` `enhance` does not appear to work for sites behind auth.  I think this is because the [fetch request](https://github.com/sveltejs/kit/blob/87b3037bb6fcf574d5d50c91f42cc91d3b97286c/packages/kit/src/runtime/app/forms.js#L84-L90) doesn't allow `credentials: 'include'`. 

### Describe the proposed solution

It would be great if there were some way to configure the fetch request used in `enhance`. 

### Alternatives considered

Create a custom enhancer. This is what we currently have to do, but it'd' be great to not have to recreate the wheel.

### Importance

would make my life easier

### Additional Information

As always, thanks for the great work, folks!

**Comment by dummdidumm** [comment]
The only kind of API I currently come up with that makes this possible that isn't a breaking change or makes things worse for other use cases is something like this:
```js
({ setHeaders }) => {
  ...
  setHeaders({ credentials: 'include' });
  return () => ...
}
```
Would correspond to the `setHeaders` API in `load`, might be nice, might also be confusing? Not sure how I feel about it.

**Comment by Rich-Harris** [comment]
Interesting — is the form action cross-origin? Credentials are included by default for a same-origin fetch, I wonder if we should add `credentials: 'include'` automatically for cross-origin cases? Not sure what the ramifications of that would be

**Comment by Rich-Harris** [comment]
Then again I'm not sure what it would mean to `enhance` a cross-origin fetch. So I'm going to err on the side of 'I haven't understood the issue' 😅

**Comment by david-plugge** [comment]
Just curious, does it even make sense to enhance a cross origin form?

And i wonder what exactly isn´t working for you @john-michael-murphy

**Comment by samjacoby** [comment]
We did some poking around on this and it appears that underlying issue is we're unintentionally doing a cross-origin fetch. Though we're hitting the same host, our `request.url.origin` protocol is reported as `http` while `request.headers.get("origin")` is `https`, so we're failing the sveltekit csrf check. I think that's by design. 

Our working theory is that this is the case because we're running the vite dev server in a deployed https environment (Google CloudRun). We're doing something a bit funky, in that we're deploying lots of intermediary small-scale servers for internal development; the easiest way to do that is to run the vite dev server.

I think our options would be to either provide a signed-certificate for the dev server or disable csfr. We're already in a secure environment, so we're going to opt for the latter. Happy to entertain smarter choices. Either way, I think this is an our problem, and we're good here! Thanks for the look!

**Comment by dummdidumm** [comment]
Thanks for the detailed rundown of the root cause! Will close this then 👍
