### ISSUE TITLE
extending the html forms with objects and arrays

### ISSUE THREAD

**Issue by KevsRepos** [sveltejs/kit#7345]
### Describe the problem

Using forms natively without requiring manually writing a `fetch` request is a great idea. And that it works without javascript, is even better but right there is the pitfall: Making it available without javascript also means, that we need to use the old fashioned FormData instead of json for the request. But using a json format on the backend makes things easier. With the FormData, we cant have nothing but strings and arrays of only strings. It really is frustrating and makes it more complex validating the data on the server. Also we cant make use of intellisense for the request.formData, as vscode could'nt propose type completions like `data.username`, because we receive our data as `data.get('username')` - which are also a few more characters to type.

### Describe the proposed solution

The title might seem weird and this FR might seem weird as well, but before putting this off immediately, (which is I think most people would do), please think about it before saying that its bad after reading this proposal.

Coming from the php world, we use something looking like that:

Coming from the php world, we use something looking like that:

```html
    <input name="guests[group1][]" placeholder="Guest 1..." />
    <input name="guests[group1][]" placeholder="Guest 2..." />
    <input name="guests[group2][]" placeholder="Guest 3..." />
    <input name="guests[group2][]" placeholder="Guest 4..." />
```
That might look confusing at first, but php interprets this automatically as an array (and an array in php is just a map which can have strings as keys (and so like a javascript object or map)), looking like this:
```
Array {
  guests => [
    group1 => ["Guest 1", "Guest 2"],
    group2 => ["Guest 3", "Guest 4"]
  ]
}
```
In javascript, it would be an object structured like this:
```js
Object {
  guests: {
    group1: ["Guest 1", "Guest 2"],
    group2: ["Guest 3", "Guest 4"]
  }
}
```
If no key is provided or if a integer key is provided, it should be interpreted as an array.

A structure like this gives us a lot of cool features out of the box. For example, we can take the `guests` object and directly count the groups the user set up and immediately have their names.

Now, what if Sveltekits `+page.server.ts` gave us this instead of the relatively uneasy to handle FormData map thing where we couldnt do this. The FormData map provides a method called `getAll` with which we can get entries with duplicate names, but we cant do`formData.getAll('guests')` - it will return an empty array, as there is no relation to `group1` and `group2` at all

This syntax and way of handling form data is the absolute standard the-way-to-go way in php. Why not add it to Sveltekit?
Its very easy to use and very beneficial in a lot of cases. And it would work with and without javascript, as only the server interprets the strings.
We could instantly make use of all the methods objects have. We can actually have a json-like object with only a form submission.

Both Svelte and Sveltekit are very opionated about all kinds of different things, so I think something like this would fit perfectly into kit natively. And if people dont like it - then they dont have to use it.
And to prevent making breaking changes, I would add another method to the FormData object - `event.request.formDataObject()`
which returns us a javascript object which displays the brackets in the `name` attributes as object or arrays.

It means being able to do more out of the box and one big argument to using the fetch api with a json body over the enhanced form is, that json is still much easier to work with than formData. With that, we can really provide the best experience with less code to write and no javascript on the client.

### Alternatives considered

We could think about different syntax, though I dont can think of any. We cant use curly braces, as svelte would interpret them as inline javascript.

Edit: Actually, we should consider nesting the brackets like `guests[group1[]]` instead of `guests[group1][]`
 - makes much more sense.
Or leave as is.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
This could easily live in userland. You already have access to the `FormData` object, which will have the form fields, including the multiple entries with the same name. The code to iterate through that and construct the JSON object doesn't need to live in the framework. My feeling is that it should not.

**Comment by KevsRepos** [comment]
I feel like the form enhancement is not done yet. We still have the backdraw, that working with FormData stuff is simply not as intuitive and easy as working with something more json like. We are limited to having strings and arrays of strings and while this could be a separate package, it feels like the way Sveltekit does the form things itself isnt thought out enough

**Comment by KevsRepos** [comment]
Why is github UI so bad... Re-opened.

**Comment by Conduitry** [comment]
If "form enhancement" refers to form progressive enhancement, that doesn't seem relevant. The idea is that the form would work in a no-JS environment, and so you'd still be dealing with `FormData` in the form action itself either way.

If you're in a no-JS environment, strings (and files) will be all that you can submit with the form anyway. Interpreting these as JSON in some way sounds over-opinionated to me. They would either have to be inflexible with weird gotchas (e.g. "everything that looks it might be a number is exposed as a number instead of as a string") or they'd have to be way too configuration to be convenient. As the author of your app, you're in a much better position to know which fields are numbers or booleans, at which point it's a lot fewer moving parts for you to just convert them than it is for you to tell SvelteKit how to convert them.

If you want something where you have complete control over the JSON that's sent and received, you can build your site to use `+server.js` endpoints and client-side JS to send requests to them in `on:click` event handlers, etc.

If you want something that can work without JS, that's the problem that form actions are intended to solve. And in that case, you're going to be working with key-value data where the values are all strings or files, and you as the app author are in a much better position to know what this data should mean then the framework could be.
