### ISSUE TITLE
Prerender tries to render outgoing link

### ISSUE THREAD

**Issue by percybolmer** [sveltejs/kit#7361]
### Describe the bug

First off, sorry if this is the wrong place, I am fairly new to all the things going on here.

I have been trying to create a blog which uses SvelteKit, mdsvex and a static adapter.
Everything works smooth until I start adding links inside the markdown files.

If any .md file has any outgoing link, it seems the prerender tries to find those sites on my site.
This causes it to fail ofcourse.

The issue can be resolved by setting `onerror` for the prerenderer into `continue`
but I would like to avoid that since now any missing posts will also be continuned.

### Reproduction

Clone the repository and try running the build command

```bash
git clone git@github.com:percybolmer/pp-blog-svelte.git
cd pp-blog-svelte
git checkout bug/prerender-outgoinglink
npm install
npm run build
```

### Logs

```Shell
percy@pc038:~/private/blog/pp-blog-svelte$ npm run build

> build
> vite build

vite v3.1.8 building for production...
✓ 75 modules transformed.
vite v3.1.8 building SSR bundle for production...
✓ 81 modules transformed.
Generated an empty chunk: "hooks"
.svelte-kit/output/server/vite-manifest.json                          4.99 KiB
.svelte-kit/output/server/index.js                                    69.60 KiB
.svelte-kit/output/server/entries/endpoints/rss/_server.js            1.42 KiB
.svelte-kit/output/server/entries/endpoints/api/posts/_server.js      0.43 KiB
.svelte-kit/output/server/entries/pages/_layout.svelte.js             1.58 KiB
.svelte-kit/output/server/entries/pages/_layout.js                    0.15 KiB
.svelte-kit/output/server/entries/fallbacks/error.svelte.js           1.50 KiB
.svelte-kit/output/server/entries/pages/_page.svelte.js               0.65 KiB
.svelte-kit/output/server/entries/pages/about/_page.svelte.js         0.38 KiB
.svelte-kit/output/server/entries/pages/blog/_page.svelte.js          2.57 KiB
.svelte-kit/output/server/entries/pages/blog/_page.js                 0.16 KiB
.svelte-kit/output/server/entries/pages/blog/_slug_/_page.svelte.js   0.81 KiB
.svelte-kit/output/server/entries/pages/blog/_slug_/_page.js          0.87 KiB
.svelte-kit/output/server/entries/pages/contact/_page.svelte.js       0.38 KiB
.svelte-kit/output/server/entries/pages/uses/_page.md.js              0.45 KiB
.svelte-kit/output/server/chunks/paths.js                             0.17 KiB
.svelte-kit/output/server/chunks/index.js                             3.53 KiB
.svelte-kit/output/server/chunks/index2.js                            0.97 KiB
.svelte-kit/output/server/chunks/index3.js                            0.79 KiB
.svelte-kit/output/server/chunks/hooks.js                             0.00 KiB
.svelte-kit/output/server/chunks/2.js                                 0.91 KiB
.svelte-kit/output/server/chunks/thumbnail.js                         0.12 KiB
.svelte-kit/output/server/chunks/preview-ide-of-the-future.js         23.67 KiB
.svelte-kit/output/server/chunks/test.js                              0.54 KiB
Error: Unknown variable dynamic import: ../posts/www.jetbrains.com.md
    at file:///home/percy/private/blog/pp-blog-svelte/.svelte-kit/output/server/entries/pages/blog/_slug_/_page.js:7:92
    at new Promise (<anonymous>)
    at __variableDynamicImportRuntimeHelper (file:///home/percy/private/blog/pp-blog-svelte/.svelte-kit/output/server/entries/pages/blog/_slug_/_page.js:6:10)
    at load (file:///home/percy/private/blog/pp-blog-svelte/.svelte-kit/output/server/entries/pages/blog/_slug_/_page.js:11:22)
    at load_data (file:///home/percy/private/blog/pp-blog-svelte/.svelte-kit/output/server/index.js:626:39)
    at async file:///home/percy/private/blog/pp-blog-svelte/.svelte-kit/output/server/index.js:1416:18
  500 /pp-blog-svelte/blog/www.jetbrains.com (linked from /pp-blog-svelte/blog/preview-ide-of-the-future)
```

### System Info

```Shell
System:
    OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 1.99 GB / 15.36 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
  Browsers:
    Brave Browser: 106.1.44.101
    Chrome: 106.0.5249.61
    Firefox: 105.0
  npmPackages:
    @sveltejs/adapter-static: ^1.0.0-next.46 => 1.0.0-next.46 
    @sveltejs/kit: 1.0.0-next.516 => 1.0.0-next.516 
    svelte: ^3.52.0 => 3.52.0 
    vite: ^3.1.8 => 3.1.8
```

### Severity

annoyance

### Additional Information

Hopefully it is not just me being dumb!

**Comment by dummdidumm** [comment]
I think the reason is that one of your links in the Jetbrains Fleet blog post is missing the protocol: `I've been waiting a long time for [JetBrains](www.jetbrains.com) to release ...`
SvelteKit therefore treats it as an internal relative link and then fails.

Technically this "works as expected" but I'm wondering if we could make the error message more clear in this instance.

**Comment by percybolmer** [comment]
I've confirmed that you are right @dummdidumm 
Adding https does in fact solve it.

Now that you mention it, it does make sense, but I recommend we either make it more clear in the docs that prerender will treat any URL without a protocol as internal. (Maybe its just me who is dumb, but I am gonna guess others will face this also)

Or as you say, make the error message a bit more clear, however that might be harder?:) 

I remved continue on error and it is now building

**Comment by Conduitry** [comment]
> make it more clear in the docs that prerender will treat any URL without a protocol as internal

It's not prerendering that's doing that, really. It's how links in HTML work. You have a link to a local URL `.../www.jetbrains.com` in your HTML.

---

@dummdidumm I'm not sure what we could do to make the error message clearer here. There _is_ a dynamic import of this module in https://github.com/percybolmer/pp-blog-svelte/blob/bug/prerender-outgoinglink/src/routes/blog/%5Bslug%5D/%2Bpage.js which is getting called for the catch-all route for all of the blog posts, and I don't think there's anything we could be doing here to notice that this is being rendered because of a link that is accidentally same-domain.

**Comment by dummdidumm** [comment]
Ideally we could backtrack the error to invoking prerender on that link, and wrap that error message with something that gives it the proper context. Something like "error while trying to prerender link X" and we could even check if X starts with `www.` to say "if you expect this to be an external link, make sure to prefix it with the proper protocol (http or https)"

**Comment by Rich-Harris** [comment]
We can't solve this in the general case — the repro above no longer exists but from the clues still available it looks like the issue was that the crawler was trying to render `/blog/www.jetbrains.com`, which caused a non-existent module to be dynamically imported. Aside from very unwise regex hackery, there's no way we could figure out that the error resulted from a missing protocol.

I'm going to close this because as @Conduitry says, this is just how links work — it's not specific to prerendering or even to SvelteKit, so there really isn't a place that it would belong in the documentation.
