### ISSUE TITLE
Catch prefetch server error

### ISSUE THREAD

**Issue by Ohyenno** [sveltejs/kit#7463]
### Describe the bug

Hello. Dangerous bug that I catch with SEO.

When the API goes down (restart server for example), prefetch returns an error. The user or crawler may continue to navigate. The pages will display the 500 error text, but the page will return a 200 code.

Code 500 is not given and incorrect headings get into the search engine index.
This leads to loss of positions in the index.

Need to catch the error and force a page reload or disable navigation.

### Reproduction

Just disable api

### System Info

```Shell
"@sveltejs/kit": "1.0.0-next.516"
```

### Severity

blocking all usage of SvelteKit

**Comment by Rich-Harris** [comment]
Please provide a reproduction showing an error page with a 500 response.

**Comment by Ohyenno** [comment]
https://github.com/Ohyenno/fjwpk45s

Just run the project.
It loads dynamic header from API
By clicking on the link you will get a new title

After the first or second page, open the browser console and emulate offline - select Network -> Offline.
Then click on any page link

You will get error text and title 500 from +error.svelte because $page.status will be 500

If a search engine is associated with crawlers, it uses counters to update the SEO data.
If the title changes, then the scanner updates the page information for the page.

I caught a problem when I was updating the api, some user used the site, api went offline for a few seconds, the user saw a 500 error, and the search engine updated the information. Now in search results page title 500.

**Comment by Ohyenno** [comment]
It seems to me that the best solution would be in the case of a prefetch if the page did not return the code 200 or 204, then preventDefault action and return the code in the callback (I'll use it in notification informer).

By the way, in parallel there was a topic with prefetching external sites. At the level of this middleware it’s good to check status and the domain.

**Comment by Rich-Harris** [comment]
If you navigate within the app while offline then yes, the error page will be shown, and your network tab will show the 200 response you got when the app first loaded. But if the API is offline, causing a rendering error, then the status code will be 500. Search engines discard 500 responses. I'm not sure what you're actually reporting here, sorry.

**Comment by origanumio** [comment]
Some search engines (not Google yet) have mechanisms for fast indexing due to counters and their own browsers. Their algorithms read information, meta data and other things, and update the ranking. That is, if the title or description changes on the page, the search engine considers that the content has been updated.

In the usual story, it’s true that search engines don’t read a 500 error, but if the browser data is updated, and the response code of the north is 200, the information changes.

Search engines seek to reduce the load on bots, so they use the power of users' computers for indexing. And this development will be more and more.

It seems to me what needs to be done I wrote earlier: it’s enough to prevent default action and return the callback after the prefetch through store. For example:
`if ($page.prefetchCode !== 200){ ... }`

**Comment by Ohyenno** [comment]
Some search engines (not Google yet) have mechanisms for fast indexing due to counters and their own browsers. Their algorithms read information, meta data and other things, and update the ranking. That is, if the title or description changes on the page, the search engine considers that the content has been updated.

In the usual story, it’s true that search engines don’t read a 500 error, but if the browser data is updated, and the response code of the north is 200, the information changes.

Search engines seek to reduce the load on bots, so they use the power of users' computers for indexing. And this development will be more and more.

It seems to me what needs to be done I wrote earlier: it’s enough to prevent default action and return the callback after the prefetch through store. For example:
if ($page.prefetchCode !== 200){ ... }

**Comment by Rich-Harris** [comment]
Which search engines, specifically? I'm having an extremely hard time believing this.

**Comment by Ohyenno** [comment]
Yandex.com

Details about this feature. This works really perfect. New pages goes to index during few hours.
https://yandex.com/support/webmaster/indexing-options/link-metrica.html

Yandex.Metrica is the same as Google Analytics

**Comment by Rich-Harris** [comment]
The linked document says nothing about the behaviour you describe.

**Comment by Ohyenno** [comment]
No search engine will reveal their algorithms and campaigns to avoid fraud. The question is that I described the mechanics of work based on specific personal situations. On this page, it was described that their analytics system will speed up search crawlers.

**Comment by Rich-Harris** [comment]
I'm sorry, I just don't believe that this is a real situation. I'm sure there's a misunderstanding somewhere. If you have evidence that this is happening, please share it, because it's simply not credible. If it was happening as you describe, there's nothing that any framework could do to guard against such an obviously broken system.

**Comment by Ohyenno** [comment]
Please see your email box with link and screenshot

**Comment by Rich-Harris** [comment]
Ok, well I see the search result but as I say there's absolutely nothing SvelteKit can do about this. If their search index is being updated by users because you added their analytics package then all I can suggest is 'don't do that'. It's a deeply, horrifically flawed approach.
