### ISSUE TITLE
Should / get picked up by [...index].svelte?

### ISSUE THREAD

**Issue by rinti** [sveltejs/kit#751]
**Describe the bug**
Lets say I have this route structure:

`routes/[...index].svelte` <-- only file
so no `routes/index.svelte`

In my mind / should get picked up by my "catch all"-route, but I'm forced to create a routes/index.svelte to make / work.

**To Reproduce**
Create a new project
Rename `index.svelte` to `[...index].svelte`.
Open dev-server, localhost:9000/foo/bar/baz works as intended, but localhost:9000 doesn't get picked up.

**Expected behavior**
localhost:9000/ should get picked up by [...index].svelte

**Severity**
Low

**Comment by CaptainCodeman** [comment]
This sounds like the same issue I have: I wanted to have a folder structure with the URL matching the path starting at `/folders/` (root) and then `/folders/2021` for a child and so on.

Because the trailing slash is automatically stripped it needs to have both `index.svelte` and `[...path].svelte` to match - I found it easier to have both of these be completely empty with the actual code in a `$layout.svelte` file. It works but it feels hacky and not-obvious.

I'd ideally like to be able to have the trailing-slash behavior be configurable.

**Comment by Rich-Harris** [comment]
I think we probably do want rest params to be optional, yeah

**Comment by Conduitry** [comment]
Yeah, I think that probably makes the most sense. It doesn't even need to be configurable route-by-route, because you could just check the value in `load` and fall through if it was empty and you didn't want to match that.
