### ISSUE TITLE
Cannot have encoded `%` in URL outside of parameter

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#7554]
### Describe the bug

https://github.com/sveltejs/kit/pull/7521 will not allow you to have a URL like this:

![Screenshot from 2022-11-08 14-27-39](https://user-images.githubusercontent.com/322311/200692834-65827729-1d0f-44b7-ac49-0b29f1f48aa9.png)

Probably the way to fix this is to replace the parameters with placeholders, decodeURI the altered URL, match with regex, and then decodeURIComponent on the parameters

### Reproduction

https://github.com/benmccann/kit/tree/encoded-percent-test

### System Info

```Shell
`master`
```

### Severity

annoyance

**Comment by dmkret** [comment]
@benmccann here what i've found:

1. It seems like you forgot to add a link to [+page.svelte](https://github.com/benmccann/kit/blob/encoded-percent-test/packages/kit/test/apps/basics/src/routes/encoded/%2Bpage.svelte)
```html
<a href="/encoded/99%">99%</a>
```
2. Decoding `/encoded/99%` uri will throw en error, so `%` should be `/encoded/99%25`
```javascript
decodeURI('/encoded/99%')
// Uncaught URIError: URI malformed
//     at decodeURI (<anonymous>)
//     at <anonymous>:1:1

decodeURI('/encoded/99%25')
// '/encoded/99%'

```
3. There is an issue with `%` in directory names, caused by [viteTransformMiddleware](https://github.com/vitejs/vite/blob/da632bf36f561c0fc4031830721a7d4d86135efb/packages/vite/src/node/server/middlewares/transform.ts#L53) (at least).
This middleware [uses decodeURI](https://github.com/vitejs/vite/blob/da632bf36f561c0fc4031830721a7d4d86135efb/packages/vite/src/node/server/middlewares/transform.ts#L60) on folder path. `/encoded/[percent]%25` becomes `/encoded/[percent]%` and any attempt to resolve `/encoded/[percent]%25` causes 404.

It seems that it is safe to use characters that are ignored by `decodeURI`: `%3B %2F %3F %3A %40 %26 %3D %2B %24 %2C %23` (`; / ? : @ & = + $ , #`) and others.

**Comment by dmkret** [comment]
As a solution maybe we can check path segments on build like this:
```javascript
const decoded = decodeURI(segment);
if (decoded !== segment) {
  throw Error('there is an unavailable encoded character') // and show original and decoded segments
}
```

**Comment by benmccann** [comment]
Thanks for catching my mistakes in the test! Sorry about that. I just pushed the fixes you mentioned

I'm not sure I understand what you're suggesting might be wrong with `viteTransformMiddleware`. Can you explain in more detail?

I'm actually pretty confused at the moment because the Playwright tests are failing, but I can load the page just fine in my browser:

![Screenshot from 2022-11-08 21-38-38](https://user-images.githubusercontent.com/322311/200747969-9d62f464-0d81-429e-b1ea-a2279d35c519.png)

**Comment by dmkret** [comment]
@benmccann excepts should be updated too:

```javascript
test('allows %-encoded percent character in directory names', async ({ page, clicknav }) => {
	await page.goto('/encoded');
	await clicknav('[href="/encoded/99%"]');
	expect(await page.textContent('h1')).toBe('dynamic');
	expect(await page.textContent('h2')).toBe('/encoded/99%25: 99%');
	expect(await page.textContent('h3')).toBe('/encoded/99%25: 99%');
});
```

**Comment by dmkret** [comment]
About `viteTransformMiddleware`, sorry, i was wrong, here is the more correct explaining:

When we create manifest, we perform decoding of directory segments, so `[percent]%25` becomes `[percent]%`:
https://github.com/sveltejs/kit/blob/11950e00ac57919b09e6148b78004bbeb002a446/packages/kit/src/utils/routing.js#L24

When user requests `/encoded/99%25` manifest expects `[percent]%`. It is 404 (if we don't have another valid match candidate).

More interesting example:
If we name directory as `/encoded/[percent]%2525` to use `[percent]%25` in manifest, it will be 200 on `/encoded/99%25`! But...
After that, if hydration is enabled, client will request `/encoded/99%2525/+page.svelte` (not `/encoded/99%25/+page.svelte`, which causes 404. I think it is another issue.

**Comment by dmkret** [comment]
The simpliest workaround will be using `%2525` as `%` in folder names. 
In tests it will fall with 500, because there is another error on hydration step.

As a complete solution I see exec candidate patters twice on decoded and encoded pathnames and compare results inside `decode_params`:

https://github.com/sveltejs/kit/blob/11950e00ac57919b09e6148b78004bbeb002a446/packages/kit/src/runtime/server/index.js#L73-L82

```javascript
const encoded_match = candidate.pattern.exec(url.pathname);
const decoded_match = candidate.pattern.exec(decoded);

if (!encoded_match || !decoded_match) continue;

for (const candidate of options.manifest._.routes) {
  const encoded_matched = exec(encoded_match, candidate, matchers);
  const decoded_matched = exec(decoded_match, candidate, matchers);
  
  if (encoded_matched && decoded_matched) {
    route = candidate;
    params = decode_params(encoded_matched, decoded_matched);
    break;
  }
}
```
