### ISSUE TITLE
preloaded with link preload was not used within a few seconds. Warning

### ISSUE THREAD

**Issue by DoodlingTurtle** [sveltejs/kit#7557]
### Describe the bug

On a Site build via @sveltejs/adapter-static
Firefox puts strange warnings into the console.

The resource at  URL preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.

URL means usually something like: https://[DOMAIN]/_app/immutable/chunks/1-b645c4a1.js

At first glance, this only seems to relate to files in the "_app/immutable" folder

Browser:
Firefox: 106.0.5 (64-Bit)
OS: Linux Mint 21

The strange thing is, that Chrome does not do this.

this is my package.json.
[package.json.txt](https://github.com/sveltejs/kit/files/9967663/package.json.txt)

![Screen Capture_select-area_20221109063710](https://user-images.githubusercontent.com/52770682/200747718-3843c461-0a4e-4cb4-a409-91711822850f.png)

### Reproduction

- create new project.
- install @sveltejs/adapter-static
- change adapter in svelte.config.js to '@sveltejs/adapter-static'
- build project
- move content of build directory to a static hoster.
- call page in firefox
- wait a few seconds.

### System Info

```Shell
System:
    OS: Linux 5.15 Linux Mint 21 (Vanessa)
    CPU: (16) x64 AMD Ryzen 9 5900HS with Radeon Graphics
    Memory: 7.50 GB / 15.04 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.18.0 - /usr/local/bin/node
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chromium: 106.0.5249.119
    Firefox: 106.0.5
```

### Severity

annoyance

**Comment by dummdidumm** [comment]
I don't think we can do much here. All modules related to the page are preloaded for maximum speed, and if some of them are not used right away that's probably better than loading them only when they are needed. I feel like it's safe to ignore this warning.

**Comment by Rich-Harris** [comment]
I think this might actually be a problem — the files in question are getting loaded twice in Firefox. I believe it's something to do with Vite's module preloading, though I can't offer any specifics beyond that right now

**Comment by Rich-Harris** [comment]
I'm still seeing it on (for example) https://kit.svelte.dev, which is built with Vite 3.2. Something else must be afoot

**Comment by DoodlingTurtle** [comment]
Hey,  thanks for the replys. 

To give a bit of context:
I'd love to use pure Svelte to create multi-page projects (as in multiple *.html files) but that is not its intended use and I respect that. However, having 100+ MB development overhead for each page (mainly the repeated node_modules) is also not an option.

So I'm trying to teach myself SvelteKit by converting an existing Svelte based, single page PWA Project to it.
 You can check out how it's going so far,  if you like.
https://github.com/DoodlingTurtle/SvelteKitLearningProject

There are a few (yet) unused components in there. Could that have something to do with it?

Unfortunately, I had no luck in getting any clones of the GitHub-Repo to run since they always complain about some sort of "polyfill" being missing (when calling `npm run dev`).

The build is also forced to be hosted on an Apache2 + PHP + MySQL Server combo, so static is the only adapter I can use.


And just to finish it. Please allow me to geek out for a second.
 👏🤩. I love Svelte so much 😍. Thank you, It has been a super fun experience so far.

**Comment by dummdidumm** [comment]
This definitely comes from Vite. The `<link rel="preload" as="script" href="..">` tags are inserted through a [preload script](https://github.com/vitejs/vite/blob/fc007dfba2e0392bd29f7e6e2663ca910ed18a6b/packages/vite/src/node/plugins/importAnalysisBuild.ts#L64) by Vite which is injected into the `start-[hash].js` chunk.

**Comment by benmccann** [comment]
I think we should turn off `modulePreload` completely. It looks to be preloading all routes for the application in both Chrome and Firefox. I think what it's doing is looking for all dynamic imports and preloading them and when it comes across the routes manifest it preloads the whole app. I believe SvelteKit's built-in behavior of doing it only for the current route is a better solution

**Comment by Rich-Harris** [comment]
> I think we should turn off modulePreload completely. It looks to be preloading all routes for the application in both Chrome and Firefox.

That's not what I'm seeing. If we disable module preloading, we'll be left with waterfalls.

In Chrome, here's what the `<head>` of https://kit.svelte.dev looks like after hydration:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1162160/203403262-776c8eb5-d1c1-4392-8311-147fc3a85853.png">

Here's Firefox:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/1162160/203403322-9a43838f-74e1-43ed-997c-ed78fac8d242.png">

Note that the block of `<link>` elements at the end is different — in Chrome we get `modulepreload` links, while in Firefox we get `rel="preload" as="script"`, because Firefox doesn't support `modulepreload`. Vite chooses `preload` [here](https://github.com/vitejs/vite/blob/f777b55a63d83eb13a54385b7de442649bc8e94a/packages/vite/src/node/plugins/importAnalysisBuild.ts#L54-L61).

I'm left wondering if Vite should just not bother injecting `<link>` elements if `modulepreload` isn't supported — as far as I can tell, `preload` links [just don't work](https://developer.chrome.com/blog/modulepreload/#ok-so-why-doesnt-link-relpreload-work-for-modules), and it's causing extra work for no benefit.

**Comment by benmccann** [comment]
You're right. I got confused by the change in the routing manifest.

It works for me if we turn back on the polyfill. Any idea why that's disabled and can we just re-enable it?

**Comment by Rich-Harris** [comment]
It adds bytes. Not a lot of bytes, but: https://guybedford.com/es-module-preloading-integrity#modulepreload-polyfill

We need to figure out which we value more: shipping fewer bytes in browsers that support `modulepreload`, or avoiding waterfalls in [those that don't](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/modulepreload#browser_compatibility)

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1162160/203408511-ad469721-53dc-4d07-a9b9-100d19ca9321.png">

**Comment by dummdidumm** [comment]
Vite claims to have a polyfill for this which would make it work for `modulepreload`. AFAICT Vite preloads everything a file would import, so I guess we don't actually save any bandwith by telling Vite to not add these links - as Rich says, we only make it a little worse by having a little waterfall.
Regarding the double load problem, https://vitejs.dev/config/build-options.html#build-modulepreload has a `resolveDependencies` option which we maybe could use to remove that from the array of preloads (because it's loaded through the `await import('..')` anyway)

**Comment by benmccann** [comment]
> Vite claims to have a polyfill for this which would make it work for modulepreload.

Yes, but we've disabled it. I sent a PR to turn it back on: https://github.com/sveltejs/kit/pull/7770

The impact of a waterfall is somewhat substantial while the impact of the extra bytes is pretty minimal and non-detectable
