### ISSUE TITLE
Make Cookies available on SSR.

### ISSUE THREAD

**Issue by carlosV2** [sveltejs/kit#7564]
### Describe the problem

While coding on the server part of the project, you have access to an object of type [`Cookies`](https://github.com/sveltejs/kit/blob/5f96fe910007a0f35d75551daaf4e7d4f773d179/packages/kit/types/index.d.ts#L148-L182) in the [`RequestEvent`](https://github.com/sveltejs/kit/blob/5f96fe910007a0f35d75551daaf4e7d4f773d179/packages/kit/types/index.d.ts#L511). However, when coding on the SSR part, this object does not exist plus you can't access the `document` object in the browser.

### Describe the proposed solution

I believe while the request is being SSR, there should still be access to the request's headers so, my proposal is to also allow the `Cookies` object to exist in the `load` functions.

Obviosuly this will break the `load` functions when they are CSR so the solution should be some sort of polyfill that transparently integrates with either the request's headers or the `document.cookie` in the browser.

### Alternatives considered

I'm afraid I can't think of an alternative at this moment as in the SSR zone, there is no access to neither the `Cookies` object nor the `document` object.

Perhaps the only "solution" would be to not use cookies and return the data directly instead? But this would require the client code to manually send it back on every request.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
To clarify: Are you talking about `load` functions inside `+page.js`/`+layout.js`?

Adding support there would probably introduce other sorts of confusion: "why can't I access this cookie in the browser, but on first SSR on the server I can?" (answer: because it's a http only cookie by default).

I suggest to use `+page.server.js` or `+layout.server.js` instead where you have access to cookies, as that `load` function is guaranteed to always run on the server.

**Comment by carlosV2** [comment]
@dummdidumm yes, I mean the `load` functions in `+page.js`/`+layout.js`.

I understand your concerns but they are the same issue as explaining the users the difference between SSR and CSR (imho). 

Utlimately, the proposed polyfill could filter the HttpOnly cookies out (for the sake of browser transparency) giving the server files the only ones capable of manipulating them.
This could be signaled easily with types in a similar fashion as it is done now with the `PageLoad` and `PageServerLoad` types: `ClientCookies` vs `ServerCookies` (where the `ClientCookies` would be the polyfill I'm talking about including the filter for the HttpOnly cookies and `ServerCookies` could be exactly as it is right now).

**Comment by Rich-Harris** [comment]
This is something that has been discussed in the past, and it's not something we want to do. It would be a mistake. If you want to read cookies, use a `+page|layout.server.js` file

**Comment by carlosV2** [comment]
Hi @Rich-Harris, I humbly disagree with this logic. I understand this is, perhaps, not an SvelteKit sort of functionality to maintain (kind of like sessions are not SvelteKit's functionality either). However, the problem I have is that I can't even provide a polyfill myself. There is no way (that I know) to circumvent this limitation. SSR environment does not have access to the `Cookies` object, nor it does to the `document` object, and it does event prevent the modification of the cookies header via `setHeader` (this is why I suggested SvelteKit could filter the HttpOnly cookies out seeing that it already does stuff like this for good reasons).

In addition to this, this issue limits quite drastically what the SvelteKit is good for like, precisely, the SSR environment. You can't use it if you rely on accessing cookies in the client (or you must use it by proxifying the cookies throught the server which, imho, it's a bit silly and unecessary).

**Comment by dummdidumm** [comment]
Could you expand on your use case? Why do you need to read/modify cookies in the browser and why does that need to happen in `load`?

**Comment by carlosV2** [comment]
I've setup an authentication system that relies on HttpOnly cookies. Because they are HttpOnly, I have no way to know if I have a logged in user or not in the client code. To circumvent this, I'm creating a separate regular cookie as token to notify the client so SvelteKit can render the apropiate HTML. I need to read this cookie during the load function to either send the user to the login page (in case there is not a logged in user), or to discriminate by role.

I originally did this by returning a value in a server page (like you guy mentioned) but because the log in information is system-wide (think about it like showing a `Login/Logout` link on the page header), I'm reading it in the root layout which requires me to use the `parent` function which has the potential of triggering circular dependencies. That's why I though on the cookie solution.

**Comment by dummdidumm** [comment]
Why has using `await parent()` the potential of triggering circular dependencies?

```js
// +layout.server.js
export function load({ cookies, url }) {
  if (!cookies.get('user') && url.pathname !== '/login') {
    throw redirect('/login');
  }
}
```

**Comment by carlosV2** [comment]
Thanks for your sugestion, @dummdidumm. The problem is that his file is evaluated only once. I know there is a way to declare dependencies and invalidations but this requires to insert them on every single load method (again, layout are -to the best of my knowledge- not enough) with the potential of a very bad security flaw if you forget one.

The other solution would be to inject a handler in the `hooks.server.ts` file that does this but you cannot return data in this handler.

I've re-read the `parent` documentation and I can't find the circular dependency problem I mentioned (sorry, I guess I confused the waterfall warning with a circular dependency 🤦🏼‍♂️). So, I guess I could use the `parent` function to retrieve the data from the server which is better than the cookie, yay! However I still have the issue of the layout server not being run for every request thus forcing me to polute the project with `page.server.ts` files doing all of them pretty much the same 🤔.

**Comment by dummdidumm** [comment]
I'm not sure I follow - so your problem is not actually the cookie, but using the cookie to achieve something specific? Poking-in-the-dark-suggestions:
- you can attach something to `locals` in `hooks.server.ts` which all `+layout/page.server.ts` files can access
- you can add a dependency on `url` in your root `+layout.server.ts` so it runs on every page change: `export function load ({ url }) { url.pathname; ... }`

**Comment by carlosV2** [comment]
Oh! That's very interesting! I didn't know I could force the run of the layouts by using `url.pathname`. From the documentation, I though that could only be accomplished with `depends` and `invalidate`.

I will revert from using a cookie and I'll use a variable passed from the server.

Imho, I still think allowing for some degree of cookie access at SSR would be beneficial (it could just be allowing to access the request headers, for example) but, for my case, it is no longer required.

Thanks so much for your help @dummdidumm!

**Comment by david-plugge** [comment]
I´m currently facing some issues while working on the supabase auth helpers for sveltekit.

The problem is this:
We can easily read the cookie inside handle hook/server load functions/actions/request handlers and even update the session by saving it to the cookie. But how are we supposed to do this in shared load functions on the server?
We can use the root layout load to pass down the current session value, but there is no way to update it. So what happens if an access_token expires right in the middle of the shared load chain? The client is not authenticated anymore and we are not able to refresh the token and save it to the cookie.

Since we are not supposed to use cookies in shared load functions, how should this be implemented? I thought about using `event.fetch` to get/set/delete the session from another endpoint, but that add complexity (custom hook with an api endpoint) that seems unneccesary.

**Comment by carlosV2** [comment]
Hi @david-plugge, I'm not sure I fully understand your use case but I also thought on having potential problems in similar situation so I resorted to make the cookie to artificially expire a few minutes earlier so I have a grace period to refresh the token or, at least, to guarantee that it won't expire in the middle of a request.

I hope this helps!

**Comment by david-plugge** [comment]
Yeah that´s what we currently do aswell but it feels hacky.
Though I´d prefer a framework level solution as cookies are not limited to server only.
