### ISSUE TITLE
import.meta.glob works in script but breaks in template

### ISSUE THREAD

**Issue by janosh** [sveltejs/kit#7671]
### Describe the bug

The following errors

```svelte
<script>
  console.log(import.meta.glob(`./*`))  // works
</script>

<!-- breaks -->
{import.meta.glob(`./*`)}
```

> [plugin:vite:import-glob] Invalid glob import syntax: Expect CallExpression, got BinaryExpression

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-khnpjr?file=src%2Froutes%2F%2Blayout.svelte&terminal=devr

### System Info

```Shell
StackBlitz
```

### Severity

annoyance

**Comment by gtm-nayan** [comment]
I'd say this is a Vite bug because instead of transforming and replacing just the `import.meta.glob('./*')` part with an object, it's looking at the whole expression generated by Svelte to coerce the object to a string.

You can file an issue upstream with a simplified repro without SvelteKit and as a workaround, you can use a comma operator like `{(0,import.meta.glob("./*"))}` to force svelte to include the parens and get Vite to parse the glob import in isolation.
