### ISSUE TITLE
Make `handleError` `async`

### ISSUE THREAD

**Issue by vekunz** [sveltejs/kit#7756]
### Describe the problem

I want to use the handleError hook of SvelteKit, but I realized that it currently has to be a synchronous function. But unfortunately, our error mapper is an asynchronous function. Since it is not possible in JavaScript to synchronously await an asynchronous function (like in C#), it seems we cannot use the handleError hook currently.

### Describe the proposed solution

Make the return type of `HandleServerError` and `HandleClientError` a `MaybePromise`, like the handle-hook.

```ts
export interface HandleServerError {
  (input: { error: unknown; event: RequestEvent }): MaybePromise<void | App.Error>;
}

export interface HandleClientError {
  (input: { error: unknown; event: NavigationEvent }): MaybePromise<void | App.Error>;
}
```

### Alternatives considered

Continue not to use `handleError`.

### Importance

would make my life easier

**Comment by dummdidumm** [comment]
What is your error mapper doing that needs it to be asynchronous?

**Comment by vekunz** [comment]
Some of the error objects are `Response` objects (these come from a third-party library, so cannot change this behavior). In our error mapper, we need to read the content of the response with `await response.json()`, because it contains an error dto we need for proper error handling and logging.

**Comment by Rich-Harris** [comment]
How important is it that the DTO is attached to the publicly-facing error? In other words, could you do this?

```js
export function handleError({ error, event }) {
  getLoggingData(error).then(data => {
    console.log(data);
  });

  return {
    message: 'oh no'
  };
}
```

Making `handleError` async makes me somewhat nervous — if something goes wrong, we ideally need the simplest/fastest possible path to recovery. Adding async moving parts complicates that — for example what if the third-party service is temporarily unavailable? By enforcing a sync signature, that async work can happen in the background where failure is non-catastrophic.

**Comment by dummdidumm** [comment]
I feel the same honestly, but did the PR regardless, mainly to see how much impact on the code base it has. It's something of a "if you want to shoot yourself in the foot real bad you can do so anyway" situation, with `async` making this a little easier.

**Comment by dummdidumm** [comment]
I can sympathize with such situations, because I've been in these previously, too. It's not great to have to do this, but if people have to, we shouldn't be in the business of actively prohibiting it, which in your case leads to more repetitive code which only moves the issue of having to do a backend call elsewhere.

**Comment by Rich-Harris** [comment]
@vekunz we're working on better integrated error handling in Svelte itself, which will be used in SvelteKit — basically, Svelte gets provided with a `transformError` function that transforms any errors that occur inside an [error boundary](https://svelte.dev/docs/svelte/svelte-boundary) before they are used to render the `failed` snippet. SvelteKit, in turn, would create error boundaries for every `+error.svelte` file, and use the user-provided `handleError` hook inside `transformError`. This is important if people are using [remote functions](https://svelte.dev/docs/kit/remote-functions) inside components to load data, instead of using `load` functions.

It would be great if `transformError` could be synchronous, because otherwise we have to figure out what happens to the contents of the boundary while we're waiting for the returned promise to resolve — this poses a lot of very tricky questions. But it can't be synchronous if `handleError` is allowed to be synchronous. This morning we were trying to remember why it's possible to return a promise from `handleError`, which led us here.

So here's my question: does `handleError` need to be async on both the server _and_ the client? Or would it be acceptable for `handleError` to be async on the server (where it doesn't pose these difficult problems) but sync on the client? (This is purely information-gathering, not saying that's what we're going to do!)
