### ISSUE TITLE
`throw error(204)` returns invalid response

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#7765]
### Describe the bug

Undici is fails to `fetch` an endpoint which returns `throw error(204)` because it expects there to be no body. Users cannot currently save in the REPL as a result

### Reproduction

https://github.com/sveltejs/sites/blob/9c15c79b4bcdf043166b4b3974576e86bb783289/sites/svelte.dev/src/routes/(authed)/repl/%5Bid%5D.json/%2Bserver.js#L98

### System Info

```Shell
`master`
```

### Severity

blocking an upgrade

**Comment by Rich-Harris** [comment]
`throw error(204)` makes no sense — a 204 response isn't an error. That line should be changed to this:

```js
return new Response(undefined, { status: 204 });
```

We should disallow error codes below 400.

**Comment by zharsing** [comment]
Hey Rich, what's the deal with this?

if I do

`return new Response(undefined, { status: 204 });`

it results the following in my log on a node server:

`TypeError: Cannot set property status of #<_Response> which has only a getter`

**Comment by Rich-Harris** [comment]
Please open a new issue instead of commenting on closed ones — it's pure happenstance that I saw this

**Comment by zharsing** [comment]
not my issue mate ..

**Comment by zharsing** [comment]
Fair enough, although you could just point me the right way to chip in.

I must admit I do benefit from your efforts, to say the least I owe you some, for sure.

I might have some skills under my belt that could come handy at some point in the project.

I've had no idea you'd even turn up, but I really appreciate it! (hope its not a bot on the other end)

Svelte = Good Stuff For Sure!       --> .. am coming from JavaFX, they would be a quite interesting combination to be fair ..

As of now I'm just a new user of svelte and the web as it is of div-s and css classes to the point I know, of course with other strangers around as in any html otherwise. 

I really like the effectively expressive language models, svelte is GREAT. Keep It Going!
