### ISSUE TITLE
Issues with search field in SvelteKit documentation (on iOS).

### ISSUE THREAD

**Issue by Leftium** [sveltejs/kit#7947]
### Describe the bug

Some minor annoyances with the SvelteKit documentation on iOS:

1. It is impossible to tap the 'x' on the right that clears the search input. Instead, the hamburger menu always "steals" the tap. Workaround is to select the text and delete. Or keep tapping keyboard backspace until text is gone.
2. Perhaps related to the issue above, the search field seems to be covered by the navigation header. As you can see in the screen shots below, the input cursor overlaps the Svelte logo.
3. In dark mode, you cannot see the text you entered. This seems to only happen on iOS in dark mode. (Also tried Windows 11 Chrome and Android Chrome.) Happens in both Safari and Chrome. In the image below, you can see I entered 'test' into the search field, but you cannot see the search input text, only the input cursor.

![image](https://user-images.githubusercontent.com/381217/205685727-79d54b70-11a3-413d-b021-39a34bb5d9b7.png)

Normally the search input is visible in light mode, but when in auto dark mode and forcing light mode via the iOS control center, it still invisible. Perhaps in normal light mode, the search input was low enough to see the text and 'x':
![image](https://user-images.githubusercontent.com/381217/205688191-8cabf899-45e3-4350-8ef1-7657ffb82c84.png)

### Reproduction

Search documentation on https://kit.svelte.dev/ 

### Logs

```Shell
n/a
```

### System Info

```Shell
- iOS version 16.0.3
- iPhone SE (2020)
```

### Severity

annoyance

**Comment by s3812497** [comment]
> It is impossible to tap the 'x' on the right that clears the search input. Instead, the hamburger menu always "steals" the tap. Workaround is to select the text and delete. Or keep tapping keyboard backspace until text is gone.

This is the expected behaviour. The 'x' closes the modal in both mobile and desktop. Although, I can agree it's confusing since most search bars use it to clear the input rather than close. Maybe this should be changed?

> Perhaps related to the issue above, the search field seems to be covered by the navigation header. As you can see in the screen shots below, the input cursor overlaps the Svelte logo.
In dark mode, you cannot see the text you entered. This seems to only happen on iOS in dark mode. (Also tried Windows 11 Chrome and Android Chrome.) Happens in both Safari and Chrome. In the image below, you can see I entered 'test' into the search field, but you cannot see the search input text, only the input cursor.

I was only able to reproduce this on my iPhone 7 but not in Safari. It seems that the `z-index` CSS property is not being handled correctly? The nav bar is taking precedence with `z-index: 101` although the search box has `z-index: 9999`.
