### ISSUE TITLE
Font size fix

### ISSUE THREAD

**Issue by AramRafeq** [sveltejs/kit#8215]
### Describe the problem

Hello, 
I am really excited for svelte kit release 🎉, I was going through the website and the font size on some sections were really small even parts of the documentation, I think it would be a good idea to increase the font size to improve readability it maybe only me or my personal preference but I think there is room for improvement bellow are some examples 

Example 1: 
![image](https://user-images.githubusercontent.com/6641251/208307666-14e6a231-fa20-47b3-8bb2-9298187202ff.png)

Example2: 
![image](https://user-images.githubusercontent.com/6641251/208307739-410542a4-010f-4bb0-86b0-50a57afe1d9e.png)

 

### Describe the proposed solution

It would be great if fonts had  size consistency inside the landing page of svelte kit and increasing fonts in some places.

### Importance

nice to have

**Comment by enBonnet** [comment]
Which one could be the approach to resolving this issue? Should we define a base font size for all the pages base on REM value?

Should we define sizes for paragraphs, titles, subtitles, and more?

**Comment by Hetarth02** [comment]
I personally think that the later off the two is the way to go, defining different sizes for paragraphs, titles and other elements would help better differentiate visually.

Moreover, instead of REM can't we use `ch` for font-size? [Reference]("ch
Character unit. The CSS ch unit is defined as the width of the character 0 (zero, or U+0030) of the font.

While the ch unit works as an exact measurement for monospaced / fixed width fonts like Courier, it can be unpredictable with proportional fonts like Arial."
 https://www.freecodecamp.org/news/css-unit-guide/#:~:text=ch,fonts%20like%20Arial.)

**Comment by enBonnet** [comment]
> defining different sizes for paragraphs, titles and other elements would help better differentiate visually.

Strongly agree.

**Comment by Rich-Harris** [comment]
Agree, there's nothing that needs changing here — the font-size for body text on the docs is 16px which is very standard (and larger than the 14px on GitHub — typefaces aren't directly comparable, but Overpass at 16px is perceptually larger than the system font at 14px), and if you really want to read the wall of text then you can zoom in or copy-and-paste.
