### ISSUE TITLE
PWA out of the box.

### ISSUE THREAD

**Issue by pgcr71** [sveltejs/kit#8247]
### Describe the problem

making PWA out of sveltekit requires some additional steps. PWA functionality should be provided out of the box

### Describe the proposed solution

 just like prerender=true, provide a flag offline = true for PWA offline access. Also, provide an option to export web app to Android App, ios App etc

### Alternatives considered

NA

### Importance

nice to have

**Comment by dummdidumm** [comment]
Please be more specific with the requirements. PWA functionality _is_ provided, and since everyone has different opinions/needs, it's deliberately low level so you can adjust this to your needs. Things like Vite plugin PWA or workbox should do what you want. Why would you use opinionated unflexible config over these solutions?

Exporting something to Android is out of scope of this project.

**Comment by kvetoslavnovak** [comment]
I believe short description/tutorial in Sveltekit documentation how to use Vite PWA tool may be enough.

**Comment by juslin03** [comment]
How about adding some description in the documentation on how to implement Vite PWA

**Comment by dominikg** [comment]
vite-pwa is already mentioned in our docs https://kit.svelte.dev/docs/service-workers , last paragraph links to https://vite-pwa-org.netlify.app/frameworks/sveltekit.html , see also https://github.com/vite-pwa/sveltekit

**Comment by dummdidumm** [comment]
Closing since we don't want to add more PWA config at this time, and more full-fledged/opinionated solutions like workbox and Vite PWA are linked in the docs

**Comment by ESchouten** [comment]
Simply linking to [VitePWA](https://github.com/vite-pwa/sveltekit) seems insufficient to me. The libraries support for offline working has been broken for months/ever. [Issue](https://github.com/vite-pwa/sveltekit/issues/16).
