### ISSUE TITLE
Load function weird behaviour when importing values

### ISSUE THREAD

**Issue by printfhere** [sveltejs/kit#825]
**Describe the bug**

- When importing and updating a value in the load function, I get assignment to constant variable but my variable is not constant. 
- When updating a store (e.g a count) in the load function and refreshing the page I got a page from the server with an updated store then the csr reset the variable -> don't really know what more to say as I didn't really understand yet how load is accessing the stores on server side. (does not happen with prerender disabled and ssr : false).
In the exemple below when I refresh I will get store 2 for the first paint and then 1, refresh again store 3 and then 1, etc...

 
index.svelte
```
<script context="module">
  import { count, notStore } from "../store";
  import { get } from "svelte/store";

  export async function load() {
    count.set(get(count) + 1); //works
    notStore++; //does not work
    return {
      props: { value: notStore },
    };
  }
</script>

<script>
  export let value;
</script>

<main>
  <p>{$count}</p>
  <p>{value}</p>
</main>

```
store.js
```
import { writable } from "svelte/store";

export const count = writable(0);
export let notStore = 0;
```

**Logs**
```
TypeError: Assignment to constant variable.
    at load (http://localhost:3000/src/routes/index.svelte?import:99:10)
    at Renderer._load (http://localhost:3000/.svelte/dev/runtime/internal/start.js:698:35)
    at async Renderer.start (http://localhost:3000/.svelte/dev/runtime/internal/start.js:421:18)
    at async start (http://localhost:3000/.svelte/dev/runtime/internal/start.js:872:15)
```

**To Reproduce**
New sveltekit project and copy paste the code below

**Expected behavior**

- If I can update stores in load (even if it does nothing server side and only work client side), shouldn't I be able to update other variables ? 
- When refreshing the page, stores should be reset (not sure how it works server side).

**Information about your SvelteKit Installation:**

System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.14 GB / 7.73 GB
  Binaries:
    Node: 14.4.0 - ~\scoop\apps\nodejs\current\node.EXE
    npm: 6.14.5 - ~\scoop\apps\nodejs\current\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.67
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5

- Your browser Brave

- Your adapter (e.g. Node, static, Vercel, Begin, etc...) node 

**Severity**
In my opinion load shouldn't reference application code as it could be run on the server without app context but some things works and some don't and I don't get why. Load can also be used when building SPA to prevent displaying a page building piece by piece so maybe it makes sense to be clearer on what is possible or not / be more opiniated on what should be in load.

The refresh issue is weird and someone should have found this before so maybe it's a problem with my install.

**Comment by rmunn** [comment]
> When importing and updating a value in the load function, I get assignment to constant variable but my variable is not constant.

That's unrelated to Svelte; it's just how Javascript works. The `import { someValue } from 'module'` statement is treated the same as:

```js
import module from 'module';
const someValue = module.someValue;
```

Try this:

```js
// bar.js
export let b = 5;

// foo.js
import { b } from './bar.js';
console.log('Should be 5:', b);
b = 6;
console.log('Should be 6:', b);
```

Run `node foo.js` and you'll see "Should be 5: 5" followed by the same "TypeError: Assignment to constant variable" error that you're seeing in your own code. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import says that "The static import statement is used to import **read only** live bindings which are exported by another module. [...] Bindings imported are called live bindings because they are updated by the module that exported the binding." (Emphasis mine).

That's why foo.js cannot change the value of `b` in my example, because that value belongs to `bar.js` and is read-only everywhere else. But notice that sentence about bindings being updated by the module that exported them? `bar.js` is still allowed to change the value of `b`. The following will work:

```js
// bar.js
export let b = 5;

export function setB(newVal) {
  b = newVal;
}

// foo.js
import { b, setB } from './bar.js';
console.log('Should be 5:', b);
setB(6);
console.log('Should be 6:', b);
```

Now if you run `foo.js`, you'll see that `b` is 5 before the setB() call, and 6 after the call. That's because `bar.js` is allowed to update the value of `b`. And that is essentially what Svelte stores are doing at their core: storing a value, and giving you a `set` function that you're allowed to call to update the value. Of course, Svelte stores do a whole lot more than that. But that's why the `count.set` function call is working for you (the value of the store belongs to the `svelte/store` module and is being updated by a function in that module) but assigning to `notStore` does not work (the value of that variable belongs to your `store.js` module, and your `index.svelte` module is not allowed to reassign a variable belonging to `store.js`). If you added a function to `store.js` called `updateNotStore(newValue)` and called that fro `index.svelte`, it would work.

In other words, this is not a bug, but a part of Javascript's design.

As for the part about the store always getting set to 1 after a refresh, that's because you shouldn't do `store.set(store.get() + 1)`. The function you want is `store.update()`. Specifically, `store.update(n => n + 1)`. I don't have time right now to explain the issues with calling `store.get() + 1`, but think about threading race conditions and caching and you may get the idea. The short version is: if you rely on the current value of the store to calculate the new value, don't use `store.get()` as the store value may have changed between when you get it and when you set it, and then you'll be setting a stale value. Instead, use `store.update(oldValue => newValue + calculated + from + oldValue)` and you'll get the *current* value at the time that update is called.

**Comment by dummdidumm** [comment]
Thanks @rmunn for the detailed explanation!

**Comment by printfhere** [comment]
@rmunn thank you for having taken the time to write a cleared and detailed explanation even if my misunderstanding was unrelated to sveltekit.
You helped me understand more about how js works as I tend to use stuff without understanding much how it works behind the scene. 
Take care
