### ISSUE TITLE
Dependencies being eagerly executed due to default noExternal value

### ISSUE THREAD

**Issue by AdityaJain1030** [sveltejs/kit#826]
**Describe the bug**
OnMount running serverside with Node Adapter and SSR. This leads to a client-side lib being dynamically imported on the server.

**Logs**

![image](https://user-images.githubusercontent.com/50159919/113366381-dc036500-930d-11eb-8c1e-d0c470d0da40.png)

**To Reproduce**
```
git clone https://github.com/AdityaJain1030/Minimal-Kit-SSR-bug-example .
yarn install
yarn run build
yarn run start
```

**Expected behavior**
The SSR should build and run normally. What actually happens is that the SSR tries to render OnMount on the server, causing a client-side library to throw an error

**Information about your SvelteKit Installation:**
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
    Memory: 6.49 GB / 15.91 GB
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.63)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.58
    svelte: ^3.29.0 => 3.35.0
    vite: ^2.1.0 => 2.1.2
```

**Your browser**
- Brave (chromium-based)
 
**Your adapter (e.g. Node, static, Vercel, Begin, etc...)**
- Node

**Severity**
Low. Unexpected behavior that is hard to debug and leads to a lot of wasted time, but nothing more. 

**Additional context**
The issue goes away when you do `if(browser)` inside the `onMount`, but it seems counterintuitive, and the docs don't mention it.

**Comment by c-bandy** [comment]
The url to your repo is wrong, should be `https://github.com/AdityaJain1030/Minimal-Kit-SSR-bug-example.git`

**Comment by AdityaJain1030** [comment]
Updated

**Comment by Rich-Harris** [comment]
The issue here isn't that the code inside `onMount` is running in Node, it's that all your dependencies (server- and client-side) are being inlined into the built `app.js`. Even though it's hidden behind an `await import(...)`, the code executes eagerly, resulting in the bug you see.

The reason you don't see it with the `if (browser)` check is that it gets rewritten as `if (false)` and dead-code-eliminated.

In this case the fix is fairly simple: you just need to remove the `noExternal` section from your `svelte.config.js` (which is there because some people were having the opposite problem — they needed external dependencies to be inlined). I'll leave this open for the minute though, until we can settle on better default behaviour.

**Comment by Conduitry** [comment]
Closing, as the `noExternal` stuff has been more or less settled for a while now.
