### ISSUE TITLE
Do we really need `vite-manifest.json` in publicly accessible build dir?

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#8360]
### Describe the problem

I'm using latest stable Kit (`"@sveltejs/kit": "1.0.3"`) and `"@sveltejs/adapter-static": "1.0.0"` with SSR disabled at all.

After `npm run build` I get a `vite-manifest.json` file in `build` dir.

Since this file is then publicly served to the world, I would like to understand if it is strictly necessary or if we can do without it.

Thanks for your immense work!

**Comment by Rich-Harris** [comment]
Honestly I'm a bit confused by this myself. It seems very odd that we should need to write this file to the filesystem, instead of having it be returned from `vite.build`. I would definitely be in favour of removing it, though it might theoretically cause issues for other Vite plugins that need to read the manifest for whatever reason — @benmccann might have a better idea about whether we can safely get rid of it.

**Comment by benmccann** [comment]
I thought we were removing it in the very final build hook. We were doing that at some point I believe. Perhaps it got lost in some refactoring?

A longer-term fix would probably be to make improvements in Vite: https://github.com/vitejs/vite/issues/9636
