### ISSUE TITLE
load event should check event source

### ISSUE THREAD

**Issue by y0zong** [sveltejs/kit#8380]
### Describe the bug

any img element e.g `<img src="demo-path/demo.jpg"/>` can be captured by `event.params` in `load` function

in `routes/[key1]/[key2]+page.svelte`
``` html
...
<img src="demo-path/demo.jpg"/>
...
```
in `routes/[key1]/[key2]+page.ts`
``` typescript
export const load: LayoutLoad = async (event) => {
        console.log(event.params)
        // { key1: 'demo-path', key2: 'demo.jpg' }
}
```

event source should be limited to only `a`

### Reproduction

any simple code like above

### System Info

```Shell
Binaries:
    Node: 18.2.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.0 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.1
```

### Severity

serious, but I can work around it

**Comment by Conduitry** [comment]
I can't really tell what's going on in your example. You didn't give a proper reproduction, as requested in the template.

You have a `+page.ts` file but you're typing it as a `LayoutLoad`, not a `PageLoad`.

**Comment by y0zong** [comment]
> I can't really tell what's going on in your example. You didn't give a proper reproduction, as requested in the template.
> 
> You have a `+page.ts` file but you're typing it as a `LayoutLoad`, not a `PageLoad`.

I just copy my `load` code, but **any load** `LayoutLoad` `LayoutServerLoad` `PageServer` `PageLoad` is same result, and it's easy to reproduction, any `img` with `src=relative/path` can hit this or an error. sorry I have no much time to do a reproduction repo today, this basic thing is the request form `img` or other assets should not be captured.
![Uploading Screen Shot 2023-01-07 at 21.45.13.png…]()

**Comment by Algoinde** [comment]
This is correct. You have defined a catch-all parameter in your route (`/[key1]/`), which is mapped to the root of the site. You're trying to request the image from the root of the site as well. It happens to fall into the `/[key1]/[key2]`, as the URL matches.

Four solutions:
0. Type your routes so they only catch non-jpg things (https://kit.svelte.dev/docs/advanced-routing#matching) by setting up a proper regex / substring lookup
1. Don't use a parametric `[route]` right in the root of your `routes`,
2. Create a `demo-path` folder with a blank `+page.svelte` so your JPG images do not match that route
3. Move all images to `/static/assets/` instead of `/static/` and do the step 2 but with `assets` as the folder

**Comment by Rich-Harris** [comment]
SvelteKit is behaving as intended — if you have a static asset (`static/demo-path/demo.jpg`) or a more specific route (`src/routes/demo-path/demo.jpg/+server.js`) they will be hit first. If the route is unexpectedly handling a request for `/demo-path/demo.jpg` it's a bug in your app.
