### ISSUE TITLE
Import is undefined on server but defined on the client

### ISSUE THREAD

**Issue by raulfdm** [sveltejs/kit#8395]
### Describe the bug

I've been trying to create a setup within `sanity` + `sveltekit` but I'm struggling with the following problem:

Whenever I import `import * as Sanity from 'sanity'`, it throws an error in the server because `sanity` module seems to be undefined, but in the client that works.

> I'm importing with "*" because that's the only way it won't throw an error.

I've tried a bunch of `vite` config to manage that like `optimizeDeps.include`, `ssr` stuff but nothing seems to work.

### Reproduction

1. clone this https://github.com/devraul/sveltekit-sanity-ssr-undefined
2. install deps `pnpm i`
3. run sveltekit `pnpm -F sveltekit run dev`
4. open the server
5. See the console on both server and client

### System Info

```Shell
System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 1.36 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.18.1 - ~/.asdf/installs/nodejs/16.18.1/bin/node
    npm: 9.2.0 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.10.10.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.0 
    @sveltejs/kit: ^1.0.0 => 1.0.7 
    svelte: ^3.54.0 => 3.55.0 
    vite: ^4.0.0 => 4.0.4
```

### Severity

annoyance

### Additional Information

I tried with a client-only svelte project (from vite template) and because it has no SSR, the config is there.

**Comment by Rich-Harris** [comment]
This is a Sanity bug, not a SvelteKit one. If you create a blank Node project with `sanity` and its peer dependencies...

```js
// package.json
{
  "type": "module",
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-is": "^18.2.0",
    "sanity": "^3.1.4",
    "styled-components": "^5.3.6"
  }
}
```

...and a plain module that imports it...

```js
// index.js
import * as Sanity from 'sanity';
```

...then when you try to run it you'll see this warning followed by screenfuls of gibberish...

> Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.

...then an error:

> SyntaxError: Cannot use import statement outside a module

This is because Sanity is incorrectly packaged for use with modern ESM projects. It's difficult to diagnose further because it's a [sprawling package](https://npmgraph.js.org/?q=sanity) containing minified code, but I'm afraid you'll have to take it up with them.

That said, while I'm not personally familiar with Sanity, their own docs appear to recommend using the `@sanity/client` package rather than `sanity`: https://www.sanity.io/docs/connect-your-content-to-sveltekit

If that doesn't work, and replacing Sanity isn't an option, then you might have to just disable SSR for the pages in question.

**Comment by raulfdm** [comment]
Nice catch @Rich-Harris ... thanks for checking this out. I'm going to raise this point there.
