### ISSUE TITLE
naming conflict when importing dynamic/public and /private environment variables

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/kit#8474]
### Describe the bug

Both `dynamic/private` and `dynamic/public` export the variables as `env`

```js
import { env } from '$env/dynamic/private'; // ok
import { env } from '$env/dynamic/public'; // "env" is already defined !!
```
It is a bit surprising (to not say disappointing) that this wouldn't work out of the box for an otherwise excellent framework.

### Reproduction

NA

### Logs

```Shell
NA
```

### System Info

```Shell
@sveltejs/kit@1.0.11
```

### Severity

annoyance

### Additional Information

Can be easily worked around with:
```js
import { env as pubenv } from '$env/dynamic/public';
```
(perhaps it is enough to add this example to docs in one of those red boxes ?)

**Comment by dummdidumm** [comment]
Two imports with the same name are not allowed by JavaScript, there's nothing we can do about that. Renaming one of them in a future version feels wrong, too, since I assume it's not that common to use both at the same time, so we would optimize for a minor use case. I'm also not sure if this warrants a documentation entry, since these import conflicts can happen in many other places, too, so this is more of a general "good to know" thing of JavaScript.
I'm not sure that you need to have both anyway, since AFAIK the private dynamic env includes the public env variables. Therefore closing this issue.

**Comment by stephane-vanraes** [comment]
I don't think they do, the docs explicitly state

> This module only includes variables that do not begin with [config.kit.env.publicPrefix](https://kit.svelte.dev/docs/configuration#env).

But I do agree it is a bit of edge case.
