### ISSUE TITLE
npm run check make app reload and CSP blocks the navigation

### ISSUE THREAD

**Issue by frederikhors** [sveltejs/kit#8525]
### Describe the bug

I start development. The app starts in the browser. Everything works.

I launch in another shell's console "`npm run check`" and then the browser reloads the page and I cannot use more the app because of the below errors (I'm using CSP):

```shell
Refused to connect to 'ws://localhost:4000/' because it violates the following Content Security Policy directive: "default-src https://*.project.com". Note that 'connect-src' was not explicitly set, so 'default-src' is used as a fallback.
```

In my `svelte.config.js` I have this:

```js
import adapter from "@sveltejs/adapter-static";
import { vitePreprocess } from "@sveltejs/kit/vite";
import "dotenv/config";

const dev = process.env.NODE_ENV === "development";

/** @type {import('@sveltejs/kit').Config} */
const config = {
  preprocess: vitePreprocess(),

  kit: {
    adapter: adapter({
      fallback: "index.html",
    }),

    serviceWorker: {
      register: !dev,
    },

    csp: dev
      ? undefined
      : {
          directives: {
            "default-src": [`https://*.${process.env.PUBLIC_PROJECT_URL}`],
            "style-src": [
              `https://*.${process.env.PUBLIC_PROJECT_URL}`,
              "unsafe-inline",
            ],
            "img-src": ["*", "data:"],
          },
        },
  },
};

export default config;
```

I think `npm run check` is restarting the app without `process.env.NODE_ENV === 'development'`.

My `npm run check` is: `"check": "svelte-kit sync && svelte-check --tsconfig ./tsconfig.json"`.

**Is there a way to disable CSP during development?**

### System Info

```Shell
System:
    OS: Windows 10 10.0.19045
  Binaries:
    Node: 18.13.0
    npm: 8.19.3
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.62)
  npmPackages:
    @sveltejs/adapter-static: 1.0.2 => 1.0.2
    @sveltejs/kit: 1.1.0 => 1.1.0
    svelte: 3.55.1 => 3.55.1
    vite: 4.0.4 => 4.0.4
```

### Severity

blocking an upgrade

### Additional Information

This didn't happen with `@sveltejs/kit@1.0.2`.

**Comment by Rich-Harris** [comment]
Ah, I see what's happening here.

When you run `pnpm dev` or `pnpm build`, various files are generated, including `.svelte-kit/generated/server-internal.js` which contains this:

```js
export const options = {
  csp: {...} // the CSP options specified in your svelte.config.js
```

The dev server reads the contents of that file and configures the page headers accordingly.

When you run `npm run check` (or just `npx svelte-kit sync`, since `svelte-check` isn't part of the problem) that file is regenerated, except this time `process.env.NODE_DEV` is not `development`. So the generated file includes the production CSP config.

(This didn't happen in older versions, where `options` wasn't written out to a module but was generated in memory for each new request — the new approach is simpler and has certain advantages, but it means we're uncovering these fun edge cases.)

I suspect the solution is for `svelte-kit sync` (the CLI, not the internal API) to only write out the files that are necessary for typechecking to be successful, since that's what it's designed for.

**Comment by frederikhors** [comment]
I can confirm https://github.com/sveltejs/kit/pull/8552 fixes this.
