### ISSUE TITLE
the interactive tutorial is not easy to find

### ISSUE THREAD

**Issue by paulovieira** [sveltejs/kit#8567]
### Describe the problem

The interactive tutorial is the best resource to start working with svelte kit, however it's not easy to find in https://kit.svelte.dev. The only available link to the tutorial seems to be buried in the "Announcing SvelteKit 1.0" blog post: https://svelte.dev/blog/announcing-sveltekit-1.0

### Describe the proposed solution

Add a new link in the top bar of https://kit.svelte.dev, next to the "Docs" (similar to what we have in the main https://svelte.dev website).

![Screenshot_2023-01-17_13-17-58](https://user-images.githubusercontent.com/2184309/212910597-71fdc19e-bf9e-440b-a8d8-c31744c8caf9.png)

### Importance

nice to have

**Comment by dummdidumm** [comment]
This is somewhat deliberate, since the tutorial is not completely done yet, and some parts of the Svelte tutorial don't work yet. After that's done, we absolutely should do what you propose. I also imagine some kind of "further reading" at the bottom of each page linking to relevant tutorials and other docs.

**Comment by s3812497** [comment]
learn.svelte.dev is now complete and default tutorial
