### ISSUE TITLE
Warn when trying to set cookie that exceeds common browser limits

### ISSUE THREAD

**Issue by extremelygooddeveloper** [sveltejs/kit#8584]
### Describe the problem

Just learnt the painful way that most browsers limit how big cookies can be.
Would it be smart to provide a warning when trying to set cookies that most likely will not be set by the browser because it exceeds 4096 bytes?

### Describe the proposed solution

Provide a warning when trying to set cookies that most likely will not be set by the browser because it exceeds 4096 bytes?

### Importance

nice to have

### Additional Information

I`d be happy to introduce a PR for this.

**Comment by Conduitry** [comment]
I believe browsers have a limit on the total size of all cookies for a particular host, not just a limit per cookie. I'm not sure whether it might be worth it to try to take that into account too somehow.

**Comment by Rich-Harris** [comment]
Per [RFC 6265 #6.1](https://datatracker.ietf.org/doc/html/rfc6265#section-6.1):

> General-use user agents SHOULD
   provide each of the following minimum capabilities:
>
> - At least 4096 bytes per cookie (as measured by the sum of the length of the cookie's name, value, and attributes).
> - At least 50 cookies per domain.
> - At least 3000 cookies total.

We can't reliably know how many cookies there are per domain, since a request for `/foo` will omit any cookies that have `Path=/bar`, though we _could_ warn if we know there are _at least_ 50 cookies and we try to set a new one. Warning on individual cookies is definitely the easier win though.

Should it be a warning or an error? In production you _probably_ don't want a request to fail because of an outsize cookie, since not all cookies are essential. But in development you probably do want that. So maybe it's just a dev-time error?

**Comment by extremelygooddeveloper** [comment]
I think a dev time warning is the way to go since this limit is kind of loose (rfc uses SHOULD/at least) and has the possibility to change in the future (even though i think that is unlikely).

**Comment by extremelygooddeveloper** [comment]
[This change in chrome 95](https://chromestatus.com/feature/4946713618939904) states that there is a limit on the cookie key aswell.

**Comment by Rich-Harris** [comment]
I've just tested this in Chrome and Firefox:

```js
/** @type {import('@sveltejs/kit').Handle} */
export function handle({ event, resolve }) {
  console.log(`small.length ${event.cookies.get('small')?.length}`);
  console.log(`large.length ${event.cookies.get('large')?.length}`);

  event.cookies.set('small', 'a'.repeat(3000), { path: '/' });
  event.cookies.set('large', 'a'.repeat(5000), { path: '/' });

  return resolve(event);
}
```

After the initial load, both report the same thing:

```
small.length 3000
large.length undefined
```

The large cookie is simply discarded — which is potentially very bad — so I'm strongly of the view that this should be an error rather than a warning. Though oddly the limit in both browsers appears to be 4,129 bytes (for the whole thing — attributes and value) rather than 4,096.

**Comment by extremelygooddeveloper** [comment]
IMO, since SvelteKit can't actually tell if the browser will/did set the cookie, a warning is best, but I'm not married to the warning.
