### ISSUE TITLE
svelte-package breaks yarn v3 workspaces due to duplicate `package.json` with same `name`

### ISSUE THREAD

**Issue by samijaber** [sveltejs/kit#8629]
### Describe the bug

Related to https://github.com/sveltejs/kit/issues/6824

I have a yarn v3 workspaces project. Running `svelte-package` will cause me to have 2 `package.json` files with the same `name`. This makes it impossible for `yarn install` to succeed for the entire workspace, because Yarn is not able to resolve the workspace graph (due to the duplicate names).

I think 

### Reproduction

https://github.com/samijaber/svelte-package-yarn-workspaces-bug

### Logs

<img width="1565" alt="CleanShot 2023-01-20 at 11 28 59@2x" src="https://user-images.githubusercontent.com/1393142/213736162-840f91ca-3f76-412a-a8e3-613741be7378.png">

### System Info

```Shell
System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 78.53 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - ~/.asdf/installs/nodejs/17.4.0/bin/node
    Yarn: 3.2.0 - ~/.asdf/installs/nodejs/17.4.0/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm
    Watchman: 2022.02.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Brave Browser: 109.1.47.171
    Chrome: 109.0.5414.87
    Firefox: 107.0.1
    Safari: 15.2
```

### Severity

annoyance

### Additional Information

- My current workaround is to patch `svelte package`'s logic so that it creates a `--package.json` file.
- Another potential workaround is to make sure the yarn `workspaces` glob does not include the inner svelte package. My actual project facing this issue involves a lot of nested workspaces that I need to match, so this might be a bit tricky to achieve...

**Comment by Rich-Harris** [comment]
I don't see this changing, honestly — I'm not sure what a solution could possibly look like that wouldn't make things quite a bit more confusing. I guess adding a way to modify the resulting package.json could solve it, but at a cost (you'd have to do it manually for every package).

We don't make any secret of the fact that we recommend [pnpm](https://pnpm.io/) as a package manager because it doesn't suffer from any of these sorts of gotchas, but with Yarn I think tweaking the `workspaces` glob is the way to go.

**Comment by samijaber** [comment]
Gotcha, appreciate the response. I've been considering a move to `pnpm` for other reasons, so this might push me over the edge. 👍🏽

**Comment by Rich-Harris** [comment]
Cool — will close this issue since there's not much we can change
