### ISSUE TITLE
Support CSR as first class citizen in kit

### ISSUE THREAD

**Issue by laoshaw** [sveltejs/kit#8631]
### Describe the problem

I'm from Vue and I like the fact that Vue is a pure CSR all-in-one framework and keeps its SSR  Nuxt a separated project.

Sveltekit seems a SSR-first project to me and it treats CSR as a second class citizen in a fallback mode. 

There are many users that care about CSR-only Svelte and do not need SSR or SEO at all(internal projects, tauri|wails|electronjs, etc). As the sole official framework for Svelte, I hope Sveltekit treat both CSR and SSR as first class citizens by design.

### Describe the proposed solution

Adding a client-side route package, disable SSR and prerender, enable static adapter,etc.

When I do `npm create svelte@latest` please offer a CSR-only option, in parallel with SSR options.

### Importance

i cannot use SvelteKit without it

**Comment by dummdidumm** [comment]
I'm not sure what you mean by "second class citizen in fallback mode". All you need to do is have `export const ssr = false` at the root of your project, and you have a good ol' SPA.
To preconfigure the adapter seems limiting because `adapter-static` isn't suitable for all deployment targets - or rather, it's way easier to for example use `adapter-vercel` to deploy your SPA to Vercel. Furthermore, there's a step-by-step section in `adapter-static` that tells you what to do in order to create an SPA with it.

That said, it sounds like you already know this, so I'm curious what makes you think that SPA's are not a first class citizen.

**Comment by benmccann** [comment]
Ah, the "SvelteKit demo app" is not a good choice if you want a SPA. Maybe we should rename that choice to "SvelteKit SSR demo app" to make it clearer that "Skeleton project" is a better one to start with if you want a SPA

**Comment by Rich-Harris** [comment]
The trouble with this approach is that the definition of 'SPA' is very fuzzy. Many people these days use it to mean something like the SvelteKit default (i.e. server-rendered pages with client-side routing), for example. For some people it implies a single `index.html` shell (your definition would require adapter-static to be installed and configured to use a fallback page, though the name of the fallback page will differ from one webserver to another), but for others it purely describes the rendering and routing approach, and doesn't preclude dynamically rendered API routes (which means you _can't_ use adapter-static).

So there's no single definition that would make sense for inclusion in the `create-svelte` template list (and we don't want the list to balloon with lots of increasingly complex options).

On top of that, while there _are_ valid reasons to build something without SSR, it's a bad default for the majority of projects, so we want there to be a _little_ bit of friction.

We could possibly add a page to the docs explaining all of the above, but I don't see us changing anything in the framework itself.

**Comment by Rich-Harris** [comment]
SvelteKit isn't analogous to Vue and React though, it's analogous to Nuxt and Next

**Comment by dummdidumm** [comment]
To be clear you can absolutely create such SPAs with SvelteKit, all you need is what's described in the SPA section of adapter-static which you intended to use. The file based routing is independent of the rendering mode.

I agree with Rich that we don't need to change something inside Kit itself, and that it's more about better documentation of the different rendering modes, how you use them, and what that means for adapters. "Page options" is a good starting point but needs more in-depth explanations and maybe also more prominently linked from other places.

**Comment by jkbz64** [comment]
I've recently started using kit and wanted to turn it into SPA ONLY mode and I've also thought the SSR was first class citizen in kit but there is no first class citizen in sveltekit, it's just flexible - all levers are turned on by default. That being said it's in my opinion a fault of flexible framework to not explicitly indicate what rendering modes it is globally using without digging into documentation defaults because it just markets itself as "flexible".
Why not at least ship `+layout.js` with default options (+ maybe some comments/link to docs for every mode) inside skeleton project? I think it would help to quickly test out ssr/csr/prerender modes for people who don't want to jump right into docs from the beginning.

One extra thing that confused me was that sveltekit does not indicate/still builds ssr bundle when SSR is disabled globally during build - it still builds and shows "building SSR bundle for production" even though generated files from this step are not even used with static adapter.

**Comment by Rich-Harris** [comment]
> it still builds and shows "building SSR bundle for production" even though generated files from this step are not even used with static adapter

They _are_ used — they're used during prerendering

**Comment by jkbz64** [comment]
> > it still builds and shows "building SSR bundle for production" even though generated files from this step are not even used with static adapter
> 
> They _are_ used — they're used during prerendering

True... I missed that, should've noted CSR only (`ssr = false prerender = false`) instead of SSR but it still does it with this combination.

**Comment by Rich-Harris** [comment]
Even if SSR is disabled, you still need a server (whether to respond to requests dynamically or for prerendering) - something has to serve up the empty app shell. It's true that you could theoretically get away without building all the component code in SSR mode, but we're talking about extra complexity for fairly minimal gains

**Comment by trepetti** [comment]
I think one of the things that may help people using hoping to make a single-page CSR app for static sites or offline applications may be the addition of a dedicated template on the svelte `npm create` template list. As a newcomer to Svelte after SvelteKit came on the scene, I was able to figure this out without too many issues, but it did require some digging into what adapter settings were needed to do so. Svelte's historical success with single-page, rich, interactive experiences for data visualization were what originally attracted me to it. In this light, I can see why other people in similar situation after SvelteKit may feel lost without having a dedicated CSR starter template to cut their teeth on.

**Comment by Rich-Harris** [comment]
You shouldn't be disabling SSR unless you have a good reason for it. If we offer a template, people will create CSR-only SPAs because that's what they're used to, or because there's a mistaken perception that it's somehow 'easier', and users will suffer a worse experience as a result.

**Comment by trepetti** [comment]
That is a good point. My use case is indeed pretty niche, so the expectation of having to do a bit more setup than the common/best practice case is not unreasonable.

**Comment by Kiho** [comment]
I have same problem, I've been work with C# for long time, I don't have any reason to run both ASP.Net & nodejs server in same project. There is no official dot.net core adopter here. I had to write my own  adaptor https://github.com/Kiho/svelte-adapter-aspcore
But I can't find any reason to use svelte kit SSR over SPA with lots more of complexity.

**Comment by dummdidumm** [comment]
That's not true though, you can use it for SPA's just as well. It requires a little change to the default setup, that's all.
I'm split on how to proceed here. I agree with Rich that people reach for SPA's more often than they should. I disagree that SSR is just as easy - it's not. You need to think about two environments, about global state and not leaking it etc. That's a lot to ask from a newcomer or someone used to this style, especially if there's no need for them to change (for example of they are building internal business apps).
I think we need to do _something_ here. If our goal is to be SvelteKit be the tool you reach for for all apps and sizes, no matter if you're a beginner or not, the barrier for entry needs to be lower

**Comment by theetrain** [comment]
Would it be enough to add a warning to this page: https://kit.svelte.dev/docs/creating-a-project

Something like this:

> By default, SvelteKit scaffolds a project with server side rendering that comes with many benefits for web-based sites including [progressive enhancement](https://kit.svelte.dev/docs/form-actions#progressive-enhancement). It's possible to opt out of SSR on a per-route basis, though if you wish to build a completely static site, or a single page application for a good reason such as situations that don't require SEO, native applications, or embedded software; then look into using [adapter-static](https://kit.svelte.dev/docs/adapter-static) with SvelteKit.

Though SSR is generally encouraged, and SPAs are lightly discouraged to appeal to the majority of users authoring websites, adapter-static is an official solution that can be represented a bit earlier in the docs.

**Comment by benmccann** [comment]
If you want a SPA, SvelteKit is still what you want to use because you will need a router, which SvelteKit provides. It's much easier to setup a SvelteKit project and turn on SPA mode than it is to try to setup a router on your own which will not be nearly as well maintained or documented.

> there's a mistaken perception that it's somehow 'easier'

It sounds like one of the main drivers of that is that a lot of people have accounts with legacy hosting providers and can easily deploy a SPA (i.e. static files) there whereas to deploy an SSR-based solution they sometimes need to create a new account at a serverless provider or obtain a VPS to run their own Node instance. It sounds like some CPanels will let you run Node and some won't and when you can it's not always obvious how to set it up (we should probably document it). If you're starting from scratch, the serverless option is probably the easiest, but if you have an account at a legacy hosting provider and don't want to move from it for whatever reason then I can see people reaching for a SPA even if it's not better for users because it might be the easier choice from a deployment perspective.

A few examples:
- https://www.reddit.com/r/sveltejs/comments/ookqde/how_do_i_deploy_my_sveltekit_app/
- https://stackoverflow.com/questions/71278902/can-i-deploy-a-svelte-kit-app-on-php-hosting-without-nodejs
- https://stackoverflow.com/questions/72820259/sveltekit-nodejs-build-not-running-in-cpanel-on-shared-hosting

**Comment by dummdidumm** [comment]
I think the bigger problem for people with regards to SSR is the increased learning curve. With SPA you can use global imports freely, don't have to worry about state, can do many things the "JS-way" (for example doing fetch requests when submitting forms instead of leveraging the form actions), don't have to worry about browser globals being undefined, etc. We should definitly encourage people to learn the SSR parts, too, because this will over time make them a better developer and many kinds of apps benefit from such an architecture, but this is a process that should happen over time. Right now it's "here's the default, have fun" and it's a different default than what they expected. Starting out with SPA, getting confortable with SvelteKit's routing conventions, and _then_ opting into SSR might be a better "one at a time" learning path for some. At the same time we don't want to just go "yeah do everything in JS that's the best" because that harms the web overall. Super hard to balance this.

Maybe more prominent add-ons (through `svelte-add`, for example) can help here. Like there's a "next steps" section at the end of the prompt, and it should call out additional setups more prominently. 
Another idea would be some kind of "learning path" page helping people to know where to look next when they have background x, y or z - hard to strike a good balance though to not make it duplicative, noisy.

Whatever we chose, we should guide a newcomer more closely through the first steps with Svelte(Kit).

**Comment by niemyjski** [comment]
Seems like every single example and docs has a server component even for things like forms. For those who are CSR only because we already have an existing backend it's brutal to get started with svelte/sveltekit.

**Comment by niemyjski** [comment]
The basic tutorials should ask who am I. I'm a developer targeting ssr or csr.. and show correct examples or not supported banners. Aurelia does a great job at this.. Form examples can be dead simple example of docs that should support both.
