### ISSUE TITLE
SvelteKit swallows parse errors

### ISSUE THREAD

**Issue by benmccann** [sveltejs/kit#8799]
### Describe the bug

If `vite-plugin-svelte` throws a `ParseError` it gets swallowed by SvelteKit making it impossible to figure out what's wrong in many cases

### Reproduction

Put this in `+page.svelte`
```
<script>
</script>

<script>
</script>
```

### System Info

```Shell
`latest`
```

### Severity

serious, but I can work around it

**Comment by gtm-nayan** [comment]
The default handle error [here](https://github.com/sveltejs/kit/blob/a8a0d74fe94bc996e208efb84178d45b8c3e8183/packages/kit/src/runtime/server/index.js#L43) only logs the stack, which appears to not be populated with anything at the moment.

Although I think it should probably be logged [here](https://github.com/sveltejs/kit/blob/a8a0d74fe94bc996e208efb84178d45b8c3e8183/packages/kit/src/exports/vite/dev/index.js#L57) instead, 

I got an output like this using `vite.config.logger.error`, is there another utility in vite to present the error in a better way?

![image](https://user-images.githubusercontent.com/50981692/215661301-f7295739-0c4f-4e12-b7f2-fa2d1f1b1f17.png)

**Comment by dominikg** [comment]
you can send the error over devserver websocket so it gets presented to the user as an overlay. 
thrown errors from plugin hooks should end up there automatically.

might need a bit of transformation to get the error to display nicely https://github.com/sveltejs/vite-plugin-svelte/blob/360171392990cd907c87b6ba16e17d7698fe9f8e/packages/vite-plugin-svelte/src/utils/error.ts#L11

**Comment by gtm-nayan** [comment]
Hmm, if the error happens while editing a loaded page, or client side navigating to a broken page there is already an overlay. The user just doesn't see anything when doing a native navigation to a page with the compiler error and the ws wouldn't be ready by then.

> thrown errors from plugin hooks should end up there automatically

Turns out there was something logged before 1.0.13,
![image](https://user-images.githubusercontent.com/50981692/215777236-fc660fb5-de58-4eda-bf24-8ba0366bc0b7.png) 
Was this logged from one of v-p-s's hooks? I think Kit calling loadSsrModule in a middleware makes the error not show up as a plugin hook error.

1.0.13 was [this](https://github.com/sveltejs/kit/pull/8429) huge change so it's going to be fun trying to figure out what changed there to suppress V-P-S's logging.

**Comment by benmccann** [comment]
We definitely used to log the `frame` property. I remember adding that like a year or two ago. It looks like that was somehow lost in a refactoring. We should probably update the default `handleError` to use the `frame` and `message` properties when `frame` is present.
