### ISSUE TITLE
Client-side navigation does not perform trailing slash redirect

### ISSUE THREAD

**Issue by s3812497** [sveltejs/kit#8842]
### Describe the bug

After building, client-side navigating to an incorrect URL, such as `/test/`, does not redirect to its counterpart `/test`.

The issue occurs when the preload data attribute is present on the link.

### Reproduction

https://stackblitz.com/edit/github-vabxnk?file=src%2Froutes%2Ftest%2F%2Bpage.svelte,src%2Froutes%2F%2Blayout.svelte,src%2Froutes%2F%2Bpage.svelte

1. Run `pnpm build && pnpm preview`.
2. Click on the link to the page `/test/`

#### Expected
Redirect from `/test/` to `/test`.

#### Actual
Client loads `/test` page content and does not redirect. Browser URL remains as `/test/`.

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.2 => 1.0.2 
    @sveltejs/kit: ^1.3.8 => 1.3.8 
    svelte: ^3.55.1 => 3.55.1 
    vite: ^4.0.4 => 4.0.4
```

### Severity

serious, but I can work around it

**Comment by goynang** [comment]
Interestingly I have the exact opposite problem after upgrading to Kit v1.5.x

I have trailing slashes set to 'always' but a URL like `/test/` is getting changed to `/test`. This is breaking navigation on my site as it then gets document relative links wrong. **Reverting back to Kit v1.4.0 fixes it for me**. I don't have a minimal test case but could create one if it turns out unrelated to this issue.

Refreshing a page (i.e. hitting SSR) that is missing the slash does correctly put it back so it looks like it is only client-side navigation that is broken.

I only experience the problem after build... it's fine running in dev mode.
