### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by johnyvelho** [sveltejs/kit#889]
Add the possibility to force HTTPS redirect.
When using nextjs, its possible to create a middleware to force this redirect. How would be this possible on sveltekit? Should be a Vite feature?

**Comment by Conduitry** [comment]
Redirecting from HTTP to HTTPS should be the responsibility of the reverse proxy or hosting provider or whatever is sitting in front of the production Kit app. In production, Kit apps don't even serve HTTPS, and in any case you would almost always want to be using nginx or something else for this rather than Node's native HTTPS support.

**Comment by johnyvelho** [comment]
@Conduitry why force to use a reverse proxy when the adapter-node is already running a server? Wouldn't be interesting to be able to have an option on the adapter to force the https or add custom middleware to polka?
