### ISSUE TITLE
Will SvelteKit solve these two problems?

### ISSUE THREAD

**Issue by johnknoop** [sveltejs/kit#899]
Hi

My website is currently using Svelte (not sapper). There are currently two problems with it, which I hope SvelteKit will solve.

**Problem 1**: As you know, the Svelte routing happens entirely in the browser, and the only document that exists on the server side is the index.html file. So if you enter the URL other than the root directly in the browser, you'll get a 404. I've solved this by adding a rule in my CDN, that will match any request with the accept header `text/html` and rewrite the URL to 'index.html'. This only happens server side, so the web server will server the index.html page, and when Svelte loads up in the browser, it will still see the original URL and load the correct route. SvelteKit´s static adapter will solve this, right? Since all the routes will have physical html files, I mean.

**Problem 2**: Since the Svelte app is built in the browser using JavaScript, it doesn't work to paste a URL into a Facebook post and get a preview thumbnail (instead you just get a bubble saying "WebContentNotFound"). I'm guessing that this is because Facebooks robot that scans the page doesn't support JavaScript. I should be able to get around this as well using the static adapter, right?

Thanks!

**Comment by antony** [comment]
Sorry @johnknoop, as the github issue template states, github issues is not the right place to get support. Please use the [https://svelte.dev/chat](discord chat) for support questions and help with your issue.

In addition, both of the issues above are specific to your code, and are not an issue with Svelte nor a limitation caused by Javascript applications.
