### ISSUE TITLE
Add an option to prevent removal of unused CSS selectors/classes

### ISSUE THREAD

**Issue by Cluster2a** [sveltejs/kit#9035]
### Describe the problem

Hey, I am using UIkit (https://getuikit.com/docs/introduction) for my application and added it via scss:

app.scss:

```scss
$global-link-color: #ff4600;
$global-primary-background: #ff4600;
$button-primary-background: $global-primary-background !default;
$button-primary-hover-background: darken($button-primary-background, 15%) !default;
$text-lead-color: #646464;
$global-font-family: 'Poppins', sans-serif;

@import 'uikit/src/scss/variables-theme.scss';
@import 'uikit/src/scss/mixins-theme.scss';
@import 'uikit/src/scss/uikit-theme.scss';
```

In my +layout.svelte I added:
```js
import '../app.scss';
```

Now SvelteKit removes all my css with many messages like this:

`[vite-plugin-svelte] /src/lib/Components/Contact.svelte:11626:0 Unused CSS selector ".uk-light .uk-subnav-pill > * > :first-child"`

I tried to import it via global, but this leads to another error message (:global(...) must contain a single selector) - this is not an option.

### Describe the proposed solution

There should be an option to disable this feature for ppl who are working with external CSS frameworks.people

### Alternatives considered

I could include the framework within the app.html, but I won't be able to set my scss-Variables. I would need to override everything via global CSS, which would be possible but could be better.

### Importance

would make my life easier

**Comment by Conduitry** [comment]
This has come up a lot of time before, for example in https://github.com/sveltejs/svelte/issues/1594 https://github.com/sveltejs/svelte/issues/3371 https://github.com/sveltejs/svelte/issues/5804 - This feature is working as intended. If you want to have styles that Svelte doesn't try to scope at all, you can import them from your `<script>` block instead of from a `<style>` block. Anything that ends up in a `<style>` block in a component gets run through Svelte's CSS processing.
