### ISSUE TITLE
Fetching works on initial page load, not on page reload

### ISSUE THREAD

**Issue by evan-thurston** [sveltejs/kit#906]
**Describe the bug**
I'm fetching data from an API in my route's `load` function, but I can't find a way to make it work on subsequential loads.

**Logs**
using ctx.fetch: TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation at load
using fetch: ReferenceError: fetch is not defined at load

**To Reproduce**
install sveltekit
create a component that loads data in the `<script>` tag, as follows:
`export async function load(ctx) {
    // Call our fetch
    let postsData;
    postsData = await fetch(
	    'https://jsonplaceholder.typicode.com/posts'
	    ).then((x) => x.json());
    console.log(postsData);
}`

**Expected behavior**
I expect the response to be logged to the console on each pageload.
Using fetch, it works on initial load, not reloads.
Using ctx.fetch, it works on reloads, but not inital load.

**Stacktraces**
Unfamiliar with stacktraces. This is my first time publishing an issue to a repo, so any information about this/how I can better format my issues would be much appreciated. I have more bugs/issues I've found that I'm too scared to post. Really hate bugging you guys when you're working so hard, but I'm lost on a few things.

**Information about your SvelteKit Installation:**

<details>
  <summary>Diagnostics</summary>

- The output of `npx envinfo --system --npmPackages svelte,@sveltejs/kit,vite --binaries --browsers`
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 8.92 GB / 15.89 GB
  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE     
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD       
    npm: 7.7.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
    Internet Explorer: 11.0.19041.1
  npmPackages:
    @sveltejs/kit: next => 1.0.0-next.69
    svelte: ^3.29.0 => 3.37.0
    vite: ^2.1.0 => 2.1.5

- Your browser

(Using NPM & Brave Web Browser)

- Your adapter (e.g. Node, static, Vercel, Begin, etc...)
Node adapter
</details>

**Severity**
How severe an issue is this bug to you? Is this annoying, blocking some users, blocking an upgrade or blocking your usage of SvelteKit entirely?

I guess I could store content statically, but this is a big problem for me as I'm trying to use Sveltekit to refactor some of my projects that use APIs everywhere. Axios might work as a workaround, but I'm trying to use as many Svelte/Sveltekit features as possible because I'm a big believer in what you guys are doing. If I could figure this out & some other problems I'm having, I'm ready to start refactoring some of my projects to use Svelte/Sveltekit instead of react & related helped frameworks

**Additional context**
I love what you guys are doing & would love to help if I can. Svelte is a breath of fresh air after getting annoyed & leaving the development community years ago. Thank you so much for everything youre doing, even if you can't help me out

**Comment by CaptainCodeman** [comment]
One thing to remember with the `load` function is that it can run on both the server OR the client.

So when you say you see it in the console, do you mean the terminal window where you are running `npm run dev` or the browser console?

With SSR enabled (the default) the `load` function is called on the server and the response embedded into the page so that it doesn't need to re-run on the client (but in dev, it does re-run). One the app has been loaded then navigating between routes will call the appropriate `load` functions for them but only on the client at that point. So, be sure to check both.

Minor tip: as you already have the function marked as `async` it's easier to use `await` than ye-olde promise chaining, so you could write:

```js
export async function load(ctx) {
  const resp = await fetch( 'https://jsonplaceholder.typicode.com/posts' )
  const post = await resp.json()
  return {
    props: post
  }
}
```

(assuming the route component has a property named `post`)

**Comment by rmunn** [comment]
@evan-thurston You're forgetting to use the `fetch` parameter passed to your `load` function. Because `load` can run on the server or the client, but the built-in `window.fetch` function is only available on the client, Svelte-Kit includes a `fetch` function that will work in either environment, and passes it to your `load` function as a parameter. You're supposed to use that function rather than the built-in `fetch`. So change your `load` function to use `ctx.fetch` instead of `fetch` and it should work. Or rewrite it the way the documentation recommends (and the way CaptainCodeman showed in his example) using destructuring to get the `fetch` parameter, i.e. `export async function load({ fetch })` and then you can just write `await fetch('...')` and you'll be using Svelte-Kit's supplied function.
