### ISSUE TITLE
Writable gets cleared after SSR load

### ISSUE THREAD

**Issue by kivox** [sveltejs/kit#9105]
### Describe the bug

When a writable object is modified from a server side load function it gets cleared a few seconds in client side load.

### Reproduction

https://replit.com/@kivox17/Sveltekit-SSR-Issue

### Logs

```Shell
n/a
```

### System Info

```Shell
  System:
    OS: Linux 6.1 Fedora Linux 37 (KDE Plasma)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 21.91 GB / 31.27 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chrome: 110.0.5481.100
    Firefox: 110.0
  npmPackages:
    @sveltejs/adapter-auto: ^1.0.0 => 1.0.3 
    @sveltejs/adapter-node: ^1.1.6 => 1.1.7 
    @sveltejs/kit: ^1.0.0 => 1.5.2 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.1
```

### Severity

serious, but I can work around it

**Comment by karimfromjordan** [comment]
My response from Discord:

There are two main issues with your code:
1. On the server you have a toast and on the client you don't. So when the page is server rendered you see the toast and when the page is hydrated you reset the store to on empty array. That's why it flashes. The time between the flash is where the browser downloads the JavaScript and Svelte hydrates the page after the initial server rendered response.
2. You are leaking the data on the server. Because you render the toast on the server and your toast store is created globally on the server every user sees the same toasts and the store grows infinitely which is probably not what you want.

You can verify this by reloading the page few times (each time you get one more message) and by disabling JavaScript in the browser which will result in no flash anymore.

So this issue can probably be closed.
