### ISSUE TITLE
Working with SvelteKit and PouchDB

### ISSUE THREAD

**Issue by RobertoOrtis** [sveltejs/kit#912]
Hello,

I am having a hard time to get pouchdb to work with sveltekit. I had it working with sapper without any issues. It was pretty simple to setup. However, with sveltekit, it's a pain! 

Could anybody please help me out. I believe the issue is with vite, but i have never used it before. I have read some solutions online related to vite and vue but none has helped.

**Comment by rmunn** [comment]
Nobody's going to be able to help you without more information on your problem. When you created this issue, assuming you created it as a bug report, there was a new-issue template you were supposed to fill out to give people the information they'll need to be able to help you. (If you didn't create this as a bug report, that's why you didn't see it: go back to the New Issue button and this time choose "Bug Report" to get the template). Fill out the bug report template properly, and then people will be able to help you with the issue. But with only what you've written so far, nobody can even guess what the problem is. Even just the error message would have been helpful, but we have zero information to help you with. Fill out the bug report template and then we'll be able to help you.

**Comment by benmccann** [comment]
It's better to ask on Discord. Please see https://github.com/sveltejs/kit/blob/master/documentation/faq/70-packages.md for some ideas on fixing this
