### ISSUE TITLE
Cookie with name 'fail-type' was not found at path '...'

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#9130]
### Describe the bug

I keep seeing this error when I run the tests:

> Cookie with name 'fail-type' was not found at path '...', but a cookie with that name exists at these paths: '/errors/error-html'. Did you mean to set its 'path' to '/' instead?

It doesn't happen every time, but it happens often. The `fail-type` cookie is set here...

https://github.com/sveltejs/kit/blob/9c626a9da8db1627a4de4f68247816ef7ffa7b4c/packages/kit/test/apps/basics/src/routes/errors/error-html/make-root-fail/%2Bserver.js#L4-L7

...so that it can be read here:

https://github.com/sveltejs/kit/blob/9c626a9da8db1627a4de4f68247816ef7ffa7b4c/packages/kit/test/apps/basics/src/routes/%2Blayout.server.js#L15-L18

As you can see, the `path` _is_ set, so it's unclear why this message appears. But it feels indicative of a real bug, just one I haven't wrapped my head round.

### Reproduction

Run `pnpm test` enough times, you'll see it.

### System Info

```Shell
workspace
```

### Severity

annoyance

**Comment by Smirow** [comment]
I am also seeing these warnings in my projet. It rapidly appeared when I implemented auth in a near blank project, so should be easily reproducible.

**Comment by mustofa-id** [comment]
It also happens to me when using the `--host` flag when I want to show my project on another computer using the host computer's IP address, and can't log in without any error message, just redirected to login page. I was using adapter-node.

**Comment by cdcarson** [comment]
This was introduced because folks were inadvertently setting cookies on `__data` paths. For the same reason and more worrisome, IMO, this line got added...

https://github.com/sveltejs/kit/blob/46eec8241094cfdffb57bb27e1b71368b6f311ff/packages/kit/src/runtime/server/cookie.js#L27-L28

- This theoretically fixes the special `_data` case. Only theoretically, because it's unlikely that a request to, say, `/sign-in/__data.js` should result in a cookie being set to `/sign-in`.
- For other cases it changes `/foo/123` to `/foo`, which most likely would be the opposite of what's intended. 
- Note this behavior, unlike the error message, isn't limited to dev.

I think it's reasonable to require `path` when setting a cookie.  It's a good thing to make me think about where I want to set a cookie, even if the usual case is just `/`.

But that would be a breaking change, so how about this:

- For now, get rid of  the notion of maintaining cookie state across requests in dev, which is causing the flakiness mentioned above.
- Get rid of the current dev error. Instead warn that `cookies.set` will eventually require `path`.
- Later, actually require `path` and get rid of the line of code above.

**Comment by dummdidumm** [comment]
As stated in the comment, this emulated the native browser behavior, so it's as if the path isn't set from a browser perspective, only that it also handles the `/__data.json` case.
I don't think that the linked snippet is wrong, it's more likely that something in the dev time detection heuristics is wrong.

**Comment by cdcarson** [comment]
Hi @dummdidumm: I understand where you're coming from. I still disagree. Sure browsers and the underlying `cookie` api we use allow setting cookies without the path, but they don't have special concerns, like `__data` urls. 

I guess I'd come around if someone could show me a case where requiring path to be set prevents doing something useful. I can't think of any, but who knows? In the meantime I'll agree to disagree.

**Comment by csellis** [comment]
> It also happens to me when using the `--host` flag when I want to show my project on another computer using the host computer's IP address, and can't log in without any error message, just redirected to login page. I was using adapter-node.

Had this same issue trying to log out on a remotely connected device. It would not set the cookie preventing the user from logging out.
