### ISSUE TITLE
Get access to the list of pages generated 

### ISSUE THREAD

**Issue by wighawag** [sveltejs/kit#923]
**Is your feature request related to a problem? Please describe.**
on my fully static website I usually have a service worker that cache the pages on first load

Currently svelte-kit gives us a list of build files but not any list of pages

**Describe the solution you'd like**
it would be great if there was a way to get the list of pages (dynamic ones would be given their non actualised params)

**Describe alternatives you've considered**
One workaround is to read from the file system the routes, but this duplicate what svelte kit is already doing and would be brittle to emulate

**How important is this feature to you?**
This is important as otherwise I have to do some workaround as mentioned above

**Comment by devgar** [comment]
Routify uses a `layout` store which instantiates more immediate parent layout. his layout store contains a list of children `nodes` which represents routes.

This is how a navbar can be auto-generated by routify:
```html
<!-- src/pages/_layout.svelte --> <script> import { layout } from '@roxi/routify' </script> {#each $layout.children as node} <a href="{node.path}">{node.title}</a> {/each}
```

**Comment by lucianoratamero** [comment]
hi everyone! 

@wighawag I'm having the same issues right now. I tried many ways to work around it, to no success =/
after digging around the source code, I found this [`build_service_worker`](https://github.com/sveltejs/kit/blob/353afa1bbc8799abc9247544422dd9b2f240f878/packages/kit/src/core/build/index.js#L465) function, which is the one that provides [these variables](https://kit.svelte.dev/docs#modules-$service-worker) to be used on the service worker. it writes a file at build time that makes them available, then goes forward to build the service worker file for production.

it didn't seem to be that much of a hassle to add the routes to the file as well, since they're already available in the `manifest` object that is injected into the function. as a proof of concept, I was able to get everything working. :]

my solution was to add the following code to [the line 483 of build.js](https://github.com/sveltejs/kit/blob/353afa1bbc8799abc9247544422dd9b2f240f878/packages/kit/src/core/build/index.js#L483) (985 of the `node_modules/@svelte/kit/dist/chunks/index4.js`, if you're using the npm installed package):

```
export const pageRoutes = [
	${manifest.routes
		.filter((route) => route.type === "page")
		.map(
			(page) =>
			`${s(`${page.path.endsWith("/") ? page.path : page.path + "/"}`)}`
			)
			.join(",\n\t\t\t\t")}
];
```

I'd be happy to discuss this further, and provide a PR, if everyone is fine with this proposal!

**Comment by oneezy** [comment]
I'm interested in this too! It would be really cool to have something similar to the way [11ty (eleventy)](https://www.11ty.dev/docs/data-eleventy-supplied/) handles this.

Eleventy gives you [Collections](https://www.11ty.dev/docs/collections/) along with something called Supplied Data so you can do things like:

```
{% for page in collections.pages %}

  <section id="{{ page.fileSlug }}" class="container my-20 prose lg:prose-xl">
    <article class="flex flex-col items-start justify-center lg:h-[50vh]">
      <h2>{{ page.data.title }}</h2>
      <p>{{ page.data.description }}</p>
      <a href="{{ page.fileSlug }}" class="button">Learn More</a>
    </article>
  </section>
  
{% endfor %}
```

SvelteKit needs this.

**Comment by patricknelson** [comment]
Thanks for working on this @Rich-Harris! I just noticed that this was closed. Is there any direction now on what the official method is for accomplishing this inside of a component? I’m new to this, sorry if this is a dumb question. 😅

**Comment by oneezy** [comment]
I'm curious about this too @patricknelson . I updated my comment above yours with more information if you'd like to look at a _hacky_ way to solve it.

**Comment by patricknelson** [comment]
Good suggestions. Actually @oneezy, I'm starting my first statically generated site, and at the time I posted my comment above I just so happened to be in the process of deciding between SvelteKit and 11ty as the foundation for the project.

I will still likely be using Svelte components (via [Slinkity](https://slinkity.dev/)), maybe even at the top level with minimal Nunjucks templating in my case. However, that particular functionality and flexibility of 11ty was precisely what pushed me over the edge. Specifically: It's powerful [page collections](https://www.11ty.dev/docs/collections/) and it's [data cascade](https://www.11ty.dev/docs/data-cascade/). I know SvelteKit probably can't quite match that since it doesn't quite exist to solve the same problems per se (11ty has the advantage of [front matter](https://www.11ty.dev/docs/data-frontmatter/) for `tags`), but at least having better access to at least enumerate the routes, maybe grouped by directory structure/slug, instead of using tags like 11ty, would still be _super_ useful. Especially if you can't use 11ty and you've got a real SSR application.

**Comment by oneezy** [comment]
Pretty much in the same boat 😅 . I went down the **11ty** rabbit hole first and currently going down the **Svelte/SvelteKit** rabbit hole. The 11ty features are super powerful and I agree that it would be _super awesome_ if **SvelteKit** adopted some of these ideas. I really like the direction **Slinkity** has taken as well to act as the glue between these 2 worlds _(along with whatever else)_. I might take that path also but still deciding. 

You might want to try out [MDSVEX](https://mdsvex.pngwn.io/). It lets you use `frontmatter` and `markdown` within `Svelte Components` but not sure what else _(that's the next rabbit hole I'm going down)_.

**Comment by winston0410** [comment]
I am curious on this one as well, as this feature is useful in many scenario. Will this be implmented in the coming future?

Btw +1 for the workaround mentioned up there

**Comment by elron** [comment]
@hyunbinseo Thanks, however its not working in the latest svelte:
```
  '@sveltejs/adapter-auto': 2.1.0_@sveltejs+kit@1.18.0
  '@sveltejs/kit': 1.18.0_svelte@3.59.1+vite@4.3.8
  vite: 4.3.8
```

(pages always return `{}`)

Or am I missing something?

**Comment by hyunbinseo** [comment]
@elron Things have changed in SvelteKit v1. Pages now have a filename of `+page.svelte`. Try the following.

```typescript
const pageRegex = /\/\+page\.svelte$/;

const paths = Object.keys(modules)
  // Convert relative path to absolute path
  .map((path) => path.replace(/^(.\/)/, directory))
  // Filter paths with dynamic parameters (e.g. /blog/[slug].svelte)
  .filter((path) => !/\[.*\]/.test(path))
  // Filter paths that end with `/+page.svelte`
  .filter((path) => pageRegex.test(path))
  // Remove the trailing `/+page.svelte` string
  .map((path) => path.replace(pageRegex, ''))
  // Set empty path string to '/' ('./index.svelte' is converted to '')
  .map((path) => path || '/')
  .sort();
```

These lines are removed.

```diff
- .filter((path) => !/(?:(?:^_|\/_)|(?:^\.|\/\.)(?!well-known))/.test(path))
- .map((path) => path.replace(/(\/index)?(@.*)?.svelte/, ''))
```

**Comment by aakash14goplani** [comment]
@hyunbinseo - any idea how do can we handle dynamic paths e.g. `src/routes/utility/[country]/[language]/+page.svelte` ?

**Comment by MrTango** [comment]
The workaround is nice, but it does not work when building and running the app with node and adapter-node later, or should that work too?
I only see parts of my navigation then, which are liked by static links too. So everything which is dynamic is missing.
