### ISSUE TITLE
Bizarre behavior of `<p>` as a parent to a component with slots.

### ISSUE THREAD

**Issue by watche** [sveltejs/kit#9363]
### Describe the bug

When a `<p>` tag encloses a component with a slot (can be default or named), the `<p>` tag will be broken up, and slot content will be moved outside of any enclosing markup in the component.

With `src/routes/+page.svelte` looking like so:
```
<script>
  import Comp from '$routes/comp.svelte'
</script>
<p>
  (Before Comp)
  <Comp>
    <p>This shouldn't be visible.</p>
  </Comp>
  (After Comp)
</p>
```
And Comp looking like so:
```
<span style="display:none;">
  <slot />
</span>
```
The contents of the hidden slot appear briefly when the page first loads. A few observations:
- This happens even if you use nest the `<p>` inside of another element. It can even be nested multiple levels deep.
- This happens with `<p>` as parent and `<p>` in the named slot, but also seems to happen with `<section>` and `<article>` in the named slot, but *not* with either of those elements as parent.
- The source code of the page does not have this problem, so it's not a bug in the SSR.
- This also happens for named slots.
- If you have more than one slot in the component, seemingly only the first slot containing an "offensive" element (`<p>`, `<section>`, or `<article>`) gets leaked, and the others do not. At least, this appears to the case in my test repo; I have not been able to exploit this using bogus slots to eliminate the problem in the more complicated scenario where I discovered this.

When the content is "leaking" out of the slot, the DOM has this structure: (copypasted from "edit HTML" in Chrome)
```
<p>(Before Comp)
  <span style="display:none;"></span></p><p>This shouldn't be visible.</p>
  (After Comp)
<p></p>
```
After the "leak" is corrected (a tenth of a second or so after the page loads), the DOM has this structure:
```
<p>(Before Comp)
  <span style="display:none;"><p>This shouldn't be visible.</p></span><!--<Comp>-->
  (After Comp)</p>
```

And here it is from viewing the source:
```
<p>(Before Comp)
  <span style="display:none;"><p>This shouldn&#39;t be visible.</p></span>
  (After Comp)
</p>
```

### Reproduction

https://github.com/watche/svelte-p-bug-reproduction

This repo is a skeleton project created using `npm create svelte@latest`. Here is the output from its creation:

create-svelte version 3.1.1

┌  Welcome to SvelteKit!
│
◇  Where should we create your project?
│    (hit Enter to use current directory)
│
◇  Which Svelte app template?
│  Skeleton project
│
◇  Add type checking with TypeScript?
│  No
│
◇  Select additional options (use arrow keys/space bar)
│  none
│
└  Your project is ready!

Install community-maintained integrations:
  https://github.com/svelte-add/svelte-add

Next steps:
  1: npm install (or pnpm install, etc)
  2: git init && git add -A && git commit -m "Initial commit" (optional)
  3: npm run dev -- --open

To close the dev server, hit Ctrl-C

Stuck? Visit us at https://svelte.dev/chat

### Logs

None

### System Info

```Shell
Tested on Chrome, Firefox, and Safari

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 443.52 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 19.6.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.4.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0
    @sveltejs/kit: ^1.5.0 => 1.10.0
    svelte: ^3.54.0 => 3.55.1
    vite: ^4.0.0 => 4.1.4
```
Also happens on my Android phone in Chrome.

### Severity

serious, but I can work around it

### Additional Information
Happens in both dev (`npm run dev`) and production (`npm run build` `npm run preview`).

**Comment by dummdidumm** [comment]
I believe something similar came up some time ago. It boils down to invalid HTML and the browser "repairs" it by shuffling the elements. There's nothing we can do about this.

**Comment by Conduitry** [comment]
Yeah, it has to do with how SSR'd HTML is constructed in one pass as a string. Correctly handling situations like this would make SSR a lot more complicated and slower (because it would need to do something like re-parse the HTML it just generated, or keep everything in a big tree that enforces DOM rules and then serializes that, or something else similar). It's not worth it.

Closing, as this isn't a SvelteKit issue anyway - it's a limitation of Svelte's SSR mechanism that we're not interested in addressing, because being able to construct a string is so much faster. I don't remember whether there's a specific issue for this currently in the Svelte repo. I'm not sure whether this is even something we want to document.

**Comment by Rich-Harris** [comment]
I wouldn't say it's a limitation of Svelte's SSR mechanism so much as a consequence of how HTML works — a `<p>` just can't contain another `<p>`.

The DOM, interestingly, does not share this limitation, which is why it magically 'fixes' itself when hydration occurs and Svelte repairs any mismatches.

In other words there's nothing we could do to fix this on the SSR side no matter what performance tradeoffs we were prepared to make — instead, we would have to enforce HTML rules in the DOM, which seems like an unnecessary limitation. I do think there's a good case for identifying these cases and warning about them at render time though, during development. We would have to make that change in Svelte rather than Kit though.
