### ISSUE TITLE
svelte-package puts `d.ts` files in `src/dist/__package_types_tmp__` when `src` directory contains a `tsconfig.json`

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/kit#9372]
### Describe the bug

i usually put a `tsconfig.json` inside my `src` folder so i can isolate the config for my svelte code from the config for other typescript code in my project (eg. playwright code, config files, etc.). 

this seems to confuse `svelte-package` and cause it to output the types to the wrong place.

### with a `tsconfig.json` in `src`
![image](https://user-images.githubusercontent.com/57028336/223913796-b79d4fba-84cd-4083-b006-0eec4405575d.png)

### without
![image](https://user-images.githubusercontent.com/57028336/223913703-763ed0f0-a774-4564-8c35-e64379528e13.png)

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-qbhpge?file=src/dist/__package_types_tmp__/asdf.svelte.d.ts

run `svelte-package`

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.11.0 
    @sveltejs/package: ^2.0.2 => 2.0.2 
    svelte: ^3.54.0 => 3.55.1 
    vite: ^4.0.0 => 4.1.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
I'm not sure if this is really a bug. I think we shouldn't butcher with the semantics of a `tsconfig.json` too much, which we would need to do to solve this. In your example you're extending the SvelteKit base config, which expects the tsconfig to be at the root. The output, includes etc are written relative to it. So I think the solution is to implement #9373 so that you can put a `tsconfig.package.json` in your root next to your regular `tsconfig.json`.
