### ISSUE TITLE
`svelte-package` - "exports" section in documentation does not work

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/kit#9389]
### Describe the bug

https://kit.svelte.dev/docs/packaging#anatomy-of-a-package-json-exports

the `"exports"` section in `package.json` does not work
```json
{
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "svelte": "./dist/index.js"
    }
  }
}
```
however moving `"types"` and `"svelte"` to the top level of `package.json` does work

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-jsw8jz?file=src%2Froutes%2F%2Bpage.svelte,package.json&terminal=dev

https://github.com/DetachHead/svelte-schema-form/blob/d214c3260199d375d3674a2a2077c1eca601fca5/package.json#L21-L26

run `svelte-check`
```
❯ svelte-check

====================================
Loading svelte-check in workspace: /home/projects/sveltejs-kit-template-default-jsw8jz
Getting Svelte diagnostics...

/home/projects/sveltejs-kit-template-default-jsw8jz/src/routes/+page.svelte:2:29
Error: Cannot find module '@detachhead/svelte-schema-form' or its corresponding type declarations. (js)
<script>
        import { SchemaForm } from '@detachhead/svelte-schema-form'
</script>


====================================
svelte-check found 1 error and 0 warnings in 1 file
```

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
  npmPackages:
    @sveltejs/adapter-auto: ^2.0.0 => 2.0.0 
    @sveltejs/kit: ^1.5.0 => 1.11.0 
    svelte: ^3.54.0 => 3.56.0 
    vite: ^4.0.0 => 4.1.4
```

### Severity

serious, but I can work around it

**Comment by dummdidumm** [comment]
This is expected (unfortunately). By default, TypeScript ignores the `exports` map completly. You have to use `"moduleResolution": "Node16"` or `"moduleResolution": "NodeNext"` for it to work - but that will make your whole experience for everything with relative files miserable, because now you are required to import everything including a `.js` file ending, and index shorthands are also not supported.

Luckily, TypeScript 5.0 which is coming soon will solve this through a new `"moduleResolution": "bundler"` setting, which will give you the best of both worlds - recognizing the `exports` map but allowing you to continue using shorthand imports etc.
