### ISSUE TITLE
fallthrough response

### ISSUE THREAD

**Issue by stephane-vanraes** [sveltejs/kit#9480]
### Describe the problem

Given the routing setup

```
/routes
  /[article_slug]/+page.svelte/js
  /[category_slug]/+page.svelte/js
```

It is not possible to clearly define when each route should match if the slugs can be dynamic since `matchers` are not suited for dynamic processes like this.

In earlier versions of SvelteKit we had to concept of "fallthrough" where if the `load` function did not return anything, it would attempt to load the next best matched route, it seems this feature has been removed somehow.

It is not possible to return nothing from current load function, nor is it possible to achieve the same result by throwing an error (or redirect).

### Describe the proposed solution

Introduce a helper `fallthrough` that can be called in a load function if SvelteKit should attempt a fallthrough, this is inline with `error` or `redirect`.

```js
import { fallthrough } from '@sveltejs/kit';

export async function load() {
  if (not_this_route_please) {
    throw fallthrough();
  }  
}
```

### Alternatives considered

restructure routing to
```
/routes
  /[article_or_category]
    +page.svelte
    +page.js
    Article.svelte
    Category.svelte
```
and have `load` return both data and type, which is then used to render Article or Category.

This structure can become cumbersome if we are also dealing with different subpaths, actions, ... and is not very elegant DX.

```
/routes
  /[type-1]
    /order
  /[type-2]
    /contact
    /support
```

Having the above structure mashed into one folder and writing extra code to detect where you are would quickly become messy.

### Importance

would make my life easier

### Additional Information

some relevant issues:

https://github.com/sveltejs/kit/issues/548
https://github.com/sveltejs/kit/issues/4609

**Comment by Conduitry** [comment]
Fallthrough was consciously removed in order to (besides greatly simplifying the routing logic) allow the current route and param information to already be available in the `event` object at the start of the `handle` hook. Param matchers were created as a partial solution to this when you're able to synchronously determine whether you want to match a certain route. Beyond that, 'alternatives considered' is the intended way to do this. It's less convenient, but the other benefits of not having a fallback anymore are more valuable.
