### ISSUE TITLE
Specify which pages to prerender without relying on the crawler

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#9506]
### Describe the problem

By default, SvelteKit will find pages to prerender by starting at every parameter-less route (we call these _entries_), prerendering them (if possible), and crawling the resulting HTML to find new links.

You can specify new entries in `svelte.config.js` if you have pages that need to be prerendered but which are not, for whatever reason, findable by following `<a>` tags.

This works, but the ergonomics aren't super great, and there's no type safety.

### Describe the proposed solution

Next has a couple of solutions to this — [`getStaticPaths`](https://nextjs.org/docs/basic-features/data-fetching/get-static-paths) for old apps, and [`generateStaticParams`](https://beta.nextjs.org/docs/api-reference/generate-static-params) if you're using the App Router.

We could have our own version of `generateStaticParams` — for consistency with the configuration option, I'd propose `entries`:

```js
// src/routes/blog/[slug]/+page.server.js
export async function entries() {
  const posts = await get_posts_from_cms();

  return posts.map((post) => {
    return { slug: post.slug };
  });
}
```

The return value could be typed (including automatically, thanks to https://svelte.dev/blog/zero-config-type-safety).

In `entries` was specified for a page, the resulting entries would be included in `*`, meaning that they would be included by default, but you would still have total control over which entries were considered:

```js
export default {
  kit: {
    prerender: {
      // this is the default config, so can be omitted
      entries: ['*'] // include all parameter-less routes, plus pages that specify `entries`
    }
  }
};

export default {
  kit: {
    prerender: {
      entries: ['*', '/x/y/z'] // include all of the above _plus_ `/x/y/z`
    }
  }
};

export default {
  kit: {
    prerender: {
      entries: ['/x/y/z'] // only prerender `/x/y/z`
    }
  }
};
```

For consistency we should probably allow the same for `+server.js` files.

**Comment by rgglez** [comment]
What about apps without SSR? I programed a front-end with SvelteKit pre-1 some months ago, which I built with adapter-static and published to AWS CloudFront as a bunch of static files. Following your example, I loaded some dinamycally/randomy chosen featured posts in the frontpage of the blog, using axios to fetch them from a AWS Lambda RESTful API served by AWS ELB. The links to the full posts are in the form /blog/[post] . In pre-1 I had /blog/[post].svelte and this was built and worked without problems, but now with /blog/[post]/+page.* [it doesn't](https://discord.com/channels/457912077277855764/1086340154710564904/1090513429174964224).  Fetching potentially millions of blog post entries with get_posts_from_cms() (as per your example) from the API wouldn't be practical, IMO.

**Comment by PuruVJ** [comment]
THIS!! Really needed this for a while now 🧡

One question though: Why is the return type `Array<{ slug: string }>`? Could just be `Array<string>`? Unless you plan to provide other options in the returning array... 🤔

**Comment by tcc-sejohnson** [comment]
@PuruVJ

We can provide type-safety for the params you return -- i.e. if you're on `/[year]/[month]/[[day]]` we can enforce that the type you return is `Array<{ year: string, month: string, day?: string }>`. This provides a great deal more safety than just returning a string does! If you want to provide an `Array<string>`, though, the top-level config option still remains.

**Comment by tcc-sejohnson** [comment]
> What about apps without SSR (no +server.js/+page.server.js/execution-in-server at all)? I programed a front-end with SvelteKit pre-1 some months ago, which I built with adapter-static and published it to AWS CloudFront as a bunch of static files. Following your example, I loaded some dinamycally/randomly chosen featured posts in the frontpage of the blog, using axios to fetch them from a AWS Lambda RESTful API served by AWS ELB. The links to the full posts are in the form /blog/[post] . In pre-1 I had /blog/[post].svelte and this was built and worked without problems, but now with /blog/[post]/+page.* [it doesn't](https://discord.com/channels/457912077277855764/1086340154710564904/1090513429174964224). Fetching potentially millions of blog post entries with get_posts_from_cms() (as per your example) from the API wouldn't be practical, IMO.
> 
> I wonder what changed to broke the old behavior? Is svelte+sveltekit still good for my architecture?
> 
> P.S. in case you wonder why this architecture? Well, to decrease costs, mainly. I don't have to pay for a VM, everything is serverless (from Aurora Serverless to the FaaS to S3 to the CDN).

This is off-topic for this issue, so I'm hiding it, but I did want to give you a response. 

Fundamentally, you have two options: Render blog posts at buildtime or render them at runtime. If you render them at buildtime (prerendering), you get the benefit of static files -- retrieving these is speedy, good for SEO, and cheap (no runtime servers!). If you render them at runtime, you have two suboptions: 

1. Fetch them clientside in `onMount` (no infra required, as users' browsers are fetching the content, but bad for SEO and annoying because you have to display loading spinners while the client loads the content)
2. Fetch them serverside using SSR. You don't want to do this, because costs. 
    - You can _also_ prerender the most popular blog posts and then SSR the others using `auto` instead of `true` in `export const prerender`.

If you go for the first option, you just have to fetch all of your blog posts at buildtime. There's no way around it -- you can't host static files you haven't generated, and you can't generate static files without the data that's supposed to be in them. 🤷🏻 

If you go for the "prerender a shell, fetch the content on the client" option, you end up with bad SEO and loading spinners. If you go for the SSR approach, you need to have _some_ sort of server, even if it's just a lambda. For your needs, the tool _I_ would reach for is Vercel's ISR. Or I would just prerender all of my content. I tried prerendering a million pages the other day, and it really didn't take long. 🤷🏻 

You haven't provided any reproductions here or in the Discord thread, so there's not much more I can help with -- if there's an actual bug, please do file an issue, though! Providing a link to a repository where the behavior you need is working in the pre-1.0 Kit but not working in the post-1.0 Kit would be the quickest way to nail down what the problem is.

**Comment by madeleineostoja** [comment]
LOVE this idea, the crawler is great as a default but relying on it solely has been a footgun a few times for me. For example something as simple as building a blog — if there aren’t any posts yet sveltekit errors out saying the page can’t be pre-rendered because it’s not linked to
