### ISSUE TITLE
data-sveltekit-replacestate does not work for #hash links

### ISSUE THREAD

**Issue by edde746** [sveltejs/kit#9546]
### Describe the bug

When clicking on a hash link that has the `data-sveltekit-replacestate` attribute, the expected behavior is to update the URL without pushing a new history entry. However, the bug causes the history object to be pushed even when the `data-sveltekit-replacestate` attribute is used, resulting in unexpected navigation history behavior.

### Reproduction

https://stackblitz.com/edit/sveltejs-kit-template-default-jsaxq9

1. Create a new SvelteKit project or open an existing one
2. Add a hash link with the `data-sveltekit-replacestate` attribute, like the following: `<a data-sveltekit-replacestate href="#c">c</a>`
3. Start the development server and navigate to the page containing the hash link
4. Click on the link with the attribute
5. Observe the URL change and the browser's navigation history

### System Info

```Shell
Not applicable
```

### Severity

annoyance

**Comment by vicentematus** [comment]
I think i know why this is happening: 

We have the following options element which contains:

https://github.com/sveltejs/kit/blob/5191e165b75f5616bd6b4aadf9d8a6c52e75c562/packages/kit/src/runtime/client/client.js#L1530

It returns an object which contains `replace_state`, which is a `boolean`. It activates whenever we click on  a `div` which contains `data-sveltekit-replacestate`. It will return `options.replace_state` as `true` This is working as expected.

But we have a problem, because whever we click, the logic of only updating the hash will update.That will trigger the `pushHistory` Which is the following

https://github.com/sveltejs/kit/blob/5191e165b75f5616bd6b4aadf9d8a6c52e75c562/packages/kit/src/runtime/client/client.js#L1564-L1592

Even if `options.replace_state` is `true`, it will always enter this `itf` condition and `push` the `store` because of the `stores.page.set`. It will never reach the expected `navigate` function which has the logic of triggering the `replaceHistory`. 


This is the function that is expected to replace the state with replaceState

https://github.com/sveltejs/kit/blob/5191e165b75f5616bd6b4aadf9d8a6c52e75c562/packages/kit/src/runtime/client/client.js#L1580-L1593

**Comment by nosovsh** [comment]
@vicentematus thanks for the explanation. Are you planning to release this?

**Comment by vicentematus** [comment]
> @vicentematus thanks for the explanation. Are you planning to release this?

No sir, im not currently working on it. Its free to work on it if you want (or anyone else reading this) 🤖

**Comment by sweetamino** [comment]
+1 I ran into this too. Would be nice to have a fix. What I did was just use the format ```href="?showModal"``` rather than ```href="#showModal"``` with ```data-sveltekit-replacestate``` which works as expected.

**Comment by s3812497** [comment]
Sorry this flew under the radar. I managed to see it thanks to a GitHub browser extension I just installed that sorts issues by comment date.
