### ISSUE TITLE
Provide an option to opt-out from putting `x-sveltekit-page: true` header

### ISSUE THREAD

**Issue by devunt** [sveltejs/kit#9572]
### Describe the problem

Please provide an option to opt-out from putting `x-sveltekit-page: true` header.
I'd like to keep my http response headers clean and minimal.

### Describe the proposed solution

Options like `noBranding: true` will work.

### Alternatives considered

Deleting `x-sveltekit-page` header in `hooks.server.ts`.

### Importance

nice to have

**Comment by Conduitry** [comment]
There are already several other `x-sveltekit-*` headers that SvelteKit uses as part of its core functionality - not to mention all of the other indications in the HTML itself that this is a SvelteKit app. Perhaps the `x-sveltekit-page` header could be removed entirely, because I don't see off the top of my head where it gets used, but there won't be an option to control this.

In general, if you want to mutate the incoming requests or outgoing responses, this is exactly what the `handle` hook is for. We don't want to provide a different API or option for each different possible mutation someone might want to do. You're free to try removing the `x-sveltekit-page` header yourself, but, as always when you're manipulating the internals of a library, it may well eventually lead to problems.

**Comment by Sciumo** [comment]
You should reopen this.  
Exposing the internal constructs of a product is a possible information assurance vulnerability.
