### ISSUE TITLE
Build finish successfully but get stuck and not exit

### ISSUE THREAD

**Issue by TedMeftah** [sveltejs/kit#965]
**Describe the bug**
When running `yarn build` the build finishes successfully but does not exit. This cause an issue with automating builds. 

**To Reproduce**
I have boiled down the issue to having `setInterval` in a script.

```
<script>
  let time = 1;
  setInterval(() => {
    time += 1;
  }, 1000);
</script>

{time}
```
A solution to this is of course to use `onMount`

```
<script>
  import { onMount } from "svelte";

  let time = 1;
  onMount(() => {
    setInterval(() => {
      time += 1;
    }, 1000);
  })
</script>

{time}
```
**Expected behavior**
I'm not sure if this is expected behavior or not but, In `Sapper` this did not happen, the first snippet of code run just fine.

**Severity**
Not severe since there is a workaround but I think it maybe need to be documented.

**Comment by Conduitry** [comment]
Interesting. I'm not entirely sure why it's causing a hang in SvelteKit but not in Sapper. But, regardless, having a `setInterval` without a `clearInterval` is a bad idea, because of memory leaks. And that's especially a problem on the server, where every single time someone loads a page that contains that component, it creates another `setInterval`, which then hangs around forever.

I think the path forward here is not to make it not hang, but to do something to warn people that this is a bad thing to be doing. In SSR, there's not really a reason to be creating an interval (or a timeout) at all, because it's not going to fire until after the SSR'd HTML is rendered. I don't know what's an effective way to warn about this. Static analysis won't really help. Do we override these globals with our own versions, and display a warning if we detect that one is being run during the synchronous period that the server-side rendering is happening? I'm not sure.

**Comment by KubaJastrz** [comment]
I've also noticed this today. It only hangs when using `@sveltejs/adapter-static`, `@sveltejs/adapter-node` works fine.

In both cases, the `build` folder gets populated with correct data though 🤔 

I'll try to create a reproduction soon.

**Comment by matt3224** [comment]
![Screenshot 2021-04-16 at 10 30 11 pm](https://user-images.githubusercontent.com/2401925/115085965-4f5ac880-9f03-11eb-8234-f0838dc1e3b7.png)

I also run into this, when using `@sveltejs/adapter-static` running `pnpm build` runs fine but never exits stays on the above screen ^^

**Comment by matt3224** [comment]
this works with the new structure:
```js
adapter: {
   adapt: static
},
```

**Comment by KubaJastrz** [comment]
Here's reproduction: https://github.com/KubaJastrz/svelte-kit-hang

For me it's caused by using https://github.com/SvelteStack/svelte-query in the application, I don't have any setIntervals anywhere.

**Comment by ignatiusmb** [comment]
I can't reproduce this with the repo above or with the first snippet in the latest version. If this somehow still happens, please open a new issue with a complete and minimal repo that we can clone and run.

**Comment by NormandoHall** [comment]
Only for reference.

If I use a [redis](https://github.com/redis/node-redis/tree/master) client at top of a module and do `client.connect()` then build no exits. So to workaround this I do inside the method that use it:

```js
method xxx : async () => {
  // ...
  if (!client.isReady) await client.connect();
//...
}
```

I don't know if happens with other libraries.
