### ISSUE TITLE
`use:enhance` shadows `data`

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/kit#9845]
### Describe the problem

I want to access the `data` prop in my `use:enhance` callback, but I also want to reference the `FormData` object that was passed in. Right now I have to do `({ data: formData }) => {...}` or similar:

```svelte
<script>
  import { enhance } from '$app/forms';

  export let data;
</script>

<h1>total: {data.total}</h1>

<form
  use:enhance={({ data: formData }) => {
    data.total += +formData.get('n');
  }}
  method="POST"
>
  <input name="n" type="number" />
  <button>add {n}</button>
</form>
```

### Describe the proposed solution

It should probably just be `formData` in the first place. We can do this non-breakingly (but maybe deprecate `data` for removal in version 2?)

### Alternatives considered

`formdata`? `fd`? `stuff`?

### Importance

nice to have

**Comment by Rich-Harris** [comment]
I suppose `form` also shadows `form`, though it's less likely that you'd reference the `form` prop inside the callback. Hmm

**Comment by ghostdevv** [comment]
+1 on `formData`

**Comment by dummdidumm** [comment]
I had to do the same renaming in some other example app before. Which makes me wonder if this is just a good renaming opportunity or if it's a symptom of a bigger problem which is that we want to update `data` without reloading it, and if there's some opportunity here for `enhance` to do this somewhat automatically (opt-in).

**Comment by gtm-nayan** [comment]
@dummdidumm That one, I think you're referring to result.data, where as Rich is talking about the FormData object that the SubmitFunction receives before the request is sent.

Although, it seems the FormData is passed in to the callback that runs after the submit, but it doesn't appear in the types. Should that be removed or renamed?
https://github.com/sveltejs/kit/blob/6e2efcf627ce8d179c941212d761aa93568b1724/packages/kit/src/runtime/app/forms.js#L113
And if it is renamed, would it be a breaking change to only keep formData there since it wasn't documented before?
