### ISSUE TITLE
Add `+form.server.js` for form actions

### ISSUE THREAD

**Issue by accuser** [sveltejs/kit#9854]
### Describe the problem

Exporting form actions alongside a `PageServerLoad` from a `+page.server.js` feels a little awkward. I've just been explaining the exporting of `load` and `actions` to a developer, and it struct me that an improvement could be to separate the concerns by adding a `+form.server.js` specifically for form actions.

### Describe the proposed solution

I would like to see support for `+form.server.js` in routes for specifically handling form actions. 

### Importance

nice to have

**Comment by tcc-sejohnson** [comment]
While I see your perspective, I personally don't want yet another reserved file in the tree, especially when `+page.server.ts` serves this need just fine. I don't see any specific advantage in clarity by having `+form.server.ts`. I've been wrong before, though! 😁

**Comment by dummdidumm** [comment]
We have debated this when adding form actions but decided against it because at a certain point there's file bloat - some people already feel we've crossed that border (can't satisfy everyone). We chose to add it to `+page.server.js` because form actions belong to a page and can only be executed on the server, so it fits. Therefore closing.
